import type {ProductCluster,ProvenanceKind,ProviderIdentity} from '../commerce/domain/commerce'
import type {SearchRequest} from '../commerce/client/catalog-client'
import type {CatalogProductResult,CatalogSearchResult} from '../commerce/providers/catalog-provider'
import {normalizeSourceField} from './field-normalization'
import {resourceCandidateSchema,type ResourceCandidate,type SourcingSource} from './domain/source-contracts'

export const CATALOG_SOURCE_ID='shopify-global-catalog'
export interface CatalogSourcePort{search(input:SearchRequest):Promise<CatalogSearchResult>;product(input:{identity:ProviderIdentity;market:{country:string;currency:string;language?:string}}):Promise<CatalogProductResult>}
const provenance=(kind:ProvenanceKind):'source_explicit'|'source_inferred'|'cosource_derived'|'unknown'=>kind==='provider_explicit'?'source_explicit':kind==='provider_inferred'?'source_inferred':kind
const project=(product:ProductCluster,now:string):ResourceCandidate=>resourceCandidateSchema.parse({identity:{sourceId:CATALOG_SOURCE_ID,id:product.identity.id},resourceType:'product',label:product.title.value,summary:product.description?.value,provenance:{sourceId:CATALOG_SOURCE_ID,trust:'aggregated_provider',retrievedAt:now},externalDataTrust:'untrusted_external_data',facts:product.attributes?.value.slice(0,50).map(item=>({name:item.name,value:item.value,provenance:provenance(product.attributes!.provenance.kind)}))??[],inspection:{supported:true,reference:product.identity.id},refreshReference:product.identity.id})

export function createCatalogSourcingSource(catalog:CatalogSourcePort,now=()=>new Date().toISOString()):SourcingSource<ProductCluster>{return{
 declaration:{identity:{id:CATALOG_SOURCE_ID,kind:'product_catalog',name:'Shopify Global Catalog',providerId:'shopify_global_catalog',version:'1',trust:'aggregated_provider'},capabilities:{resourceTypes:['product'],search:true,inspection:true,pagination:true,market:{country:true,currency:true,language:false,location:false},constraintSemantics:{requiredHardFilter:true,softPreference:false,negativeFilter:false},constraintOperators:['equals'],fields:['condition','color','size','target gender'],attributeFamilies:['taxonomy'],quantityAware:false,deadlineAware:false,availabilityEvidence:true,costFilter:true,freshnessEvidence:false,compatibilityEvidence:false,licensingEvidence:false,limits:{maximumResults:50,maximumQueryLength:500,maximumConstraints:4}}},
 specializedIdentity(product){if(product.identity.provider!=='shopify_global_catalog')throw new TypeError('Specialized product belongs to another provider');return{sourceId:CATALOG_SOURCE_ID,id:product.identity.id}},
 async search(input){const condition=input.appliedConstraints.find(item=>normalizeSourceField(item.field??'')==='condition'&&item.operator==='equals')?.value,attributeNames:Record<string,'Color'|'Size'|'Target gender'>={color:'Color',size:'Size','target gender':'Target gender'},attributes=input.appliedConstraints.flatMap(item=>{const name=attributeNames[normalizeSourceField(item.field??'')];return name&&item.operator==='equals'&&item.value?[{name,values:[item.value]}]:[]}),result=await catalog.search({query:input.query,country:input.market?.country??'GB',currency:input.market?.currency??'GBP',intent:input.intent,limit:input.resultLimit,cursor:input.continuation?.opaqueCursor,available:true,shipsTo:input.market?.country,maximumPrice:input.cost?.unitCeiling,condition:condition==='new'||condition==='secondhand'?condition:undefined,attributes,view:'offer'}),candidates=result.products.map(product=>project(product,now()));return{output:{candidates,messages:result.messages,estimatedTotal:result.pagination.estimatedTotal,continuation:result.pagination.hasMore&&result.pagination.cursor?{sourceId:CATALOG_SOURCE_ID,requirementId:input.requirementId,requirementRevision:input.requirementRevision,channel:input.channel,criteriaKey:input.criteriaKey,opaqueCursor:result.pagination.cursor}:undefined},specializedCandidates:result.products}},
 async inspect(identity,market){if(identity.sourceId!==CATALOG_SOURCE_ID)throw new TypeError('Candidate does not belong to the catalogue source');const result=await catalog.product({identity:{provider:'shopify_global_catalog',id:identity.id},market:{country:market?.country??'GB',currency:market?.currency??'GBP',language:market?.language}});if(result.product.identity.id!==identity.id)throw Object.assign(new TypeError('Catalogue returned a different product identity'),{code:'evidence_unavailable'});return{candidate:project(result.product,now()),specializedCandidate:result.product}}
}}
