import {describe,expect,it} from 'vitest'
import {createPurchaseGoal} from '../goals/domain/purchase-goal'
import {compileDiscoveryStrategy} from './compile-discovery-strategy'
const condition=(id:string,field:string,value:string)=>({id,operator:'equals' as const,field,value})
describe('discovery strategy projection',()=>{
 it('projects only supported same-currency constraints and never uses overall budget as unit price',()=>{const goal=createPurchaseGoal({id:'g',summary:'Equip students',searchFocus:'student raincoats',quantity:150,maximumItemPrice:{minorAmount:3000,currency:'GBP'},budget:{minorAmount:450000,currency:'GBP'},requirements:[condition('condition','condition','new'),condition('colour','colour','Blue'),{id:'waterproof',operator:'free_text',value:'waterproof'}],preferences:[condition('gender','target gender','Unisex')],exclusions:[]});const strategy=compileDiscoveryStrategy(goal);expect(strategy).toMatchObject({query:'student raincoats',humanIntent:'Equip students',constraints:{available:true,shipsToCountry:'GB',maximumPrice:{minorAmount:3000,currency:'GBP'},condition:'new',attributes:[{name:'Color',values:['Blue']},{name:'Target gender',values:['Unisex']}]}});expect(strategy.constraints.maximumPrice).not.toEqual(goal.budget);expect(strategy.evidenceGaps).toEqual(expect.arrayContaining([expect.objectContaining({goalConditionId:'waterproof'}),expect.objectContaining({description:'Quantity 150',resolution:'requires_merchant_verification'})]))})
 it('does not convert a mismatched item-price currency',()=>{const goal=createPurchaseGoal({id:'g',summary:'Buy coats',searchFocus:'coats',maximumItemPrice:{minorAmount:3000,currency:'USD'},budget:{minorAmount:999,currency:'GBP'},requirements:[],preferences:[],exclusions:[]});const strategy=compileDiscoveryStrategy(goal,{country:'GB',currency:'GBP'});expect(strategy.constraints.maximumPrice).toBeUndefined();expect(strategy.warnings).toContain('Maximum item price was not applied because currencies differ.');expect(strategy.evidenceGaps[0]).toMatchObject({resolution:'unsupported_by_provider'})})
 it('keeps delivery and unsupported requirements explicit',()=>{const goal=createPurchaseGoal({id:'g',summary:'Need mugs by Friday',searchFocus:'reusable mugs',requirements:[{id:'delivery',operator:'free_text',value:'delivery by Friday'},{id:'durable',operator:'is_true',field:'hard-wearing'}],preferences:[],exclusions:[]});expect(compileDiscoveryStrategy(goal).evidenceGaps).toEqual(expect.arrayContaining([expect.objectContaining({goalConditionId:'delivery',resolution:'requires_merchant_verification'}),expect.objectContaining({goalConditionId:'durable',resolution:'inspect_product'})]))})
})
