import {describe,expect,it,vi} from 'vitest'
import type {ProductCluster,ProvenanceKind} from '../commerce/domain/commerce'
import type {ResourceRequirement} from '../requirements'
import {createCatalogSourcingSource} from './catalog-source-adapter'
import type {SourceCapabilities,SourcingSource} from './domain/source-contracts'
import {SourceRegistry} from './source-registry'
import {compileSourcingPlan,SourcingCoordinator} from './sourcing-coordinator'

const provider='shopify_global_catalog' as const,provenance=(kind:ProvenanceKind='provider_explicit')=>({kind,provider}),product=(kind:ProvenanceKind='provider_explicit'):ProductCluster=>({identity:{provider,id:'product-1'},title:{value:'Coat',provenance:provenance()},attributes:{value:[{name:'Color',value:'Blue'}],provenance:provenance(kind)},media:[],offers:[],offerCompleteness:'provider_returned_unknown',provenance:provenance()})
const base=(constraints:ResourceRequirement['constraints']=[]):ResourceRequirement=>({id:'requirement',revision:2,context:{requester:{kind:'test'}},resource:{type:'product',purpose:'Find a coat',searchFocus:'coat',specification:[]},constraints,compatibility:[],market:{country:'GB',currency:'GBP'},qualityFloor:[],existingResources:[],preferredSources:[],excludedSources:[],riskLimits:[],approvalPolicy:{consequentialDecision:'requester_approval_required',fulfillmentAuthority:'recommendation_only'}})
const request=(constraints:ResourceRequirement['constraints']=[],changes:Record<string,unknown>={})=>({...base(constraints),channel:'human' as const,criteriaKey:'criteria',resultLimit:6,...changes})
const caps=(changes:Partial<SourceCapabilities>={}):SourceCapabilities=>({resourceTypes:['product'],search:true,inspection:false,pagination:true,market:{country:true,currency:true,language:false,location:false},constraintSemantics:{requiredHardFilter:true,softPreference:false,negativeFilter:false},constraintOperators:['equals'],fields:['color','condition','target gender'],attributeFamilies:[],quantityAware:false,deadlineAware:false,availabilityEvidence:true,costFilter:true,freshnessEvidence:false,compatibilityEvidence:false,licensingEvidence:false,limits:{maximumResults:50,maximumQueryLength:500,maximumConstraints:4},...changes})
const empty=()=>({output:{candidates:[],messages:[]},specializedCandidates:[] as string[]}),fixture=(id:string,changes:Partial<SourceCapabilities>={},search=vi.fn(async()=>empty())):SourcingSource<string>=>({declaration:{identity:{id,kind:'fixture',name:id,version:'1',trust:'authoritative_provider'},capabilities:caps(changes)},specializedIdentity:value=>({sourceId:id,id:value}),search})

describe('R5R sourcing truthfulness',()=>{
 it('keeps required, preferred, and excluded equality semantics distinct',()=>{const constraints=[{id:'required',importance:'required' as const,operator:'equals' as const,field:'Color',value:'Blue'},{id:'preferred',importance:'preferred' as const,operator:'equals' as const,field:'Color',value:'Green'},{id:'excluded',importance:'excluded' as const,operator:'equals' as const,field:'Color',value:'Red'}],plan=compileSourcingPlan(request(constraints),new SourceRegistry([fixture('catalog')])),leg=plan.legs[0]!;expect(leg.appliedConstraintIds).toEqual(['required']);expect(leg.projectedInput.appliedConstraints.map(item=>item.value)).toEqual(['Blue']);expect(plan.preferenceGaps).toMatchObject([{constraintId:'preferred'}]);expect(plan.mandatoryGaps).toMatchObject([{constraintId:'excluded'}])})
 it('never sends preferred or excluded equality as a positive catalogue filter',async()=>{const search=vi.fn(async()=>({products:[],messages:[],pagination:{hasMore:false}})),source=createCatalogSourcingSource({search,product:vi.fn()}),coordinator=new SourcingCoordinator(new SourceRegistry([source]));await coordinator.search(request([{id:'required',importance:'required',operator:'equals',field:'Color',value:'Blue'},{id:'preferred',importance:'preferred',operator:'equals',field:'Color',value:'Green'},{id:'excluded',importance:'excluded',operator:'equals',field:'condition',value:'secondhand'}]));expect(search).toHaveBeenCalledWith(expect.objectContaining({attributes:[{name:'Color',values:['Blue']}],condition:undefined}))})
 it.each([['Color','color'],['color','color'],['colour','color'],['Target gender','target gender']])('normalizes %s to %s without fuzzy matching',(field)=>{const plan=compileSourcingPlan(request([{id:'field',importance:'required',operator:'equals',field,value:'x'}]),new SourceRegistry([fixture('source')]));expect(plan.legs[0]?.appliedConstraintIds).toEqual(['field'])})
 it('rejects duplicate normalized fields and unsupported near matches',()=>{expect(()=>new SourceRegistry([fixture('source',{fields:['Color',' colour ']})])).toThrow(/Duplicate normalized/);const plan=compileSourcingPlan(request([{id:'near',importance:'required',operator:'equals',field:'colors',value:'Blue'}]),new SourceRegistry([fixture('source')]));expect(plan.legs[0]?.appliedConstraintIds).toEqual([])})
 it('prioritizes mandatory constraints and never claims overflow as applied',()=>{const constraints=[{id:'preference',importance:'preferred' as const,operator:'equals' as const,field:'color',value:'Green'},{id:'required',importance:'required' as const,operator:'equals' as const,field:'condition',value:'new'}],plan=compileSourcingPlan(request(constraints),new SourceRegistry([fixture('limited',{constraintSemantics:{requiredHardFilter:true,softPreference:true,negativeFilter:false},limits:{maximumResults:50,maximumQueryLength:500,maximumConstraints:1}})])),leg=plan.legs[0]!;expect(leg.appliedConstraintIds).toEqual(['required']);expect(leg.projectedInput.appliedConstraints.map(item=>item.id)).toEqual(['required']);expect(leg.limitations).toEqual(expect.arrayContaining([expect.objectContaining({constraintId:'preference',reason:expect.stringContaining('limit')})]))})
 it('separates per-source limitations from globally unresolved gaps',()=>{const constraint={id:'color',importance:'required' as const,operator:'equals' as const,field:'color',value:'Blue'},plan=compileSourcingPlan(request([constraint]),new SourceRegistry([fixture('a',{fields:[]}),fixture('b')]));expect(plan.legs.find(leg=>leg.source.id==='a')?.limitations).toHaveLength(1);expect(plan.mandatoryGaps).toEqual([]);const unresolved=compileSourcingPlan(request([constraint]),new SourceRegistry([fixture('a',{fields:[]}),fixture('b',{fields:[]})]));expect(unresolved.mandatoryGaps).toHaveLength(1)})
 it('does not truncate over-limit queries or call the source',async()=>{const search=vi.fn(async()=>empty()),source=fixture('short',{limits:{maximumResults:50,maximumQueryLength:4,maximumConstraints:4}},search),coordinator=new SourcingCoordinator(new SourceRegistry([source])),result=await coordinator.search(request([],{resource:{...base().resource,searchFocus:'long query'}}));expect(result.plan.legs[0]).toMatchObject({executable:false,projectedInput:{query:'long query'}});expect(search).not.toHaveBeenCalled()})
 it.each([['provider_explicit','source_explicit'],['provider_inferred','source_inferred'],['cosource_derived','cosource_derived'],['unknown','unknown']] as const)('maps %s provenance exactly',(kind,expected)=>{const source=createCatalogSourcingSource({search:vi.fn(),product:vi.fn()}),candidate=(source.search as never);void candidate;const item=product(kind);expect(item.attributes?.provenance.kind).toBe(kind);const search=vi.fn(async()=>({products:[item],messages:[],pagination:{hasMore:false}})),adapter=createCatalogSourcingSource({search,product:vi.fn()},()=> '2026-09-07T12:00:00+01:00');return expect(adapter.search({requirementId:'r',requirementRevision:0,resourceType:'product',channel:'human',criteriaKey:'c',query:'coat',intent:'coat',market:{country:'GB',currency:'GBP'},approvalPolicy:{consequentialDecision:'requester_approval_required',fulfillmentAuthority:'recommendation_only'},appliedConstraints:[],resultLimit:1})).resolves.toMatchObject({output:{candidates:[{facts:[{provenance:expected}]}]}})})
 it('rejects impossible inspection declarations before use',()=>expect(()=>new SourceRegistry([{...fixture('bad'),declaration:{...fixture('bad').declaration,capabilities:caps({inspection:true})}}])).toThrow(/inspection declaration/))
})

describe('R5R source output validation',()=>{
 const candidate=(sourceId='source')=>({identity:{sourceId,id:'candidate'},resourceType:'product',label:'Candidate',provenance:{sourceId,trust:'authoritative_provider' as const,retrievedAt:'2026-09-07T12:00:00+01:00'},externalDataTrust:'untrusted_external_data' as const,facts:[],inspection:{supported:false}})
 const run=(output:unknown)=>new SourcingCoordinator(new SourceRegistry([fixture('source',{},vi.fn(async()=>output as never))])).search(request())
 it('rejects candidate source/provenance mismatch and duplicates',async()=>{await expect(run({output:{candidates:[candidate('other')],messages:[]},specializedCandidates:['x']})).rejects.toThrow();await expect(run({output:{candidates:[candidate(),candidate()],messages:[]},specializedCandidates:['x','y']})).rejects.toThrow(/Duplicate/)})
 it('rejects unbounded messages, unsafe totals, and unknown output fields',async()=>{await expect(run({output:{candidates:[],messages:Array.from({length:51},()=>({level:'info',text:'x'}))},specializedCandidates:[]})).rejects.toThrow();await expect(run({output:{candidates:[],messages:[],estimatedTotal:Number.MAX_SAFE_INTEGER+1},specializedCandidates:[]})).rejects.toThrow();await expect(run({output:{candidates:[],messages:[],rawProvider:{}},specializedCandidates:[]})).rejects.toThrow()})
 it('rejects returned continuation mismatch before exposing results',async()=>{await expect(run({output:{candidates:[],messages:[],continuation:{sourceId:'other',requirementId:'requirement',requirementRevision:2,channel:'human',criteriaKey:'criteria',opaqueCursor:'x'}},specializedCandidates:[]})).rejects.toThrow(/continuation/)})
})
