import {describe,expect,it,vi} from 'vitest'
import type {ResourceRequirement} from '../requirements'
import type {ResourceCandidate,SourceCapabilities,SourcingSource} from './domain/source-contracts'
import type {ProductCluster} from '../commerce/domain/commerce'
import {createCoSourceApplication} from '../application/cosource-application'
import {durableProjection} from '../application/persistence/workspace-persistence'
import {SourceRegistry} from './source-registry'
import {SourcingCoordinator} from './sourcing-coordinator'

const capabilities=(changes:Partial<SourceCapabilities>={}):SourceCapabilities=>({resourceTypes:['product'],search:true,inspection:false,pagination:true,market:{country:true,currency:true,language:false,location:false},constraintSemantics:{requiredHardFilter:true,softPreference:false,negativeFilter:false},constraintOperators:[],fields:[],attributeFamilies:[],quantityAware:false,deadlineAware:false,availabilityEvidence:false,costFilter:false,freshnessEvidence:false,compatibilityEvidence:false,licensingEvidence:false,limits:{maximumResults:10,maximumQueryLength:100,maximumConstraints:0},...changes})
const candidate=(id:string,changes:Partial<ResourceCandidate>={}):ResourceCandidate=>({identity:{sourceId:'products',id},resourceType:'product',label:id,provenance:{sourceId:'products',trust:'authoritative_provider',retrievedAt:'2026-09-08T12:00:00Z'},externalDataTrust:'untrusted_external_data',facts:[],inspection:{supported:false},...changes})
const source=(search:SourcingSource<string>['search'],changes:Partial<SourceCapabilities>={}):SourcingSource<string>=>({declaration:{identity:{id:'products',kind:'fixture',name:'Products',version:'1',trust:'authoritative_provider'},capabilities:capabilities(changes)},specializedIdentity:value=>({sourceId:'products',id:value}),search})
const requirement:ResourceRequirement={id:'requirement',revision:1,context:{requester:{kind:'test'}},resource:{type:'product',purpose:'Find products',searchFocus:'products',specification:[]},constraints:[],compatibility:[],market:{country:'GB',currency:'GBP'},qualityFloor:[],existingResources:[],preferredSources:[],excludedSources:[],riskLimits:[],approvalPolicy:{consequentialDecision:'requester_approval_required',fulfillmentAuthority:'recommendation_only'}}
const request=(changes:Record<string,unknown>={})=>({...requirement,channel:'human' as const,criteriaKey:'criteria',resultLimit:1,...changes})

describe('R5R2 source result boundary reproductions',()=>{
 it('rejects a reversed neutral/specialized association',async()=>{const search=vi.fn(async()=>({output:{candidates:[candidate('one'),candidate('two')],messages:[]},specializedCandidates:['two','one']})),coordinator=new SourcingCoordinator(new SourceRegistry([source(search)]));await expect(coordinator.search(request({resultLimit:2}))).rejects.toThrow(/candidate.*association/i)})
 it('rejects a candidate of the wrong resource type',async()=>{const search=vi.fn(async()=>({output:{candidates:[candidate('one',{resourceType:'service'})],messages:[]},specializedCandidates:['one']})),coordinator=new SourcingCoordinator(new SourceRegistry([source(search)]));await expect(coordinator.search(request())).rejects.toThrow(/resource type/i)})
 it('rejects results beyond the projected leg limit',async()=>{const search=vi.fn(async()=>({output:{candidates:[candidate('one'),candidate('two')],messages:[]},specializedCandidates:['one','two']})),coordinator=new SourcingCoordinator(new SourceRegistry([source(search)]));await expect(coordinator.search(request())).rejects.toThrow(/result limit/i)})
 it('rejects continuation returned by a source without pagination',async()=>{const continuation={sourceId:'products',requirementId:'requirement',requirementRevision:1,channel:'human' as const,criteriaKey:'criteria',opaqueCursor:'next'},search=vi.fn(async()=>({output:{candidates:[],messages:[],continuation},specializedCandidates:[]})),coordinator=new SourcingCoordinator(new SourceRegistry([source(search,{pagination:false})]));await expect(coordinator.search(request())).rejects.toThrow(/pagination/i)})
 it('rejects contradictory trust and inspection claims',async()=>{const trust=vi.fn(async()=>({output:{candidates:[candidate('one',{provenance:{sourceId:'products',trust:'unknown',retrievedAt:'2026-09-08T12:00:00Z'}})],messages:[]},specializedCandidates:['one']})),inspection=vi.fn(async()=>({output:{candidates:[candidate('one',{inspection:{supported:true,reference:'one'}})],messages:[]},specializedCandidates:['one']}));await expect(new SourcingCoordinator(new SourceRegistry([source(trust)])).search(request())).rejects.toThrow(/trust/i);await expect(new SourcingCoordinator(new SourceRegistry([source(inspection)])).search(request())).rejects.toThrow(/inspection/i)})
 it('rejects duplicate specialized identities',async()=>{const search=vi.fn(async()=>({output:{candidates:[candidate('one'),candidate('two')],messages:[]},specializedCandidates:['one','one']}));await expect(new SourcingCoordinator(new SourceRegistry([source(search)])).search(request({resultLimit:2}))).rejects.toThrow(/Duplicate specialized/)})
 it('keeps an all-or-nothing multi-source failure bound to its source',async()=>{const failed=source(vi.fn(async()=>{throw new Error('offline')})),later={...source(vi.fn(async()=>({output:{candidates:[],messages:[]},specializedCandidates:[]}))),declaration:{...source(vi.fn()).declaration,identity:{...source(vi.fn()).declaration.identity,id:'z-products',name:'Z Products'}}},coordinator=new SourcingCoordinator(new SourceRegistry([later,failed]));await expect(coordinator.search(request())).rejects.toMatchObject({sourceId:'products'});expect(later.search).not.toHaveBeenCalled()})
 it('rejects ambiguous provider ownership at registration',()=>{const first={...source(vi.fn()),declaration:{...source(vi.fn()).declaration,identity:{...source(vi.fn()).declaration.identity,providerId:'provider'}}},second={...first,declaration:{...first.declaration,identity:{...first.declaration.identity,id:'other'}}};expect(()=>new SourceRegistry([first,second])).toThrow(/Ambiguous provider binding/)})
 it('rejects an inspected specialized identity that does not match the request',async()=>{const base=source(vi.fn(),{inspection:true}),inspectable:SourcingSource<string>={...base,declaration:{...base.declaration,capabilities:{...base.declaration.capabilities,inspection:true}},inspect:async()=>({candidate:{...candidate('one'),inspection:{supported:true,reference:'one'}},specializedCandidate:'other'})};await expect(new SourcingCoordinator(new SourceRegistry([inspectable])).inspect('products',{sourceId:'products',id:'one'},{country:'GB',currency:'GBP'})).rejects.toThrow(/mismatched inspected/)})
})

const commerceProvider='shopify_global_catalog' as const,commerceProvenance={kind:'provider_explicit' as const,provider:commerceProvider}
const product=(id:string):ProductCluster=>({identity:{provider:commerceProvider,id},title:{value:id,provenance:commerceProvenance},media:[],offers:[],offerCompleteness:'provider_returned_unknown',provenance:commerceProvenance})
const productSource=(id:string,providerId:string,search:SourcingSource<ProductCluster>['search'],inspect?:SourcingSource<ProductCluster>['inspect']):SourcingSource<ProductCluster>=>({declaration:{identity:{id,kind:'product_fixture',name:id,providerId,version:'1',trust:'aggregated_provider'},capabilities:{...capabilities({inspection:Boolean(inspect)}),resourceTypes:['product'],inspection:Boolean(inspect)}},specializedIdentity:item=>({sourceId:id,id:item.identity.id}),search,...(inspect?{inspect}:{})})
const sourceResult=(sourceId:string,items:ProductCluster[],cursor?:string,inspectable=false)=>({output:{candidates:items.map(item=>({identity:{sourceId,id:item.identity.id},resourceType:'product',label:item.title.value,provenance:{sourceId,trust:'aggregated_provider' as const,retrievedAt:'2026-09-08T12:00:00Z'},externalDataTrust:'untrusted_external_data' as const,facts:[],inspection:inspectable?{supported:true,reference:item.identity.id}:{supported:false}})),messages:[],continuation:cursor?{sourceId,requirementId:'session',requirementRevision:0,channel:'human' as const,criteriaKey:'unused',opaqueCursor:cursor}:undefined},specializedCandidates:items})

describe('R5R2 purchasing source ownership',()=>{
 it('selects one explicit source so limits and pagination cannot multiply',async()=>{const a=vi.fn(async()=>sourceResult('a',[product('a')],undefined)),b=vi.fn(async()=>sourceResult('b',[product('b')])),app=createCoSourceApplication({market:{country:'GB',currency:'GBP'},catalog:{search:vi.fn(),product:vi.fn()},sources:[productSource('b','provider-b',b),productSource('a','provider-a',a)]});const result=await app.searchCandidates({query:'packs',limit:1});expect(result).toMatchObject({ok:true,value:{products:[{identity:{id:'a'}}],pagination:{hasMore:false}}});expect(a).toHaveBeenCalledOnce();expect(b).not.toHaveBeenCalled()})
 it('executes a continuation only against its explicitly selected owner',async()=>{const a=vi.fn(async input=>({output:{...sourceResult('a',[product(input.continuation?'a2':'a1')]).output,continuation:input.continuation?undefined:{sourceId:'a',requirementId:input.requirementId,requirementRevision:input.requirementRevision,channel:input.channel,criteriaKey:input.criteriaKey,opaqueCursor:'next'}},specializedCandidates:[product(input.continuation?'a2':'a1')]})),b=vi.fn(async()=>sourceResult('b',[product('b')])),app=createCoSourceApplication({market:{country:'GB',currency:'GBP'},catalog:{search:vi.fn(),product:vi.fn()},sources:[productSource('a','provider-a',a),productSource('b','provider-b',b)]});
  const first=await app.searchCandidates({query:'packs',limit:1});expect(first).toMatchObject({ok:true,value:{pagination:{hasMore:true,cursor:'next'}}});expect(await app.searchCandidates({query:'packs',limit:1,cursor:'next'})).toMatchObject({ok:true,value:{products:[{identity:{id:'a2'}}],pagination:{hasMore:false}}});expect(a).toHaveBeenCalledTimes(2);expect(b).not.toHaveBeenCalled()})
 it('routes inspection and restored refresh to the owning registered source',async()=>{const item=product('owned'),inspect=vi.fn(async()=>({candidate:{identity:{sourceId:'custom',id:'owned'},resourceType:'product',label:'owned',provenance:{sourceId:'custom',trust:'aggregated_provider' as const,retrievedAt:'2026-09-08T12:00:00Z'},externalDataTrust:'untrusted_external_data' as const,facts:[],inspection:{supported:true,reference:'owned'}},specializedCandidate:item})),search=vi.fn(async()=>sourceResult('custom',[item],undefined,true)),make=()=>createCoSourceApplication({market:{country:'GB',currency:'GBP'},catalog:{search:vi.fn(),product:vi.fn()},sources:[productSource('custom',commerceProvider,search,inspect)]}),first=make();await first.searchCandidates({query:'owned'});expect((await first.inspectCandidate(item.identity)).ok).toBe(true);const saved=durableProjection(first.getSnapshot()),second=make();second.restoreWorkspace(saved);expect((await second.refreshRetainedEvidence(item.identity)).ok).toBe(true);expect(inspect).toHaveBeenCalledTimes(2)})
 it('fails unknown ownership before inspection and preserves retained evidence',async()=>{const item=product('owned'),inspect=vi.fn(),search=vi.fn(async()=>sourceResult('custom',[item])),app=createCoSourceApplication({market:{country:'GB',currency:'GBP'},catalog:{search:vi.fn(),product:vi.fn()},sources:[productSource('custom','different-provider',search,inspect)]});await app.searchCandidates({query:'owned'});app.retainCandidate(item.identity);const before=app.getSnapshot().retainedEvidence;expect(await app.refreshRetainedEvidence(item.identity)).toMatchObject({ok:false,code:'evidence_unavailable'});expect(inspect).not.toHaveBeenCalled();expect(app.getSnapshot().retainedEvidence).toBe(before)})
 it('keeps invalid source output out of discovery, evidence, plan, and success activity',async()=>{const item=product('bad'),invalid=sourceResult('custom',[item]);invalid.output.candidates[0]!.resourceType='service';const app=createCoSourceApplication({market:{country:'GB',currency:'GBP'},catalog:{search:vi.fn(),product:vi.fn()},sources:[productSource('custom','provider',vi.fn(async()=>invalid))]}),plan=app.getSnapshot().plan;const result=await app.sourceCandidatesForAgent({query:'bad',market:{country:'GB',currency:'GBP'}});expect(result).toMatchObject({ok:false});expect(app.getSnapshot().agentDiscovery).toMatchObject({status:'error',candidates:[],pagination:{hasMore:false}});expect(app.getSnapshot().retainedEvidence).toEqual([]);expect(app.getSnapshot().plan).toBe(plan);expect(app.getSnapshot().activities[0]).toMatchObject({kind:'agent_search',outcome:'failure'})})
})
