import {describe,expect,it,vi} from 'vitest'
import type {ProductCluster} from '../commerce/domain/commerce'
import {createCoSourceApplication} from '../application/cosource-application'
import type {ResourceRequirement} from '../requirements'
import type {SourceCapabilities,SourcingSource} from './domain/source-contracts'
import {SourceRegistry} from './source-registry'
import {compileSourcingPlan,SourcingCoordinator} from './sourcing-coordinator'

const capabilities=(changes:Partial<SourceCapabilities>={}):SourceCapabilities=>({resourceTypes:['product'],search:true,inspection:false,pagination:true,market:{country:true,currency:true,language:false,location:false},constraintSemantics:{requiredHardFilter:true,softPreference:true,negativeFilter:false},constraintOperators:['equals'],fields:['condition'],attributeFamilies:[],quantityAware:false,deadlineAware:false,availabilityEvidence:true,costFilter:true,freshnessEvidence:false,compatibilityEvidence:false,licensingEvidence:false,limits:{maximumResults:20,maximumQueryLength:500,maximumConstraints:20},...changes})
const empty=()=>({output:{candidates:[],messages:[]},specializedCandidates:[]})
const source=(id:string,changes:Partial<SourceCapabilities>={},search=vi.fn(async()=>empty())):SourcingSource<string>=>({declaration:{identity:{id,kind:'fixture',name:id,version:'1',trust:'authoritative_provider'},capabilities:capabilities(changes)},specializedIdentity:value=>({sourceId:id,id:value}),search})
const requirement:ResourceRequirement={id:'requirement',revision:1,context:{requester:{kind:'test'}},resource:{type:'product',purpose:'Find a product',searchFocus:'product',specification:[]},quantity:{amount:2,unit:'items'},constraints:[{id:'must',importance:'required',operator:'equals',field:'condition',value:'new'},{id:'prefer',importance:'preferred',operator:'equals',field:'condition',value:'blue'}],compatibility:[],market:{country:'GB',currency:'GBP'},cost:{unitCeiling:{minorAmount:1000,currency:'GBP'}},qualityFloor:[],existingResources:[],preferredSources:[],excludedSources:[],riskLimits:[],approvalPolicy:{consequentialDecision:'requester_approval_required',fulfillmentAuthority:'recommendation_only'}}
const request=(changes:Record<string,unknown>={})=>({...requirement,channel:'human' as const,criteriaKey:'criteria',resultLimit:10,...changes})

describe('R5R3 capability-first source selection',()=>{
 it('puts a fully mandatory-capable source before a less-capable preferred source',()=>{const registry=new SourceRegistry([source('limited',{quantityAware:false,costFilter:false}),source('capable',{quantityAware:true,costFilter:true})]);const plan=compileSourcingPlan(request({preferredSources:[{name:'limited'}]}),registry);expect(plan.legs.map(leg=>leg.source.id)).toEqual(['capable','limited']);expect(plan.legs[0]!.selectionReasons.join(' ')).toMatch(/mandatory/i)})
 it('puts a more capable source before a lexicographically earlier source',()=>{const registry=new SourceRegistry([source('a-limited',{quantityAware:false}),source('z-capable',{quantityAware:true})]);expect(compileSourcingPlan(request(),registry).legs.map(leg=>leg.source.id)).toEqual(['z-capable','a-limited'])})
 it('uses requester preference only when mandatory capability is equal',()=>{const registry=new SourceRegistry([source('a-source',{quantityAware:true}),source('z-source',{quantityAware:true})]);expect(compileSourcingPlan(request({preferredSources:[{name:'z-source'}]}),registry).legs.map(leg=>leg.source.id)).toEqual(['z-source','a-source'])})
 it('uses stable source ID when capability and preference are equal',()=>{const registry=new SourceRegistry([source('z-source',{quantityAware:true}),source('a-source',{quantityAware:true})]);expect(compileSourcingPlan(request(),registry).legs.map(leg=>leg.source.id)).toEqual(['a-source','z-source'])})
 it('places a non-executable source after executable sources',()=>{const registry=new SourceRegistry([source('a-short',{limits:{maximumResults:20,maximumQueryLength:2,maximumConstraints:20}}),source('z-long',{limits:{maximumResults:20,maximumQueryLength:500,maximumConstraints:20}})]);expect(compileSourcingPlan(request(),registry).legs.map(leg=>leg.source.id)).toEqual(['z-long','a-short'])})
 it('is invariant to registry input order',()=>{const sources=[source('limited',{quantityAware:false}),source('capable',{quantityAware:true})];expect(compileSourcingPlan(request(),new SourceRegistry(sources)).legs.map(leg=>leg.source.id)).toEqual(compileSourcingPlan(request(),new SourceRegistry([...sources].reverse())).legs.map(leg=>leg.source.id))})
 it('removes warnings belonging only to an unselected source',async()=>{const selected=source('selected',{quantityAware:true,limits:{maximumResults:20,maximumQueryLength:500,maximumConstraints:20}}),unselected=source('unselected',{quantityAware:true,limits:{maximumResults:2,maximumQueryLength:500,maximumConstraints:20}}),result=await new SourcingCoordinator(new SourceRegistry([unselected,selected])).searchSource(request(),'selected');expect(result.plan.legs).toHaveLength(1);expect(result.plan.legs[0]!.projectedInput.resultLimit).toBe(10);expect(result.plan.capabilityWarnings).toEqual([]);expect(selected.search).toHaveBeenCalledOnce();expect(unselected.search).not.toHaveBeenCalled()})
})

const provider='shopify_global_catalog' as const,provenance={kind:'provider_explicit' as const,provider}
const product:ProductCluster={identity:{provider,id:'owned'},title:{value:'Owned',provenance},media:[],offers:[],offerCompleteness:'provider_returned_unknown',provenance}
const nonInspectableSource:SourcingSource<ProductCluster>={declaration:{identity:{id:'products',kind:'fixture',name:'Products',providerId:provider,version:'1',trust:'aggregated_provider'},capabilities:capabilities()},specializedIdentity:item=>({sourceId:'products',id:item.identity.id}),search:vi.fn(async()=>({output:{candidates:[{identity:{sourceId:'products',id:'owned'},resourceType:'product',label:'Owned',provenance:{sourceId:'products',trust:'aggregated_provider' as const,retrievedAt:'2026-09-08T12:00:00Z'},externalDataTrust:'untrusted_external_data' as const,facts:[],inspection:{supported:false}}],messages:[]},specializedCandidates:[product]}))}

describe('R5R3 inspection-owner eligibility',()=>{
 it('rejects candidate inspection before retaining evidence or changing session state',async()=>{const catalog={search:vi.fn(),product:vi.fn()},app=createCoSourceApplication({catalog,market:{country:'GB',currency:'GBP'},sources:[nonInspectableSource]});await app.searchCandidates({query:'owned'});const before=structuredClone(app.getSnapshot());expect(await app.inspectCandidate(product.identity)).toMatchObject({ok:false,code:'evidence_unavailable'});expect(catalog.product).not.toHaveBeenCalled();expect(app.getSnapshot()).toEqual(before)})
 it('rejects retained-evidence refresh before allocating refresh lifecycle',async()=>{const catalog={search:vi.fn(),product:vi.fn()},app=createCoSourceApplication({catalog,market:{country:'GB',currency:'GBP'},sources:[nonInspectableSource]});await app.searchCandidates({query:'owned'});app.retainCandidate(product.identity);const before=structuredClone(app.getSnapshot());expect(await app.refreshRetainedEvidence(product.identity)).toMatchObject({ok:false,code:'evidence_unavailable'});expect(catalog.product).not.toHaveBeenCalled();expect(app.getSnapshot()).toEqual(before)})
})
