import {describe,expect,it} from 'vitest'
import {resourceCandidateSchema,resourceSourcingRequestSchema,sourceCapabilitiesSchema,sourceDeclarationSchema} from './domain/source-contracts'

const requirement={id:'requirement-1',revision:3,context:{requester:{kind:'corap_presence_os',id:'presence-1'}},resource:{type:'service',purpose:'Accessibility audit',searchFocus:'WCAG audit',specification:[]},quantity:{amount:1,unit:'engagement'},constraints:[],compatibility:[],deadline:{neededBy:'2026-10-01T12:00:00+01:00',timezone:'Europe/London'},market:{country:'GB',currency:'GBP',location:'London'},cost:{totalBudget:{minorAmount:500000,currency:'GBP'}},qualityFloor:[],existingResources:[],preferredSources:[],excludedSources:[],riskLimits:[],evidenceFreshness:{maximumAgeDays:30},approvalPolicy:{consequentialDecision:'requester_approval_required',fulfillmentAuthority:'recommendation_only'},channel:'human',criteriaKey:'criteria-1',resultLimit:10} as const
const capabilities={resourceTypes:['service'],search:true,inspection:false,pagination:true,market:{country:true,currency:true,language:false,location:true},constraintSemantics:{requiredHardFilter:true,softPreference:false,negativeFilter:false},constraintOperators:['equals'],fields:['standard'],attributeFamilies:[],quantityAware:true,deadlineAware:true,availabilityEvidence:false,costFilter:false,freshnessEvidence:true,compatibilityEvidence:false,licensingEvidence:false,limits:{maximumResults:20,maximumQueryLength:500,maximumConstraints:20}} as const

describe('universal sourcing contracts',()=>{
 it('strictly validates a fully bound sourcing request',()=>expect(resourceSourcingRequestSchema.parse(requirement)).toEqual(requirement))
 it('rejects unknown properties and oversized collections',()=>{expect(resourceSourcingRequestSchema.safeParse({...requirement,provider:'secret'}).success).toBe(false);expect(resourceSourcingRequestSchema.safeParse({...requirement,constraints:Array.from({length:91},(_,i)=>({id:`c${i}`,importance:'required',operator:'free_text',value:'x'}))}).success).toBe(false)})
 it('rejects invalid capability declarations',()=>{expect(sourceCapabilitiesSchema.safeParse({...capabilities,resourceTypes:[]}).success).toBe(false);expect(sourceCapabilitiesSchema.safeParse({...capabilities,search:false,pagination:true}).success).toBe(false)})
 it('accepts bounded extensible source and resource kinds',()=>expect(sourceDeclarationSchema.parse({identity:{id:'service-a',kind:'regional_service_directory',name:'Services A',version:'2026-09',trust:'authoritative_provider'},capabilities}).identity.kind).toBe('regional_service_directory'))
 it('validates neutral source-scoped untrusted candidates without retail fields',()=>{const candidate=resourceCandidateSchema.parse({identity:{sourceId:'assets',id:'asset-1'},resourceType:'licensed_creative_asset',label:'City skyline',summary:'Rights-managed photograph',provenance:{sourceId:'assets',trust:'authoritative_provider',retrievedAt:'2026-09-07T12:00:00+01:00'},externalDataTrust:'untrusted_external_data',facts:[{name:'license',value:'Editorial',provenance:'source_explicit'}],inspection:{supported:true,reference:'asset-1'}});expect(candidate.externalDataTrust).toBe('untrusted_external_data');expect(candidate).not.toHaveProperty('rawPayload');expect(candidate).not.toHaveProperty('offers')})
})
