import {describe,expect,it,vi} from 'vitest'
import type {ResourceRequirement} from '../requirements'
import type {SourceCapabilities,SourcingSource} from './domain/source-contracts'
import {SourceRegistry} from './source-registry'
import {compileSourcingPlan,SourcingCoordinator} from './sourcing-coordinator'

const capability=(resourceTypes:string[],changes:Partial<SourceCapabilities>={}):SourceCapabilities=>({resourceTypes,search:true,inspection:false,pagination:true,market:{country:true,currency:true,language:true,location:true},constraintSemantics:{requiredHardFilter:true,softPreference:false,negativeFilter:false},constraintOperators:['equals'],fields:['grade','standard','platform','license'],attributeFamilies:[],quantityAware:true,deadlineAware:true,availabilityEvidence:true,costFilter:true,freshnessEvidence:true,compatibilityEvidence:true,licensingEvidence:false,limits:{maximumResults:20,maximumQueryLength:500,maximumConstraints:20},...changes})
const source=(id:string,types:string[],search=vi.fn(async()=>({output:{candidates:[],messages:[]},specializedCandidates:[]})),changes:Partial<SourceCapabilities>={}):SourcingSource<string>=>({declaration:{identity:{id,kind:'test_fixture',name:id,version:'1',trust:'authoritative_provider'},capabilities:capability(types,changes)},specializedIdentity:value=>({sourceId:id,id:value}),search})
const requirement=(type:string,changes:Partial<ResourceRequirement>={}):ResourceRequirement=>({id:'requirement-1',revision:4,context:{requester:{kind:'test'}},resource:{type,purpose:`Find ${type}`,searchFocus:type,specification:[]},quantity:{amount:2,unit:'units'},constraints:[{id:'must',importance:'required',operator:'equals',field:type==='material'?'grade':'standard',value:'A'},{id:'prefer',importance:'preferred',operator:'is_true',field:'local'}],compatibility:[],deadline:{neededBy:'2026-10-01T12:00:00+01:00'},market:{country:'GB',currency:'GBP',location:'London'},qualityFloor:[],existingResources:[],preferredSources:[],excludedSources:[],riskLimits:[],evidenceFreshness:{maximumAgeDays:7},approvalPolicy:{consequentialDecision:'requester_approval_required',fulfillmentAuthority:'recommendation_only'},...changes})
const request=(type:string,changes:Record<string,unknown>={})=>({...requirement(type),channel:'human' as const,criteriaKey:'criteria-1',resultLimit:10,...changes})

describe('capability-aware sourcing coordinator',()=>{
 it('rejects duplicate stable source IDs',()=>expect(()=>new SourceRegistry([source('same',['material']),source('same',['service'])])).toThrow(/Duplicate source ID/))
 it.each(['material','service','software_subscription','licensed_creative_asset'])('selects a %s fixture without kernel category branches',type=>expect(compileSourcingPlan(request(type),new SourceRegistry([source(`${type}-source`,[type])])).legs[0]?.source.id).toBe(`${type}-source`))
 it('preserves mandatory and preference gaps separately',()=>{const plan=compileSourcingPlan(request('material'),new SourceRegistry([source('materials',['material'])]));expect(plan.mandatoryGaps).toEqual([]);expect(plan.preferenceGaps).toMatchObject([{constraintId:'prefer',relevance:'preference'}]);expect(plan.legs[0]).toMatchObject({appliedConstraintIds:['must'],fullyCapable:true})})
 it('matches constraint operators and fields rather than source-array position',()=>{const plan=compileSourcingPlan(request('material'),new SourceRegistry([source('unsupported',['material'],undefined,{constraintOperators:[],fields:[]}),source('supported',['material'])]));expect(plan.legs.find(item=>item.source.id==='unsupported')).toMatchObject({appliedConstraintIds:[],fullyCapable:false});expect(plan.legs.find(item=>item.source.id==='supported')?.appliedConstraintIds).toEqual(['must'])})
 it('never invokes excluded or unsupported sources',async()=>{const excludedCall=vi.fn(),wrongCall=vi.fn(),registry=new SourceRegistry([source('blocked',['material'],excludedCall),source('services',['service'],wrongCall)]),coordinator=new SourcingCoordinator(registry);const result=await coordinator.search(request('material',{excludedSources:[{name:'blocked'}]}));expect(result.plan.legs).toEqual([]);expect(excludedCall).not.toHaveBeenCalled();expect(wrongCall).not.toHaveBeenCalled()})
 it('orders suitable preferred sources deterministically without selecting a winner',()=>{const registry=new SourceRegistry([source('z-source',['material']),source('a-source',['material'])]),plan=compileSourcingPlan(request('material',{preferredSources:[{name:'z-source'}]}),registry);expect(plan.legs.map(item=>item.source.id)).toEqual(['z-source','a-source']);expect(plan.legs).toHaveLength(2)})
 it('propagates market, location, deadline, quantity, freshness gaps and recommendation-only authority',()=>{const plan=compileSourcingPlan(request('service'),new SourceRegistry([source('services',['service'],undefined,{freshnessEvidence:false})])),leg=plan.legs[0]!;expect(leg.projectedInput).toMatchObject({market:{country:'GB',currency:'GBP',location:'London'},quantity:{amount:2},deadline:{neededBy:'2026-10-01T12:00:00+01:00'},approvalPolicy:{fulfillmentAuthority:'recommendation_only'}});expect(plan.mandatoryGaps.some(item=>item.description==='Evidence freshness')).toBe(true)})
 it('performs no provider call during capability-only compilation',()=>{const search=vi.fn(),registry=new SourceRegistry([source('materials',['material'],search)]);compileSourcingPlan(request('material'),registry);expect(search).not.toHaveBeenCalled()})
 it('binds continuation to source, requirement revision, channel and criteria',async()=>{const search=vi.fn(async()=>({output:{candidates:[],messages:[]},specializedCandidates:[]})),coordinator=new SourcingCoordinator(new SourceRegistry([source('materials',['material'],search)])),continuation={sourceId:'materials',requirementId:'requirement-1',requirementRevision:4,channel:'human' as const,criteriaKey:'criteria-1',opaqueCursor:'opaque'};await coordinator.search(request('material',{continuation}));expect(search).toHaveBeenCalledOnce();await expect(coordinator.search(request('material',{revision:5,continuation}))).rejects.toThrow(/Continuation/);await expect(coordinator.search(request('material',{channel:'agent',continuation}))).rejects.toThrow(/Continuation/);await expect(coordinator.search(request('material',{criteriaKey:'other',continuation}))).rejects.toThrow(/Continuation/);expect(search).toHaveBeenCalledOnce()})
})
