import {z} from 'zod'
import {resourceRequirementSchema} from '../../requirements/domain/resource-requirement'
import {normalizeSourceField} from '../field-normalization'

const id=z.string().trim().min(1).max(100),kind=z.string().trim().min(1).max(100),text=z.string().trim().min(1).max(1000),safeCount=z.number().int().safe().min(0)
export const constraintOperatorSchema=z.enum(['free_text','equals','is_true','is_false','at_most','at_least'])
export const sourceIdentitySchema=z.object({id,kind,name:z.string().trim().min(1).max(200),providerId:id.optional(),version:z.string().trim().min(1).max(50),trust:z.enum(['first_party','authoritative_provider','aggregated_provider','unknown'])}).strict()
export const sourceCapabilitiesSchema=z.object({resourceTypes:z.array(kind).min(1).max(50),search:z.boolean(),inspection:z.boolean(),pagination:z.boolean(),market:z.object({country:z.boolean(),currency:z.boolean(),language:z.boolean(),location:z.boolean()}).strict(),constraintSemantics:z.object({requiredHardFilter:z.boolean(),softPreference:z.boolean(),negativeFilter:z.boolean()}).strict(),constraintOperators:z.array(constraintOperatorSchema).max(6),fields:z.array(z.string().trim().min(1).max(200)).max(100),attributeFamilies:z.array(z.string().trim().min(1).max(200)).max(50),quantityAware:z.boolean(),deadlineAware:z.boolean(),availabilityEvidence:z.boolean(),costFilter:z.boolean(),freshnessEvidence:z.boolean(),compatibilityEvidence:z.boolean(),licensingEvidence:z.boolean(),limits:z.object({maximumResults:z.number().int().min(1).max(500),maximumQueryLength:z.number().int().min(1).max(5000),maximumConstraints:z.number().int().min(0).max(500)}).strict()}).strict().superRefine((value,ctx)=>{if(new Set(value.resourceTypes).size!==value.resourceTypes.length)ctx.addIssue({code:'custom',message:'Duplicate resource type'});if(new Set(value.constraintOperators).size!==value.constraintOperators.length)ctx.addIssue({code:'custom',message:'Duplicate constraint operator'});const fields=value.fields.map(normalizeSourceField);if(new Set(fields).size!==fields.length)ctx.addIssue({code:'custom',message:'Duplicate normalized capability field'});if(!value.search&&value.pagination)ctx.addIssue({code:'custom',message:'Pagination requires search support'})})
export const sourceDeclarationSchema=z.object({identity:sourceIdentitySchema,capabilities:sourceCapabilitiesSchema}).strict()
export const continuationSchema=z.object({sourceId:id,requirementId:id,requirementRevision:z.number().int().safe().min(0),channel:z.enum(['human','agent']),criteriaKey:z.string().min(1).max(4096),opaqueCursor:z.string().min(1).max(4096)}).strict()
export const resourceSourcingRequestSchema=resourceRequirementSchema.extend({channel:z.enum(['human','agent']),criteriaKey:z.string().min(1).max(4096),resultLimit:z.number().int().safe().min(1).max(500),continuation:continuationSchema.optional()}).strict()
export type ResourceSourcingRequest=z.infer<typeof resourceSourcingRequestSchema>;export type SourceDeclaration=z.infer<typeof sourceDeclarationSchema>;export type SourceCapabilities=z.infer<typeof sourceCapabilitiesSchema>;export type SourceContinuation=z.infer<typeof continuationSchema>
export const candidateFactSchema=z.object({name:z.string().trim().min(1).max(200),value:z.string().trim().min(1).max(1000),provenance:z.enum(['source_explicit','source_inferred','cosource_derived','unknown'])}).strict()
export const resourceCandidateSchema=z.object({identity:z.object({sourceId:id,id:z.string().trim().min(1).max(500)}).strict(),resourceType:kind,label:z.string().trim().min(1).max(1000),summary:z.string().max(4000).optional(),provenance:z.object({sourceId:id,trust:sourceIdentitySchema.shape.trust,retrievedAt:z.iso.datetime({offset:true})}).strict(),externalDataTrust:z.literal('untrusted_external_data'),facts:z.array(candidateFactSchema).max(50),inspection:z.object({supported:z.boolean(),reference:z.string().min(1).max(1000).optional()}).strict(),refreshReference:z.string().min(1).max(1000).optional()}).strict().superRefine((value,ctx)=>{if(value.identity.sourceId!==value.provenance.sourceId)ctx.addIssue({code:'custom',message:'Candidate provenance source mismatch'});if(!value.inspection.supported&&value.inspection.reference)ctx.addIssue({code:'custom',message:'Unsupported inspection cannot have a reference'})})
export type ResourceCandidate=z.infer<typeof resourceCandidateSchema>
export const sourcingGapSchema=z.object({constraintId:id.optional(),description:text,relevance:z.enum(['mandatory','preference']),reason:text}).strict();export type SourcingGap=z.infer<typeof sourcingGapSchema>
const projectedInputSchema=z.object({requirementId:id,requirementRevision:z.number().int().safe().min(0),resourceType:kind,channel:z.enum(['human','agent']),criteriaKey:z.string().min(1).max(4096),query:z.string().trim().min(1).max(1000),intent:z.string().trim().min(1).max(1000),market:resourceRequirementSchema.shape.market,cost:resourceRequirementSchema.shape.cost,quantity:resourceRequirementSchema.shape.quantity,deadline:resourceRequirementSchema.shape.deadline,approvalPolicy:resourceRequirementSchema.shape.approvalPolicy,appliedConstraints:z.array(resourceRequirementSchema.shape.constraints.element).max(90),resultLimit:z.number().int().safe().min(1).max(500),continuation:continuationSchema.optional()}).strict()
export const compiledSourceLegSchema=z.object({source:sourceIdentitySchema,projectedInput:projectedInputSchema,appliedConstraintIds:z.array(id).max(90),limitations:z.array(sourcingGapSchema).max(100),fullyCapable:z.boolean(),executable:z.boolean(),selectionReasons:z.array(text).max(20)}).strict()
export const compiledSourcingPlanSchema=z.object({requirementId:id,requirementRevision:z.number().int().safe().min(0),market:resourceRequirementSchema.shape.market,resultLimit:z.number().int().safe().min(1).max(500),legs:z.array(compiledSourceLegSchema).max(20),mandatoryGaps:z.array(sourcingGapSchema).max(100),preferenceGaps:z.array(sourcingGapSchema).max(100),capabilityWarnings:z.array(text).max(100)}).strict()
export type CompiledSourceLeg=z.infer<typeof compiledSourceLegSchema>;export type CompiledSourcingPlan=z.infer<typeof compiledSourcingPlanSchema>;export type ProjectedSourceInput=z.infer<typeof projectedInputSchema>
const sourceMessageSchema=z.object({level:z.enum(['info','warning','error','unknown']),code:z.string().max(100).optional(),path:z.string().max(500).optional(),text:z.string().min(1).max(1000)}).strict()
export const sourceSearchOutputSchema=z.object({candidates:z.array(resourceCandidateSchema).max(500),messages:z.array(sourceMessageSchema).max(50),continuation:continuationSchema.optional(),estimatedTotal:safeCount.optional()}).strict().superRefine((value,ctx)=>{const ids=value.candidates.map(item=>`${item.identity.sourceId}\0${item.identity.id}`);if(new Set(ids).size!==ids.length)ctx.addIssue({code:'custom',message:'Duplicate candidate identity'})})
export type SourceSearchOutput=z.infer<typeof sourceSearchOutputSchema>
export interface SourceSearchResult<T>{output:SourceSearchOutput;specializedCandidates:readonly T[]}
export interface SourceInspectionResult<T>{candidate:ResourceCandidate;specializedCandidate:T}
export interface SourcingSource<T>{declaration:SourceDeclaration;specializedIdentity(candidate:T):ResourceCandidate['identity'];search(input:ProjectedSourceInput):Promise<SourceSearchResult<T>>;inspect?(identity:ResourceCandidate['identity'],market:ResourceSourcingRequest['market']):Promise<SourceInspectionResult<T>>}
export interface SourceExecutionResult<T>{sourceId:string;output:SourceSearchOutput;specializedCandidates:readonly T[]}
