import {z} from 'zod'
import {moneySchema,type Money} from '../../shared/domain/money'
import {evidenceStrengthSchema} from '../../evidence/domain/evidence'

export const costCategorySchema=z.enum(['base_price','delivery','tax','import_duty','mandatory_fee','discount','other'])
export const costEvidenceSchema=z.object({strength:evidenceStrengthSchema,source:z.string().trim().min(1).max(100),observedAt:z.iso.datetime({offset:true}).optional()}).strict()
export const costCoverageSchema=z.object({status:z.enum(['complete','partial']),evidence:costEvidenceSchema,unresolvedCategories:z.array(costCategorySchema.exclude(['base_price'])).max(20).optional(),reasons:z.array(z.string().trim().min(1).max(300)).max(20).optional()}).strict().superRefine((value,ctx)=>{const categories=new Set(value.unresolvedCategories??[]),reasons=new Set(value.reasons??[]);if(value.status==='complete'&&(categories.size||reasons.size))ctx.addIssue({code:'custom',message:'Complete coverage cannot contain unresolved evidence'});if(value.status==='partial'&&!categories.size&&!reasons.size)ctx.addIssue({code:'custom',message:'Partial coverage requires an unresolved category or reason'})})
export type CostCoverage=z.infer<typeof costCoverageSchema>
export const costComponentSchema=z.object({id:z.string().trim().min(1).max(100),category:costCategorySchema,effect:z.enum(['addition','deduction']),basis:z.enum(['per_unit','per_line','per_order','per_plan','recurring','usage_unresolved']),applicability:z.enum(['applies','does_not_apply','unknown']),knowledge:z.discriminatedUnion('kind',[z.object({kind:z.literal('exact'),amount:moneySchema}).strict(),z.object({kind:z.literal('range'),minimum:moneySchema,maximum:moneySchema}).strict().superRefine((value,ctx)=>{if(value.minimum.currency!==value.maximum.currency)ctx.addIssue({code:'custom',message:'Cost range currency mismatch'});if(value.minimum.minorAmount>value.maximum.minorAmount)ctx.addIssue({code:'custom',message:'Cost range minimum exceeds maximum'})}),z.object({kind:z.literal('unknown'),currency:z.string().regex(/^[A-Z]{3}$/).optional()}).strict()]),timing:z.enum(['one_time','recurring','usage_based']),evidence:costEvidenceSchema,orderScope:z.string().trim().min(1).max(200).optional(),label:z.string().trim().min(1).max(200).optional()}).strict().superRefine((value,ctx)=>{if(value.effect==='deduction'&&!['discount','other'].includes(value.category))ctx.addIssue({code:'custom',message:'Only discount or identified other costs may deduct'});if(value.category==='other'&&!value.label)ctx.addIssue({code:'custom',message:'Other costs require a meaningful label'});if(value.basis==='per_order'&&!value.orderScope)ctx.addIssue({code:'custom',message:'Order costs require a supplier-order scope'});if(value.basis==='recurring'&&value.timing!=='recurring')ctx.addIssue({code:'custom',message:'Recurring basis requires recurring timing'});if(value.basis==='usage_unresolved'&&value.timing!=='usage_based')ctx.addIssue({code:'custom',message:'Usage basis requires usage timing'})})
export type CostComponent=z.infer<typeof costComponentSchema>

export interface CostLineInput{id:string;quantity:number;unitSemantics:'single_unit'|'unknown';components:CostComponent[];coverage:CostCoverage}
export interface CurrencyCostTotal{currency:string;baseSubtotal:Money;knownAdditions:Money;knownDeductions:Money;knownLowerBound:Money;upperBound?:Money;exactLandedTotal?:Money}
export interface CostBudgetAssessment{status:'satisfied'|'failed'|'unknown';budget:Money;reason:string}
export interface CostAssessment{completeness:'complete_exact'|'bounded'|'incomplete'|'conflicting';currencyTotals:CurrencyCostTotal[];recurring:CostComponent[];unresolved:CostComponent[];unknownApplicability:CostComponent[];missingCategories:string[];conflicts:string[];verificationReasons:string[];budget?:CostBudgetAssessment}
