import type { ProductEvaluation } from '../evaluation/domain/product-evaluation'
import type { ProductComparison, ComparisonCandidate, ComparisonMetrics, EvidenceMetrics } from './domain/product-comparison'
import type { Money, ProviderIdentity } from '../commerce/domain/commerce'

export interface ComparisonInput { product:ProviderIdentity; title:string; evaluation:ProductEvaluation }
function metrics(evaluation:ProductEvaluation):ComparisonMetrics { return { mandatoryFailures:evaluation.requirements.filter(x=>x.status==='failed').length, exclusionViolations:evaluation.exclusions.filter(x=>x.status==='failed').length, mandatoryUnknowns:evaluation.requirements.filter(x=>x.status==='unknown').length+(evaluation.budget?.status==='unknown'?1:0), mandatorySatisfied:evaluation.requirements.filter(x=>x.status==='satisfied').length, preferencesSatisfied:evaluation.preferences.filter(x=>x.status==='satisfied').length, preferencesUnknown:evaluation.preferences.filter(x=>x.status==='unknown').length } }
function evidence(evaluation:ProductEvaluation):EvidenceMetrics {const result:EvidenceMetrics={provided:0,inferred:0,derived:0,unknown:0};const outcomes=[...evaluation.requirements,...evaluation.preferences,...evaluation.exclusions,...(evaluation.budget?[evaluation.budget]:[])];for(const outcome of outcomes){if(outcome.evidence.kind==='provider_explicit')result.provided++;else if(outcome.evidence.kind==='provider_inferred')result.inferred++;else if(outcome.evidence.kind==='cosource_derived')result.derived++;else result.unknown++}return result}
function candidate(input:ComparisonInput):ComparisonCandidate { return { ...input, metrics:metrics(input.evaluation), evidence:evidence(input.evaluation), itemPrice:input.evaluation.budget?.itemPrice } }
function dominates(a:ComparisonMetrics,b:ComparisonMetrics){const safer=a.mandatoryFailures<=b.mandatoryFailures&&a.exclusionViolations<=b.exclusionViolations&&a.mandatoryUnknowns<=b.mandatoryUnknowns;const definiteSafetyGain=a.mandatoryFailures<b.mandatoryFailures||a.exclusionViolations<b.exclusionViolations;if(safer&&definiteSafetyGain)return true;const noWorse=safer&&a.mandatorySatisfied>=b.mandatorySatisfied&&a.preferencesSatisfied>=b.preferencesSatisfied;const better=a.mandatoryUnknowns<b.mandatoryUnknowns||a.mandatorySatisfied>b.mandatorySatisfied||a.preferencesSatisfied>b.preferencesSatisfied;return noWorse&&better}
function priceReason(a?:Money,b?:Money){ if(!a||!b)return 'Price comparison unavailable until one evidence-selected offer exists for each product.'; if(a.currency!==b.currency)return `Price comparison unavailable without FX data (${a.currency} and ${b.currency}).`; if(a.minorAmount===b.minorAmount)return `Known item prices are equal in ${a.currency}.`; return `Known ${a.currency} item prices differ; this does not include shipping or tax.` }
export function compareProductEvaluations(aInput:ComparisonInput,bInput:ComparisonInput):ProductComparison { const a=candidate(aInput),b=candidate(bInput),ad=dominates(a.metrics,b.metrics),bd=dominates(b.metrics,a.metrics); const known=[a.metrics.mandatoryFailures,a.metrics.exclusionViolations,a.metrics.mandatorySatisfied,a.metrics.preferencesSatisfied,b.metrics.mandatoryFailures,b.metrics.exclusionViolations,b.metrics.mandatorySatisfied,b.metrics.preferencesSatisfied].some(Boolean); let outcome:ProductComparison['outcome']; if(ad)outcome='candidate_a_stronger'; else if(bd)outcome='candidate_b_stronger'; else if(!known&&(a.metrics.mandatoryUnknowns>0||b.metrics.mandatoryUnknowns>0))outcome='insufficient_evidence'; else if(JSON.stringify(a.metrics)===JSON.stringify(b.metrics))outcome='equivalent_on_known_evidence'; else outcome='tradeoff'; const reasons=outcome==='candidate_a_stronger'?[`${a.title} is stronger on the evaluated dimensions without additional mandatory failures, exclusion violations, or unknowns.`]:outcome==='candidate_b_stronger'?[`${b.title} is stronger on the evaluated dimensions without additional mandatory failures, exclusion violations, or unknowns.`]:outcome==='equivalent_on_known_evidence'?['Both products are equivalent on currently known evaluation dimensions.']:outcome==='insufficient_evidence'?['There is not enough verified mandatory evidence to identify a stronger product.']:['No clear winner: each product has an evidence-backed advantage or disadvantage.']; return {candidateA:a,candidateB:b,outcome,reasons,priceReason:priceReason(a.itemPrice,b.itemPrice)} }
