import {describe,expect,it,vi} from 'vitest'
import {createCoSourceApplication} from '../application/cosource-application'
import type {ProductCluster} from '../commerce/domain/commerce'
import {composeWorkspaceHealth,projectWorkspaceHealth} from './domain/workspace-health'

const at='2026-09-12T10:00:00.000Z',provider='shopify_global_catalog' as const,provenance={kind:'provider_explicit' as const,provider},evidence={strength:'source_explicit' as const,source:'fixture'},product:ProductCluster={identity:{provider,id:'product'},title:{value:'Product',provenance},attributes:{value:[{name:'Size',value:'large'}],provenance},media:[],offers:[{identity:{provider,id:'offer'},title:{value:'Offer',provenance},merchant:{identity:{provider,id:'merchant'},name:'Merchant',policyLinks:[],provenance},price:{minorAmount:1000,currency:'GBP'},oneTimeCostCoverage:{status:'complete',evidence},availability:{state:'available',basis:'catalog_signal',provenance},selectedOptions:[],media:[],correlations:[],provenance}],offerCompleteness:'featured_only',featuredOfferId:'offer',provenance}

async function fixture(){let ids=0;const lookup=vi.fn(async()=>({product,selectedOptions:[],messages:[]})),application=createCoSourceApplication({market:{country:'GB',currency:'GBP'},makeId:()=>`id-${++ids}`,now:()=>at,catalog:{search:vi.fn(async()=>({products:[product],messages:[],pagination:{hasMore:false}})),product:lookup}});application.editGoal({summary:'Buy two products',quantity:2});application.addGoalCondition('requirement');const condition=application.getSnapshot().goalDraft.requirements[0]!;application.editGoalCondition('requirement',condition.id,{operator:'equals',field:'Size',value:'large'});application.commitGoalDraft();await application.searchCandidates({query:'product'});application.retainCandidate(product.identity);application.addCandidateToPlan(product.identity);let line=application.getSnapshot().plan.lines[0]!;application.setPlanLineQuantity(line.id,2);application.selectPlanLineOffer(line.id,product.offers[0]!.identity);const snapshot=application.getSnapshot();application.restoreWorkspace({...snapshot,plan:{...snapshot.plan,lines:snapshot.plan.lines.map(item=>({...item,unitSemantics:'single_item'}))}});const supplier=application.retainSupplier(product.identity,product.offers[0]!.identity);if(!supplier.ok)throw new Error('supplier fixture');application.recordSupplierQuotation(supplier.value.id,{subject:{kind:'offer',source:provider,externalId:'offer'},components:[],coverage:{status:'complete',evidence},evidence});application.recordSupplierReliability(supplier.value.id,{category:'delivery_outcome',outcome:'positive',summary:'Reliable',evidence});line=application.getSnapshot().plan.lines[0]!;return{application,lookup,line,getIds:()=>ids}}

describe('S8R2 persistence route and monitored rebase acceptance',()=>{
 it.each([{status:'conflict' as const,retrySupported:false,message:'Memory preserved'},{status:'unavailable' as const,retrySupported:false,message:'Unsupported'}])('routes non-retryable persistence to its own surface',persistence=>{const project=projectWorkspaceHealth({workspaceId:'w',activeGoal:{id:'g',revision:1},draftDiverged:false,plan:{id:'p',revision:1,lineCount:0},issues:[],operations:[],evaluatedAt:at}),health=composeWorkspaceHealth(project,{persistence,webmcp:{status:'ready',toolCount:13,requiredToolCount:13}}),finding=health.findings.find(item=>item.owner==='persistence');expect(finding).toMatchObject({route:'inspect_persistence',routeKind:'informational'});expect(finding?.repair).toBeUndefined();expect(finding?.route).not.toBe('review_plan')})
 it('rebases one exact stale pre-handoff case and rejects command reuse',async()=>{const{application,lookup,line,getIds}=await fixture(),opened=application.openOperationalCase();expect(opened.ok).toBe(true);if(!opened.ok)return;application.setPlanLineQuantity(line.id,3);const health=application.getWorkspaceHealth(),repairs=health.findings.filter(item=>item.subject.id===opened.value.id&&item.repair?.kind==='rebase_operation');expect(repairs).toHaveLength(1);const finding=repairs[0]!,before=application.getSnapshot(),beforeCase=before.operationalCases[0]!,result=await application.executeMonitoringRepair({findingId:finding.id,basisFingerprint:health.basisFingerprint,targetId:opened.value.id});expect(result.ok).toBe(true);expect(lookup).not.toHaveBeenCalled();const after=application.getSnapshot(),afterCase=after.operationalCases[0]!;expect(afterCase.revision).toBe(beforeCase.revision+1);expect(after.activities.length).toBe(before.activities.length+1);expect(application.getOperationalCases()[0]?.stale).toBe(false);const idsAfter=getIds(),snapshotAfter=application.getSnapshot();expect(await application.executeMonitoringRepair({findingId:finding.id,basisFingerprint:health.basisFingerprint,targetId:opened.value.id})).toMatchObject({ok:false,code:'stale_state'});expect(application.getSnapshot()).toBe(snapshotAfter);expect(getIds()).toBe(idsAfter);expect(lookup).not.toHaveBeenCalled()})
 it('does not expose executable rebase after external handoff',async()=>{const{application,line}=await fixture(),opened=application.openOperationalCase();expect(opened.ok).toBe(true);if(!opened.ok)return;expect(application.requestOperationalApproval({caseId:opened.value.id}).ok).toBe(true);expect(application.approveOperationalHandoff({caseId:opened.value.id}).ok).toBe(true);expect(application.recordExternalAction({caseId:opened.value.id,lineIds:[line.id],externalReference:'outside-handoff',representedAt:at,evidence}).ok).toBe(true);application.setPlanLineQuantity(line.id,3);const finding=application.getWorkspaceHealth().findings.find(item=>item.subject.id===opened.value.id);expect(finding).toMatchObject({route:'review_operation',routeKind:'informational'});expect(finding?.repair).toBeUndefined()})
})
