import {describe,expect,it,vi} from 'vitest'
import {createCoSourceApplication} from '../application/cosource-application'
import {COMMERCE_PROVIDERS,type ProductCluster} from '../commerce/domain/commerce'
import {createPersistentApplication} from '../application/persistence/persistent-application'

const provider=COMMERCE_PROVIDERS.shopifyGlobalCatalog,provenance={kind:'provider_explicit' as const,provider},candidate:ProductCluster={identity:{provider,id:'candidate'},title:{value:'Candidate',provenance},media:[],offers:[],offerCompleteness:'featured_only',provenance}
function fixture(fail=false){let id=0;const product=vi.fn(async()=>{if(fail)throw new Error('private provider body');return{product:candidate,selectedOptions:[],messages:[]}});const application=createCoSourceApplication({market:{country:'GB',currency:'GBP'},catalog:{search:async()=>({products:[candidate],messages:[],pagination:{hasMore:false}}),product},makeId:()=>`id-${++id}`,now:()=> '2026-09-12T12:00:00.000Z'});return{application,product}}
async function refreshable(fail=false){const value=fixture(fail),app=value.application;app.editGoal({summary:'Buy a blue candidate',searchFocus:'candidate'});app.addGoalCondition('requirement');const condition=app.getSnapshot().goalDraft.requirements[0]!;app.editGoalCondition('requirement',condition.id,{operator:'equals',field:'colour',value:'blue'});app.commitGoalDraft();await app.searchCandidates({query:'candidate'});app.retainCandidate(candidate.identity);return value}

describe('workspace health application boundary',()=>{
 it('is read-only and stable',()=>{const{application,product}=fixture(),before=application.getSnapshot(),first=application.getWorkspaceHealth(),second=application.getWorkspaceHealth();expect(second).toEqual(first);expect(application.getSnapshot()).toBe(before);expect(product).not.toHaveBeenCalled();expect(first).toMatchObject({status:'blocked',findings:[{owner:'goal'}]})})
 it('rejects malformed and stale repair commands without side effects',async()=>{const{application,product}=fixture(),before=application.getSnapshot();expect(await application.executeMonitoringRepair({findingId:'x'})).toMatchObject({ok:false,code:'invalid_input'});expect(await application.executeMonitoringRepair({findingId:'x',basisFingerprint:'old',targetId:'x'})).toMatchObject({ok:false,code:'stale_state'});expect(application.getSnapshot()).toBe(before);expect(product).not.toHaveBeenCalled()})
 it('delegates one exact evidence refresh and sequences accepted observation history',async()=>{const{application,product}=await refreshable(),before=application.getSnapshot().retainedEvidence[0]!,health=application.getWorkspaceHealth(),finding=health.findings.find(item=>item.repair?.kind==='refresh_evidence');expect(finding?.repair).toBeDefined();const result=await application.executeMonitoringRepair({findingId:finding!.id,basisFingerprint:health.basisFingerprint,targetId:finding!.repair!.targetId,provider:finding!.repair!.provider});expect(result.ok).toBe(true);expect(product).toHaveBeenCalledOnce();const after=application.getSnapshot().retainedEvidence[0]!;expect(after.current.sequence).toBe(before.current.sequence+1);expect(after.history[0]?.id).toBe(before.current.id)})
 it('bounds provider failure and preserves the accepted observation',async()=>{const{application,product}=await refreshable(true),before=application.getSnapshot().retainedEvidence[0]!,health=application.getWorkspaceHealth(),finding=health.findings.find(item=>item.repair?.kind==='refresh_evidence')!;const result=await application.executeMonitoringRepair({findingId:finding.id,basisFingerprint:health.basisFingerprint,targetId:finding.repair!.targetId,provider:finding.repair!.provider});expect(result).toMatchObject({ok:false});expect(JSON.stringify(result)).not.toContain('private provider body');expect(product).toHaveBeenCalledOnce();expect(application.getSnapshot().retainedEvidence[0]!.current).toEqual(before.current)})
 it('does not write persistence while reading health',async()=>{const{application}=fixture(),compareAndSave=vi.fn(async(record)=>({ok:true as const,record})),persistent=createPersistentApplication(application,{load:async()=>undefined,compareAndSave});await persistent.initialize();compareAndSave.mockClear();application.getWorkspaceHealth();application.getWorkspaceHealth();expect(compareAndSave).not.toHaveBeenCalled();persistent.dispose()})
})
