import {describe,expect,it} from 'vitest'
import {COMMERCE_PROVIDERS,type ProductCluster} from '../commerce/domain/commerce'
import {createPurchaseGoal} from '../goals/domain/purchase-goal'
import {createPurchasePlan} from '../planning/domain/purchase-plan'
import {addProductToPlan,setPlanLineQuantity} from '../planning/mutate-plan'
import type {PlanChangeProposal} from './domain/plan-change-proposal'
import {approveProposal,createPlanChangeProposal,proposalEffectiveStatus,rejectProposal,type ProposalState} from './proposal-service'

const provider=COMMERCE_PROVIDERS.shopifyGlobalCatalog,provenance={kind:'provider_explicit' as const,provider}
function product(id:string,providerValue=provider):ProductCluster{return{identity:{provider:providerValue,id},title:{value:id,provenance},media:[],offerCompleteness:'provider_returned_unknown',provenance,offers:[{identity:{provider:providerValue,id:`${id}-offer`},title:{value:id,provenance},price:{minorAmount:1000,currency:'GBP'},availability:{state:'available',basis:'catalog_signal',provenance},selectedOptions:[],media:[],correlations:[],provenance}]}}
const goal=createPurchaseGoal({id:'goal',summary:'item',requirements:[],preferences:[],exclusions:[]}),item=product('item'),other=product('other')
function state():ProposalState{return{goal,plan:addProductToPlan(createPurchasePlan('plan',goal.id,goal.revision),item,'line'),retainedProducts:[item,other]}}
const now=()=> '2026-08-31T12:00:00.000Z',id=()=> 'proposal-id'
function create(input:Record<string,unknown>,current=state()){return createPlanChangeProposal({planId:current.plan.id,planRevision:current.plan.revision,goalId:current.goal!.id,goalRevision:current.goal!.revision,...input},current,id,now)}

describe('plan change proposals',()=>{
  it('creates a unique, bounded proposal without mutating the plan',()=>{const current=state(),before=current.plan,result=create({reason:'Add retained evidence',operations:[{type:'add_retained_product',product:other.identity}]},current);expect(result.ok&&result.proposal).toMatchObject({id:'proposal-id',status:'pending',source:'agent_webmcp'});expect(current.plan).toBe(before);expect(create({operations:Array.from({length:21},()=>({type:'rebase_to_current_goal'}))},current)).toMatchObject({ok:false,code:'invalid_operations'})})
  it('rejects stale revisions, arbitrary fields, unretained and unsupported-provider identities',()=>{expect(create({planRevision:99,operations:[{type:'rebase_to_current_goal'}]})).toMatchObject({ok:false,code:'stale_revision'});expect(create({url:'https://bad.test',operations:[{type:'rebase_to_current_goal'}]})).toMatchObject({ok:false,code:'invalid_input'});expect(create({operations:[{type:'add_retained_product',product:{...other.identity,id:'absent'}}]})).toMatchObject({ok:false,code:'invalid_operation'});expect(create({operations:[{type:'add_retained_product',product:{provider:'other_provider',id:other.identity.id}}]})).toMatchObject({ok:false,code:'invalid_operation'})})
  it('validates line quantities and offer membership',()=>{expect(create({operations:[{type:'set_quantity',lineId:'line',quantity:0}]})).toMatchObject({ok:false,code:'invalid_operation'});expect(create({operations:[{type:'select_merchant_offer',lineId:'line',offer:other.offers[0]!.identity}]})).toMatchObject({ok:false,code:'invalid_operation'});expect(create({operations:[{type:'select_merchant_offer',lineId:'line',offer:item.offers[0]!.identity}]}).ok).toBe(true)})
  it('applies all operations atomically with authoritative revision increments',()=>{const current=state(),result=create({operations:[{type:'set_quantity',lineId:'line',quantity:2},{type:'select_merchant_offer',lineId:'line',offer:item.offers[0]!.identity}]},current);expect(result.ok).toBe(true);const approved=approveProposal((result as {proposal:PlanChangeProposal}).proposal,current,now);expect(approved.proposal).toMatchObject({status:'applied',appliedPlanRevision:current.plan.revision+2});expect(approved.plan?.lines[0]).toMatchObject({quantity:2,selectedOffer:item.offers[0]!.identity})})
  it('blocks stale application and rejects without changing the plan',()=>{const current=state(),result=create({operations:[{type:'set_quantity',lineId:'line',quantity:2}]},current) as {proposal:PlanChangeProposal};const changed={...current,plan:setPlanLineQuantity(current.plan,'line',3)};expect(proposalEffectiveStatus(result.proposal,changed)).toBe('stale');expect(approveProposal(result.proposal,changed,now).proposal.status).toBe('stale');expect(rejectProposal(result.proposal,now)).toMatchObject({status:'rejected'});expect(current.plan.lines[0]?.quantity).toBe(1)})
  it('fails the whole temporary application when a later operation becomes invalid',()=>{const current=state(),proposal:PlanChangeProposal={id:'p',status:'pending',createdAt:now(),source:'agent_webmcp',planId:current.plan.id,expectedPlanRevision:current.plan.revision,expectedGoalId:goal.id,expectedGoalRevision:goal.revision,operations:[{type:'set_quantity',lineId:'line',quantity:2},{type:'remove_plan_line',lineId:'missing'}]};const approved=approveProposal(proposal,current,now);expect(approved.proposal.status).toBe('failed');expect(approved.plan).toBeUndefined();expect(current.plan.lines[0]?.quantity).toBe(1)})
})
