// @vitest-environment jsdom
import {useState} from 'react'
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import '@testing-library/jest-dom/vitest'
import {afterEach,describe,expect,it,vi} from 'vitest'
import App from '../App'
import {ScenarioPlanningPanel} from '../planning/DecisionWorkspace'
import type {ScenarioSet} from '../scenarios/domain/scenario'

vi.mock('../evidence/EvidenceResolutionPanel',()=>({EvidenceResolutionPanel:()=>{const[value,setValue]=useState('');return <section id="evidence-resolution"><label>Advanced draft<input value={value} onChange={event=>setValue(event.target.value)}/></label></section>}}))
vi.mock('../application/browser-application',async()=>{const[{createCoSourceApplication},{createProjectPortfolio},{MemoryProjectPortfolioPersistence},{catalogClient}]=await Promise.all([import('../application/cosource-application'),import('../application/portfolio/project-portfolio-controller'),import('../application/portfolio/memory-project-portfolio-persistence'),import('../commerce/client/catalog-client')]);return{createBrowserApplication:()=>{const repository=new MemoryProjectPortfolioPersistence();repository.compareAndSaveProject=async(_id,record)=>({ok:true,record});return createProjectPortfolio(()=>createCoSourceApplication({catalog:{search:catalogClient.search,product:input=>catalogClient.product({product:input.identity,country:input.market.country,currency:input.market.currency,selectedOptions:input.selectedOptions})},market:{country:'GB',currency:'GBP',language:'en'}}),repository)}}})

afterEach(()=>{delete (document as Document&{modelContext?:WebMCPModelContext}).modelContext;Reflect.deleteProperty(HTMLElement.prototype,'scrollIntoView');vi.unstubAllGlobals();vi.restoreAllMocks();window.history.replaceState(null,'','/');cleanup()})
const renderApp=async()=>{const view=render(<App/>);await screen.findByText('Advanced workspace');return view}
const candidate=()=>{const provenance={kind:'provider_explicit',provider:'shopify_global_catalog'};return{identity:{provider:'shopify_global_catalog',id:'candidate-1'},title:{value:'Candidate raincoat',provenance},description:{value:'Catalog evidence',provenance},media:[],featuredOfferId:'offer-1',offerCompleteness:'featured_only',provenance,offers:[{identity:{provider:'shopify_global_catalog',id:'offer-1'},title:{value:'Candidate raincoat',provenance},merchant:{name:'Merchant',provenance},productUrl:'https://merchant.test/product',price:{minorAmount:2499,currency:'GBP'},availability:{state:'available',basis:'catalog_signal',provenance},selectedOptions:[],media:[],correlations:[],provenance}]}}
async function setupAdvancedMonitoringRoute(){
 const user=userEvent.setup();Object.defineProperty(document,'modelContext',{configurable:true,value:Object.assign(new EventTarget(),{async registerTool(){}})});vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(JSON.stringify({ok:true,data:{products:[candidate()],messages:[],pagination:{hasMore:false}}}),{status:200,headers:{'Content-Type':'application/json'}})));const scrollIntoView=vi.fn();Object.defineProperty(HTMLElement.prototype,'scrollIntoView',{configurable:true,value:scrollIntoView});render(<App/>);await screen.findByText('WebMCP ready');fireEvent.click(screen.getByRole('button',{name:'Use example buying need'}));fireEvent.click(screen.getByRole('button',{name:'Commit draft as active goal'}));fireEvent.click(screen.getByRole('button',{name:/Source active goal/}));await screen.findByText('Candidate raincoat');fireEvent.click(screen.getByRole('button',{name:'Select for comparison'}));let link!:HTMLAnchorElement;await waitFor(()=>{link=screen.getByRole('link',{name:'Go to safest next action'}) as HTMLAnchorElement;expect(link).toHaveAttribute('href','#evidence-resolution')});return{user,link,advanced:screen.getByText('Advanced workspace').closest('details')!,scrollIntoView}
}
async function openAndPreserveDraft(setup:Awaited<ReturnType<typeof setupAdvancedMonitoringRoute>>){expect(document.getElementById('evidence-resolution')).not.toBeInTheDocument();await setup.user.click(setup.link);await waitFor(()=>{expect(window.location.hash).toBe('#evidence-resolution');expect(setup.advanced.open).toBe(true);expect(document.getElementById('evidence-resolution')).toBeInTheDocument();expect(setup.scrollIntoView).toHaveBeenCalled()});expect(document.getElementById('supplier-intelligence')).toBeInTheDocument();expect(document.getElementById('scenario-planning')).toBeInTheDocument();expect(document.getElementById('supervised-operations')).toBeInTheDocument();const input=screen.getByLabelText('Advanced draft');fireEvent.change(input,{target:{value:'unfinished verification note'}});await setup.user.click(setup.advanced.querySelector('summary')!);await waitFor(()=>expect(setup.advanced.open).toBe(false));expect(window.location.hash).toBe('#evidence-resolution');expect(input).toBeInTheDocument();expect(input).toHaveValue('unfinished verification note');setup.scrollIntoView.mockClear();return input}

// Complete-App interaction needs a bounded integration budget under aggregate worker contention.
describe('CUX1R2 presentation defects',{timeout:10_000},()=>{
 it('places the one real Scenario planning presentation inside Advanced workspace after first reveal',async()=>{const user=userEvent.setup();await renderApp();const advanced=screen.getByText('Advanced workspace').closest('details')!;expect(screen.queryByText('Scenario planning')).not.toBeInTheDocument();await user.click(advanced.querySelector('summary')!);const scenarios=screen.getAllByText('Scenario planning');expect(scenarios).toHaveLength(1);expect(advanced).toContainElement(scenarios[0]!);expect(document.querySelector('a#scenario-planning')).not.toBeInTheDocument()})
 it('mounts advanced descendants lazily once and retains them when closed',async()=>{const user=userEvent.setup();await renderApp();const advanced=screen.getByText('Advanced workspace').closest('details')!;expect(advanced.open).toBe(false);expect(document.getElementById('supplier-intelligence')).not.toBeInTheDocument();expect(document.getElementById('evidence-resolution')).not.toBeInTheDocument();expect(document.getElementById('scenario-planning')).not.toBeInTheDocument();await user.click(advanced.querySelector('summary')!);expect(advanced.open).toBe(true);expect(document.getElementById('supplier-intelligence')).toBeInTheDocument();expect(document.getElementById('evidence-resolution')).toBeInTheDocument();expect(document.getElementById('scenario-planning')).toBeInTheDocument();await user.click(advanced.querySelector('summary')!);expect(advanced.open).toBe(false);expect(document.getElementById('supplier-intelligence')).toBeInTheDocument();expect(document.getElementById('evidence-resolution')).toBeInTheDocument();expect(document.getElementById('scenario-planning')).toBeInTheDocument()})
 it('preserves local advanced input across close and reopen',async()=>{const user=userEvent.setup();await renderApp();const advanced=screen.getByText('Advanced workspace').closest('details')!;await user.click(advanced.querySelector('summary')!);const input=screen.getByLabelText('Advanced draft');fireEvent.change(input,{target:{value:'unfinished verification note'}});await user.click(advanced.querySelector('summary')!);expect(advanced.open).toBe(false);expect(input).toHaveValue('unfinished verification note');await user.click(advanced.querySelector('summary')!);expect(screen.getByLabelText('Advanced draft')).toBe(input);expect(input).toHaveValue('unfinished verification note')})
 it('gives truthful scenario prerequisites before a goal is committed',async()=>{const user=userEvent.setup();await renderApp();await user.click(screen.getByText('Advanced workspace').closest('details')!.querySelector('summary')!);expect(screen.getByText('Commit a buying goal and retain suitable candidate evidence to generate bounded scenarios.')).toBeInTheDocument();expect(screen.queryByText('Retain candidate evidence first.')).not.toBeInTheDocument()})
 it('reveals initial and changed advanced hashes without duplicate ids',async()=>{window.history.replaceState(null,'','/#scenario-planning');await renderApp();const advanced=screen.getByText('Advanced workspace').closest('details')!;await waitFor(()=>expect(advanced.open).toBe(true));expect(document.getElementById('scenario-planning')).toBeInTheDocument();window.location.hash='#evidence-resolution';fireEvent(window,new HashChangeEvent('hashchange'));await waitFor(()=>expect(document.getElementById('evidence-resolution')).toBeInTheDocument());const ids=[...document.querySelectorAll('[id]')].map(element=>element.id);expect(new Set(ids).size).toBe(ids.length)})
 it('retains the existing exact scenario command and feedback authority',()=>{const onApplyScenario=vi.fn().mockReturnValue({ok:true,value:{revision:4}}),scenarios={basisFingerprint:'basis-current',counts:{ready_on_current_evidence:1,conditional_verification_required:0,blocked:0},enumerationTruncated:false,resultLimited:false,scenarios:[{id:'scenario-1',basisFingerprint:'basis-current',status:'ready_on_current_evidence',objectives:[],selections:[{product:{provider:'source',id:'product-1'},productTitle:'Candidate',offer:{provider:'source',id:'offer-1'},quantity:2}],evaluation:{merchantCount:1,mandatoryFailures:0,exclusionViolations:0,mandatoryUnknowns:0,preferencesSatisfied:0,preferencesUnknown:0,unresolvedCosts:[]},blockingIssueIds:[],verificationIssueIds:[],reasons:[],tradeoffs:[]}]} as unknown as ScenarioSet;render(<ScenarioPlanningPanel scenarios={scenarios} onApplyScenario={onApplyScenario}/>);fireEvent.click(screen.getByRole('button',{name:'Apply this scenario'}));expect(onApplyScenario).toHaveBeenCalledWith({scenarioId:'scenario-1',basisFingerprint:'basis-current'});expect(screen.getByText('Scenario applied. Plan revision 4.')).toHaveAttribute('role','status')})
 it('reopens Advanced workspace from the same hash using keyboard Enter alone',async()=>{const setup=await setupAdvancedMonitoringRoute(),input=await openAndPreserveDraft(setup);setup.link.focus();await setup.user.keyboard('{Enter}');await waitFor(()=>{expect(setup.advanced.open).toBe(true);expect(window.location.hash).toBe('#evidence-resolution');expect(setup.scrollIntoView).toHaveBeenCalled();expect(input).toHaveValue('unfinished verification note')});const ids=[...document.querySelectorAll('[id]')].map(element=>element.id);expect(new Set(ids).size).toBe(ids.length)})
 it('reopens Advanced workspace from the same hash using a mouse click alone',async()=>{const setup=await setupAdvancedMonitoringRoute(),input=await openAndPreserveDraft(setup);await setup.user.click(setup.link);await waitFor(()=>{expect(setup.advanced.open).toBe(true);expect(window.location.hash).toBe('#evidence-resolution');expect(setup.scrollIntoView).toHaveBeenCalled();expect(input).toHaveValue('unfinished verification note')});const ids=[...document.querySelectorAll('[id]')].map(element=>element.id);expect(new Set(ids).size).toBe(ids.length)})
})
