// @vitest-environment jsdom
import {useState} from 'react'
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import '@testing-library/jest-dom/vitest'
import {afterEach,describe,expect,it,vi} from 'vitest'
import App from '../App'
import {ScenarioPlanningPanel} from '../planning/DecisionWorkspace'
import type {ScenarioSet} from '../scenarios/domain/scenario'

vi.mock('../evidence/EvidenceResolutionPanel',()=>({EvidenceResolutionPanel:()=>{const[value,setValue]=useState('');return <section id="evidence-resolution"><label>Advanced draft<input value={value} onChange={event=>setValue(event.target.value)}/></label></section>}}))
vi.mock('../application/browser-application',async()=>{const[{createCoSourceApplication},{createProjectPortfolio},{MemoryProjectPortfolioPersistence},{catalogClient}]=await Promise.all([import('../application/cosource-application'),import('../application/portfolio/project-portfolio-controller'),import('../application/portfolio/memory-project-portfolio-persistence'),import('../commerce/client/catalog-client')]);return{createBrowserApplication:()=>{const repository=new MemoryProjectPortfolioPersistence();repository.compareAndSaveProject=async(_id,record)=>({ok:true,record});return createProjectPortfolio(()=>createCoSourceApplication({catalog:{search:catalogClient.search,product:input=>catalogClient.product({product:input.identity,country:input.market.country,currency:input.market.currency,selectedOptions:input.selectedOptions})},market:{country:'GB',currency:'GBP',language:'en'}}),repository)}}})

afterEach(()=>{delete (document as Document&{modelContext?:WebMCPModelContext}).modelContext;vi.unstubAllGlobals();vi.restoreAllMocks();window.history.replaceState(null,'','/');cleanup()})
const renderApp=async()=>{Object.defineProperty(document,'modelContext',{configurable:true,value:Object.assign(new EventTarget(),{async registerTool(){}})});render(<App/>);await screen.findByText('WebMCP ready')}
const openIntelligence=async()=>{await userEvent.click(screen.getByRole('link',{name:'Decision intelligence'}));return screen.getByRole('navigation',{name:'Decision intelligence areas'})}

describe('focused decision-intelligence workflow',{timeout:10_000},()=>{
 it('mounts only the active intelligence area initially',async()=>{await renderApp();expect(document.getElementById('evidence-resolution')).not.toBeInTheDocument();await openIntelligence();expect(document.getElementById('evidence-resolution')).toBeVisible();expect(document.getElementById('supplier-intelligence')).not.toBeInTheDocument();expect(document.getElementById('scenario-planning')).not.toBeInTheDocument()})
 it('shows one intelligence area at a time',async()=>{await renderApp();await openIntelligence();await userEvent.click(screen.getByRole('link',{name:'Suppliers'}));expect(document.getElementById('supplier-intelligence')).toBeVisible();expect(document.getElementById('evidence-resolution')).not.toBeVisible()})
 it('preserves local input after a lazily mounted area is revisited',async()=>{await renderApp();await openIntelligence();const input=screen.getByLabelText('Advanced draft');await userEvent.type(input,'unfinished verification note');await userEvent.click(screen.getByRole('link',{name:'Suppliers'}));await userEvent.click(screen.getByRole('link',{name:'Evidence'}));expect(screen.getByLabelText('Advanced draft')).toBe(input);expect(input).toHaveValue('unfinished verification note')})
 it('gives truthful scenario prerequisites before commitment',async()=>{await renderApp();await openIntelligence();await userEvent.click(screen.getByRole('link',{name:'Scenarios'}));expect(screen.getByText('Commit a buying goal and retain suitable candidate evidence to generate bounded scenarios.')).toBeInTheDocument()})
 it('routes a direct descendant hash to the one intended area',async()=>{window.history.replaceState(null,'','/#scenario-planning');await renderApp();await waitFor(()=>expect(document.getElementById('scenario-planning')).toBeVisible());expect(screen.getByRole('link',{name:'Scenarios'})).toHaveAttribute('aria-current','page')})
 it('keeps all canonical ids unique as areas are mounted',async()=>{await renderApp();await openIntelligence();for(const name of ['Suppliers','Scenarios'])await userEvent.click(screen.getByRole('link',{name}));const ids=[...document.querySelectorAll('[id]')].map(element=>element.id);expect(new Set(ids).size).toBe(ids.length)})
 it('supports keyboard activation and visible current-area state',async()=>{await renderApp();await openIntelligence();const link=screen.getByRole('link',{name:'Suppliers'});link.focus();await userEvent.keyboard('{Enter}');expect(link).toHaveAttribute('aria-current','page');expect(document.getElementById('supplier-intelligence')).toBeVisible()})
 it('presents only the selected major workflow surface',async()=>{await renderApp();expect(document.getElementById('stage-define')).toBeInTheDocument();await userEvent.click(screen.getByRole('link',{name:'Discover'}));expect(document.getElementById('stage-discover')).toBeInTheDocument();expect(document.getElementById('stage-define')).not.toBeInTheDocument();expect(document.getElementById('stage-review')).not.toBeInTheDocument()})
 it('preserves an unfinished goal draft across presentation navigation',async()=>{await renderApp();const draft=screen.getByLabelText('What are you trying to buy or achieve?');await userEvent.type(draft,'Unfinished workstation brief');await userEvent.click(screen.getByRole('link',{name:'Overview'}));await userEvent.click(screen.getByRole('link',{name:'Define'}));expect(screen.getByLabelText('What are you trying to buy or achieve?')).toHaveValue('Unfinished workstation brief')})
 it('does not turn presentation navigation into goal commitment',async()=>{await renderApp();await userEvent.type(screen.getByLabelText('What are you trying to buy or achieve?'),'Draft only');await userEvent.click(screen.getByRole('link',{name:'Discover'}));expect(screen.getByText('Commit a valid requirement to make evidence-led sourcing the primary action.')).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Source active requirement'})).not.toBeInTheDocument()})
 it('routes a direct major-stage hash without mounting sibling stages',async()=>{window.history.replaceState(null,'','/#stage-review');await renderApp();expect(document.getElementById('stage-review')).toBeInTheDocument();expect(document.getElementById('stage-define')).not.toBeInTheDocument();expect(document.getElementById('stage-discover')).not.toBeInTheDocument()})
 it('exposes seven unique canonical journey destinations',async()=>{await renderApp();const links=screen.getByRole('navigation',{name:'Workspace navigation'}).querySelectorAll<HTMLAnchorElement>('a[href]');const destinations=[...links].map(link=>link.hash);expect(destinations).toHaveLength(7);expect(new Set(destinations).size).toBe(7)})
 it('keeps the review surface local instead of mounting decision intelligence',async()=>{await renderApp();await userEvent.click(screen.getByRole('link',{name:'Review'}));expect(document.getElementById('stage-review')).toBeInTheDocument();expect(document.getElementById('decision-intelligence')).not.toBeInTheDocument();expect(screen.getByRole('navigation',{name:'Review areas'})).toBeInTheDocument()})
 it('retains the exact scenario command and feedback authority',()=>{const onApplyScenario=vi.fn().mockReturnValue({ok:true,value:{revision:4}}),scenarios={basisFingerprint:'basis-current',counts:{ready_on_current_evidence:1,conditional_verification_required:0,blocked:0},enumerationTruncated:false,resultLimited:false,scenarios:[{id:'scenario-1',basisFingerprint:'basis-current',status:'ready_on_current_evidence',objectives:[],selections:[{product:{provider:'source',id:'product-1'},productTitle:'Candidate',offer:{provider:'source',id:'offer-1'},quantity:2}],evaluation:{merchantCount:1,mandatoryFailures:0,exclusionViolations:0,mandatoryUnknowns:0,preferencesSatisfied:0,preferencesUnknown:0,unresolvedCosts:[]},blockingIssueIds:[],verificationIssueIds:[],reasons:[],tradeoffs:[]}]} as unknown as ScenarioSet;render(<ScenarioPlanningPanel scenarios={scenarios} onApplyScenario={onApplyScenario}/>);fireEvent.click(screen.getByRole('button',{name:'Apply this scenario'}));expect(onApplyScenario).toHaveBeenCalledWith({scenarioId:'scenario-1',basisFingerprint:'basis-current'});expect(screen.getByText('Scenario applied. Plan revision 4.')).toHaveAttribute('role','status')})
})
