import {describe,expect,it} from 'vitest'
import {composeWorkspaceHealth,projectWorkspaceHealth,workspaceHealthSchema} from './workspace-health'

const base={workspaceId:'workspace-1',activeGoal:{id:'goal-1',revision:2},draftDiverged:false,plan:{id:'plan-1',revision:3,lineCount:1},issues:[],evaluation:undefined,scenarioBasis:'scenario-a',operations:[],evaluatedAt:'2026-09-12T12:00:00.000Z'}

describe('canonical workspace health projection',()=>{
 it('is deterministic within a phase and changes its basis with temporal phases',()=>{const first=projectWorkspaceHealth(base),again=projectWorkspaceHealth(base),changed=projectWorkspaceHealth({...base,scenarioBasis:'scenario-b'});expect(again).toEqual(first);expect(changed.basisFingerprint).not.toBe(first.basisFingerprint)})
 it('orders independently of input order and applies unavailable then blocked precedence',()=>{const operations=[{id:'post',revision:1,lifecycle:'externally_actioned',stale:true,safeNextAction:'review',canRebase:false},{id:'pre',revision:1,lifecycle:'draft',stale:true,safeNextAction:'rebase',canRebase:true}],runtime={persistence:{status:'unavailable' as const,retrySupported:false,message:'IndexedDB is unavailable.'},webmcp:{status:'ready' as const,toolCount:13,requiredToolCount:13 as const}},a=composeWorkspaceHealth(projectWorkspaceHealth({...base,operations}),runtime),b=composeWorkspaceHealth(projectWorkspaceHealth({...base,operations:[...operations].reverse()}),runtime);expect(a.findings.map(item=>item.id)).toEqual(b.findings.map(item=>item.id));expect(a.status).toBe('unavailable');expect(a.findings[0]?.owner).toBe('persistence')})
 it('suppresses downstream noise without an active goal',()=>{const health=projectWorkspaceHealth({...base,activeGoal:undefined,plan:{...base.plan,lineCount:0},operations:[{id:'case',revision:1,lifecycle:'draft',stale:true,safeNextAction:'rebase',canRebase:true}]});expect(health.findings).toHaveLength(1);expect(health.findings[0]).toMatchObject({owner:'goal',blocking:true,route:'commit_goal'})})
 it('uses closed schemas and bounded collections without provider-specific domain vocabulary',()=>{const health=projectWorkspaceHealth({...base,operations:Array.from({length:80},(_,index)=>({id:`case-${index}`,revision:1,lifecycle:'draft',stale:true,safeNextAction:'rebase',canRebase:true}))});expect(health.findings).toHaveLength(50);expect(workspaceHealthSchema.safeParse({...health,unknown:true}).success).toBe(false);expect(JSON.stringify(health)).not.toMatch(/shopify|amazon|ebay/i)})
})
