import {z} from 'zod'
import type {ProviderIdentity} from '../../commerce/domain/commerce'
import type {EvidenceIssue} from '../../evidence/domain/evidence-resolution'
import type {PlanEvaluation} from '../../planning/domain/purchase-plan'

export const monitoringOwnerSchema=z.enum(['goal','evidence','cost','supplier','plan','scenario','operation','persistence','webmcp'])
export const monitoringStatusSchema=z.enum(['ready','attention_required','blocked','unavailable'])
export const monitoringRouteSchema=z.enum(['commit_goal','review_evidence','refresh_evidence','review_plan','review_supplier','review_scenarios','review_operation','rebase_operation','retry_persistence','inspect_persistence','inspect_webmcp'])
const subjectSchema=z.object({kind:z.enum(['workspace','requirement','product','plan','supplier','operation','persistence','webmcp']),id:z.string().min(1).max(500),provider:z.string().min(1).max(100).optional()}).strict()
export const monitoringFindingSchema=z.object({id:z.string().min(1).max(160),owner:monitoringOwnerSchema,subject:subjectSchema,severity:z.enum(['info','attention','blocking','unavailable']),blocking:z.boolean(),reason:z.string().min(1).max(1000),whyItMatters:z.string().min(1).max(1000),route:monitoringRouteSchema,routeKind:z.enum(['informational','navigational','executable']),humanApprovalRequired:z.boolean(),repair:z.object({kind:z.enum(['refresh_evidence','rebase_operation','retry_persistence']),targetId:z.string().min(1).max(500),provider:z.string().min(1).max(100).optional()}).strict().optional(),canonicalIssueIds:z.array(z.string().min(1).max(500)).max(20),phase:z.string().min(1).max(500)}).strict()
export const workspaceHealthSchema=z.object({workspaceId:z.string().min(1).max(100),requirement:z.object({id:z.string().min(1).max(100),revision:z.number().int().safe().min(0)}).strict().optional(),plan:z.object({id:z.string().min(1).max(100),revision:z.number().int().safe().min(0)}).strict(),evaluatedAt:z.iso.datetime({offset:true}),basisFingerprint:z.string().min(1).max(100),projectBasisFingerprint:z.string().min(1).max(100),status:monitoringStatusSchema,counts:z.object({blocking:z.number().int().min(0),attention:z.number().int().min(0),informational:z.number().int().min(0),total:z.number().int().min(0)}).strict(),highestPriorityReason:z.string().min(1).max(1000).optional(),findings:z.array(monitoringFindingSchema).max(50)}).strict()
export type MonitoringFinding=z.infer<typeof monitoringFindingSchema>;export type WorkspaceHealth=z.infer<typeof workspaceHealthSchema>

const stable=(value:unknown):string=>value&&typeof value==='object'?Array.isArray(value)?`[${value.map(stable).join(',')}]`:`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${stable(item)}`).join(',')}}`:JSON.stringify(value)
const hash=(value:string)=>{let result=2166136261;for(let index=0;index<value.length;index++){result^=value.charCodeAt(index);result=Math.imul(result,16777619)}return(result>>>0).toString(36)}
const finding=(value:Omit<MonitoringFinding,'id'>):MonitoringFinding=>({...value,id:`health-${hash(stable({owner:value.owner,subject:value.subject,route:value.route,phase:value.phase,issues:value.canonicalIssueIds}))}`})
const rank={unavailable:0,blocking:1,attention:2,info:3},ownerRank={goal:0,persistence:1,evidence:2,cost:3,supplier:4,plan:5,scenario:6,operation:7,webmcp:8}
export function orderMonitoringFindings(items:MonitoringFinding[]){return[...items].sort((a,b)=>rank[a.severity]-rank[b.severity]||ownerRank[a.owner]-ownerRank[b.owner]||a.id.localeCompare(b.id))}
export interface MonitoringInput{workspaceId:string;activeGoal?:{id:string;revision:number};draftDiverged:boolean;plan:{id:string;revision:number;lineCount:number};issues:EvidenceIssue[];evaluation?:PlanEvaluation;scenarioBasis?:string;operations:Array<{id:string;revision:number;lifecycle:string;stale:boolean;safeNextAction:string;canRebase:boolean}>;evaluatedAt:string}
export interface MonitoringRuntimeFacts{persistence:{status:'ready'|'saving'|'save_error'|'conflict'|'unavailable'|'recovery_required';retrySupported:boolean;message?:string;access?:'gated'|'memory_preserved'};webmcp:{status:'unavailable'|'registering'|'ready'|'error';toolCount:number;requiredToolCount:13}}
const summarize=(items:MonitoringFinding[])=>{const findings=orderMonitoringFindings(items).slice(0,50),counts={blocking:findings.filter(item=>item.blocking).length,attention:findings.filter(item=>item.severity==='attention').length,informational:findings.filter(item=>item.severity==='info').length,total:findings.length},status=findings.some(item=>item.severity==='unavailable')?'unavailable':findings.some(item=>item.blocking)?'blocked':findings.some(item=>item.severity==='attention'||item.severity==='info')?'attention_required':'ready';return{findings,counts,status:monitoringStatusSchema.parse(status),highestPriorityReason:findings[0]?.reason}}
export function projectWorkspaceHealth(input:MonitoringInput):WorkspaceHealth{
 const items:MonitoringFinding[]=[]
 if(!input.activeGoal)items.push(finding({owner:'goal',subject:{kind:'workspace',id:input.workspaceId},severity:'blocking',blocking:true,reason:'No purchase goal is committed.',whyItMatters:'Downstream evidence and planning cannot be judged without a human-committed requirement.',route:'commit_goal',routeKind:'navigational',humanApprovalRequired:true,canonicalIssueIds:[],phase:'no-active-goal'}))
 else{
  if(input.draftDiverged)items.push(finding({owner:'goal',subject:{kind:'requirement',id:input.activeGoal.id},severity:'attention',blocking:false,reason:'The editable goal differs from the committed requirement.',whyItMatters:'Sourcing and evaluation continue to use the committed revision until the human commits changes.',route:'commit_goal',routeKind:'navigational',humanApprovalRequired:true,canonicalIssueIds:[],phase:`${input.activeGoal.revision}:draft-diverged`}))
  for(const issue of input.issues.filter(item=>!item.resolved).slice(0,30)){const candidate=issue.subject.kind==='candidate'?issue.subject:undefined,refresh=Boolean(candidate&&issue.routes.includes('refresh_evidence')),severity=issue.blocksReadiness?'blocking':issue.importance==='preference'?'info':'attention';items.push(finding({owner:'evidence',subject:candidate?{kind:'product',id:candidate.id,provider:candidate.source}:{kind:issue.subject.kind==='supplier'?'supplier':'requirement',id:'id'in issue.subject?issue.subject.id:input.activeGoal.id},severity,blocking:issue.blocksReadiness,reason:issue.reason,whyItMatters:issue.blocksReadiness?'This canonical evidence issue prevents current decision readiness.':'This evidence may improve the decision but does not block it.',route:refresh?'refresh_evidence':'review_evidence',routeKind:refresh?'executable':'navigational',humanApprovalRequired:refresh,repair:refresh&&candidate?{kind:'refresh_evidence',targetId:candidate.id,provider:candidate.source}:undefined,canonicalIssueIds:[issue.id],phase:`${issue.kind}:${issue.observation?.id??'none'}:${issue.observation?.sequence??0}:${issue.evidence.state}`}))}
  if(!input.plan.lineCount)items.push(finding({owner:'plan',subject:{kind:'plan',id:input.plan.id},severity:'attention',blocking:false,reason:'The purchase plan is empty.',whyItMatters:'A plan is needed before whole-plan cost and handoff readiness can be established.',route:'review_plan',routeKind:'navigational',humanApprovalRequired:true,canonicalIssueIds:[],phase:`${input.plan.revision}:empty`}))
  else if(input.evaluation){
   if(input.evaluation.costAssessment&&input.evaluation.costAssessment.completeness!=='complete_exact')items.push(finding({owner:'cost',subject:{kind:'plan',id:input.plan.id},severity:input.evaluation.costAssessment.completeness==='conflicting'?'blocking':'attention',blocking:input.evaluation.costAssessment.completeness==='conflicting',reason:input.evaluation.costAssessment.verificationReasons[0]??input.evaluation.unresolvedCosts[0]??'Complete landed cost is not yet exact.',whyItMatters:'The canonical cost owner cannot establish an exact one-time landed plan total.',route:'review_plan',routeKind:'navigational',humanApprovalRequired:true,canonicalIssueIds:[],phase:`cost-${hash(stable(input.evaluation.costAssessment))}`}))
   const supplier=input.evaluation.supplierAssessments?.find(item=>item.readiness!=='ready_on_current_evidence');if(supplier)items.push(finding({owner:'supplier',subject:{kind:'supplier',id:supplier.supplierId},severity:supplier.readiness.startsWith('blocked_')?'blocking':'attention',blocking:supplier.readiness.startsWith('blocked_'),reason:supplier.reasons[0]??'Supplier evidence requires review.',whyItMatters:'The canonical supplier owner does not consider this supplier ready on current evidence.',route:'review_supplier',routeKind:'navigational',humanApprovalRequired:true,canonicalIssueIds:[],phase:`supplier-${hash(stable(supplier))}`}))
   if(input.evaluation.readiness!=='ready_on_current_evidence')items.push(finding({owner:'plan',subject:{kind:'plan',id:input.plan.id},severity:input.evaluation.readiness?.startsWith('blocked_')?'blocking':'attention',blocking:Boolean(input.evaluation.readiness?.startsWith('blocked_')),reason:input.evaluation.readinessReasons?.[0]??'The current plan needs review.',whyItMatters:'The canonical plan evaluator does not consider this plan ready on current evidence.',route:'review_plan',routeKind:'navigational',humanApprovalRequired:true,canonicalIssueIds:[],phase:`${input.plan.revision}:${input.evaluation.readiness??input.evaluation.status}`}))
  }
  for(const operation of input.operations){if(!operation.stale)continue;items.push(finding({owner:'operation',subject:{kind:'operation',id:operation.id},severity:operation.canRebase?'attention':'blocking',blocking:!operation.canRebase,reason:operation.canRebase?'This pre-handoff operational case is stale.':'This post-handoff operational case is stale and its historical basis is immutable.',whyItMatters:'Operational history must remain bound to the exact approved decision basis.',route:operation.canRebase?'rebase_operation':'review_operation',routeKind:operation.canRebase?'executable':'informational',humanApprovalRequired:operation.canRebase,repair:operation.canRebase?{kind:'rebase_operation',targetId:operation.id}:undefined,canonicalIssueIds:[],phase:`${operation.revision}:${operation.lifecycle}:${operation.safeNextAction}`}))}
 }
 const summary=summarize(items),basisFingerprint=`health-${hash(stable({workspaceId:input.workspaceId,goal:input.activeGoal,plan:input.plan,scenarioBasis:input.scenarioBasis,findings:summary.findings.map(item=>({id:item.id,phase:item.phase,repair:item.repair}))}))}`
 return workspaceHealthSchema.parse({workspaceId:input.workspaceId,requirement:input.activeGoal,plan:{id:input.plan.id,revision:input.plan.revision},evaluatedAt:input.evaluatedAt,basisFingerprint,projectBasisFingerprint:basisFingerprint,...summary})
}
export function composeWorkspaceHealth(project:WorkspaceHealth,runtime:MonitoringRuntimeFacts):WorkspaceHealth{const items=[...project.findings],persistence=runtime.persistence;if(persistence.status!=='ready'&&persistence.status!=='saving'){const unavailable=persistence.status==='unavailable'||persistence.status==='recovery_required',reason=persistence.message??(persistence.status==='conflict'?'Another tab saved a newer workspace; current memory is preserved.':'Local persistence needs attention.');items.push(finding({owner:'persistence',subject:{kind:'persistence',id:project.workspaceId},severity:unavailable?'unavailable':'blocking',blocking:true,reason,whyItMatters:'Workspace durability and safe agent access depend on the canonical persistence lifecycle.',route:persistence.retrySupported?'retry_persistence':'inspect_persistence',routeKind:persistence.retrySupported?'executable':'informational',humanApprovalRequired:persistence.retrySupported,repair:persistence.retrySupported?{kind:'retry_persistence',targetId:project.workspaceId}:undefined,canonicalIssueIds:[],phase:stable(persistence)}))}const webmcp=runtime.webmcp;if(webmcp.status!=='ready'||webmcp.toolCount!==webmcp.requiredToolCount)items.push(finding({owner:'webmcp',subject:{kind:'webmcp',id:project.workspaceId},severity:'unavailable',blocking:true,reason:webmcp.status==='registering'?'The bounded agent tool surface is registering.':'The bounded agent tool surface is unavailable or incomplete.',whyItMatters:`Agent access requires exactly ${webmcp.requiredToolCount} registered tools.`,route:'inspect_webmcp',routeKind:'informational',humanApprovalRequired:false,canonicalIssueIds:[],phase:`${webmcp.status}:${webmcp.toolCount}:${webmcp.requiredToolCount}`}));const summary=summarize(items);return workspaceHealthSchema.parse({...project,...summary,basisFingerprint:`${project.basisFingerprint}-${hash(stable(runtime))}`})}
export const monitoringRepairCommandSchema=z.object({findingId:z.string().min(1).max(160),basisFingerprint:z.string().min(1).max(100),targetId:z.string().min(1).max(500),provider:z.string().min(1).max(100).optional()}).strict()
export type MonitoringRepairCommand=z.infer<typeof monitoringRepairCommandSchema>
export function identityFromRepair(findingValue:MonitoringFinding):ProviderIdentity|undefined{return findingValue.repair?.kind==='refresh_evidence'&&findingValue.repair.provider?{provider:findingValue.repair.provider as ProviderIdentity['provider'],id:findingValue.repair.targetId}:undefined}
