import {describe,expect,it} from 'vitest'
import {createCoSourceApplication} from '../application/cosource-application'
import {createApplicationTools} from './application-tools'

function fixture(){let id=0;return createCoSourceApplication({market:{country:'GB',currency:'GBP'},catalog:{search:async()=>({products:[],messages:[],pagination:{hasMore:false}}),product:async()=>{throw new Error('unused')}},makeId:()=>`id-${++id}`})}
const base=(application:ReturnType<typeof fixture>,condition:Record<string,unknown>)=>{const state=application.getSnapshot();return{sessionId:state.id,draftId:state.goalDraft.id,draftRevision:state.goalDraft.revision,proposed:{summary:'Schema fidelity',requirements:[condition],preferences:[],exclusions:[]},interpretationNotes:'Representative runtime validation.',assumptions:[],unresolvedQuestions:[]}}

describe('B3R advertised goal interpretation schema',()=>{
 it('advertises discriminated condition requirements and exact runtime bounds',()=>{const tool=createApplicationTools(fixture()).find(item=>item.name==='propose_goal_interpretation')!,schema=tool.inputSchema as {properties:{proposed:{properties:{maximumItemPrice:{properties:{minorAmount:Record<string,unknown>;currency:{enum:string[]}}};requirements:{items:{oneOf:Array<{properties:{operator:{const:string};value?:{pattern?:string}};required:string[];additionalProperties:boolean}>}}}}}};const proposed=schema.properties.proposed.properties,variants=proposed.requirements.items.oneOf,required=(operator:string)=>variants.find(item=>item.properties.operator.const===operator)!.required;expect(variants).toHaveLength(6);expect(required('free_text')).toContain('value');expect(required('equals')).toEqual(expect.arrayContaining(['field','value']));expect(required('at_most')).toEqual(expect.arrayContaining(['field','value']));expect(required('at_least')).toEqual(expect.arrayContaining(['field','value']));expect(required('is_true')).toContain('field');expect(required('is_false')).toContain('field');expect(variants.every(item=>item.additionalProperties===false)).toBe(true);expect(variants.find(item=>item.properties.operator.const==='at_most')!.properties.value!.pattern).toBeTruthy();expect(proposed.maximumItemPrice.properties.minorAmount).toMatchObject({type:'integer',minimum:0,maximum:Number.MAX_SAFE_INTEGER});expect(proposed.maximumItemPrice.properties.currency.enum).toContain('GBP');expect(proposed.maximumItemPrice.properties.currency.enum).not.toContain('ZZZ')})
 it.each([['12',true],['12.5',true],['-2.5',true],['0x10',false],['NaN',false],['Infinity',false],['1e9999',false],['1'.repeat(33),false]] as const)('keeps advertised and runtime numeric acceptance aligned for %s',(value,expected)=>{const application=fixture(),tool=createApplicationTools(application).find(item=>item.name==='propose_goal_interpretation')!,schema=tool.inputSchema as {properties:{proposed:{properties:{requirements:{items:{oneOf:Array<{properties:{operator:{const:string};value?:{pattern?:string;maxLength?:number}}}>}}}}}},variant=schema.properties.proposed.properties.requirements.items.oneOf.find(item=>item.properties.operator.const==='at_least')!,advertised=Boolean(value.length<=(variant.properties.value!.maxLength??Infinity)&&new RegExp(variant.properties.value!.pattern!).test(value)),runtime=application.submitGoalInterpretation(base(application,{id:'a',operator:'at_least',field:'value',value})).ok;expect(advertised).toBe(expected);expect(runtime).toBe(advertised)})
 it.each([
  ['free_text',{id:'a',operator:'free_text',value:'waterproof'}],['equals',{id:'a',operator:'equals',field:'colour',value:'black'}],['is_true',{id:'a',operator:'is_true',field:'recyclable'}],['is_false',{id:'a',operator:'is_false',field:'contains latex'}],['at_most',{id:'a',operator:'at_most',field:'weight',value:'1.5'}],['at_least',{id:'a',operator:'at_least',field:'warranty',value:'2'}],
  ['negative decimal',{id:'a',operator:'at_least',field:'temperature',value:'-2.5'}],
 ])('accepts the advertised valid %s variant at runtime',(_operator,condition)=>{const application=fixture();expect(application.submitGoalInterpretation(base(application,condition))).toMatchObject({ok:true})})
 it.each([
  ['free_text missing value',{id:'a',operator:'free_text'}],['equals missing field',{id:'a',operator:'equals',value:'black'}],['boolean missing field',{id:'a',operator:'is_true'}],['maximum nonnumeric',{id:'a',operator:'at_most',field:'weight',value:'many'}],['minimum missing value',{id:'a',operator:'at_least',field:'warranty'}],['hexadecimal',{id:'a',operator:'at_least',field:'warranty',value:'0x10'}],['NaN',{id:'a',operator:'at_least',field:'warranty',value:'NaN'}],['Infinity',{id:'a',operator:'at_least',field:'warranty',value:'Infinity'}],['exponent overflow',{id:'a',operator:'at_least',field:'warranty',value:'1e9999'}],['excessive digits',{id:'a',operator:'at_least',field:'warranty',value:'1'.repeat(33)}],['additional property',{id:'a',operator:'free_text',value:'x',extra:true}],
 ])('rejects the advertised invalid %s variant at runtime',(_label,condition)=>{const application=fixture();expect(application.submitGoalInterpretation(base(application,condition))).toMatchObject({ok:false,code:'invalid_input'})})
})
