import {describe,expect,it,vi} from 'vitest'
import {createCoSourceApplication} from '../application/cosource-application'
import {COMMERCE_PROVIDERS,type ProductCluster} from '../commerce/domain/commerce'
import {createApplicationTools} from './application-tools'
const provider=COMMERCE_PROVIDERS.shopifyGlobalCatalog,provenance={kind:'provider_explicit' as const,provider},product:ProductCluster={identity:{provider,id:'real'},title:{value:'Real',provenance},media:[],offers:[],offerCompleteness:'featured_only',provenance}
function fixture(){const search=vi.fn(async()=>({products:[product],messages:[],pagination:{hasMore:false}})),application=createCoSourceApplication({market:{country:'GB',currency:'GBP'},catalog:{search,product:async()=>({product,selectedOptions:[],messages:[]})},makeId:(()=>{let n=0;return()=>`id-${++n}`})()});application.editGoal({summary:'Equip team',searchFocus:'products',quantity:150,requirements:[{id:'proof',operator:'free_text',value:'verified'}]});application.commitGoalDraft();return{application,search,tools:createApplicationTools(application)}}
describe('application-backed sourcing tools',()=>{
 it('stores bounded agent candidates without retaining or changing plan',async()=>{const{application,search,tools}=fixture(),before=application.getSnapshot().plan;expect(await tools.find(tool=>tool.name==='search_products')!.execute({query:'products',country:'GB',currency:'GBP'})).toMatchObject({ok:true});expect(search).toHaveBeenCalled();expect(application.getSnapshot().agentDiscovery.candidates).toHaveLength(1);expect(application.getSnapshot().retainedProducts).toHaveLength(0);expect(application.getSnapshot().plan).toBe(before)})
 it('rejects arbitrary filters and reads kernel evidence gaps',async()=>{const{tools,search}=fixture(),source=tools.find(tool=>tool.name==='search_products')!,gaps=tools.find(tool=>tool.name==='get_evidence_gaps')!;expect(await source.execute({query:'products',country:'GB',currency:'GBP',url:'https://bad.test'})).toMatchObject({ok:false,error:{code:'invalid_input'}});expect(search).not.toHaveBeenCalled();expect(await gaps.execute({})).toMatchObject({ok:true,data:{gaps:expect.arrayContaining([expect.objectContaining({description:'verified'}),expect.objectContaining({description:'Quantity 150'})])}})})
 it('returns only the four candidates accepted by the final bounded page',async()=>{const make=(id:string):ProductCluster=>({...product,identity:{provider,id},title:{value:id,provenance}}),first=Array.from({length:6},(_,index)=>make(`p${index+1}`)),second=Array.from({length:6},(_,index)=>make(`p${index+7}`)),search=vi.fn().mockResolvedValueOnce({products:first,messages:[],pagination:{hasMore:true,cursor:'next'}}).mockResolvedValueOnce({products:second,messages:[],pagination:{hasMore:true,cursor:'discarded'}}),application=createCoSourceApplication({market:{country:'GB',currency:'GBP'},catalog:{search,product:async()=>({product,selectedOptions:[],messages:[]})}}),source=createApplicationTools(application).find(tool=>tool.name==='search_products')!;await source.execute({query:'products',country:'GB',currency:'GBP',limit:6});const response=await source.execute({query:'products',country:'GB',currency:'GBP',limit:6,cursor:'next'}) as {data:{candidates:Array<{identity:{id:string}}>;pagination:{hasMore:boolean;cursor?:string}}};expect(response.data.candidates.map(item=>item.identity.id)).toEqual(['p7','p8','p9','p10']);expect(response.data.pagination).toEqual({hasMore:false});expect(application.getSnapshot().agentDiscovery.candidates).toHaveLength(10)})
})
