import {describe,expect,it,vi} from 'vitest'
import {createCoSourceApplication} from '../application/cosource-application'
import {COMMERCE_PROVIDERS,type ProductCluster} from '../commerce/domain/commerce'
import {createApplicationTools,registerApplicationTools,WEBMCP_TOOL_NAMES} from './application-tools'
const provider=COMMERCE_PROVIDERS.shopifyGlobalCatalog,provenance={kind:'provider_explicit' as const,provider},product:ProductCluster={identity:{provider,id:'a'},title:{value:'A',provenance},media:[],offers:[],offerCompleteness:'featured_only',provenance}
function app(){let n=0;const application=createCoSourceApplication({market:{country:'GB',currency:'GBP'},catalog:{search:async()=>({products:[product],messages:[],pagination:{hasMore:false}}),product:async()=>({product,selectedOptions:[],messages:[]})},makeId:()=>`id-${++n}`});application.editGoal({summary:'Buy A',searchFocus:'products'});application.commitGoalDraft();return application}
const execute=async(name:string,input:unknown={})=>createApplicationTools(app()).find(tool=>tool.name===name)!.execute(input) as Promise<{ok:boolean;data?:Record<string,unknown>;error?:{code:string}}>
describe('application-backed WebMCP tools',()=>{
 it('registers all unique tools atomically',async()=>{const registered:WebMCPToolDefinition[]=[];const application=app(),controller=new AbortController();expect(await registerApplicationTools({registerTool:async tool=>{registered.push(tool)}},application,controller.signal)).toBe(13);expect(new Set(registered.map(tool=>tool.name)).size).toBe(13)})
 it('reads the projected canonical resource requirement',async()=>expect(await execute('get_resource_requirement')).toMatchObject({ok:true,data:{resource:{type:'product'},approvalPolicy:{fulfillmentAuthority:'recommendation_only'}}}))
 it('reads the live plan',async()=>expect((await execute('get_purchase_plan')).data).toMatchObject({revision:0}))
 it('evaluates the plan through the kernel',async()=>expect((await execute('evaluate_purchase_plan')).ok).toBe(true))
 it('lists retained evidence only after promotion',async()=>{const application=app();await application.searchCandidates({query:'products'});application.retainCandidate(product.identity);const tool=createApplicationTools(application).find(item=>item.name==='list_retained_products')!;expect(await tool.execute({})).toMatchObject({ok:true,data:{products:[{identity:product.identity}]}})})
 it('rejects invalid identities',async()=>expect((await execute('inspect_product',{product:{provider:'unsupported',id:'a'}})).error?.code).toBe('invalid_identity'))
 it('compares through the shared kernel',async()=>{const application=app(),second={...product,identity:{provider,id:'b'},title:{value:'B',provenance}};await application.searchCandidates({query:'products'});application.retainCandidate(product.identity);const unavailable=application.compareCandidates(product.identity,second.identity);expect(unavailable.ok).toBe(false)})
 it('contains no direct plan-application tool',()=>{expect(WEBMCP_TOOL_NAMES.join(' ')).not.toContain('apply_plan_changes');expect(vi.fn()).not.toHaveBeenCalled()})
 it('keeps exactly thirteen tools with no supplier mutation authority',()=>{expect(WEBMCP_TOOL_NAMES).toHaveLength(13);expect(WEBMCP_TOOL_NAMES.join(' ')).not.toMatch(/supplier|merchant|quotation|risk|contact|rename|link/)})
 it('exposes bounded canonical issues without human-verification authority',async()=>{const application=app();const output=await createApplicationTools(application).find(item=>item.name==='get_evidence_gaps')!.execute({});expect(output).toHaveProperty('ok');expect(WEBMCP_TOOL_NAMES).toHaveLength(13);expect(WEBMCP_TOOL_NAMES.join(' ')).not.toMatch(/verify|confirm|reject_evidence|record_fact|dismiss_issue/)})
 it('exposes interpretation proposal authority without human adoption or commitment tools',async()=>{const application=app(),tools=createApplicationTools(application),context=await tools.find(item=>item.name==='get_goal_context')!.execute({}) as {data:{sessionId:string;draft:{id:string;revision:number}}},before=application.getSnapshot(),submission=await tools.find(item=>item.name==='propose_goal_interpretation')!.execute({sessionId:context.data.sessionId,draftId:context.data.draft.id,draftRevision:context.data.draft.revision,proposed:{summary:'Interpreted intent',searchFocus:'chairs',requirements:[],preferences:[],exclusions:[]},interpretationNotes:'Structured only the supplied intent.',assumptions:[],unresolvedQuestions:['Preferred material?']}) as {ok:boolean;data:{authority:string;evidenceStatus:string;proposed:{summary:string}}};expect(submission).toMatchObject({ok:true,data:{authority:'awaiting_human_review',evidenceStatus:'validated_agent_input_not_commerce_evidence',proposed:{summary:'Interpreted intent'}}});expect(application.getSnapshot().goalDraft).toBe(before.goalDraft);expect(application.getSnapshot().activeGoal).toBe(before.activeGoal);expect(WEBMCP_TOOL_NAMES.join(' ')).not.toMatch(/adopt|reject.*interpretation|commit_goal|activate/);expect(tools.find(item=>item.name==='propose_goal_interpretation')!.annotations?.readOnlyHint).toBe(false)})
 it('rejects malformed interpretation input without changing state',async()=>{const application=app(),before=application.getSnapshot(),tool=createApplicationTools(application).find(item=>item.name==='propose_goal_interpretation')!;expect(await tool.execute({sessionId:before.id,draftId:before.goalDraft.id,draftRevision:before.goalDraft.revision,proposed:{summary:'x',requirements:[],preferences:[],exclusions:[],provider:'forbidden'},interpretationNotes:'note',assumptions:[],unresolvedQuestions:[]})).toMatchObject({ok:false,error:{code:'invalid_input'}});expect(application.getSnapshot()).toBe(before)})
})
