// @vitest-environment jsdom
import { cleanup,renderHook,waitFor } from '@testing-library/react'
import { afterEach,describe,expect,it } from 'vitest'
import { createCoSourceApplication } from '../application/cosource-application'
import { useWebMCP } from './use-webmcp'

afterEach(()=>{cleanup();Reflect.deleteProperty(document,'modelContext')})
const state=createCoSourceApplication({market:{country:'GB',currency:'GBP'},catalog:{search:async()=>({products:[],messages:[],pagination:{hasMore:false}}),product:async()=>{throw new Error('unused')}},makeId:(()=>{let id=0;return()=>`id-${++id}`})()})

describe('WebMCP registration lifecycle',()=>{
  it('does not register before restoration is safe and registers thirteen tools afterward',async()=>{const registrations:WebMCPToolDefinition[]=[];const context=Object.assign(new EventTarget(),{async registerTool(tool:WebMCPToolDefinition){registrations.push(tool)}});Object.defineProperty(document,'modelContext',{configurable:true,value:context});const view=renderHook(({enabled})=>useWebMCP(state,enabled),{initialProps:{enabled:false}});expect(registrations).toHaveLength(0);expect(view.result.current).toMatchObject({status:'unavailable',toolCount:0});view.rerender({enabled:true});await waitFor(()=>expect(view.result.current).toMatchObject({status:'ready',toolCount:13}));expect(new Set(registrations.map(item=>item.name)).size).toBe(13)})
  it('becomes ready only after all thirteen registrations succeed and owns lifecycle state only',async()=>{const signals:AbortSignal[]=[];const context=Object.assign(new EventTarget(),{async registerTool(_tool:WebMCPToolDefinition,options?:{signal?:AbortSignal}){signals.push(options!.signal!)}});Object.defineProperty(document,'modelContext',{configurable:true,value:context});const view=renderHook(()=>useWebMCP(state));await waitFor(()=>expect(view.result.current).toMatchObject({status:'ready',toolCount:13}));expect(Object.keys(view.result.current).sort()).toEqual(['status','toolCount']);expect(signals).toHaveLength(13);view.unmount();expect(signals.every(signal=>signal.aborted)).toBe(true)})
  it('atomically aborts earlier registrations and reports zero tools when one fails',async()=>{const registrations:Array<{name:string;signal:AbortSignal}>=[];const context=Object.assign(new EventTarget(),{async registerTool(tool:WebMCPToolDefinition,options?:{signal?:AbortSignal}){registrations.push({name:tool.name,signal:options!.signal!});if(tool.name==='evaluate_purchase_plan')throw new Error('intentional registration failure')}});Object.defineProperty(document,'modelContext',{configurable:true,value:context});const view=renderHook(()=>useWebMCP(state));await waitFor(()=>expect(view.result.current.status).toBe('error'));expect(view.result.current.toolCount).toBe(0);expect(registrations.length).toBeGreaterThan(1);expect(new Set(registrations.map(item=>item.signal)).size).toBe(1);expect(registrations.every(item=>item.signal.aborted)).toBe(true);view.unmount()})
  it('does not publish ready or error after unmount during pending registration',async()=>{let release!:()=>void;const pending=new Promise<void>(resolve=>{release=resolve}),signals:AbortSignal[]=[];const context=Object.assign(new EventTarget(),{async registerTool(_tool:WebMCPToolDefinition,options?:{signal?:AbortSignal}){signals.push(options!.signal!);await pending}});Object.defineProperty(document,'modelContext',{configurable:true,value:context});const view=renderHook(()=>useWebMCP(state));expect(view.result.current.status).toBe('registering');view.unmount();expect(signals.every(signal=>signal.aborted)).toBe(true);release();await pending})
  it('rebinds exactly thirteen tools and invalidates old handlers when the active project changes',async()=>{const registrations:Array<{tool:WebMCPToolDefinition;signal:AbortSignal}>=[],context=Object.assign(new EventTarget(),{async registerTool(tool:WebMCPToolDefinition,options?:{signal?:AbortSignal}){registrations.push({tool,signal:options!.signal!})}});Object.defineProperty(document,'modelContext',{configurable:true,value:context});const other=createCoSourceApplication({market:{country:'GB',currency:'GBP'},catalog:{search:async()=>({products:[],messages:[],pagination:{hasMore:false}}),product:async()=>{throw new Error('unused')}},makeId:()=> 'other'}),view=renderHook(({application})=>useWebMCP(application),{initialProps:{application:state}});await waitFor(()=>expect(view.result.current.toolCount).toBe(13));const old=registrations.slice();view.rerender({application:other});await waitFor(()=>expect(registrations).toHaveLength(26));expect(old.every(item=>item.signal.aborted)).toBe(true);expect(registrations.slice(13).every(item=>!item.signal.aborted)).toBe(true);expect(new Set(registrations.slice(13).map(item=>item.tool.name))).toHaveLength(13)})
  it('keeps only new-project handlers observably active after rebinding',async()=>{const active=new Map<string,WebMCPToolDefinition>(),context=Object.assign(new EventTarget(),{async registerTool(tool:WebMCPToolDefinition,options?:{signal?:AbortSignal}){active.set(tool.name,tool);options?.signal?.addEventListener('abort',()=>{if(active.get(tool.name)===tool)active.delete(tool.name)},{once:true})}});Object.defineProperty(document,'modelContext',{configurable:true,value:context});const first=createCoSourceApplication({market:{country:'GB',currency:'GBP'},catalog:{search:async()=>({products:[],messages:[],pagination:{hasMore:false}}),product:async()=>{throw new Error('unused')}},makeId:()=> 'project-A'}),second=createCoSourceApplication({market:{country:'GB',currency:'GBP'},catalog:{search:async()=>({products:[],messages:[],pagination:{hasMore:false}}),product:async()=>{throw new Error('unused')}},makeId:()=> 'project-B'}),view=renderHook(({application})=>useWebMCP(application),{initialProps:{application:first}});await waitFor(()=>expect(active.size).toBe(13));expect(await active.get('get_goal_context')!.execute({})).toMatchObject({data:{sessionId:'project-A'}});view.rerender({application:second});await waitFor(()=>expect(active.size).toBe(13));expect(await active.get('get_goal_context')!.execute({})).toMatchObject({data:{sessionId:'project-B'}})})
})
