import {IDBDatabase,IDBFactory} from 'fake-indexeddb'
import {describe,expect,it,vi} from 'vitest'
import {createCoSourceApplication} from '../application/cosource-application'
import {durableProjection,PERSISTED_WORKSPACE_FORMAT_VERSION,type PersistedWorkspaceEnvelope} from '../application/persistence/workspace-persistence'
import {COSOURCE_WORKSPACE_DATABASE,COSOURCE_WORKSPACE_DATABASE_VERSION,COSOURCE_WORKSPACE_KEY,COSOURCE_WORKSPACE_STORE,createIndexedDBWorkspacePersistence} from './indexeddb-workspace-persistence'

const market={country:'GB',currency:'GBP',language:'en'}
function record(summary='',durableRevision=0):PersistedWorkspaceEnvelope{const application=createCoSourceApplication({market,makeId:()=> 'workspace',now:()=> '2026-09-07T00:00:00.000Z',catalog:{search:async()=>({products:[],messages:[],pagination:{hasMore:false}}),product:async()=>{throw new Error('unused')}}});if(summary)application.editGoal({summary});const payload=durableProjection(application.getSnapshot());return{formatVersion:PERSISTED_WORKSPACE_FORMAT_VERSION,workspaceId:payload.id,durableRevision,savedAt:'2026-09-07T00:00:00.000Z',market,payload}}
function rawPut(factory:IDBFactory,value:unknown){return new Promise<void>((resolve,reject)=>{const request=factory.open(COSOURCE_WORKSPACE_DATABASE,COSOURCE_WORKSPACE_DATABASE_VERSION);request.onupgradeneeded=()=>request.result.createObjectStore(COSOURCE_WORKSPACE_STORE);request.onerror=()=>reject(request.error);request.onsuccess=()=>{const database=request.result,transaction=database.transaction(COSOURCE_WORKSPACE_STORE,'readwrite');transaction.objectStore(COSOURCE_WORKSPACE_STORE).put(value,COSOURCE_WORKSPACE_KEY);transaction.oncomplete=()=>{database.close();resolve()};transaction.onerror=()=>{database.close();reject(transaction.error)}}})}
const tick=()=>new Promise(resolve=>setTimeout(resolve,0))

describe('IndexedDB workspace persistence',()=>{
 it('loads absence, creates once, loads back, and saves with the exact expected revision',async()=>{const factory=new IDBFactory(),close=vi.spyOn(IDBDatabase.prototype,'close'),deletion=vi.spyOn(factory,'deleteDatabase'),repository=createIndexedDBWorkspacePersistence(factory),first=record();expect(await repository.load()).toBeUndefined();expect(await repository.compareAndSave(first,undefined)).toEqual({ok:true,record:first});expect(await repository.load()).toEqual(first);const second=record('newer',1);expect(await repository.compareAndSave(second,0)).toEqual({ok:true,record:second});expect(await repository.load()).toEqual(second);expect(close).toHaveBeenCalledTimes(5);expect(deletion).not.toHaveBeenCalled()})
 it('uses one atomic readwrite transaction so concurrent instances cannot both replace the same revision',async()=>{const factory=new IDBFactory(),first=createIndexedDBWorkspacePersistence(factory),second=createIndexedDBWorkspacePersistence(factory);await first.compareAndSave(record(),undefined);const results=await Promise.all([first.compareAndSave(record('first',1),0),second.compareAndSave(record('second',1),0)]);expect(results.filter(result=>result.ok)).toHaveLength(1);expect(results.filter(result=>!result.ok)).toEqual([{ok:false,reason:'conflict',currentRevision:1}]);const saved=await first.load() as PersistedWorkspaceEnvelope;expect(['first','second']).toContain(saved.payload.goalDraft.summary)})
 it('rejects an expected revision when the record is missing without creating data',async()=>{const repository=createIndexedDBWorkspacePersistence(new IDBFactory());expect(await repository.compareAndSave(record('new',1),0)).toEqual({ok:false,reason:'conflict',currentRevision:0});expect(await repository.load()).toBeUndefined()})
 it.each([{durableRevision:'1'},{durableRevision:-1},{durableRevision:0,bad:true},{bad:true}])('does not derive a revision from or overwrite malformed current data',async malformed=>{const factory=new IDBFactory();await rawPut(factory,malformed);const repository=createIndexedDBWorkspacePersistence(factory);await expect(repository.compareAndSave(record('replacement',1),0)).rejects.toThrow('stored workspace record is invalid');expect(await repository.load()).toEqual(malformed)})
 it('surfaces transaction data errors without committing a partial record',async()=>{const repository=createIndexedDBWorkspacePersistence(new IDBFactory()),uncloneable={...record(),payload:{...record().payload,goalDraft:()=>undefined}} as unknown as PersistedWorkspaceEnvelope;await expect(repository.compareAndSave(uncloneable,undefined)).rejects.toBeInstanceOf(Error);expect(await repository.load()).toBeUndefined()})
 it('surfaces a bounded unavailable-open failure',async()=>{const request:Record<string,unknown>={};const factory={open:()=>{queueMicrotask(()=>{(request as unknown as IDBOpenDBRequest).onerror?.(new Event('error'))});return request}} as unknown as IDBFactory;await expect(createIndexedDBWorkspacePersistence(factory).load()).rejects.toThrow('storage unavailable')})
 it('rejects a blocked open and closes a database delivered by a late success',async()=>{const close=vi.fn(),request:Record<string,unknown>={};const factory={open:()=>{queueMicrotask(()=>{(request as unknown as IDBOpenDBRequest).onblocked?.(new Event('blocked') as unknown as IDBVersionChangeEvent);queueMicrotask(()=>{Object.defineProperty(request,'result',{value:{close}});(request as unknown as IDBOpenDBRequest).onsuccess?.(new Event('success'))})});return request}} as unknown as IDBFactory;await expect(createIndexedDBWorkspacePersistence(factory).load()).rejects.toThrow('storage blocked');await tick();expect(close).toHaveBeenCalledOnce()})
})
