import {costComponentSchema,costCoverageSchema,type CostAssessment,type CostBudgetAssessment,type CostComponent,type CostLineInput,type CurrencyCostTotal} from './domain/cost'
import {createMoney,type Money} from '../shared/domain/money'

const add=(a:number,b:number)=>{const value=a+b;if(!Number.isSafeInteger(value))throw new RangeError('Cost addition exceeds the safe integer range');return value}
const scale=(value:number,factor:number)=>{const result=value*factor;if(!Number.isSafeInteger(result))throw new RangeError('Cost multiplication exceeds the safe integer range');return result}
const signature=(component:CostComponent)=>JSON.stringify({category:component.category,effect:component.effect,basis:component.basis,applicability:component.applicability,knowledge:component.knowledge,timing:component.timing,label:component.label})
const claimIdentity=(component:CostComponent,lineId:string)=>`${component.evidence.source}\0${component.basis==='per_order'?`order:${component.orderScope}`:component.basis==='per_plan'?'plan':`line:${lineId}`}\0${component.id}\0${component.category}`
const componentIdentity=(component:CostComponent)=>`${component.evidence.source}\0${component.basis}\0${component.orderScope??''}\0${component.id}\0${component.category}\0${signature(component)}\0${JSON.stringify(component.evidence)}`
const evidenceRank={source_explicit:4,cosource_derived:3,source_inferred:2,unknown:1} as const
const decisionGrade=(strength:CostComponent['evidence']['strength'])=>strength==='source_explicit'||strength==='cosource_derived'
const instant=(value?:string)=>value===undefined?Number.NEGATIVE_INFINITY:Date.parse(value)
const preferEvidence=(a:CostComponent,b:CostComponent)=>evidenceRank[b.evidence.strength]-evidenceRank[a.evidence.strength]||instant(b.evidence.observedAt)-instant(a.evidence.observedAt)||JSON.stringify(a).localeCompare(JSON.stringify(b))
const sortAmount=(component:CostComponent)=>component.knowledge.kind==='unknown'?Number.MAX_SAFE_INTEGER:component.knowledge.kind==='exact'?component.knowledge.amount.minorAmount:component.knowledge.minimum.minorAmount

export function assessCosts(linesInput:CostLineInput[],budget?:Money):CostAssessment{
 const lines=linesInput.map(line=>{if(!line.id||!Number.isSafeInteger(line.quantity)||line.quantity<1)throw new TypeError('Cost lines require a positive safe-integer quantity');return{...line,coverage:costCoverageSchema.parse(line.coverage),components:line.components.map(item=>costComponentSchema.parse(item))}})
 if(new Set(lines.map(line=>line.id)).size!==lines.length)throw new TypeError('Cost line identifiers must be unique')
 const conflicts:string[]=[],groups=new Map<string,Array<{component:CostComponent;factor:number}>>()
 for(const line of lines)for(const component of line.components){if(component.applicability==='does_not_apply')continue;const factor=component.basis==='per_unit'?(line.unitSemantics==='unknown'&&line.quantity>1?0:line.quantity):1,key=claimIdentity(component,line.id),group=groups.get(key)??[];group.push({component,factor});groups.set(key,group)}
 const components:Array<{component:CostComponent;factor:number}>=[]
 for(const [key,claims] of [...groups].sort(([a],[b])=>a.localeCompare(b))){const variants=[...new Set(claims.map(item=>`${item.factor}\0${signature(item.component)}`))];if(variants.length>1){const sample=claims.map(item=>item.component).sort(preferEvidence)[0]!;conflicts.push(`Conflicting ${sample.category} evidence for scoped claim ${key.replaceAll('\0',' / ')}.`);continue}components.push(claims.slice().sort((a,b)=>preferEvidence(a.component,b.component))[0]!)}
 components.sort((a,b)=>sortAmount(a.component)-sortAmount(b.component)||componentIdentity(a.component).localeCompare(componentIdentity(b.component)))
 type Total={baseMin:number;baseMax:number;addMin:number;addMax:number;deductMin:number;deductMax:number;upperKnown:boolean;lowerKnown:boolean;additionComponents:CostComponent[];baseComponents:CostComponent[]}
 const totals=new Map<string,Total>(),unresolved:CostComponent[]=[],unknownApplicability:CostComponent[]=[],recurring:CostComponent[]=[]
 const totalFor=(currency:string)=>{let value=totals.get(currency);if(!value){value={baseMin:0,baseMax:0,addMin:0,addMax:0,deductMin:0,deductMax:0,upperKnown:true,lowerKnown:true,additionComponents:[],baseComponents:[]};totals.set(currency,value)}return value}
 let unknownCurrencyDeduction=false,overflowed=false
 const scaled=(value:number,factor:number)=>{try{return scale(value,factor)}catch{return undefined}}
 const accumulated=(current:number,value:number|undefined)=>{if(value===undefined)return undefined;try{return add(current,value)}catch{return undefined}}
 const composePayable=(base:number,addition:number,deduction:number)=>{const additionDeduction=Math.min(addition,deduction),remainingAddition=addition-additionDeduction,remainingDeduction=deduction-additionDeduction,baseDeduction=Math.min(base,remainingDeduction),remainingBase=base-baseDeduction,value=accumulated(remainingBase,remainingAddition);return{value:value??Math.max(remainingBase,remainingAddition),complete:value!==undefined}}
 for(const {component,factor} of components){const possible=component.applicability==='unknown',weak=!decisionGrade(component.evidence.strength);if(possible){unknownApplicability.push(component);unresolved.push(component)}if(component.timing==='recurring'){recurring.push(component);if(possible||weak)unresolved.push(component);continue}if(component.timing==='usage_based'||factor===0){unresolved.push(component);continue}if(weak){unresolved.push(component);const currency=component.knowledge.kind==='unknown'?component.knowledge.currency:component.knowledge.kind==='exact'?component.knowledge.amount.currency:component.knowledge.minimum.currency;if(currency){const total=totalFor(currency);if(component.effect==='addition')total.upperKnown=false;else total.lowerKnown=false}else if(component.effect==='deduction')unknownCurrencyDeduction=true;continue}if(component.knowledge.kind==='unknown'){unresolved.push(component);if(component.knowledge.currency){const total=totalFor(component.knowledge.currency);if(component.effect==='addition')total.upperKnown=false;else total.lowerKnown=false}else if(component.effect==='deduction')unknownCurrencyDeduction=true;continue}const minimum=component.knowledge.kind==='exact'?component.knowledge.amount:component.knowledge.minimum,maximum=component.knowledge.kind==='exact'?component.knowledge.amount:component.knowledge.maximum;if(minimum.currency!==maximum.currency)throw new TypeError('Cross-currency cost range');const total=totalFor(minimum.currency),min=scaled(minimum.minorAmount,factor),max=scaled(maximum.minorAmount,factor);let componentOverflow=false;if(component.effect==='addition'){const base=component.category==='base_price'&&!possible;if(base)total.baseComponents.push(component);else total.additionComponents.push(component);const minField=base?'baseMin':'addMin',maxField=base?'baseMax':'addMax',nextMin=accumulated(total[minField],possible?0:min);if(nextMin===undefined)componentOverflow=true;else total[minField]=nextMin;const nextMax=accumulated(total[maxField],max);if(nextMax===undefined){componentOverflow=true;total.upperKnown=false}else total[maxField]=nextMax}else{const nextMin=accumulated(total.deductMin,possible?0:min);if(nextMin===undefined)componentOverflow=true;else total.deductMin=nextMin;const nextMax=accumulated(total.deductMax,max);if(nextMax===undefined){componentOverflow=true;total.lowerKnown=false}else total.deductMax=nextMax}if(componentOverflow){overflowed=true;unresolved.push(component)}}
 if(unknownCurrencyDeduction)for(const total of totals.values())total.lowerKnown=false
 const partial=lines.filter(line=>line.coverage.status==='partial'||!decisionGrade(line.coverage.evidence.strength)),missingCategories=[...new Set(partial.flatMap(line=>line.coverage.unresolvedCategories??[]))].sort(),coverageReasons=[...new Set(partial.flatMap(line=>line.coverage.status==='partial'?(line.coverage.reasons??[]):[`Complete coverage is supported only by ${line.coverage.evidence.strength} evidence and requires verification.`]))].sort()
 for(const [currency,total] of totals){const payableMaximum=accumulated(total.baseMax,total.addMax);if(total.upperKnown&&payableMaximum!==undefined&&total.deductMin>payableMaximum)conflicts.push(`Known deductions exceed payable additions in ${currency}.`)}
 const hasRanges=components.some(({component})=>component.applicability==='applies'&&component.knowledge.kind==='range'&&component.timing==='one_time'),conflicting=conflicts.length>0
 const projected=[...totals].sort(([a],[b])=>a.localeCompare(b)).map(([currency,total])=>{const positiveMinimum=accumulated(total.baseMin,total.addMin),lowerProjection=composePayable(total.baseMin,total.addMin,total.deductMax);if(positiveMinimum===undefined){overflowed=true;unresolved.push(...(total.additionComponents.length?total.additionComponents:total.baseComponents))}if(!lowerProjection.complete){overflowed=true;unresolved.push(...(total.additionComponents.length?total.additionComponents:total.baseComponents))}const lower=total.lowerKnown?lowerProjection.value:0;const positiveMaximum=total.upperKnown?accumulated(total.baseMax,total.addMax):undefined,upperProjection=total.upperKnown?composePayable(total.baseMax,total.addMax,total.deductMin):undefined;if(total.upperKnown&&positiveMaximum===undefined){overflowed=true;unresolved.push(...(total.additionComponents.length?total.additionComponents:total.baseComponents))}if(upperProjection&&!upperProjection.complete){overflowed=true;unresolved.push(...(total.additionComponents.length?total.additionComponents:total.baseComponents))}const upper=total.upperKnown&&upperProjection?.complete?upperProjection.value:undefined;return{currency,total,lower,upper}})
 const incomplete=unresolved.length>0||partial.length>0||recurring.length>0||overflowed
 const currencyTotals:CurrencyCostTotal[]=projected.map(({currency,total,lower,upper})=>({currency,baseSubtotal:createMoney(total.baseMin,currency),knownAdditions:createMoney(total.addMin,currency),knownDeductions:createMoney(total.deductMin,currency),knownLowerBound:createMoney(lower,currency),upperBound:upper!==undefined&&!conflicting?createMoney(upper,currency):undefined,exactLandedTotal:!incomplete&&!conflicting&&!hasRanges&&upper===lower?createMoney(lower,currency):undefined}))
 const completeness:CostAssessment['completeness']=conflicting?'conflicting':incomplete?'incomplete':hasRanges?'bounded':'complete_exact'
 const reasons=[...conflicts,...coverageReasons,...(overflowed?['One or more cost components exceed the safe aggregate range and remain unresolved.']:[]),...(components.some(({component})=>!decisionGrade(component.evidence.strength))?['Inferred or unknown cost amounts require decision-grade verification.']:[]),...(unknownApplicability.length?['One or more cost components may apply but applicability is unknown.']:[]),...(recurring.length?['Recurring costs require a separate evaluation horizon.']:[]),...(components.some(({component})=>component.timing==='usage_based')?['Usage-based costs cannot be totalled without measured usage.']:[])]
 let budgetResult:CostBudgetAssessment|undefined
 if(budget){const comparable=currencyTotals.find(item=>item.currency===budget.currency),mixed=currencyTotals.some(item=>item.currency!==budget.currency);if(comparable&&comparable.knownLowerBound.minorAmount>budget.minorAmount)budgetResult={status:'failed',budget,reason:'The unavoidable landed-cost lower bound already exceeds the budget.'};else if(completeness==='complete_exact'&&!mixed&&comparable?.exactLandedTotal)budgetResult={status:comparable.exactLandedTotal.minorAmount<=budget.minorAmount?'satisfied':'failed',budget,reason:comparable.exactLandedTotal.minorAmount<=budget.minorAmount?'The complete exact landed total is within budget.':'The complete exact landed total exceeds budget.'};else budgetResult={status:'unknown',budget,reason:mixed?'Mixed currencies cannot be compared with one budget without FX evidence.':'The budget cannot be proven while landed costs are incomplete, ranged, recurring, usage-based, or conflicting.'}}
 const orderedUnique=(items:CostComponent[])=>[...new Map(items.slice().sort((a,b)=>componentIdentity(a).localeCompare(componentIdentity(b))).map(item=>[componentIdentity(item),item])).values()]
 return{completeness,currencyTotals,recurring:orderedUnique(recurring),unresolved:orderedUnique(unresolved),unknownApplicability:orderedUnique(unknownApplicability),missingCategories,conflicts:[...new Set(conflicts)].sort(),verificationReasons:[...new Set(reasons)].slice(0,30),budget:budgetResult}
}
