import {describe,expect,it} from 'vitest'
import {assessCosts} from './assess-cost'
import {costComponentSchema,type CostComponent,type CostLineInput} from './domain/cost'
import {offerCostLine} from './commerce-cost-adapter'

const money=(minorAmount:number,currency='GBP')=>({minorAmount,currency})
const component=(id:string,minorAmount:number,changes:Partial<CostComponent>={}):CostComponent=>({id,category:'base_price',effect:'addition',basis:'per_unit',applicability:'applies',knowledge:{kind:'exact',amount:money(minorAmount)},timing:'one_time',evidence:{strength:'source_explicit',source:'fixture'},...changes})
const coverage={status:'complete' as const,evidence:{strength:'source_explicit' as const,source:'fixture'}}
const line=(components:CostComponent[],changes:Partial<CostLineInput>={}):CostLineInput=>({id:'line',quantity:2,unitSemantics:'single_unit',components,coverage,...changes})

describe('canonical cost assessment',()=>{
 it('adapts an offer listing price as exact base evidence',()=>{const provenance={kind:'provider_explicit' as const,provider:'shopify_global_catalog' as const},offer={identity:{provider:'shopify_global_catalog' as const,id:'offer'},title:{value:'Offer',provenance},price:money(2499),availability:{state:'available' as const,basis:'catalog_signal' as const,provenance},selectedOptions:[],media:[],correlations:[],provenance};expect(assessCosts([offerCostLine({id:'line',quantity:1,unitSemantics:'single_item'},offer)]).currencyTotals[0]?.baseSubtotal).toEqual(money(2499))})
 it('multiplies exact per-unit money in minor units',()=>expect(assessCosts([line([component('base',1250)])]).currencyTotals[0]?.exactLandedTotal).toEqual(money(2500)))
 it('contains multiplication overflow as unresolved evidence',()=>expect(assessCosts([line([component('base',Number.MAX_SAFE_INTEGER)])])).toMatchObject({completeness:'incomplete',currencyTotals:[{exactLandedTotal:undefined}],unresolved:[{id:'base'}]}))
 it('contains addition overflow without emitting an unsafe exact total',()=>expect(assessCosts([line([component('a',Number.MAX_SAFE_INTEGER,{basis:'per_line'}),component('b',1,{basis:'per_line'})],{quantity:1})])).toMatchObject({completeness:'incomplete',currencyTotals:[{exactLandedTotal:undefined}],unresolved:[{id:'a'}]}))
 it('keeps mixed currencies separate',()=>expect(assessCosts([line([component('gbp',10,{basis:'per_line'}),component('usd',20,{basis:'per_line',knowledge:{kind:'exact',amount:money(20,'USD')}})],{quantity:1})]).currencyTotals.map(x=>x.currency)).toEqual(['GBP','USD']))
 it('does not turn unknown cost into zero',()=>{const result=assessCosts([line([component('base',100),component('shipping',0,{category:'delivery',basis:'per_line',knowledge:{kind:'unknown',currency:'GBP'}})])]);expect(result.completeness).toBe('incomplete');expect(result.currencyTotals[0]?.exactLandedTotal).toBeUndefined()})
 it('adds exact delivery and fees',()=>{const result=assessCosts([line([component('base',100),component('ship',50,{category:'delivery',basis:'per_line'}),component('fee',25,{category:'mandatory_fee',basis:'per_line'})],{quantity:1})]);expect(result.currencyTotals[0]).toMatchObject({knownAdditions:money(75),exactLandedTotal:money(175)})})
 it('applies discounts as deductions without negative money',()=>expect(assessCosts([line([component('base',100),component('discount',25,{category:'discount',effect:'deduction',basis:'per_line'})],{quantity:1})]).currencyTotals[0]?.exactLandedTotal).toEqual(money(75)))
 it('rejects a deduction beyond payable costs as conflicting',()=>expect(assessCosts([line([component('base',100),component('discount',250,{category:'discount',effect:'deduction',basis:'per_line'})],{quantity:1})]).completeness).toBe('conflicting'))
 it('is invariant to input ordering',()=>{const a=component('base',100,{basis:'per_line'}),b=component('discount',25,{category:'discount',effect:'deduction',basis:'per_line'});expect(assessCosts([line([a,b])])).toEqual(assessCosts([line([b,a])]))})
 it('preserves a valid range without making it exact',()=>{const result=assessCosts([line([component('tax',0,{category:'tax',basis:'per_line',knowledge:{kind:'range',minimum:money(10),maximum:money(20)}})],{quantity:1})]);expect(result).toMatchObject({completeness:'bounded',currencyTotals:[{knownLowerBound:money(10),upperBound:money(20),exactLandedTotal:undefined}]})})
 it.each([[money(20),money(10)],[money(10,'GBP'),money(20,'USD')]])('rejects invalid ranges', (minimum,maximum)=>expect(()=>costComponentSchema.parse(component('range',0,{knowledge:{kind:'range',minimum,maximum}}))).toThrow())
 it('distinguishes unknown applicability',()=>{const result=assessCosts([line([component('tax',10,{category:'tax',basis:'per_line',applicability:'unknown'})])]);expect(result.unknownApplicability).toHaveLength(1);expect(result.completeness).toBe('incomplete')})
 it('ignores explicit non-applicability',()=>expect(assessCosts([line([component('base',100,{basis:'per_line'}),component('tax',50,{category:'tax',basis:'per_line',applicability:'does_not_apply'})],{quantity:1})]).currencyTotals[0]?.exactLandedTotal).toEqual(money(100)))
 it('counts per-line cost once and per-unit cost by quantity',()=>expect(assessCosts([line([component('base',100),component('fee',50,{category:'mandatory_fee',basis:'per_line'})])]).currencyTotals[0]?.exactLandedTotal).toEqual(money(250)))
 it('counts identical per-order evidence once across merchant lines',()=>{const delivery=component('delivery',50,{category:'delivery',basis:'per_order',orderScope:'merchant-a'});expect(assessCosts([line([component('a',100),delivery],{id:'a',quantity:1}),line([component('b',100),delivery],{id:'b',quantity:1})]).currencyTotals[0]?.exactLandedTotal).toEqual(money(250))})
 it('rejects conflicting order-level evidence independent of line order',()=>{const a=line([component('delivery',50,{category:'delivery',basis:'per_order',orderScope:'merchant-a'})],{id:'a',quantity:1}),b=line([component('delivery',60,{category:'delivery',basis:'per_order',orderScope:'merchant-a'})],{id:'b',quantity:1});expect(assessCosts([a,b]).completeness).toBe('conflicting');expect(assessCosts([b,a]).conflicts).toEqual(assessCosts([a,b]).conflicts)})
 it('rejects order cost with unknown merchant grouping',()=>expect(()=>assessCosts([line([component('delivery',50,{category:'delivery',basis:'per_order'})])])).toThrow(/scope/))
 it('keeps recurring costs separate',()=>{const result=assessCosts([line([component('subscription',100,{category:'other',label:'Subscription',basis:'recurring',timing:'recurring'})])]);expect(result.recurring).toHaveLength(1);expect(result.currencyTotals).toHaveLength(0)})
 it('keeps usage costs unresolved',()=>expect(assessCosts([line([component('usage',10,{category:'other',label:'Usage',basis:'usage_unresolved',timing:'usage_based'})])]).unresolved).toHaveLength(1))
 it('fails a budget when the known lower bound is already over',()=>expect(assessCosts([line([component('base',600)])],money(1000)).budget?.status).toBe('failed'))
 it('satisfies only a complete exact landed budget',()=>expect(assessCosts([line([component('base',400),component('ship',100,{category:'delivery',basis:'per_line'})],{quantity:1})],money(500)).budget?.status).toBe('satisfied'))
 it('fails a complete landed total over budget',()=>expect(assessCosts([line([component('base',501)],{quantity:1})],money(500)).budget?.status).toBe('failed'))
 it('keeps budget unknown when additions are missing',()=>expect(assessCosts([line([component('base',100)],{quantity:1,coverage:{status:'partial',evidence:{strength:'unknown',source:'fixture'},reasons:['Additional costs unresolved']}})],money(500)).budget?.status).toBe('unknown'))
 it('keeps a mixed-currency budget unknown',()=>expect(assessCosts([line([component('gbp',100,{basis:'per_line'}),component('usd',100,{basis:'per_line',knowledge:{kind:'exact',amount:money(100,'USD')}})],{quantity:1})],money(500)).budget?.status).toBe('unknown'))
 it('refuses exact multiplication when unit semantics are unknown',()=>expect(assessCosts([line([component('base',100)],{unitSemantics:'unknown'})]).completeness).toBe('incomplete'))
 it.each(['product','material','service','software_subscription','licensed_creative_asset'])('accepts provider-neutral %s boundary input',kind=>expect(assessCosts([line([component(`${kind}-base`,100)],{id:kind,quantity:1})]).completeness).toBe('complete_exact'))
 it('contains no provider-specific field in canonical output',()=>expect(JSON.stringify(assessCosts([line([component('base',100)])]))).not.toMatch(/shopify/i))
})
