import {describe,expect,it} from 'vitest'
import {assessCosts} from './assess-cost'
import {costCoverageSchema,type CostComponent,type CostLineInput} from './domain/cost'
import type {MerchantOffer,ProductCluster} from '../commerce/domain/commerce'
import {createPurchaseGoal} from '../goals/domain/purchase-goal'
import {createPurchasePlan,revisePurchasePlan,type PlanLine} from '../planning/domain/purchase-plan'
import {evaluatePurchasePlan} from '../planning/evaluate-plan'

const money=(minorAmount:number)=>({minorAmount,currency:'GBP'}),explicit={strength:'source_explicit' as const,source:'fixture'},provider='shopify_global_catalog' as const,provenance={kind:'provider_explicit' as const,provider}
const coverage=(strength:'source_explicit'|'cosource_derived'|'source_inferred'|'unknown'='source_explicit')=>({status:'complete' as const,evidence:{strength,source:'fixture'}})
const component=(id:string,minorAmount:number,changes:Partial<CostComponent>={}):CostComponent=>({id,category:'base_price',effect:'addition',basis:'per_line',applicability:'applies',knowledge:{kind:'exact',amount:money(minorAmount)},timing:'one_time',evidence:explicit,...changes})
const line=(components:CostComponent[],changes:Partial<CostLineInput>={}):CostLineInput=>({id:'line',quantity:1,unitSemantics:'single_unit',components,coverage:coverage(),...changes})
const offer=(id:string,minorAmount=1000):MerchantOffer=>({identity:{provider,id},title:{value:id,provenance},price:money(minorAmount),oneTimeCostCoverage:coverage(),availability:{state:'available',basis:'catalog_signal',provenance},selectedOptions:[],media:[],correlations:[],provenance})
const product=(id:string,offers=[offer(`${id}-offer`)]):ProductCluster=>({identity:{provider,id},title:{value:id,provenance},offers,media:[],offerCompleteness:'provider_returned_unknown',provenance})
const planLine=(item:ProductCluster,changes:Partial<PlanLine>={}):PlanLine=>({id:`line-${item.identity.id}`,product:item.identity,productTitle:item.title.value,selectedOffer:item.offers[0]?.identity,offerSelection:'explicit_human',quantity:1,unitSemantics:'single_item',...changes})
const goal=createPurchaseGoal({id:'goal',summary:'buy',budget:money(5000),requirements:[],preferences:[],exclusions:[]}),plan=(lines:PlanLine[])=>revisePurchasePlan(createPurchasePlan('plan',goal.id,goal.revision),lines)

describe('R6R2 evidence-grade certainty defects',()=>{
 it.each(['unknown','source_inferred'] as const)('does not permit %s complete coverage to prove exact or satisfy budget',strength=>{const result=assessCosts([line([component('base',1000)],{coverage:coverage(strength)})],money(5000));expect(result.completeness).toBe('incomplete');expect(result.currencyTotals[0]?.exactLandedTotal).toBeUndefined();expect(result.budget?.status).toBe('unknown')})
 it('keeps an inferred exact addition out of a failing lower bound',()=>{const result=assessCosts([line([component('base',6000,{evidence:{strength:'source_inferred',source:'fixture'}})])],money(5000));expect(result.currencyTotals[0]?.knownLowerBound).toEqual(money(0));expect(result.budget?.status).toBe('unknown')})
 it.each(['source_inferred','unknown'] as const)('keeps a %s deduction from asserting a payable bound',strength=>{const result=assessCosts([line([component('base',6000),component('discount',500,{category:'discount',effect:'deduction',evidence:{strength,source:'fixture'}})])],money(5000));expect(result.currencyTotals[0]?.knownLowerBound).toEqual(money(0));expect(result.budget?.status).toBe('unknown')})
 it.each(['source_explicit','cosource_derived'] as const)('allows decision-grade %s exact evidence',strength=>{const result=assessCosts([line([component('base',1000,{evidence:{strength,source:'fixture'}})],{coverage:coverage(strength)})],money(5000));expect(result.completeness).toBe('complete_exact');expect(result.budget?.status).toBe('satisfied')})
 it.each(['per_order','per_plan'] as const)('selects identical %s claim metadata deterministically',basis=>{const weak=component('claim',0,{category:'discount',effect:'deduction',basis,orderScope:basis==='per_order'?'order':undefined,knowledge:{kind:'unknown',currency:'GBP'},evidence:{strength:'unknown',source:'source',observedAt:'2026-01-01T00:00:00Z'}}),strong={...weak,evidence:{...weak.evidence,strength:'source_explicit' as const,observedAt:'2026-01-02T00:00:00Z'}};const a=assessCosts([line([weak],{id:'a'}),line([strong],{id:'b'})]),b=assessCosts([line([strong],{id:'b'}),line([weak],{id:'a'})]);expect(a).toEqual(b);expect(a.unresolved[0]?.evidence.strength).toBe('source_explicit')})
 it('uses timestamp and a stable tie-breaker for equal-strength identical claims',()=>{const old=component('claim',0,{category:'discount',effect:'deduction',basis:'per_order',orderScope:'order',knowledge:{kind:'unknown',currency:'GBP'},evidence:{...explicit,observedAt:'2026-01-01T00:00:00Z'}}),recent={...old,evidence:{...old.evidence,observedAt:'2026-02-01T00:00:00Z'}};expect(assessCosts([line([old,recent])]).unresolved[0]?.evidence.observedAt).toBe('2026-02-01T00:00:00Z')})
 it('bounds one invalid adapted line without erasing another safe lower bound',()=>{const valid=product('valid',[offer('valid-offer',6000)]),invalidOffer={...offer('invalid-offer'),costComponents:[component('duplicate',100)]},invalid=product('invalid',[invalidOffer]);expect(()=>evaluatePurchasePlan(goal,plan([planLine(valid),planLine(invalid)]),[valid,invalid])).not.toThrow();const result=evaluatePurchasePlan(goal,plan([planLine(valid),planLine(invalid)]),[valid,invalid]);expect(result.costAssessment).toMatchObject({completeness:'incomplete',budget:{status:'failed'},currencyTotals:[{knownLowerBound:money(6000)}]})})
 it('requires meaningful partial coverage content',()=>{expect(()=>costCoverageSchema.parse({status:'partial',evidence:explicit})).toThrow();expect(()=>costCoverageSchema.parse({status:'partial',evidence:explicit,unresolvedCategories:[],reasons:[]})).toThrow()})
 it('deduplicates partial coverage categories and reasons',()=>{const result=assessCosts([line([],{coverage:{status:'partial',evidence:explicit,unresolvedCategories:['tax','tax'],reasons:['Verify tax','Verify tax']}})]);expect(result.missingCategories).toEqual(['tax']);expect(result.verificationReasons).toEqual(['Verify tax'])})
})
