import {describe,expect,it} from 'vitest'
import {assessCosts} from './assess-cost'
import type {CostComponent,CostLineInput} from './domain/cost'

const money=(minorAmount:number)=>({minorAmount,currency:'GBP'}),evidence={strength:'source_explicit' as const,source:'fixture'},coverage={status:'complete' as const,evidence}
const component=(id:string,minorAmount:number,changes:Partial<CostComponent>={}):CostComponent=>({id,category:'base_price',effect:'addition',basis:'per_line',applicability:'applies',knowledge:{kind:'exact',amount:money(minorAmount)},timing:'one_time',evidence,...changes})
const line=(id:string,components:CostComponent[],changes:Partial<CostLineInput>={}):CostLineInput=>({id,quantity:1,unitSemantics:'single_unit',components,coverage,...changes})

describe('R6R3 complete aggregation invariants',()=>{
 it('preserves safe evidence and bounds aggregate overflow',()=>{const safe=line('safe',[component('safe',6000)]),overflow=line('overflow',[component('huge',Number.MAX_SAFE_INTEGER)]);expect(()=>assessCosts([safe,overflow],money(5000))).not.toThrow();const result=assessCosts([safe,overflow],money(5000));expect(result.completeness).toBe('incomplete');expect(result.budget?.status).toBe('failed');expect(result.currencyTotals.some(x=>x.knownLowerBound.minorAmount===6000)).toBe(true);expect(result.currencyTotals.every(x=>x.exactLandedTotal===undefined)).toBe(true);expect(result.unresolved.some(x=>x.id==='huge')).toBe(true)})
 it('keeps overflow budget unknown without a proven lower-bound failure',()=>{const result=assessCosts([line('safe',[component('safe',100)]),line('overflow',[component('huge',Number.MAX_SAFE_INTEGER)])],money(5000));expect(result.budget?.status).toBe('unknown')})
 it('makes overflow output deeply invariant to line reversal',()=>{const a=line('a',[component('a',100)]),b=line('b',[component('b',Number.MAX_SAFE_INTEGER)]);expect(assessCosts([a,b])).toEqual(assessCosts([b,a]))})
 it('compares offset timestamps by represented instant',()=>{const earlier=component('claim',0,{category:'discount',effect:'deduction',basis:'per_order',orderScope:'order',knowledge:{kind:'unknown',currency:'GBP'},evidence:{...evidence,observedAt:'2026-01-01T12:00:00+02:00'}}),later={...earlier,evidence:{...earlier.evidence,observedAt:'2026-01-01T11:00:00Z'}};expect(assessCosts([line('a',[earlier,later])]).unresolved[0]?.evidence.observedAt).toBe('2026-01-01T11:00:00Z')})
 it('uses deterministic text tie-breaking for equal instants and missing timestamps',()=>{const a=component('claim',0,{category:'discount',effect:'deduction',basis:'per_order',orderScope:'order',knowledge:{kind:'unknown',currency:'GBP'},evidence:{...evidence,observedAt:'2026-01-01T10:00:00Z'}}),b={...a,evidence:{...a.evidence,observedAt:'2026-01-01T12:00:00+02:00'}};expect(assessCosts([line('a',[a,b])])).toEqual(assessCosts([line('a',[b,a])]));const missing={...a,evidence:{strength:a.evidence.strength,source:a.evidence.source}};expect(assessCosts([line('a',[a,missing])])).toEqual(assessCosts([line('a',[missing,a])]))})
 it('deduplicates identical per-line claims within one line',()=>{const fee=component('fee',50,{category:'mandatory_fee'});expect(assessCosts([line('a',[fee,fee])]).currencyTotals[0]?.exactLandedTotal).toEqual(money(50))})
 it('conflicts incompatible duplicate per-line claims',()=>{const a=component('fee',50,{category:'mandatory_fee'}),b=component('fee',60,{category:'mandatory_fee'});expect(assessCosts([line('a',[a,b])]).completeness).toBe('conflicting')})
 it('deduplicates per-unit before multiplying quantity',()=>{const unit=component('unit',50,{basis:'per_unit'});expect(assessCosts([line('a',[unit,unit],{quantity:3})]).currencyTotals[0]?.exactLandedTotal).toEqual(money(150))})
 it('keeps the same per-line claim on separate lines',()=>{const fee=component('fee',50,{category:'mandatory_fee'});expect(assessCosts([line('a',[fee]),line('b',[fee])]).currencyTotals[0]?.exactLandedTotal).toEqual(money(100))})
 it('rejects duplicate neutral cost-line identifiers',()=>expect(()=>assessCosts([line('a',[]),line('a',[])])).toThrow(/unique/i))
 it('preserves unknown applicability for recurring costs',()=>{const item=component('subscription',50,{category:'other',label:'Subscription',basis:'recurring',timing:'recurring',applicability:'unknown'}),result=assessCosts([line('a',[item])]);expect(result.recurring).toContainEqual(item);expect(result.unresolved).toContainEqual(item);expect(result.unknownApplicability).toContainEqual(item)})
 it('preserves unknown applicability for usage costs',()=>{const item=component('usage',50,{category:'other',label:'Usage',basis:'usage_unresolved',timing:'usage_based',applicability:'unknown'}),result=assessCosts([line('a',[item])]);expect(result.unresolved).toContainEqual(item);expect(result.unknownApplicability).toContainEqual(item)})
 it('continues to exclude explicit non-applicability',()=>{const item=component('subscription',50,{category:'other',label:'Subscription',basis:'recurring',timing:'recurring',applicability:'does_not_apply'}),result=assessCosts([line('a',[item])]);expect(result.recurring).toEqual([]);expect(result.unresolved).toEqual([])})
})
