import {describe,expect,it} from 'vitest'
import {assessCosts} from './assess-cost'
import type {CostComponent,CostLineInput} from './domain/cost'

const money=(minorAmount:number,currency='GBP')=>({minorAmount,currency})
const evidence={strength:'source_explicit' as const,source:'r6r4-fixture'}
const coverage={status:'complete' as const,evidence}
const component=(id:string,knowledge:CostComponent['knowledge'],changes:Partial<CostComponent>={}):CostComponent=>({id,category:'base_price',effect:'addition',basis:'per_line',applicability:'applies',knowledge,timing:'one_time',evidence,...changes})
const line=(id:string,components:CostComponent[]):CostLineInput=>({id,quantity:1,unitSemantics:'single_unit',components,coverage})

describe('R6R4 independent conservative cost-bound accumulation',()=>{
 it('preserves an exact base and addition minimum when only the ranged maximum overflows',()=>{const base=component('base',{kind:'exact',amount:money(100)}),delivery=component('delivery',{kind:'range',minimum:money(50),maximum:money(Number.MAX_SAFE_INTEGER)},{category:'delivery'}),forward=assessCosts([line('item',[base,delivery])],money(120)),reverse=assessCosts([line('item',[delivery,base])],money(120));expect(forward).toEqual(reverse);expect(forward).toMatchObject({completeness:'incomplete',budget:{status:'failed'}});expect(forward.currencyTotals).toEqual([{currency:'GBP',baseSubtotal:money(100),knownAdditions:money(50),knownDeductions:money(0),knownLowerBound:money(150),upperBound:undefined,exactLandedTotal:undefined}]);expect(forward.unresolved.filter(item=>item.id==='delivery')).toHaveLength(1)})
 it('does not claim a false lower bound when deduction maximum overflows',()=>{const base=component('base',{kind:'exact',amount:money(100)}),known=component('known-discount',{kind:'exact',amount:money(10)},{category:'discount',effect:'deduction'}),ranged=component('ranged-discount',{kind:'range',minimum:money(20),maximum:money(Number.MAX_SAFE_INTEGER)},{category:'discount',effect:'deduction'}),result=assessCosts([line('item',[base,known,ranged])],money(50));expect(result).toMatchObject({completeness:'incomplete',budget:{status:'unknown'},currencyTotals:[{baseSubtotal:money(100),knownDeductions:money(30),knownLowerBound:money(0),upperBound:money(70),exactLandedTotal:undefined}]});expect(result.unresolved.filter(item=>item.id==='ranged-discount')).toHaveLength(1)})
 it('isolates independent overflow state by currency',()=>{const gbpBase=component('gbp-base',{kind:'exact',amount:money(100)}),gbpDelivery=component('gbp-delivery',{kind:'range',minimum:money(50),maximum:money(Number.MAX_SAFE_INTEGER)},{category:'delivery'}),usdBase=component('usd-base',{kind:'exact',amount:money(200,'USD')}),result=assessCosts([line('gbp',[gbpBase,gbpDelivery]),line('usd',[usdBase])]);expect(result.currencyTotals).toEqual([{currency:'GBP',baseSubtotal:money(100),knownAdditions:money(50),knownDeductions:money(0),knownLowerBound:money(150),upperBound:undefined,exactLandedTotal:undefined},{currency:'USD',baseSubtotal:money(200,'USD'),knownAdditions:money(0,'USD'),knownDeductions:money(0,'USD'),knownLowerBound:money(200,'USD'),upperBound:money(200,'USD'),exactLandedTotal:undefined}])})
 it('cancels deductions before safely composing an overflowed positive lower projection',()=>{const base=component('base',{kind:'exact',amount:money(Number.MAX_SAFE_INTEGER-10)}),addition=component('addition',{kind:'exact',amount:money(20)},{category:'mandatory_fee'}),deduction=component('deduction',{kind:'exact',amount:money(100)},{category:'discount',effect:'deduction'}),budget=money(Number.MAX_SAFE_INTEGER-50),forward=assessCosts([line('item',[base,addition,deduction])],budget),reverse=assessCosts([line('item',[deduction,addition,base])],budget);expect(forward).toEqual(reverse);expect(forward).toMatchObject({completeness:'incomplete',budget:{status:'unknown'},currencyTotals:[{knownLowerBound:money(Number.MAX_SAFE_INTEGER-90),exactLandedTotal:undefined}]});expect(forward.unresolved.filter(item=>item.id==='addition')).toHaveLength(1)})
 it('does not derive a deduction conflict from a partial positive upper projection',()=>{const base=component('base',{kind:'exact',amount:money(0)}),a=component('a',{kind:'exact',amount:money(50)},{category:'mandatory_fee'}),b=component('b',{kind:'range',minimum:money(60),maximum:money(Number.MAX_SAFE_INTEGER)},{category:'delivery'}),deduction=component('deduction',{kind:'exact',amount:money(100)},{category:'discount',effect:'deduction'}),forward=assessCosts([line('item',[base,a,b,deduction])]),reverse=assessCosts([line('item',[deduction,b,a,base])]);expect(forward).toEqual(reverse);expect(forward).toMatchObject({completeness:'incomplete',conflicts:[],currencyTotals:[{knownAdditions:money(110),knownDeductions:money(100),knownLowerBound:money(10),upperBound:undefined,exactLandedTotal:undefined}]});expect(forward.unresolved.filter(item=>item.id==='b')).toHaveLength(1)})
})
