import {describe,expect,it} from 'vitest'
import type {ProductCluster} from '../../commerce/domain/commerce'
import type {ProductEvidenceEntry} from '../../evidence/product-evidence-ledger'
import type {PlanEvaluation,PurchasePlan} from '../../planning/domain/purchase-plan'
import {generateScenarios,SCENARIO_CANDIDATE_LIMIT,SCENARIO_COMBINATION_LIMIT,SCENARIO_RESULT_LIMIT,scenarioSummarySchema} from './scenario'

const provider='shopify_global_catalog' as const,provenance={kind:'provider_explicit' as const,provider}
function entry(id:string,prices:number[]=[1000],currency='GBP'):ProductEvidenceEntry{const product:ProductCluster={identity:{provider,id},title:{value:id,provenance},attributes:{value:[],provenance},media:[],offers:prices.map((price,index)=>({identity:{provider,id:`${id}-offer-${index}`},title:{value:'Offer',provenance},merchant:{identity:{provider,id:`merchant-${index}`},policyLinks:[],provenance},price:{minorAmount:price,currency},availability:{state:'available',basis:'catalog_signal',provenance},selectedOptions:[],media:[],correlations:[],provenance,oneTimeCostCoverage:{status:'complete',evidence:{strength:'source_explicit',source:'fixture'}}})),offerCompleteness:'featured_only',provenance};return{subject:product.identity,current:{id:`observation-${id}`,sequence:1,observedAt:'2026-09-11T12:00:00.000Z',origin:{kind:'commerce_provider',provider},provenanceStrength:'provider_explicit',product},history:[]}}
const plan:PurchasePlan={id:'plan',revision:3,goalId:'goal',goalRevision:2,lines:[]}
function evaluation(value:PurchasePlan):PlanEvaluation{const offer=value.lines[0]!.selectedOffer!,minorAmount=Number(offer.id.match(/offer-(\d+)$/)?.[1]??0)*100+1000,currency=offer.id.startsWith('usd-')?'USD':'GBP';return{status:'ready_on_known_evidence',stale:false,mandatoryFailures:0,exclusionViolations:0,mandatoryUnknowns:0,preferencesSatisfied:minorAmount===1000?1:0,preferencesUnknown:0,merchantCount:1,currencies:[currency],knownSubtotals:[{minorAmount,currency}],unresolvedCosts:[],readiness:'ready_on_current_evidence',readinessReasons:[],costAssessment:{completeness:'complete_exact',currencyTotals:[{currency,baseSubtotal:{minorAmount,currency},knownAdditions:{minorAmount:0,currency},knownDeductions:{minorAmount:0,currency},knownLowerBound:{minorAmount,currency},upperBound:{minorAmount,currency},exactLandedTotal:{minorAmount,currency}}],recurring:[],unresolved:[],unknownApplicability:[],missingCategories:[],conflicts:[],verificationReasons:[]}}}
const input=(evidence:ProductEvidenceEntry[])=>({workspaceId:'workspace',market:{country:'GB',currency:'GBP'},requirement:{id:'goal',revision:2,quantity:1},sourcePlan:plan,evidence,verificationIds:['verification:0'],suppliers:[],temporalState:'stable',evaluate:evaluation})

describe('canonical scenario engine',()=>{
 it('is deterministic and invariant to retained input order',()=>{const a=generateScenarios(input([entry('b'),entry('a')])),b=generateScenarios(input([entry('a'),entry('b')]));expect(a).toEqual(b);expect(a.scenarios.every(item=>item.basisFingerprint===a.basisFingerprint)).toBe(true)})
 it('strictly rejects extra scenario summary fields',()=>{const scenario=generateScenarios(input([entry('a')])).scenarios[0]!;expect(scenarioSummarySchema.safeParse({...scenario,plan:undefined,evaluation:undefined,issues:undefined,dominatedBy:undefined,unexpected:true}).success).toBe(false)})
 it('deduplicates exact selections and applies hard enumeration limits',()=>{const evidence=Array.from({length:SCENARIO_CANDIDATE_LIMIT+5},(_,index)=>entry(`candidate-${index}`,Array.from({length:6},(__,offer)=>1000+offer)));const result=generateScenarios(input(evidence));expect(result.consideredCandidates).toBe(SCENARIO_CANDIDATE_LIMIT);expect(result.evaluatedCombinations).toBe(SCENARIO_COMBINATION_LIMIT);expect(result.scenarios.length).toBeLessThanOrEqual(SCENARIO_RESULT_LIMIT);expect(result.enumerationTruncated).toBe(true);expect(new Set(result.scenarios.map(item=>JSON.stringify(item.selections))).size).toBe(result.scenarios.length)})
 it('does not manufacture a lowest-cost leader across currencies',()=>{const result=generateScenarios(input([entry('gbp',[1000],'GBP'),entry('usd',[900],'USD')]));expect(result.scenarios.every(item=>!item.objectives.includes('lowest_supported_landed_cost'))).toBe(true)})
 it('marks Pareto dominance without a weighted score',()=>{const result=generateScenarios(input([entry('candidate',[1000,1100])]));const lower=result.scenarios.find(item=>item.selections[0]?.offer?.id.endsWith('-0'))!,higher=result.scenarios.find(item=>item.selections[0]?.offer?.id.endsWith('-1'))!;expect(lower.objectives).toContain('lowest_supported_landed_cost');expect(higher.dominatedBy).toContain(lower.id);expect(JSON.stringify(result)).not.toMatch(/score|weight/i)})
 it('keeps conditional and blocked alternatives truthful and never lets failure win on price',()=>{const evidence=[entry('ready'),entry('conditional'),entry('blocked',[1])],custom={...input(evidence),evaluate:(value:PurchasePlan)=>{const base=evaluation(value),id=value.lines[0]!.product.id;if(id==='blocked')return{...base,mandatoryFailures:1,status:'has_known_conflicts' as const,readiness:'blocked_by_known_failure' as const,readinessReasons:['Mandatory requirement failed.']};if(id==='conditional')return{...base,status:'incomplete' as const,readiness:'insufficient_evidence' as const,readinessReasons:['Delivery evidence is unsupported.'],costAssessment:{...base.costAssessment!,completeness:'incomplete' as const,verificationReasons:['Delivery cost is unknown.']}};return base}},result=generateScenarios(custom),blocked=result.scenarios.find(item=>item.selections[0]?.product.id==='blocked')!,conditional=result.scenarios.find(item=>item.selections[0]?.product.id==='conditional')!;expect(blocked.status).toBe('blocked');expect(blocked.objectives).not.toContain('lowest_supported_landed_cost');expect(blocked.safeNextAction).toBe('resolve_blockers');expect(conditional.status).toBe('conditional_verification_required');expect(conditional.safeNextAction).toBe('verify_evidence')})
 it('keeps IDs stable within a temporal state and changes the basis across a material boundary',()=>{const before=generateScenarios({...input([entry('a')]),temporalState:'verification:v1:before_or_at'}),repeat=generateScenarios({...input([entry('a')]),temporalState:'verification:v1:before_or_at'}),after=generateScenarios({...input([entry('a')]),temporalState:'verification:v1:after'});expect(repeat).toEqual(before);expect(after.basisFingerprint).not.toBe(before.basisFingerprint);expect(after.scenarios[0]!.id).not.toBe(before.scenarios[0]!.id)})
})
