import {describe,expect,it} from 'vitest'
import {applicableVerification,evidenceIssueId,humanVerificationSchema,orderEvidenceIssues,resolveEvidenceIssues,type EvidenceIssue,type HumanVerification} from './evidence-resolution'

const subject={kind:'candidate' as const,source:'source',id:'candidate'}
const base={workspaceId:'workspace',requirement:{id:'goal',revision:2},subject,field:'condition:size',kind:'missing' as const}
const issue=(importance:'mandatory'|'preference'|'informational'='mandatory'):EvidenceIssue=>({...base,id:evidenceIssueId(base),importance,evidence:{state:'missing'},claimReferences:[],reason:'Size is missing.',routes:['record_missing_fact'],blocksReadiness:importance==='mandatory',resolved:false})
const verification=(changes:Partial<HumanVerification>={}):HumanVerification=>({id:'verification',revision:0,workspaceId:'workspace',requirementId:'goal',requirementRevision:2,issueId:issue().id,issueBinding:{kind:'missing'},subject,field:'condition:size',outcome:'recorded',value:'large',note:'Checked the labelled specification.',verifiedAt:'2026-09-11T12:00:00.000Z',...changes})

describe('canonical evidence resolution',()=>{
 it('creates deterministic issue identities and mandatory-first order independent of input order',()=>{expect(evidenceIssueId(base)).toBe(evidenceIssueId({field:base.field,subject,kind:'missing',requirement:base.requirement,workspaceId:base.workspaceId}));const mandatory=issue(),preference={...issue('preference'),id:'preference'};expect(orderEvidenceIssues([preference,mandatory])).toEqual(orderEvidenceIssues([mandatory,preference]))})
 it('keeps preference issues non-blocking',()=>expect(issue('preference')).toMatchObject({importance:'preference',blocksReadiness:false}))
 it('uses inclusive validity boundaries and rejects future or expired verification',()=>{const item=issue(),record=verification({validUntil:'2026-09-12T00:00:00.000Z'});expect(applicableVerification(item,[record],'2026-09-11T12:00:00.000Z')).toBe(record);expect(applicableVerification(item,[record],'2026-09-12T00:00:00.000Z')).toBe(record);expect(applicableVerification(item,[record],'2026-09-12T00:00:00.001Z')).toBeUndefined();expect(applicableVerification(item,[verification({verifiedAt:'2026-09-13T00:00:00.000Z'})],'2026-09-12T00:00:00.000Z')).toBeUndefined()})
 it('requires exact workspace, requirement revision, subject, field, and issue bindings',()=>{const item=issue();for(const record of [verification({workspaceId:'other'}),verification({requirementRevision:1}),verification({issueId:'other'}),verification({field:'other'}),verification({subject:{...subject,id:'other'}})])expect(applicableVerification(item,[record],'2026-09-12T00:00:00.000Z')).toBeUndefined()})
 it('resolves only recorded facts or confirmations of retained exact claims',()=>{const item=issue();expect(resolveEvidenceIssues([item],[verification()],'2026-09-12T00:00:00.000Z')[0]).toMatchObject({resolved:true,blocksReadiness:false});expect(resolveEvidenceIssues([{...item,claimReferences:['claim']}],[verification({outcome:'confirmed',claimReference:'other'})],'2026-09-12T00:00:00.000Z')[0]).toMatchObject({resolved:false,blocksReadiness:true});expect(resolveEvidenceIssues([item],[verification({outcome:'rejected'})],'2026-09-12T00:00:00.000Z')[0]).toMatchObject({resolved:false})})
 it('strictly bounds verification records and chronology',()=>{expect(humanVerificationSchema.safeParse(verification()).success).toBe(true);expect(humanVerificationSchema.safeParse({...verification(),extra:true}).success).toBe(false);expect(humanVerificationSchema.safeParse(verification({validUntil:'2026-09-10T00:00:00.000Z'})).success).toBe(false);expect(humanVerificationSchema.safeParse(verification({outcome:'confirmed',claimReference:undefined})).success).toBe(false)})
})
