import {z} from 'zod'
import type {EvidenceStrength} from './evidence'

export const evidenceIssueKindSchema=z.enum(['missing','stale','conflicting','verification_required','unresolved_cost','unavailable'])
export const evidenceImportanceSchema=z.enum(['mandatory','preference','informational'])
export const evidenceResolutionRouteSchema=z.enum(['refresh_evidence','review_history','confirm_claim','reject_claim','record_missing_fact','review_supplier_evidence','return_to_goal','return_to_comparison','return_to_plan'])
export const evidenceSubjectSchema=z.discriminatedUnion('kind',[
 z.object({kind:z.literal('resource_requirement'),id:z.string().min(1).max(100)}).strict(),
 z.object({kind:z.literal('candidate'),source:z.string().min(1).max(100),id:z.string().min(1).max(500)}).strict(),
 z.object({kind:z.literal('offer'),source:z.string().min(1).max(100),id:z.string().min(1).max(500)}).strict(),
 z.object({kind:z.literal('plan_line'),id:z.string().min(1).max(100)}).strict(),
 z.object({kind:z.literal('supplier'),id:z.string().min(1).max(100)}).strict(),
 z.object({kind:z.enum(['supplier_quotation','supplier_reliability','supplier_risk']),supplierId:z.string().min(1).max(100),id:z.string().min(1).max(100)}).strict(),
])
export type EvidenceSubject=z.infer<typeof evidenceSubjectSchema>&{source?:string}
export type EvidenceIssueKind=z.infer<typeof evidenceIssueKindSchema>
export type EvidenceImportance=z.infer<typeof evidenceImportanceSchema>
export type EvidenceResolutionRoute=z.infer<typeof evidenceResolutionRouteSchema>
export interface EvidenceIssue{id:string;workspaceId:string;requirement?:{id:string;revision:number};subject:EvidenceSubject;field:string;kind:EvidenceIssueKind;importance:EvidenceImportance;observation?:{id:string;sequence:number;observedAt:string};evidence:{strength?:EvidenceStrength;state:'missing'|'stale'|'conflicting'|'verification_required'|'unavailable';observedAt?:string;value?:string};claimReferences:string[];reason:string;routes:EvidenceResolutionRoute[];blocksReadiness:boolean;resolved:boolean}
export const claimBindingSchema=z.object({conditionId:z.string().min(1).max(100),observationId:z.string().min(1).max(100),observationSequence:z.number().int().safe().min(1),observedAt:z.iso.datetime({offset:true}),field:z.string().min(1).max(100),value:z.string().max(2000),provenance:z.enum(['provider_explicit','provider_inferred','cosource_derived','unknown'])}).strict()
const conditionSnapshotSchema=z.object({id:z.string().min(1).max(100),operator:z.enum(['free_text','equals','is_true','is_false','at_most','at_least']),field:z.string().max(100).optional(),value:z.string().max(500).optional()}).strict()
const claimSnapshotSchema=z.object({id:z.string().min(1).max(500),field:z.string().min(1).max(100),value:z.string().max(2000),provenance:z.enum(['provider_explicit','provider_inferred','cosource_derived','unknown'])}).strict()
export const issueBindingSchema=z.object({kind:evidenceIssueKindSchema,conditionKind:z.enum(['requirement','preference','exclusion']).optional(),condition:conditionSnapshotSchema.optional(),claims:z.array(claimSnapshotSchema).max(100).optional(),offer:z.object({provider:z.string().min(1).max(100),id:z.string().min(1).max(500)}).strict().optional(),observation:z.object({id:z.string().min(1).max(100),sequence:z.number().int().safe().min(1),observedAt:z.iso.datetime({offset:true})}).strict().optional()}).strict()
export const humanVerificationSchema=z.object({id:z.string().min(1).max(100),revision:z.number().int().safe().min(0),workspaceId:z.string().min(1).max(100),requirementId:z.string().min(1).max(100),requirementRevision:z.number().int().safe().min(0),issueId:z.string().min(1).max(200),issueBinding:issueBindingSchema,subject:evidenceSubjectSchema,field:z.string().min(1).max(200),outcome:z.enum(['confirmed','rejected','recorded','requires_verification']),claimReference:z.string().min(1).max(500).optional(),claimBinding:claimBindingSchema.optional(),value:z.string().max(500).optional(),note:z.string().min(1).max(1000),verifiedAt:z.iso.datetime({offset:true}),validUntil:z.iso.datetime({offset:true}).optional()}).strict().superRefine((value,ctx)=>{if(value.validUntil&&Date.parse(value.validUntil)<Date.parse(value.verifiedAt))ctx.addIssue({code:'custom',message:'Verification validity cannot precede verification'});if((value.outcome==='confirmed'||value.outcome==='rejected')&&(!value.claimReference||!value.claimBinding))ctx.addIssue({code:'custom',message:'Claim verification requires an exact observation and claim binding'});if((value.outcome==='recorded'||value.outcome==='requires_verification')&&(value.claimReference||value.claimBinding))ctx.addIssue({code:'custom',message:'Only claim decisions may carry claim authority'});if(value.outcome==='recorded'&&!value.value)ctx.addIssue({code:'custom',message:'A recorded fact requires a value'})})
export type HumanVerification=z.infer<typeof humanVerificationSchema>
export const humanVerificationCommandSchema=z.object({issueId:z.string().min(1).max(200),outcome:z.enum(['confirmed','rejected','recorded','requires_verification']),claimReference:z.string().min(1).max(500).optional(),value:z.string().min(1).max(500).optional(),note:z.string().min(1).max(1000),validUntil:z.iso.datetime({offset:true}).optional()}).strict()
export type HumanVerificationCommand=z.infer<typeof humanVerificationCommandSchema>

const stable=(value:unknown):string=>value&&typeof value==='object'?Array.isArray(value)?`[${value.map(stable).join(',')}]`:`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${stable(item)}`).join(',')}}`:JSON.stringify(value)
function hash(value:string){let result=2166136261;for(let index=0;index<value.length;index++){result^=value.charCodeAt(index);result=Math.imul(result,16777619)}return(result>>>0).toString(36)}
export function evidenceIssueId(input:{workspaceId:string;requirement?:{id:string;revision:number};subject:EvidenceSubject;field:string;kind:EvidenceIssueKind;observation?:{id:string;sequence:number;observedAt:string}}){return`issue-${hash(stable(input))}`}
export function orderEvidenceIssues(issues:EvidenceIssue[]){const importance={mandatory:0,preference:1,informational:2};return[...issues].sort((a,b)=>importance[a.importance]-importance[b.importance]||a.id.localeCompare(b.id))}
export function applicableVerification(issue:EvidenceIssue,records:HumanVerification[],now:string){const current=Date.parse(now);return[...records].filter(record=>record.workspaceId===issue.workspaceId&&record.requirementId===issue.requirement?.id&&record.requirementRevision===issue.requirement?.revision&&record.issueId===issue.id&&stable(record.subject)===stable(issue.subject)&&record.field===issue.field&&record.issueBinding.kind===issue.kind&&stable(record.issueBinding.observation)===stable(issue.observation)&&Date.parse(record.verifiedAt)<=current&&(!record.validUntil||current<=Date.parse(record.validUntil))).sort((a,b)=>Date.parse(b.verifiedAt)-Date.parse(a.verifiedAt)||a.id.localeCompare(b.id))[0]}
export function resolveEvidenceIssues(issues:EvidenceIssue[],records:HumanVerification[],now:string){return orderEvidenceIssues(issues.map(issue=>{const record=applicableVerification(issue,records,now),resolved=issue.resolved||Boolean(record&&(record.outcome==='recorded'||record.outcome==='confirmed'&&record.claimReference&&issue.claimReferences.includes(record.claimReference)));return{...issue,resolved,blocksReadiness:issue.blocksReadiness&&!resolved}}))}
