import {describe,expect,it,vi} from 'vitest'
import {createCoSourceApplication} from '../application/cosource-application'
import type {ProductCluster} from '../commerce/domain/commerce'
import type {PlanEvaluation,PurchasePlan} from '../planning/domain/purchase-plan'
import {generateScenarios,scenarioCommandSchema} from './domain/scenario'
import type {ProductEvidenceEntry} from '../evidence/product-evidence-ledger'

const provider='shopify_global_catalog' as const,explicit={kind:'provider_explicit' as const,provider}
function product(id:string,availability:'available'|'unavailable'|'unknown'='available',availabilityKind:'provider_explicit'|'provider_inferred'|'unknown'='provider_explicit',offers=1,merchant=true):ProductCluster{return{identity:{provider,id},title:{value:id,provenance:explicit},attributes:{value:[{name:'Size',value:'large'}],provenance:explicit},media:[],offers:Array.from({length:offers},(_,index)=>({identity:{provider,id:`${id}-offer-${index}`},title:{value:`Offer ${index}`,provenance:explicit},merchant:merchant?{identity:{provider,id:`${id}-merchant-${index}`},policyLinks:[],provenance:explicit}:undefined,price:{minorAmount:1000+index*100,currency:'GBP'},oneTimeCostCoverage:{status:'complete',evidence:{strength:'source_explicit',source:'fixture'}},availability:{state:availability,basis:'catalog_signal',provenance:{kind:availabilityKind,provider:availabilityKind==='unknown'?undefined:provider}},selectedOptions:[],media:[],correlations:[],provenance:explicit})),offerCompleteness:'featured_only',provenance:explicit}}
async function app(products:ProductCluster[],quantity?:number){let id=0;const search=vi.fn(async()=>({products,messages:[],pagination:{hasMore:false}})),application=createCoSourceApplication({market:{country:'GB',currency:'GBP'},makeId:()=>`owned-${++id}`,now:()=> '2026-09-11T12:00:00.000Z',catalog:{search,product:vi.fn(async input=>({product:products.find(item=>item.identity.id===input.identity.id)!,selectedOptions:[],messages:[]}))}});application.editGoal({summary:'Products',searchFocus:'products',quantity});application.addGoalCondition('requirement');const condition=application.getSnapshot().goalDraft.requirements[0]!;application.editGoalCondition('requirement',condition.id,{operator:'equals',field:'Size',value:'large'});application.commitGoalDraft();await application.searchCandidates({query:'products'});for(const item of products)application.retainCandidate(item.identity);return{application,search}}
const entry=(item:ProductCluster,index:number):ProductEvidenceEntry=>({subject:item.identity,current:{id:`observation-${index}`,sequence:1,observedAt:'2026-09-11T12:00:00.000Z',origin:{kind:'commerce_provider',provider},provenanceStrength:'provider_explicit',product:item},history:[]})
const ready=(plan:PurchasePlan):PlanEvaluation=>{const amount=Number(plan.lines[0]!.product.id.replace('candidate-',''))||10;return{status:'ready_on_known_evidence',stale:false,mandatoryFailures:0,exclusionViolations:0,mandatoryUnknowns:0,preferencesSatisfied:0,preferencesUnknown:0,merchantCount:1,currencies:['GBP'],knownSubtotals:[{minorAmount:amount,currency:'GBP'}],unresolvedCosts:[],readiness:'ready_on_current_evidence',readinessReasons:[],costAssessment:{completeness:'complete_exact',currencyTotals:[{currency:'GBP',baseSubtotal:{minorAmount:amount,currency:'GBP'},knownAdditions:{minorAmount:0,currency:'GBP'},knownDeductions:{minorAmount:0,currency:'GBP'},knownLowerBound:{minorAmount:amount,currency:'GBP'},upperBound:{minorAmount:amount,currency:'GBP'},exactLandedTotal:{minorAmount:amount,currency:'GBP'}}],recurring:[],unresolved:[],unknownApplicability:[],missingCategories:[],conflicts:[],verificationReasons:[]}}}

describe('R9R truthful whole-plan scenarios',()=>{
 it('does not invent missing quantity or permit its application',async()=>{const{application}=await app([product('candidate')]),set=application.getScenarios();expect(set.ok).toBe(true);if(!set.ok)return;const scenario=set.value.scenarios[0]!;expect(scenario.selections[0]!.quantity).toBeUndefined();expect(scenario.status).toBe('conditional_verification_required');expect(scenario.reasons.join(' ')).toMatch(/quantity.*unresolved/i);expect(application.applyScenario({scenarioId:scenario.id,basisFingerprint:set.value.basisFingerprint})).toMatchObject({ok:false,code:'invalid_state'})})
 it.each([['unavailable','provider_explicit','blocked'],['unknown','provider_explicit','conditional_verification_required'],['available','provider_inferred','conditional_verification_required']] as const)('makes %s/%s availability %s',async(state,kind,status)=>{const{application}=await app([product('candidate',state,kind)],1),set=application.getScenarios();if(!set.ok)return;expect(set.value.scenarios[0]).toMatchObject({status});expect(set.value.scenarios[0]!.status==='ready_on_current_evidence'&&set.value.scenarios[0]!.blockingIssueIds.length>0).toBe(false)})
 it('keeps unknown merchant identity conditional and awards no merchant-count objective',async()=>{const{application}=await app([product('candidate','available','provider_explicit',1,false)],1),set=application.getScenarios();if(!set.ok)return;expect(set.value.scenarios[0]).toMatchObject({status:'conditional_verification_required',merchantIdentityComplete:false});expect(set.value.scenarios[0]!.objectives).not.toContain('fewest_merchants')})
 it('selects the cheapest full-set leader before slicing and leaves no dangling dominance IDs',()=>{const products=Array.from({length:7},(_,index)=>product(`candidate-${index+1}`)),evidence=products.map(entry),sourcePlan={id:'plan',revision:0,goalId:'goal',goalRevision:1,lines:[]},set=generateScenarios({workspaceId:'workspace',market:{country:'GB',currency:'GBP'},requirement:{id:'goal',revision:1,quantity:1},sourcePlan,evidence,verificationIds:[],suppliers:[],temporalState:'stable',evaluate:ready});expect(set.resultLimited).toBe(true);expect(set.enumerationTruncated).toBe(false);expect(set.scenarios.some(item=>item.selections[0]!.product.id==='candidate-1'&&item.objectives.includes('lowest_supported_landed_cost'))).toBe(true);expect(set.scenarios.filter(item=>item.objectives.includes('lowest_supported_landed_cost'))).toHaveLength(1);const ids=new Set(set.scenarios.map(item=>item.id));expect(set.scenarios.flatMap(item=>item.dominatedBy).every(id=>ids.has(id))).toBe(true)})
 it('preserves a two-line plan and existing line authority while enumerating offers',async()=>{const products=[product('a','available','provider_explicit',2),product('b','available','provider_explicit',2)],{application,search}=await app(products,1);application.addCandidateToPlan(products[0]!.identity);application.addCandidateToPlan(products[1]!.identity);const before=application.getSnapshot(),set=application.getScenarios();if(!set.ok)return;expect(set.value.evaluatedCombinations).toBe(4);expect(set.value.scenarios.every(item=>item.plan.lines.length===2)).toBe(true);expect(set.value.scenarios.every(item=>item.plan.lines.map(line=>line.id).join()===before.plan.lines.map(line=>line.id).join())).toBe(true);const chosen=set.value.scenarios.find(item=>item.status==='ready_on_current_evidence');if(!chosen)throw new Error(JSON.stringify(set.value.scenarios.map(item=>({status:item.status,reasons:item.reasons}))));const notify=vi.fn();application.subscribe(notify);const applied=application.applyScenario({scenarioId:chosen.id,basisFingerprint:set.value.basisFingerprint});expect(applied).toMatchObject({ok:true,value:{revision:before.plan.revision+1,lines:[{id:before.plan.lines[0]!.id},{id:before.plan.lines[1]!.id}]}});expect(notify).toHaveBeenCalledTimes(1);expect(search).toHaveBeenCalledTimes(1)})
 it('evaluates conditions and issues against each exact selected offer',async()=>{const item=product('sized','available','provider_explicit',2);item.attributes=undefined;item.offers[0]!.selectedOptions=[{name:'Size',value:'large'}];item.offers[1]!.selectedOptions=[{name:'Size',value:'small'}];const{application}=await app([item],1),set=application.getScenarios();if(!set.ok)return;const large=set.value.scenarios.find(value=>value.selections[0]!.offer.id.endsWith('-0'))!,small=set.value.scenarios.find(value=>value.selections[0]!.offer.id.endsWith('-1'))!;expect(large).toMatchObject({status:'ready_on_current_evidence',blockingIssueIds:[],verificationIssueIds:[]});expect(small.status).toBe('blocked');expect(small.blockingIssueIds.length).toBeGreaterThan(0);expect(small.reasons.join(' ')).toMatch(/mandatory|fail/i);expect(small.blockingIssueIds).not.toEqual(large.blockingIssueIds)})
 it('strictly validates the scenario command',()=>{expect(scenarioCommandSchema.safeParse({scenarioId:'scenario',basisFingerprint:'basis'}).success).toBe(true);expect(scenarioCommandSchema.safeParse({scenarioId:'scenario',basisFingerprint:'basis',extra:true}).success).toBe(false);expect(scenarioCommandSchema.safeParse({scenarioId:'scenario'}).success).toBe(false)})
})
