import {describe,expect,it,vi} from 'vitest'
import {createCoSourceApplication} from '../application/cosource-application'
import type {ProductCluster} from '../commerce/domain/commerce'
import type {ProductEvidenceEntry} from '../evidence/product-evidence-ledger'
import type {PlanEvaluation,PlanLine,PurchasePlan} from '../planning/domain/purchase-plan'
import type {SupplierAssessment,SupplierRisk} from '../suppliers/domain/supplier-intelligence'
import {generateScenarios,SCENARIO_CANDIDATE_LIMIT,SCENARIO_COMBINATION_LIMIT,SCENARIO_RESULT_LIMIT} from './domain/scenario'

const provider='shopify_global_catalog' as const,provenance={kind:'provider_explicit' as const,provider}
function product(id:string,offers=1):ProductCluster{return{identity:{provider,id},title:{value:id,provenance},attributes:{value:[{name:'Size',value:'large'}],provenance},media:[],offers:Array.from({length:offers},(_,index)=>({identity:{provider,id:`${id}-offer-${index}`},title:{value:'Offer',provenance},merchant:{identity:{provider,id:`merchant-${id}-${index}`},policyLinks:[],provenance},price:{minorAmount:1000+index,currency:'GBP'},oneTimeCostCoverage:{status:'complete',evidence:{strength:'source_explicit',source:'fixture'}},availability:{state:'available',basis:'catalog_signal',provenance},selectedOptions:[],media:[],correlations:[],provenance})),offerCompleteness:'featured_only',provenance}}
const entry=(item:ProductCluster,index:number):ProductEvidenceEntry=>({subject:item.identity,current:{id:`observation-${index}`,sequence:1,observedAt:'2026-09-11T12:00:00.000Z',origin:{kind:'commerce_provider',provider},provenanceStrength:'provider_explicit',product:item},history:[]})
const baseEvaluation=(plan:PurchasePlan):PlanEvaluation=>({status:'ready_on_known_evidence',stale:false,mandatoryFailures:0,exclusionViolations:0,mandatoryUnknowns:0,preferencesSatisfied:0,preferencesUnknown:0,merchantCount:plan.lines.length,currencies:['GBP'],knownSubtotals:[{minorAmount:1000,currency:'GBP'}],unresolvedCosts:[],readiness:'ready_on_current_evidence',readinessReasons:[],costAssessment:{completeness:'complete_exact',currencyTotals:[{currency:'GBP',baseSubtotal:{minorAmount:1000,currency:'GBP'},knownAdditions:{minorAmount:0,currency:'GBP'},knownDeductions:{minorAmount:0,currency:'GBP'},knownLowerBound:{minorAmount:1000,currency:'GBP'},upperBound:{minorAmount:1000,currency:'GBP'},exactLandedTotal:{minorAmount:1000,currency:'GBP'}}],recurring:[],unresolved:[],unknownApplicability:[],missingCategories:[],conflicts:[],verificationReasons:[]}})
const input=(evidence:ProductEvidenceEntry[],lines:PlanLine[]=[])=>({workspaceId:'workspace',market:{country:'GB',currency:'GBP'},requirement:{id:'goal',revision:1,quantity:1},sourcePlan:{id:'plan',revision:1,goalId:'goal',goalRevision:1,lines},evidence,verificationIds:[],suppliers:[],temporalState:'stable',evaluate:baseEvaluation})
const line=(item:ProductCluster,index:number):PlanLine=>({id:`human-line-${index}`,product:item.identity,productTitle:item.title.value,selectedOffer:item.offers[0]!.identity,offerSelection:'explicit_human',quantity:index+1,unitSemantics:'single_item'})
function assessment(id:string,risks:SupplierRisk[],standing:'preferred'|'allowed'='allowed'):SupplierAssessment{return{supplierId:id,name:id,standing,freshness:'current',quotationState:'current_complete',reliability:'positive',readiness:'ready_on_current_evidence',reasons:[],activeRisks:risks.map(item=>({...item,reviewOverdue:false}))}}
const risk=(id:string,severity:SupplierRisk['severity'],strength:'source_explicit'|'source_inferred'='source_explicit'):SupplierRisk=>({id,supplierId:'supplier',category:'quality',severity,status:'active',observedAt:'2026-09-01T00:00:00.000Z',reason:id,evidence:{strength,source:'fixture'}})

describe('R9R2 complete temporal and existing-plan binding',()=>{
 it('resolves an existing product outside the first 25 and supports the canonical 50-line plan',()=>{const products=Array.from({length:50},(_,index)=>product(`candidate-${String(index).padStart(2,'0')}`)),evidence=products.map(entry),outside=generateScenarios(input(evidence,[line(products[25]!,25)]));expect(outside.scenarios).toHaveLength(1);expect(outside.consideredCandidates).toBe(1);expect(outside.scenarios[0]!.selections[0]!.product.id).toBe(products[25]!.identity.id);const maximum=generateScenarios(input(evidence,products.map(line)));expect(maximum.scenarios).toHaveLength(1);expect(maximum.scenarios[0]!.selections).toHaveLength(50);expect(maximum.scenarios[0]!.plan.lines).toEqual(products.map(line));expect(maximum.consideredCandidates).toBe(50)})
 it('keeps empty-plan sampling at 25 and bounds existing combinations and results separately',()=>{const products=Array.from({length:30},(_,index)=>product(`candidate-${index}`)),empty=generateScenarios(input(products.map(entry)));expect(empty.consideredCandidates).toBe(SCENARIO_CANDIDATE_LIMIT);expect(empty.enumerationTruncated).toBe(true);const two=[product('a',11),product('b',11)],existing=generateScenarios(input(two.map(entry),two.map(line)));expect(existing.evaluatedCombinations).toBe(SCENARIO_COMBINATION_LIMIT);expect(existing.enumerationTruncated).toBe(true);expect(existing.scenarios.length).toBeLessThanOrEqual(SCENARIO_RESULT_LIMIT);expect(existing.resultLimited).toBe(true)})
 it('returns a bounded empty result instead of throwing when existing-plan evidence is missing',()=>{const missing=line(product('missing'),0);expect(()=>generateScenarios(input([], [missing]))).not.toThrow();expect(generateScenarios(input([], [missing])).scenarios).toEqual([])})
 it('uses qualitative risk dominance without treating standing or missing records as risk',()=>{const products=[product('a'),product('b')],evidence=products.map(entry),evaluated=(profiles:Record<string,SupplierAssessment>)=>generateScenarios({...input(evidence),evaluate:plan=>({...baseEvaluation(plan),supplierAssessments:[profiles[plan.lines[0]!.product.id]!]})});const identical=evaluated({a:assessment('a',[risk('same-a','low')],'preferred'),b:assessment('b',[risk('same-b','low')],'allowed')});expect(identical.scenarios.every(item=>!item.objectives.includes('lowest_supported_supplier_risk'))).toBe(true);const missing=evaluated({a:assessment('a',[]),b:assessment('b',[risk('high','high')])});expect(missing.scenarios.every(item=>!item.objectives.includes('lowest_supported_supplier_risk'))).toBe(true);const dominated=evaluated({a:assessment('a',[risk('low','low')]),b:assessment('b',[risk('high','high')])});expect(dominated.scenarios.find(item=>item.selections[0]!.product.id==='a')!.objectives).toContain('lowest_supported_supplier_risk');const tradeoff=evaluated({a:assessment('a',[risk('high','high')]),b:assessment('b',[risk('m1','medium'),risk('m2','medium')])});expect(tradeoff.scenarios.every(item=>!item.objectives.includes('lowest_supported_supplier_risk'))).toBe(true);const incomplete=evaluated({a:assessment('a',[risk('weak','low','source_inferred')]),b:assessment('b',[])});expect(incomplete.scenarios.every(item=>!item.objectives.includes('lowest_supported_supplier_risk'))).toBe(true)})
 it('changes basis at inclusive quotation start and rejects the old command without provider calls',async()=>{let at='2026-09-11T11:59:59.000Z',ids=0;const item=product('candidate'),search=vi.fn(async()=>({products:[item],messages:[],pagination:{hasMore:false}})),application=createCoSourceApplication({market:{country:'GB',currency:'GBP'},makeId:()=>`id-${++ids}`,now:()=>at,catalog:{search,product:vi.fn(async()=>({product:item,selectedOptions:[],messages:[]}))}});application.editGoal({summary:'Sized',searchFocus:'sized',quantity:1});application.addGoalCondition('requirement');const condition=application.getSnapshot().goalDraft.requirements[0]!;application.editGoalCondition('requirement',condition.id,{operator:'equals',field:'Size',value:'large'});application.commitGoalDraft();await application.searchCandidates({query:'sized'});application.retainCandidate(item.identity);const retained=application.retainSupplier(item.identity,item.offers[0]!.identity);if(!retained.ok)return;application.recordSupplierQuotation(retained.value.id,{subject:{kind:'offer',source:provider,externalId:item.offers[0]!.identity.id},validFrom:'2026-09-11T12:00:00.000Z',components:[],coverage:{status:'complete',evidence:{strength:'source_explicit',source:'fixture'}},evidence:{strength:'source_explicit',source:'fixture'}});application.recordSupplierReliability(retained.value.id,{category:'delivery_outcome',outcome:'positive',summary:'On time',evidence:{strength:'source_explicit',source:'fixture'}});const before=application.getScenarios();if(!before.ok)return;expect(before.value.scenarios[0]!.status).toBe('conditional_verification_required');const command={scenarioId:before.value.scenarios[0]!.id,basisFingerprint:before.value.basisFingerprint};at='2026-09-11T12:00:00.000Z';const boundary=application.getScenarios();if(!boundary.ok)return;expect(boundary.value.basisFingerprint).not.toBe(before.value.basisFingerprint);expect(boundary.value.scenarios[0]!.status).toBe('ready_on_current_evidence');const state=application.getSnapshot(),notify=vi.fn();application.subscribe(notify);expect(application.applyScenario(command)).toMatchObject({ok:false,code:'stale_state'});expect(application.getSnapshot()).toBe(state);expect(notify).not.toHaveBeenCalled();expect(search).toHaveBeenCalledTimes(1)})
})
