import {describe,expect,it,vi} from 'vitest'
import {createCoSourceApplication} from '../application/cosource-application'
import type {ProductCluster} from '../commerce/domain/commerce'
import {createApplicationTools,WEBMCP_TOOL_NAMES} from '../webmcp/application-tools'

const provider='shopify_global_catalog' as const,provenance={kind:'provider_explicit' as const,provider},product:ProductCluster={identity:{provider,id:'candidate'},title:{value:'Candidate',provenance},attributes:{value:[{name:'Size',value:'large'}],provenance},media:[],offers:[{identity:{provider,id:'offer'},title:{value:'Offer',provenance},merchant:{identity:{provider,id:'merchant'},policyLinks:[],provenance},price:{minorAmount:1000,currency:'GBP'},oneTimeCostCoverage:{status:'complete',evidence:{strength:'source_explicit',source:'fixture'}},availability:{state:'available',basis:'catalog_signal',provenance},selectedOptions:[],media:[],correlations:[],provenance}],featuredOfferId:'offer',offerCompleteness:'featured_only',provenance}
async function setup(){let id=0;const search=vi.fn(async()=>({products:[product],messages:[],pagination:{hasMore:false}})),application=createCoSourceApplication({market:{country:'GB',currency:'GBP'},makeId:()=>`id-${++id}`,now:()=> '2026-09-11T12:00:00.000Z',catalog:{search,product:vi.fn(async()=>({product,selectedOptions:[],messages:[]}))}});application.editGoal({summary:'Candidate',searchFocus:'candidate',quantity:1});application.addGoalCondition('requirement');const condition=application.getSnapshot().goalDraft.requirements[0]!;application.editGoalCondition('requirement',condition.id,{operator:'equals',field:'Size',value:'large'});application.commitGoalDraft();await application.searchCandidates({query:'candidate'});application.retainCandidate(product.identity);return{application,search}}

describe('scenario application authority',()=>{
 it('keeps reads pure and applies a current ready scenario atomically once',async()=>{const{application,search}=await setup(),before=application.getSnapshot(),listener=vi.fn();application.subscribe(listener);const first=application.getScenarios(),second=application.getScenarios();expect(first).toEqual(second);expect(application.getSnapshot()).toBe(before);expect(listener).not.toHaveBeenCalled();expect(search).toHaveBeenCalledTimes(1);if(!first.ok)return;const ready=first.value.scenarios.find(item=>item.status==='ready_on_current_evidence')!;const result=application.applyScenario({scenarioId:ready.id,basisFingerprint:first.value.basisFingerprint});expect(result).toMatchObject({ok:true,value:{revision:before.plan.revision+1}});if(result.ok)expect(result.value.lines[0]!.id).toMatch(/^id-/);expect(application.getSnapshot().activities[0]).toMatchObject({kind:'scenario_applied'});expect(listener).toHaveBeenCalledTimes(1);expect(search).toHaveBeenCalledTimes(1)})
 it('rejects stale and malformed scenarios without mutation or ID consumption',async()=>{const{application}=await setup(),scenarios=application.getScenarios();if(!scenarios.ok)return;const old=scenarios.value.scenarios[0]!,before=application.getSnapshot();application.addCandidateToPlan(product.identity);const changed=application.getSnapshot();expect(application.applyScenario({scenarioId:old.id,basisFingerprint:scenarios.value.basisFingerprint})).toMatchObject({ok:false,code:'stale_state'});expect(application.getSnapshot()).toBe(changed);expect(application.applyScenario({scenarioId:'',basisFingerprint:''})).toMatchObject({ok:false,code:'invalid_input'});expect(application.getSnapshot()).toBe(changed);expect(changed.plan.revision).toBe(before.plan.revision+1)})
 it('changes the basis after accepted observation refresh and exposes bounded read-only WebMCP summaries',async()=>{const{application}=await setup(),before=application.getScenarios();if(!before.ok)return;await application.refreshRetainedEvidence(product.identity);const after=application.getScenarios();expect(after.ok&&after.value.basisFingerprint).not.toBe(before.value.basisFingerprint);expect(application.applyScenario({scenarioId:before.value.scenarios[0]!.id,basisFingerprint:before.value.basisFingerprint})).toMatchObject({ok:false,code:'stale_state'});const output=await createApplicationTools(application).find(tool=>tool.name==='evaluate_purchase_plan')!.execute({}) as {data:{scenarios:unknown[];scenarioEnumeration:{evaluatedCombinations:number}}};expect(output.data.scenarios.length).toBeLessThanOrEqual(5);expect(output.data.scenarioEnumeration.evaluatedCombinations).toBeLessThanOrEqual(100);expect(WEBMCP_TOOL_NAMES).toHaveLength(13);expect(WEBMCP_TOOL_NAMES.join(' ')).not.toMatch(/apply.*scenario|scenario.*apply/)})
})
