// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest'
import {cleanup,fireEvent,render,screen} from '@testing-library/react'
import {afterEach,describe,expect,it,vi} from 'vitest'
import {createCoSourceApplication} from '../application/cosource-application'
import type {CoSourceApplication,OperationalCaseView} from '../application/cosource-application'
import {operationalCaseSchema} from './domain/operational-case'
import {OperationsPanel} from './OperationsPanel'
import type {ProductCluster} from '../commerce/domain/commerce'

const at='2026-09-12T10:00:00.000Z'
function application(){return createCoSourceApplication({market:{country:'GB',currency:'GBP'},now:()=>at,catalog:{search:vi.fn(async()=>({products:[],messages:[],pagination:{hasMore:false}})),product:vi.fn()}})}
const provider='shopify_global_catalog' as const,provenance={kind:'provider_explicit' as const,provider},decisionEvidence={strength:'source_explicit' as const,source:'fixture'},liveProduct:ProductCluster={identity:{provider,id:'product'},title:{value:'Product',provenance},attributes:{value:[{name:'Size',value:'large'}],provenance},media:[],offers:[{identity:{provider,id:'offer'},title:{value:'Offer',provenance},merchant:{identity:{provider,id:'merchant'},name:'Merchant',policyLinks:[],provenance},price:{minorAmount:1000,currency:'GBP'},oneTimeCostCoverage:{status:'complete',evidence:decisionEvidence},availability:{state:'available',basis:'catalog_signal',provenance},selectedOptions:[],media:[],correlations:[],provenance}],offerCompleteness:'featured_only',featuredOfferId:'offer',provenance}
async function operationalApplication(){let id=0;const app=createCoSourceApplication({market:{country:'GB',currency:'GBP'},makeId:()=>`id-${++id}`,now:()=>new Date().toISOString(),catalog:{search:vi.fn(async()=>({products:[liveProduct],messages:[],pagination:{hasMore:false}})),product:vi.fn(async()=>({product:liveProduct,selectedOptions:[],messages:[]}))}});app.editGoal({summary:'Buy two products',quantity:2});app.addGoalCondition('requirement');const condition=app.getSnapshot().goalDraft.requirements[0]!;app.editGoalCondition('requirement',condition.id,{operator:'equals',field:'Size',value:'large'});app.commitGoalDraft();await app.searchCandidates({query:'product'});app.retainCandidate(liveProduct.identity);app.addCandidateToPlan(liveProduct.identity);const planLine=app.getSnapshot().plan.lines[0]!;app.setPlanLineQuantity(planLine.id,2);app.selectPlanLineOffer(planLine.id,liveProduct.offers[0]!.identity);const snapshot=app.getSnapshot();app.restoreWorkspace({...snapshot,plan:{...snapshot.plan,lines:snapshot.plan.lines.map(line=>({...line,unitSemantics:'single_item'}))}});const supplier=app.retainSupplier(liveProduct.identity,liveProduct.offers[0]!.identity);if(!supplier.ok)throw new Error('supplier setup');app.recordSupplierQuotation(supplier.value.id,{subject:{kind:'offer',source:provider,externalId:'offer'},components:[],coverage:{status:'complete',evidence:decisionEvidence},evidence:decisionEvidence});app.recordSupplierReliability(supplier.value.id,{category:'delivery_outcome',outcome:'positive',summary:'Reliable',evidence:decisionEvidence});return app}

afterEach(cleanup)

describe('OperationsPanel',()=>{
 it('states the external authority boundary and disables opening an empty plan',()=>{const app=application();render(<OperationsPanel application={app} state={app.getSnapshot()}/>);expect(screen.getByText(/ordering and payment happen externally/i)).toBeVisible();expect(screen.getByRole('button',{name:/open case/i})).toBeDisabled()})
 it('keeps a terminal case inspectable with wrapped identifiers and no mutation controls',()=>{const app=application(),state=app.getSnapshot(),item=operationalCaseSchema.parse({id:'case-with-a-very-long-external-safe-identifier',workspaceId:state.id,requirementId:'goal',requirementRevision:1,sourcePlanId:state.plan.id,sourcePlanRevision:0,revision:1,lifecycle:'cancelled',createdAt:at,updatedAt:at,basis:{fingerprint:'basis',workspaceId:state.id,requirementId:'goal',requirementRevision:1,planId:state.plan.id,planRevision:0,observations:[{product:{provider:'fixture',id:'product'},id:'observation',sequence:1,observedAt:at}],verificationIds:[],suppliers:[]},lines:[{id:'line',planLineId:'line',product:{provider:'fixture',id:'product'},productTitle:'Fixture product',offer:{provider:'fixture',id:'offer'},quantity:1,unitSemantics:'single_item',observationId:'observation',observationSequence:1,observationAt:at}],expectedCost:{completeness:'incomplete',totals:[]},approvals:[],externalActions:[],fulfilment:[],actualCosts:[],reconciliation:'unresolved',exceptions:[],events:[{id:'opened',type:'opened',at,summary:'Opened'},{id:'cancelled',type:'cancelled',at,summary:'Cancelled'}]});app.restoreWorkspace({...state,operationalCases:[item]});render(<OperationsPanel application={app} state={app.getSnapshot()}/>);expect(screen.getByText('cancelled')).toBeVisible();expect(screen.getAllByText(/case-with-a-very-long/i).some(element=>element.classList.contains('operations-id'))).toBe(true);expect(screen.queryByRole('button',{name:/complete|cancel|rebase|approval|handoff|receipt|exception/i})).not.toBeInTheDocument();fireEvent.click(screen.getByText(/operational history/i));expect(screen.getByText(/Cancelled$/)).toBeVisible()})
 it('keeps exact receipt correction controls visible after receipt and reflects downgrade without losing rejected drafts',()=>{const base=application(),state=base.getSnapshot(),line={id:'line',planLineId:'line',product:{provider:'fixture',id:'product'},productTitle:'Fixture product',offer:{provider:'fixture',id:'offer'},quantity:2,unitSemantics:'single_item' as const,observationId:'observation',observationSequence:1,observationAt:at},receipt={id:'receipt',lineId:'line',kind:'receipt' as const,quantity:2,externalReference:'receipt-reference',representedAt:at,recordedAt:at,evidence:{strength:'source_explicit' as const,source:'fixture'}},item={id:'case',workspaceId:state.id,requirementId:'goal',requirementRevision:1,sourcePlanId:state.plan.id,sourcePlanRevision:0,revision:4,lifecycle:'received' as const,createdAt:at,updatedAt:at,basis:{fingerprint:'basis',workspaceId:state.id,requirementId:'goal',requirementRevision:1,planId:state.plan.id,planRevision:0,observations:[],verificationIds:[],suppliers:[]},lines:[line],expectedCost:{completeness:'incomplete' as const,totals:[]},approvals:[],externalActions:[{id:'handoff',lineIds:['line']}],fulfilment:[receipt],actualCosts:[],reconciliation:'unresolved' as const,exceptions:[],events:[]},view={case:item,stale:false,readiness:'ready_on_current_evidence',safeNextAction:'reconcile'} as unknown as OperationalCaseView;const rejected=vi.fn(()=>({ok:false as const,code:'invalid_input' as const,message:'Rejected correction'})),fake={...base,getOperationalCases:()=>[view],recordOperationalFulfilment:rejected} as unknown as CoSourceApplication;render(<OperationsPanel application={fake} state={state}/>);const quantity=screen.getByLabelText(/received quantity/i),selector=screen.getByLabelText(/correct an earlier receipt/i);fireEvent.change(quantity,{target:{value:'1'}});fireEvent.change(selector,{target:{value:'receipt'}});expect(screen.getByLabelText(/receipt reference/i)).toHaveValue('receipt-reference');fireEvent.submit(screen.getByRole('button',{name:/record receipt/i}).closest('form')!);expect(screen.getByRole('alert')).toHaveTextContent('Rejected correction');expect(quantity).toHaveValue(1);expect(rejected).toHaveBeenCalledWith(expect.objectContaining({quantity:1,externalReference:'receipt-reference',supersedesId:'receipt'}));fireEvent.click(screen.getByText(/fulfilment evidence history/i));expect(screen.getByText(/Active · receipt · 2 · receipt-reference/i)).toBeVisible()})
 it('drives receipt correction and completion authority through the real application kernel',async()=>{const app=await operationalApplication(),opened=app.openOperationalCase();expect(opened.ok).toBe(true);if(!opened.ok)return;const caseId=opened.value.id,lineId=opened.value.lines[0]!.id;app.requestOperationalApproval({caseId});app.approveOperationalHandoff({caseId});app.recordExternalAction({caseId,lineIds:[lineId],externalReference:'handoff-reference',representedAt:new Date().toISOString(),evidence:decisionEvidence});const receipt=app.recordOperationalFulfilment({caseId,lineId,kind:'receipt',quantity:2,externalReference:'receipt-reference',representedAt:new Date().toISOString(),evidence:decisionEvidence});expect(receipt.ok).toBe(true);app.recordActualCost({caseId,kind:'charged',amount:{minorAmount:2000,currency:'GBP'},externalReference:'charge-reference',representedAt:new Date().toISOString(),evidence:decisionEvidence});app.reconcileOperationalCase({caseId});render(<OperationsPanel application={app} state={app.getSnapshot()}/>);expect(screen.getByRole('button',{name:/complete case/i})).toBeVisible();fireEvent.change(screen.getByLabelText(/received quantity/i),{target:{value:'1'}});fireEvent.change(screen.getByLabelText(/correct an earlier receipt/i),{target:{value:receipt.ok?receipt.value.fulfilment.at(-1)!.id:''}});expect(screen.getByLabelText(/receipt reference/i)).toHaveValue('receipt-reference');fireEvent.submit(screen.getByRole('button',{name:/record receipt/i}).closest('form')!);expect(screen.getByText('partially received')).toBeVisible();expect(screen.queryByRole('button',{name:/complete case/i})).not.toBeInTheDocument();fireEvent.click(screen.getByText(/fulfilment evidence history/i));expect(screen.getByText(/Superseded · receipt · 2 · receipt-reference/i)).toBeVisible();expect(screen.getByText(/Active · receipt · 1 · receipt-reference/i)).toBeVisible();const quantity=screen.getByLabelText(/received quantity/i);fireEvent.change(quantity,{target:{value:'2'}});fireEvent.change(screen.getByLabelText(/receipt reference/i),{target:{value:'too-many'}});fireEvent.submit(screen.getByRole('button',{name:/record receipt/i}).closest('form')!);expect(screen.getByRole('alert')).toHaveTextContent(/contradicts/i);expect(quantity).toHaveValue(2)})
})
