import {useState} from 'react'
import type {CoSourceApplication,CoSourceSessionState,OperationalCaseView} from '../application/cosource-application'
import {activeActualCosts,activeFulfilmentRecords,type OperationalCaseLine} from './domain/operational-case'
import './OperationsPanel.css'

const evidence={strength:'source_explicit' as const,source:'human_operational_record'}
type Feedback={kind:'status'|'alert';text:string}
type Run=(action:()=>ReturnType<CoSourceApplication['openOperationalCase']>,success:string)=>boolean

function LineControls({application,view,line,run}:{application:CoSourceApplication;view:OperationalCaseView;line:OperationalCaseLine;run:Run}){
 const item=view.case,[quantity,setQuantity]=useState(''),[receiptReference,setReceiptReference]=useState(''),[receiptSupersedes,setReceiptSupersedes]=useState(''),[exceptionReason,setExceptionReason]=useState('')
 const representedAt=()=>new Date().toISOString(),handed=item.externalActions.some(action=>action.lineIds.includes(line.id)),activeReceipts=activeFulfilmentRecords(item.fulfilment).filter(record=>record.lineId===line.id&&record.kind==='receipt')
 return <article className="operations-line-controls"><h4>{line.productTitle}</h4><p className="operations-id">Product {line.product.id} · offer {line.offer.id} · merchant {line.merchant?.id??'unresolved'} · supplier {line.supplierId??'unresolved'}</p><p>Quantity {line.quantity??'unresolved'} · {line.unitSemantics.replaceAll('_',' ')} · handoff {handed?'recorded':'pending'}</p>
  {item.lifecycle==='externally_actioned'&&line.supplierId&&!item.fulfilment.some(record=>record.lineId===line.id&&record.kind==='acknowledgement')&&<button onClick={()=>run(()=>application.recordSupplierAcknowledgement({caseId:item.id,lineId:line.id,representedAt:representedAt(),note:`Supplier acknowledgement for ${line.productTitle}`,evidence}),'Supplier acknowledgement recorded in canonical contact history.')}>Record acknowledgement for {line.productTitle}</button>}
  {(['externally_actioned','acknowledged','in_fulfilment','partially_received'].includes(item.lifecycle)||(['received','reconciliation_required'].includes(item.lifecycle)&&activeReceipts.length>0))&&<form onSubmit={event=>{event.preventDefault();const amount=Number(quantity);if(run(()=>application.recordOperationalFulfilment({caseId:item.id,lineId:line.id,kind:'receipt',quantity:amount,externalReference:receiptReference,...(receiptSupersedes?{supersedesId:receiptSupersedes}:{}),representedAt:representedAt(),evidence}),'Decision-grade receipt recorded.')){setQuantity('');setReceiptReference('');setReceiptSupersedes('')}}}><label>Received quantity for {line.productTitle}<input type="number" min="1" max="100000" step="1" value={quantity} onChange={event=>setQuantity(event.target.value)} required/></label><label>Receipt reference for {line.productTitle}<input value={receiptReference} onChange={event=>setReceiptReference(event.target.value)} required maxLength={500}/></label>{activeReceipts.length>0&&<label>Correct an earlier receipt<select value={receiptSupersedes} required={['received','reconciliation_required'].includes(item.lifecycle)} onChange={event=>{setReceiptSupersedes(event.target.value);const selected=activeReceipts.find(record=>record.id===event.target.value);if(selected?.externalReference)setReceiptReference(selected.externalReference)}}><option value="">{['received','reconciliation_required'].includes(item.lifecycle)?'Select receipt to correct':'No correction'}</option>{activeReceipts.map(record=><option key={record.id} value={record.id}>{record.externalReference} · quantity {record.quantity}</option>)}</select></label>}<button type="submit">Record receipt for {line.productTitle}</button></form>}
  {!['completed','cancelled'].includes(item.lifecycle)&&<form onSubmit={event=>{event.preventDefault();if(run(()=>application.recordOperationalException({caseId:item.id,category:'other',severity:'high',reason:exceptionReason,lineId:line.id,supplierId:line.supplierId}),'Blocking line exception recorded.'))setExceptionReason('')}}><label>Exception for {line.productTitle}<input value={exceptionReason} onChange={event=>setExceptionReason(event.target.value)} required maxLength={1000}/></label><button type="submit">Record exception for {line.productTitle}</button></form>}
 </article>
}

export function OperationsPanel({application,state}:{application:CoSourceApplication;state:CoSourceSessionState}){
 const views=application.getOperationalCases(),[selectedId,setSelectedId]=useState(views.at(-1)?.case.id),[feedback,setFeedback]=useState<Feedback>(),[handoffLines,setHandoffLines]=useState<string[]>([]),[handoffReference,setHandoffReference]=useState(''),[actualAmount,setActualAmount]=useState(''),[actualKind,setActualKind]=useState<'quoted'|'authorised'|'charged'|'refunded'|'total_payable'|'manually_recorded'>('total_payable'),[actualReference,setActualReference]=useState(''),[actualSupersedes,setActualSupersedes]=useState('')
 const view=views.find(entry=>entry.case.id===selectedId)??views.at(-1),item=view?.case,active=views.some(entry=>!['completed','cancelled'].includes(entry.case.lifecycle)),representedAt=()=>new Date().toISOString()
 const run:Run=(action,success)=>{const result=action();setFeedback(result.ok?{kind:'status',text:success}:{kind:'alert',text:result.message});return result.ok}
 const completeAllowed=view?.safeNextAction==='complete',activeCosts=item?activeActualCosts(item.actualCosts):[]
 return <section className="operations-panel" aria-labelledby="operations-title"><div className="workspace-head"><div><h3 id="operations-title">Supervised operations</h3><span>CoSource prepares and records. Handoff, ordering and payment happen externally under human authority.</span></div><button disabled={!state.plan.lines.length||active} onClick={()=>{const result=application.openOperationalCase();setFeedback(result.ok?{kind:'status',text:'Operational case opened without approval or external action.'}:{kind:'alert',text:result.message});if(result.ok)setSelectedId(result.value.id)}}>Open case from current plan</button></div>
 {views.length>0&&<label className="operations-case-selector">Inspect operational case<select value={item?.id??''} onChange={event=>{setSelectedId(event.target.value);setHandoffLines([]);setHandoffReference('');setActualAmount('');setActualReference('')}}>{views.map(entry=><option key={entry.case.id} value={entry.case.id}>{entry.case.lifecycle.replaceAll('_',' ')} · {entry.case.id}</option>)}</select></label>}
 {!item?<p>No operational case is open for this project.</p>:<><div className="operations-summary"><p><strong>{item.lifecycle.replaceAll('_',' ')}</strong> · case revision {item.revision}</p><p className="operations-id">Case {item.id} · plan {item.sourcePlanId} revision {item.sourcePlanRevision} · requirement revision {item.requirementRevision}</p><p role={view.stale?'alert':'status'}>{view.stale?(item.externalActions.length?'This historical case is stale. Its post-handoff basis is immutable.':'This case is stale. Explicitly rebase before approval or handoff.'):`Current readiness: ${view.readiness?.replaceAll('_',' ')??'unavailable'}.`} Safe next action: {view.safeNextAction.replaceAll('_',' ')}.</p></div>
  <div className="operations-lines">{item.lines.map(line=><LineControls key={`${state.id}:${item.id}:${line.id}`} application={application} view={view} line={line} run={run}/>)}</div>
  {item.lifecycle==='approved_for_handoff'&&<form className="operations-handoff" onSubmit={event=>{event.preventDefault();if(run(()=>application.recordExternalAction({caseId:item.id,lineIds:handoffLines,externalReference:handoffReference,representedAt:representedAt(),evidence}),'Human-performed multi-line handoff recorded.')){setHandoffLines([]);setHandoffReference('')}}}><fieldset><legend>Select uncovered lines for one outside action</legend>{item.lines.filter(line=>!item.externalActions.some(action=>action.lineIds.includes(line.id))).map(line=><label key={line.id}><input type="checkbox" checked={handoffLines.includes(line.id)} onChange={event=>setHandoffLines(current=>event.target.checked?[...current,line.id]:current.filter(id=>id!==line.id))}/>{line.productTitle} · {line.id}</label>)}</fieldset><label>External action reference<input value={handoffReference} onChange={event=>setHandoffReference(event.target.value)} required maxLength={500}/></label><button type="submit" disabled={!handoffLines.length}>Record selected-line handoff</button></form>}
  <dl className="operations-facts"><div><dt>Expected cost</dt><dd>{item.expectedCost.completeness.replaceAll('_',' ')}</dd></div><div><dt>Approval</dt><dd>{item.approvals.at(-1)?.status??'not requested'}</dd></div><div><dt>External action</dt><dd>{new Set(item.externalActions.flatMap(action=>action.lineIds)).size} of {item.lines.length} lines</dd></div><div><dt>Fulfilment observations</dt><dd>{item.fulfilment.length}</dd></div><div><dt>Open exceptions</dt><dd>{item.exceptions.filter(value=>value.status==='open').length}</dd></div><div><dt>Reconciliation</dt><dd>{item.reconciliation.replaceAll('_',' ')}</dd></div></dl>
  {item.fulfilment.length>0&&<details><summary>Fulfilment evidence history</summary><ul>{item.fulfilment.map(record=><li key={record.id}>{activeFulfilmentRecords(item.fulfilment).some(active=>active.id===record.id)?'Active':'Superseded'} · {record.kind} · {record.quantity??'not quantified'}{record.externalReference?` · ${record.externalReference}`:''}</li>)}</ul></details>}
  <div className="operations-controls">{view.stale&&!item.externalActions.length&&!['completed','cancelled'].includes(item.lifecycle)&&<button onClick={()=>run(()=>application.rebaseOperationalCase({caseId:item.id}),'Case explicitly rebased to current evidence and plan.')}>Rebase case</button>}{item.lifecycle==='draft'&&<button onClick={()=>run(()=>application.requestOperationalApproval({caseId:item.id}),'Approval requested.')}>Request human approval</button>}{item.lifecycle==='awaiting_approval'&&<><button onClick={()=>run(()=>application.approveOperationalHandoff({caseId:item.id}),'Handoff approved by the human.')}>Approve handoff</button><button onClick={()=>run(()=>application.rejectOperationalHandoff({caseId:item.id,note:'Rejected in operations workspace'}),'Handoff rejected; no external action occurred.')}>Reject handoff</button></>}
  {item.exceptions.filter(value=>value.status==='open').map(value=><button key={value.id} onClick={()=>run(()=>application.resolveOperationalException({caseId:item.id,exceptionId:value.id}),'Exception resolved.')}>Resolve {value.category} exception</button>)}
  {['externally_actioned','acknowledged','in_fulfilment','partially_received','received','reconciliation_required'].includes(item.lifecycle)&&<form onSubmit={event=>{event.preventDefault();const settlement=['charged','refunded','total_payable'].includes(actualKind);if(run(()=>application.recordActualCost({caseId:item.id,kind:actualKind,amount:{minorAmount:Number(actualAmount),currency:state.market.currency},...(settlement?{externalReference:actualReference}:{}),...(actualSupersedes?{supersedesId:actualSupersedes}:{}),representedAt:representedAt(),evidence:actualKind==='manually_recorded'?{strength:'source_inferred',source:'human_unverified_observation'}:evidence}),'Stage-specific cost evidence recorded.')){setActualAmount('');setActualReference('');setActualSupersedes('')}}}><label>Cost evidence stage<select value={actualKind} onChange={event=>{setActualKind(event.target.value as typeof actualKind);setActualSupersedes('')}}><option value="quoted">Quoted</option><option value="authorised">Authorised</option><option value="charged">Charged transaction</option><option value="refunded">Refund transaction</option><option value="total_payable">Total payable snapshot</option><option value="manually_recorded">Verification-only manual observation</option></select></label><label>Amount in minor units<input type="number" min="0" step="1" value={actualAmount} onChange={event=>setActualAmount(event.target.value)} required/></label>{['charged','refunded','total_payable'].includes(actualKind)&&<label>Exact settlement reference<input value={actualReference} onChange={event=>setActualReference(event.target.value)} required maxLength={500}/></label>}{activeCosts.some(record=>record.kind===actualKind)&&<label>Correct earlier evidence<select value={actualSupersedes} onChange={event=>{setActualSupersedes(event.target.value);const selected=activeCosts.find(record=>record.id===event.target.value);if(selected?.externalReference)setActualReference(selected.externalReference)}}><option value="">No correction</option>{activeCosts.filter(record=>record.kind===actualKind).map(record=><option key={record.id} value={record.id}>{record.externalReference??record.id} · {record.amount.minorAmount}</option>)}</select></label>}<button type="submit">Record {actualKind.replaceAll('_',' ')}</button></form>}
  {item.actualCosts.length>0&&<details><summary>Cost evidence history</summary><ul>{item.actualCosts.map(record=><li key={record.id}>{activeCosts.some(active=>active.id===record.id)?'Active':'Superseded'} · {record.kind.replaceAll('_',' ')} · {record.amount.minorAmount} {record.amount.currency}</li>)}</ul></details>}
  {['received','reconciliation_required'].includes(item.lifecycle)&&<button onClick={()=>run(()=>application.reconcileOperationalCase({caseId:item.id}),'Expected and actual cost reconciled conservatively.')}>Reconcile costs</button>}{completeAllowed&&<button onClick={()=>run(()=>application.completeOperationalCase({caseId:item.id}),'Operational case completed.')}>Complete case</button>}{!['completed','cancelled'].includes(item.lifecycle)&&<button onClick={()=>run(()=>application.cancelOperationalCase({caseId:item.id,note:'Cancelled by the human'}),'Operational case cancelled.')}>Cancel case</button>}</div>
  {feedback&&<p role={feedback.kind} aria-live="polite" className={feedback.kind==='alert'?'notice error':'notice'}>{feedback.text}</p>}<details><summary>Operational history ({item.events.length})</summary><ol>{item.events.map(value=><li key={value.id}>{value.at}: {value.summary}</li>)}</ol></details></>}
 </section>
}
