import {describe,expect,it} from 'vitest'
import type {EvidenceReference} from '../evidence/domain/evidence'
import {actualCostCommandSchema,externalActionCommandSchema,fulfilmentCommandSchema,operationalCaseSchema,reconcileAmounts,type ExpectedCostSnapshot,type OperationalCase} from './domain/operational-case'

const at='2026-09-12T10:00:00.000Z',evidence={strength:'source_explicit' as const,source:'fixture'},weak={strength:'source_inferred' as const,source:'fixture'},amount={minorAmount:1000,currency:'GBP'},expected:ExpectedCostSnapshot={completeness:'complete_exact',totals:[{currency:'GBP',knownLowerBound:amount,upperBound:amount,exactLandedTotal:amount}]}
const cost=(id:string,kind:OperationalCase['actualCosts'][number]['kind'],strength:EvidenceReference=evidence,externalReference?:string):OperationalCase['actualCosts'][number]=>({id,kind,amount,representedAt:at,recordedAt:at,evidence:strength,...(externalReference?{externalReference}:{})})
const base=()=>({id:'case',workspaceId:'workspace',requirementId:'goal',requirementRevision:1,sourcePlanId:'plan',sourcePlanRevision:1,revision:0,lifecycle:'draft',createdAt:at,updatedAt:at,basis:{fingerprint:'basis',workspaceId:'workspace',requirementId:'goal',requirementRevision:1,planId:'plan',planRevision:1,observations:[{product:{provider:'catalog',id:'product'},id:'observation',sequence:1,observedAt:at}],verificationIds:[],suppliers:[]},lines:[{id:'line',planLineId:'line',product:{provider:'catalog',id:'product'},productTitle:'Product',offer:{provider:'catalog',id:'offer'},quantity:1,unitSemantics:'single_item',observationId:'observation',observationSequence:1,observationAt:at}],expectedCost:expected,approvals:[],externalActions:[],fulfilment:[],actualCosts:[],reconciliation:'unresolved',exceptions:[],events:[{id:'opened',type:'opened',at,summary:'Opened'}]})

describe('R10R integrity reproductions',()=>{
 it('does not double-count quotation, authorisation and charge stages',()=>{expect(reconcileAmounts(expected,[cost('quote','quoted'),cost('authorised','authorised'),cost('charge','charged',evidence,'charge-1')])).toBe('matched')})
 it('keeps verification-only settlement evidence non-conclusive',()=>{expect(reconcileAmounts(expected,[cost('charge','charged',weak,'charge-weak')])).toBe('verification_required')})
 it('reports disagreement between a supported total and supported transactions',()=>{expect(reconcileAmounts(expected,[cost('charge','charged',evidence,'charge-1'),{...cost('total','total_payable',evidence,'total-1'),amount:{minorAmount:1200,currency:'GBP'}}])).toBe('conflicting')})
 it('requires explicit non-empty multi-line handoff bindings and positive fulfilment',()=>{expect(externalActionCommandSchema.safeParse({caseId:'case',externalReference:'external',representedAt:at,evidence}).success).toBe(false);expect(externalActionCommandSchema.safeParse({caseId:'case',externalReference:'external',lineIds:['one','two'],representedAt:at,evidence}).success).toBe(true);expect(fulfilmentCommandSchema.safeParse({caseId:'case',lineId:'line',kind:'receipt',quantity:0,representedAt:at,evidence}).success).toBe(false)})
 it('rejects duplicate settlement references before they can be counted',()=>{const forged={...base(),actualCosts:[cost('one','charged',evidence,'same'),cost('two','refunded',evidence,'same')]};expect(operationalCaseSchema.safeParse(forged).success).toBe(false);expect(actualCostCommandSchema.safeParse({caseId:'case',kind:'charged',amount,representedAt:at,evidence}).success).toBe(false)})
 it('rejects completed-without-receipt, forged event references, and revision mismatch',()=>{const draft=base(),completed={...draft,revision:3,lifecycle:'completed',approvals:[{id:'request',status:'requested',at,basisFingerprint:'basis'},{id:'approval',status:'approved',at,basisFingerprint:'basis'}],externalActions:[{id:'handoff',kind:'external_handoff',occurredOutsideCoSource:true,externalReference:'external',lineIds:['line'],representedAt:at,recordedAt:at,evidence}],reconciliation:'matched',events:[draft.events[0],{id:'request-event',type:'approval_requested',at,summary:'Requested',referenceId:'request'},{id:'approval-event',type:'handoff_approved',at,summary:'Approved',referenceId:'approval'},{id:'handoff-event',type:'external_action_recorded',at,summary:'Outside',referenceId:'handoff'},{id:'completed-event',type:'completed',at,summary:'Completed'}]};expect(operationalCaseSchema.safeParse(completed).success).toBe(false);expect(operationalCaseSchema.safeParse({...draft,revision:1}).success).toBe(false);expect(operationalCaseSchema.safeParse({...draft,events:[{...draft.events[0],referenceId:'forged'}]}).success).toBe(false)})
})
