import {describe,expect,it} from 'vitest'
import {activeActualCosts,activeFulfilmentRecords,actualCostCommandSchema,fulfilmentCommandSchema,reconcileAmounts,type ExpectedCostSnapshot,type OperationalCase} from './domain/operational-case'

const at='2026-09-12T10:00:00.000Z',evidence={strength:'source_explicit' as const,source:'fixture'},amount={minorAmount:1000,currency:'GBP'},expected:ExpectedCostSnapshot={completeness:'complete_exact',totals:[{currency:'GBP',knownLowerBound:amount,upperBound:amount,exactLandedTotal:amount}]}
const cost=(id:string,kind:OperationalCase['actualCosts'][number]['kind'],minorAmount:number,externalReference:string,supersedesId?:string):OperationalCase['actualCosts'][number]=>({id,kind,amount:{minorAmount,currency:'GBP'},externalReference,representedAt:at,recordedAt:at,evidence,...(supersedesId?{supersedesId}:{})})
const receipt=(id:string,quantity:number,externalReference:string,supersedesId?:string):OperationalCase['fulfilment'][number]=>({id,lineId:'line',kind:'receipt',quantity,externalReference,representedAt:at,recordedAt:at,evidence,...(supersedesId?{supersedesId}:{})})

describe('R10R2 reconciliation and lifecycle reproductions',()=>{
 it('is input-order invariant and does not preserve a stale matched projection',()=>{const charge=cost('charge','charged',1000,'charge-1'),conflicting=cost('total','total_payable',1200,'total-1');expect(reconcileAmounts(expected,[charge])).toBe('matched');expect(reconcileAmounts(expected,[charge,conflicting])).toBe('conflicting');expect(reconcileAmounts(expected,[conflicting,charge])).toBe('conflicting')})
 it('uses append-only correction while excluding superseded cost evidence',()=>{const charge=cost('charge','charged',1000,'charge-1'),wrong=cost('wrong','total_payable',1200,'total-1'),corrected=cost('corrected','total_payable',1000,'total-1','wrong');expect(activeActualCosts([charge,wrong,corrected]).map(item=>item.id)).toEqual(['charge','corrected']);expect(reconcileAmounts(expected,[charge,wrong,corrected])).toBe('matched')})
 it('rejects non-settlement external references at command parsing before IDs can be allocated',()=>{expect(actualCostCommandSchema.safeParse({caseId:'case',kind:'quoted',amount,externalReference:'not-a-settlement',representedAt:at,evidence}).success).toBe(false)})
 it('requires exact receipt identity and supports append-only receipt correction',()=>{expect(fulfilmentCommandSchema.safeParse({caseId:'case',lineId:'line',kind:'receipt',quantity:1,representedAt:at,evidence}).success).toBe(false);const wrong=receipt('wrong',2,'receipt-1'),corrected=receipt('corrected',1,'receipt-1','wrong');expect(activeFulfilmentRecords([wrong,corrected]).map(item=>item.id)).toEqual(['corrected'])})
 it('keeps duplicate active receipt references detectable rather than double-counting silently',()=>{const first=receipt('first',1,'receipt-1'),duplicate=receipt('duplicate',1,'receipt-1');expect(activeFulfilmentRecords([first,duplicate]).map(item=>item.externalReference)).toEqual(['receipt-1','receipt-1'])})
})
