import {describe,expect,it} from 'vitest'
import {operationalCaseSchema,type OperationalCase} from './domain/operational-case'

const at='2026-09-12T10:00:00.000Z',later='2026-09-12T11:00:00.000Z',identity={provider:'fixture',id:'product'},evidence={strength:'source_explicit' as const,source:'fixture'}
function receivedCase():OperationalCase{return operationalCaseSchema.parse({id:'case',workspaceId:'workspace',requirementId:'goal',requirementRevision:1,sourcePlanId:'plan',sourcePlanRevision:1,revision:4,lifecycle:'received',createdAt:at,updatedAt:later,basis:{fingerprint:'basis',workspaceId:'workspace',requirementId:'goal',requirementRevision:1,planId:'plan',planRevision:1,observations:[{product:identity,id:'observation',sequence:1,observedAt:at}],verificationIds:[],suppliers:[]},lines:[{id:'line',planLineId:'line',product:identity,productTitle:'Product',offer:{provider:'fixture',id:'offer'},quantity:1,unitSemantics:'single_item',observationId:'observation',observationSequence:1,observationAt:at}],expectedCost:{completeness:'complete_exact',totals:[{currency:'GBP',knownLowerBound:{minorAmount:1000,currency:'GBP'},upperBound:{minorAmount:1000,currency:'GBP'},exactLandedTotal:{minorAmount:1000,currency:'GBP'}}]},approvals:[{id:'request',status:'requested',at,basisFingerprint:'basis'},{id:'approval',status:'approved',at,basisFingerprint:'basis'}],externalActions:[{id:'handoff',kind:'external_handoff',occurredOutsideCoSource:true,externalReference:'handoff-reference',lineIds:['line'],representedAt:at,recordedAt:at,evidence}],fulfilment:[{id:'receipt',lineId:'line',kind:'receipt',quantity:1,externalReference:'receipt-reference',representedAt:later,recordedAt:later,evidence}],actualCosts:[],reconciliation:'unresolved',exceptions:[],events:[{id:'opened',type:'opened',at,summary:'Opened'},{id:'requested',type:'approval_requested',at,summary:'Requested',referenceId:'request'},{id:'approved',type:'handoff_approved',at,summary:'Approved',referenceId:'approval'},{id:'handed',type:'external_action_recorded',at,summary:'Handed off',referenceId:'handoff'},{id:'received',type:'receipt_recorded',at:later,summary:'Received',lineId:'line',referenceId:'receipt'}]})}
function append(base:OperationalCase,record:OperationalCase['fulfilment'][number],type:'supplier_acknowledged'|'fulfilment_recorded'|'receipt_recorded',lifecycle:OperationalCase['lifecycle']){return{...base,lifecycle,revision:base.revision+1,fulfilment:[...base.fulfilment,record],events:[...base.events,{id:`event-${record.id}`,type,at:later,summary:'Illegal post-receipt event',lineId:'line',referenceId:record.id}]}}

describe('R10R4 persisted replay defects',()=>{
 it('rejects ordinary receipt, acknowledgement, dispatch and acceptance after received',()=>{const base=receivedCase(),common={lineId:'line',quantity:1,representedAt:later,recordedAt:later,evidence};expect(operationalCaseSchema.safeParse(append(base,{id:'extra-receipt',kind:'receipt',externalReference:'other-reference',...common,evidence:{strength:'source_inferred',source:'fixture'}},'receipt_recorded','received')).success).toBe(false);expect(operationalCaseSchema.safeParse(append(base,{id:'late-ack',kind:'acknowledgement',supplierContactId:'contact',lineId:'line',representedAt:later,recordedAt:later,evidence},'supplier_acknowledged','acknowledged')).success).toBe(false);for(const kind of ['dispatch','acceptance'] as const)expect(operationalCaseSchema.safeParse(append(base,{id:`late-${kind}`,kind,...common},'fulfilment_recorded','in_fulfilment')).success).toBe(false)})
 it('rejects reconciliation while the canonical result is unresolved',()=>{const base=receivedCase(),forged={...base,revision:base.revision+1,events:[...base.events,{id:'reconcile',type:'reconciled' as const,at:later,summary:'Forged reconciliation'}]};expect(operationalCaseSchema.safeParse(forged).success).toBe(false)})
 it('requires fulfilment represented time to follow the handoff for its exact line',()=>{const base=receivedCase(),line2={...base.lines[0]!,id:'line-2',planLineId:'line-2'},action1={...base.externalActions[0]!,lineIds:['line'],representedAt:at,recordedAt:at},action2={...base.externalActions[0]!,id:'handoff-2',externalReference:'handoff-2',lineIds:['line-2'],representedAt:later,recordedAt:later},receipt={...base.fulfilment[0]!,id:'receipt-2',lineId:'line-2',representedAt:'2026-09-12T10:30:00.000Z',recordedAt:later},value={...base,revision:6,lines:[base.lines[0]!,line2],externalActions:[action1,action2],fulfilment:[base.fulfilment[0]!,receipt],events:[...base.events.slice(0,4),{id:'handoff-event-2',type:'external_action_recorded' as const,at:later,summary:'Second handoff',referenceId:'handoff-2'},{id:'receipt-event-1',type:'receipt_recorded' as const,at:later,summary:'First receipt',lineId:'line',referenceId:'receipt'},{id:'receipt-event-2',type:'receipt_recorded' as const,at:later,summary:'Second receipt',lineId:'line-2',referenceId:'receipt-2'}]};expect(operationalCaseSchema.safeParse(value).success).toBe(false)})
})
