import {describe,expect,it} from 'vitest'
import {canTransitionOperationalCase,OPERATIONAL_EVENT_LIMIT,operationalCaseSchema,reconcileAmounts,reviseOperationalCase,type OperationalCase} from './operational-case'

const at='2026-09-12T10:00:00.000Z',identity={provider:'catalog',id:'item'},money={minorAmount:1000,currency:'GBP'}
function item():OperationalCase{return operationalCaseSchema.parse({id:'case',workspaceId:'workspace',requirementId:'goal',requirementRevision:1,sourcePlanId:'plan',sourcePlanRevision:2,revision:0,lifecycle:'draft',createdAt:at,updatedAt:at,basis:{fingerprint:'basis',workspaceId:'workspace',requirementId:'goal',requirementRevision:1,planId:'plan',planRevision:2,observations:[{product:identity,id:'observation',sequence:1,observedAt:at}],verificationIds:[],suppliers:[]},lines:[{id:'line',planLineId:'line',product:identity,productTitle:'Item',offer:{provider:'catalog',id:'offer'},quantity:1,unitSemantics:'single_item',observationId:'observation',observationSequence:1,observationAt:at}],expectedCost:{completeness:'complete_exact',totals:[{currency:'GBP',knownLowerBound:money,upperBound:money,exactLandedTotal:money}]},approvals:[],externalActions:[],fulfilment:[],actualCosts:[],reconciliation:'unresolved',exceptions:[],events:[{id:'event-open',type:'opened',at,summary:'Opened'}]})}

describe('canonical operational case domain',()=>{
 it('defines the closed lifecycle and protects terminal states',()=>{expect(canTransitionOperationalCase('draft','awaiting_approval')).toBe(true);expect(canTransitionOperationalCase('draft','externally_actioned')).toBe(false);expect(canTransitionOperationalCase('completed','draft')).toBe(false);expect(canTransitionOperationalCase('cancelled','draft')).toBe(false);const result=reviseOperationalCase({...item(),lifecycle:'cancelled'}, {},{id:'event',type:'rebased',at,summary:'no'});expect(result).toEqual({ok:false,reason:'Terminal operational cases cannot change.'})})
 it('rejects unknown fields, duplicate IDs, impossible chronology, bindings and unbounded collections',()=>{const base=item();expect(operationalCaseSchema.safeParse({...base,unknown:true}).success).toBe(false);expect(operationalCaseSchema.safeParse({...base,lines:[base.lines[0],base.lines[0]]}).success).toBe(false);expect(operationalCaseSchema.safeParse({...base,updatedAt:'2026-09-12T09:00:00.000Z'}).success).toBe(false);expect(operationalCaseSchema.safeParse({...base,basis:{...base.basis,workspaceId:'other'}}).success).toBe(false);expect(operationalCaseSchema.safeParse({...base,events:Array.from({length:OPERATIONAL_EVENT_LIMIT+1},(_,index)=>({...base.events[0]!,id:`event-${index}`}))}).success).toBe(false)})
 it('enforces safe integer quantities and money with currency-isolated reconciliation',()=>{const base=item();expect(operationalCaseSchema.safeParse({...base,lines:[{...base.lines[0]!,quantity:Number.MAX_SAFE_INTEGER+1}]}).success).toBe(false);expect(reconcileAmounts(base.expectedCost,[{id:'actual',kind:'charged',amount:money,representedAt:at,recordedAt:at,evidence:{strength:'source_explicit',source:'human'}}])).toBe('matched');expect(reconcileAmounts(base.expectedCost,[{id:'actual',kind:'charged',amount:{minorAmount:1000,currency:'USD'},representedAt:at,recordedAt:at,evidence:{strength:'source_explicit',source:'human'}}])).toBe('conflicting');expect(reconcileAmounts(base.expectedCost,[])).toBe('unresolved')})
 it('keeps deterministic append order and rejects illegal transitions without mutation',()=>{const base=item(),illegal=reviseOperationalCase(base,{lifecycle:'externally_actioned'},{id:'event',type:'external_action_recorded',at,summary:'bad'});expect(illegal).toEqual({ok:false,reason:'Lifecycle cannot move from draft to externally_actioned.'});expect(base.revision).toBe(0);const next=reviseOperationalCase(base,{lifecycle:'awaiting_approval',approvals:[{id:'approval',status:'requested',at,basisFingerprint:'basis'}]},{id:'event-request',type:'approval_requested',at,summary:'requested',referenceId:'approval'});expect(next.ok&&next.value.events.map(event=>event.id)).toEqual(['event-open','event-request'])})
 it('reserves terminal history capacity instead of stranding a live case',()=>{const base=item(),events=[base.events[0]!,...Array.from({length:98},(_,index)=>({id:`rebase-${index}`,type:'rebased' as const,at,summary:'Explicit pre-handoff rebase'}))],nearLimit=operationalCaseSchema.parse({...base,revision:98,events});expect(reviseOperationalCase(nearLimit,{}, {id:'ordinary',type:'rebased',at,summary:'Would consume terminal reserve'})).toMatchObject({ok:false});expect(reviseOperationalCase(nearLimit,{lifecycle:'cancelled'},{id:'cancel',type:'cancelled',at,summary:'Human cancelled'})).toMatchObject({ok:true,value:{lifecycle:'cancelled',revision:99}})})
})
