import type {PersistedWorkspaceEnvelope,SaveWorkspaceResult} from '../persistence/workspace-persistence'
import {parseProjectDirectory} from './project-directory-schema'
import {validateProjectWorkspaceBinding} from './project-workspace-binding'
import type {CreateProjectResult,DirectorySaveResult,PortfolioLoadResult,ProjectDirectory,ProjectPortfolioPersistencePort} from './project-portfolio'

export class MemoryProjectPortfolioPersistence implements ProjectPortfolioPersistencePort{
 directory:unknown|undefined
 legacy:unknown|undefined
 projects=new Map<string,unknown>()
 unavailable=false
 constructor(seed?:{directory?:unknown;legacy?:unknown;projects?:Array<[string,unknown]>}){this.directory=structuredClone(seed?.directory);this.legacy=structuredClone(seed?.legacy);for(const [id,value] of seed?.projects??[])this.projects.set(id,structuredClone(value))}
 async loadPortfolio():Promise<PortfolioLoadResult>{this.available();if(this.directory===undefined)return{status:'missing'};const directory=parseProjectDirectory(this.directory);if(!directory.ok)return{status:'recovery_required',reason:directory.reason,message:'Invalid directory'};let active:PersistedWorkspaceEnvelope|undefined;for(const project of directory.value.projects){const binding=validateProjectWorkspaceBinding(project.id,this.projects.get(project.id));if(!binding.ok)return{status:'recovery_required',reason:binding.reason,projectId:project.id,message:`Saved project ${project.id} failed integrity validation.`};if(project.id===directory.value.activeProjectId)active=binding.value}return{status:'ready',directory:structuredClone(directory.value),workspace:structuredClone(active!)}}
 async initializePortfolio(directory:ProjectDirectory,workspace:PersistedWorkspaceEnvelope):Promise<PortfolioLoadResult>{this.available();const proposed=parseProjectDirectory(directory),binding=validateProjectWorkspaceBinding(directory.activeProjectId,workspace);if(!proposed.ok||!binding.ok)throw new Error('invalid portfolio initialization');if(this.directory!==undefined)return this.loadPortfolio();let selected=binding.value,next=proposed.value;if(this.legacy!==undefined){const legacy=validateProjectWorkspaceBinding((this.legacy as{workspaceId?:unknown})?.workspaceId as string,this.legacy);if(!legacy.ok)return{status:'recovery_required',reason:legacy.reason,message:'Invalid legacy workspace'};selected=legacy.value;const project={...next.projects[0]!,id:selected.workspaceId};next={...next,activeProjectId:project.id,projects:[project]}}this.projects.set(selected.workspaceId,structuredClone(selected));this.directory=structuredClone(next);return{status:'ready',directory:structuredClone(next),workspace:structuredClone(selected)}}
 async loadProject(id:string){this.available();return structuredClone(this.projects.get(id))}
 async createProject(directory:ProjectDirectory,expected:number,workspace:PersistedWorkspaceEnvelope):Promise<CreateProjectResult>{this.available();const current=parseProjectDirectory(this.directory),next=parseProjectDirectory(directory),binding=validateProjectWorkspaceBinding(directory.activeProjectId,workspace);if(!current.ok||!next.ok||!binding.ok||directory.directoryRevision!==expected+1||current.value.projects.some(item=>item.id===workspace.workspaceId)||!directory.projects.some(item=>item.id===workspace.workspaceId))throw new Error('invalid project creation');if(current.value.directoryRevision!==expected)return{ok:false,reason:'conflict',currentRevision:current.value.directoryRevision};if(this.projects.has(workspace.workspaceId))throw new Error('duplicate project');this.projects.set(workspace.workspaceId,structuredClone(binding.value));this.directory=structuredClone(next.value);return{ok:true,directory:structuredClone(next.value)}}
 async compareAndSaveDirectory(directory:ProjectDirectory,expected:number):Promise<DirectorySaveResult>{this.available();const current=parseProjectDirectory(this.directory),next=parseProjectDirectory(directory);if(!current.ok||!next.ok||directory.directoryRevision!==expected+1)throw new Error('invalid directory write');if(current.value.directoryRevision!==expected)return{ok:false,reason:'conflict',currentRevision:current.value.directoryRevision};this.directory=structuredClone(next.value);return{ok:true,directory:structuredClone(next.value)}}
 async compareAndSaveProject(id:string,record:PersistedWorkspaceEnvelope,expected:number|undefined):Promise<SaveWorkspaceResult>{this.available();const incoming=validateProjectWorkspaceBinding(id,record);if(!incoming.ok)throw new Error('invalid project binding');const raw=this.projects.get(id);if(raw===undefined){if(expected!==undefined)return{ok:false,reason:'conflict',currentRevision:0}}else{const current=validateProjectWorkspaceBinding(id,raw);if(!current.ok)throw new Error('invalid project');if(current.value.durableRevision!==expected)return{ok:false,reason:'conflict',currentRevision:current.value.durableRevision}}this.projects.set(id,structuredClone(incoming.value));return{ok:true,record:structuredClone(incoming.value)}}
 private available(){if(this.unavailable)throw new Error('unavailable')}
}
