import {describe,expect,it,vi} from 'vitest'
import {createCoSourceApplication} from '../cosource-application'
import {durableProjection,PERSISTED_WORKSPACE_FORMAT_VERSION,type PersistedWorkspaceEnvelope} from '../persistence/workspace-persistence'
import {MemoryProjectPortfolioPersistence} from './memory-project-portfolio-persistence'
import {createProjectPortfolio} from './project-portfolio-controller'
import {DEFAULT_PROJECT_NAME,PROJECT_DIRECTORY_FORMAT_VERSION,PROJECT_LIMIT,type ProjectDirectory} from './project-portfolio'

const market={country:'GB',currency:'GBP',language:'en'},now=()=> '2026-09-07T12:00:00.000Z'
function setup(repository=new MemoryProjectPortfolioPersistence()){let id=0;const search=vi.fn(async()=>({products:[],messages:[],pagination:{hasMore:false as const}})),product=vi.fn(async()=>{throw new Error('unused')});const factory=()=>createCoSourceApplication({market,makeId:()=>`id-${++id}`,now,catalog:{search,product}});return{repository,factory,search,product,portfolio:createProjectPortfolio(factory,repository,now)}}
const active=(portfolio:ReturnType<typeof createProjectPortfolio>)=>portfolio.getSnapshot().active!

describe('saved project portfolio',()=>{
 it('creates exactly one fresh project across repeated initialization',async()=>{const {portfolio,repository}=setup();await Promise.all([portfolio.initialize(),portfolio.initialize()]);expect((repository.directory as ProjectDirectory).projects).toHaveLength(1);expect((repository.directory as ProjectDirectory).projects[0]?.name).toBe(DEFAULT_PROJECT_NAME);expect(repository.projects).toHaveLength(1)})
 it('keeps projects isolated and restores the active goal without provider calls',async()=>{const {portfolio,search,product}=setup();await portfolio.initialize();const firstId=active(portfolio).application.getSnapshot().id;active(portfolio).application.editGoal({summary:'Project A'});active(portfolio).application.commitGoalDraft();await new Promise(resolve=>setTimeout(resolve,0));expect(await portfolio.createProject('Project B')).toEqual({ok:true});active(portfolio).application.editGoal({summary:'Project B'});active(portfolio).application.commitGoalDraft();await new Promise(resolve=>setTimeout(resolve,0));expect(await portfolio.switchProject(firstId)).toEqual({ok:true});expect(active(portfolio).application.getSnapshot().activeGoal?.summary).toBe('Project A');expect(search).not.toHaveBeenCalled();expect(product).not.toHaveBeenCalled()})
 it('renames metadata without revising business state',async()=>{const {portfolio}=setup();await portfolio.initialize();const before=active(portfolio).application.getSnapshot();expect(await portfolio.renameActiveProject('  Annual supplies  ')).toEqual({ok:true});expect(portfolio.getSnapshot().directory?.projects[0]?.name).toBe('Annual supplies');expect(active(portfolio).application.getSnapshot()).toBe(before)})
 it('rejects invalid names before storage mutation',async()=>{const {portfolio,repository}=setup();await portfolio.initialize();const before=structuredClone(repository.directory);expect((await portfolio.createProject('   ')).ok).toBe(false);expect(repository.directory).toEqual(before)})
 it('blocks switching from unresolved save state',async()=>{const {portfolio,repository}=setup();await portfolio.initialize();await portfolio.createProject('Second');const first=(repository.directory as ProjectDirectory).projects[0]!.id;repository.unavailable=true;active(portfolio).application.editGoal({summary:'unsaved'});await new Promise(resolve=>setTimeout(resolve,0));repository.unavailable=false;expect(await portfolio.switchProject(first)).toMatchObject({ok:false,reason:'unsafe_switch'});expect(portfolio.getSnapshot().directory?.activeProjectId).not.toBe(first)})
 it('stops the previous controller from saving after a switch',async()=>{const {portfolio,repository}=setup();await portfolio.initialize();const previous=active(portfolio),firstId=previous.application.getSnapshot().id;await portfolio.createProject('Second');const stored=structuredClone(repository.projects.get(firstId));previous.application.editGoal({summary:'inactive mutation'});await new Promise(resolve=>setTimeout(resolve,0));expect(repository.projects.get(firstId)).toEqual(stored)})
 it('reports stale directory writers without overwriting the winner',async()=>{const shared=new MemoryProjectPortfolioPersistence(),a=setup(shared).portfolio,b=setup(shared).portfolio;await Promise.all([a.initialize(),b.initialize()]);expect((await a.renameActiveProject('Winner')).ok).toBe(true);expect(await b.renameActiveProject('Loser')).toMatchObject({ok:false,reason:'conflict'});expect((shared.directory as ProjectDirectory).projects[0]?.name).toBe('Winner')})
 it('enforces the project limit before storage mutation',async()=>{const {portfolio,repository}=setup();await portfolio.initialize();for(let index=1;index<PROJECT_LIMIT;index++)expect(await portfolio.createProject(`P${index}`)).toEqual({ok:true});const count=repository.projects.size;expect(await portfolio.createProject('Overflow')).toMatchObject({ok:false,reason:'limit'});expect(repository.projects.size).toBe(count)})
 it('keeps corrupt legacy bytes untouched',async()=>{const legacy={bad:true},repository=new MemoryProjectPortfolioPersistence({legacy}),{portfolio}=setup(repository);await portfolio.initialize();expect(portfolio.getSnapshot().status).toBe('recovery_required');expect(repository.legacy).toEqual(legacy);expect(repository.directory).toBeUndefined()})
 it('migrates a valid legacy envelope once with identity and revision intact',async()=>{const seed=setup(),application=seed.factory();application.editGoal({summary:'Legacy'});const payload=durableProjection(application.getSnapshot()),legacy={formatVersion:PERSISTED_WORKSPACE_FORMAT_VERSION,workspaceId:payload.id,durableRevision:1,savedAt:now(),market,payload} as PersistedWorkspaceEnvelope,repository=new MemoryProjectPortfolioPersistence({legacy}),first=setup(repository).portfolio,second=setup(repository).portfolio;await first.initialize();expect(first.getSnapshot()).toMatchObject({status:'ready'});await second.initialize();expect((repository.directory as ProjectDirectory)).toMatchObject({formatVersion:PROJECT_DIRECTORY_FORMAT_VERSION,activeProjectId:payload.id,projects:[{id:payload.id}]});expect(repository.projects).toHaveLength(1);expect(active(second).application.getSnapshot().goalDraft.summary).toBe('Legacy');expect((repository.projects.get(payload.id) as PersistedWorkspaceEnvelope).durableRevision).toBe(1)})
 it('provides honest single-workspace mode without project controls',async()=>{const {factory}=setup(),portfolio=createProjectPortfolio(factory);await portfolio.initialize();expect(portfolio.getSnapshot()).toMatchObject({status:'unavailable',active:{}});expect(await portfolio.createProject('Nope')).toMatchObject({ok:false})})
})
