import {describe,expect,it,vi} from 'vitest'
import {createCoSourceApplication} from '../cosource-application'
import {durableProjection,PERSISTED_WORKSPACE_FORMAT_VERSION,type PersistedWorkspaceEnvelope} from '../persistence/workspace-persistence'
import {MemoryProjectPortfolioPersistence} from './memory-project-portfolio-persistence'
import {parseProjectDirectory} from './project-directory-schema'
import {createProjectPortfolio} from './project-portfolio-controller'
import {PROJECT_DIRECTORY_FORMAT_VERSION,type ProjectDirectory} from './project-portfolio'

const market={country:'GB',currency:'GBP'},time='2026-09-07T12:00:00.000Z'
function harness(repository=new MemoryProjectPortfolioPersistence()){let id=0;const factory=()=>createCoSourceApplication({market,makeId:()=>`r4r-${++id}`,now:()=>time,catalog:{search:async()=>({products:[],messages:[],pagination:{hasMore:false}}),product:async()=>{throw new Error('unused')}}});return{repository,factory,portfolio:createProjectPortfolio(factory,repository,()=>time)}}
function envelope(id:string):PersistedWorkspaceEnvelope{let counter=0;const app=createCoSourceApplication({market,makeId:()=>`${id}-${++counter}`,now:()=>time,catalog:{search:async()=>({products:[],messages:[],pagination:{hasMore:false}}),product:async()=>{throw new Error('unused')}}}),payload={...durableProjection(app.getSnapshot()),id};return{formatVersion:PERSISTED_WORKSPACE_FORMAT_VERSION,workspaceId:id,durableRevision:0,savedAt:time,market,payload}}
const metadata=(id:string)=>({id,name:id,createdAt:time,updatedAt:time})
const directory=(active:string,ids:string[],revision=0):ProjectDirectory=>({formatVersion:PROJECT_DIRECTORY_FORMAT_VERSION,directoryRevision:revision,activeProjectId:active,projects:ids.map(metadata)})

describe('R4R portfolio integrity regressions',()=>{
 it('rejects an active key/envelope identity mismatch before ready',async()=>{const repository=new MemoryProjectPortfolioPersistence({directory:directory('project-A',['project-A']),projects:[['project-A',envelope('project-B')]]});expect(await repository.loadPortfolio()).toMatchObject({status:'recovery_required',reason:'identity_mismatch',projectId:'project-A'})})
 it.each(['missing','mismatched'] as const)('does not advertise an unhealthy inactive project: %s',async kind=>{const projects:Array<[string,unknown]>=[['project-A',envelope('project-A')]];if(kind==='mismatched')projects.push(['project-B',envelope('other')]);const repository=new MemoryProjectPortfolioPersistence({directory:directory('project-A',['project-A','project-B']),projects});expect(await repository.loadPortfolio()).toMatchObject({status:'recovery_required',reason:kind==='missing'?'missing_project':'identity_mismatch',projectId:'project-B'});expect(repository.projects.get('project-A')).toEqual(envelope('project-A'))})
 it('leaves the old application, directory revision, and controller alive on a mismatched switch target',async()=>{const {portfolio,repository}=harness();await portfolio.initialize();const first=portfolio.getSnapshot().directory!.activeProjectId;await portfolio.createProject('B');const old=portfolio.getSnapshot().active!,dispose=vi.spyOn(old,'dispose'),before=portfolio.getSnapshot().directory!.directoryRevision;repository.projects.set(first,envelope('wrong-project'));expect(await portfolio.switchProject(first)).toMatchObject({ok:false,reason:'missing_project'});expect(portfolio.getSnapshot().active).toBe(old);expect(portfolio.getSnapshot().directory).toMatchObject({activeProjectId:old.application.getSnapshot().id,directoryRevision:before});expect(dispose).not.toHaveBeenCalled()})
 it('rejects invalid initialize, create, and project-save writes without mutation',async()=>{const repository=new MemoryProjectPortfolioPersistence(),bad=envelope('workspace-B'),proposed=directory('project-A',['project-A']);await expect(repository.initializePortfolio(proposed,bad)).rejects.toThrow('invalid portfolio initialization');expect(repository.directory).toBeUndefined();const good=envelope('project-A');await repository.initializePortfolio(proposed,good);const before=structuredClone(repository.directory);await expect(repository.createProject({...proposed,directoryRevision:1,activeProjectId:'project-B',projects:[...proposed.projects,metadata('project-B')]},0,envelope('wrong'))).rejects.toThrow('invalid project creation');await expect(repository.compareAndSaveProject('project-A',envelope('wrong'),0)).rejects.toThrow('invalid project binding');expect(repository.directory).toEqual(before);expect(repository.projects).toHaveLength(1)})
 it.each(['create','rename','switch'] as const)('settles %s conflict without retaining an operation',async operation=>{const {portfolio,repository}=harness();await portfolio.initialize();if(operation==='switch')await portfolio.createProject('B');if(operation==='create')vi.spyOn(repository,'createProject').mockResolvedValue({ok:false,reason:'conflict',currentRevision:2});else vi.spyOn(repository,'compareAndSaveDirectory').mockResolvedValue({ok:false,reason:'conflict',currentRevision:2});const result=operation==='create'?await portfolio.createProject('C'):operation==='rename'?await portfolio.renameActiveProject('Renamed'):await portfolio.switchProject(portfolio.getSnapshot().directory!.projects[0]!.id);expect(result).toMatchObject({ok:false,reason:'conflict'});expect(portfolio.getSnapshot()).toMatchObject({status:'conflict',active:{},message:expect.stringMatching(/changed elsewhere/i)});expect(portfolio.getSnapshot().operation).toBeUndefined()})
 it('compares timestamp offsets by instant and preserves their representations',()=>{const equal=directory('a',['a']);equal.projects[0]={...equal.projects[0]!,createdAt:'2026-09-07T12:00:00+02:00',updatedAt:'2026-09-07T10:00:00Z'};expect(parseProjectDirectory(equal)).toMatchObject({ok:true,value:{projects:[{createdAt:'2026-09-07T12:00:00+02:00',updatedAt:'2026-09-07T10:00:00Z'}]}});const earlier=structuredClone(equal);earlier.projects[0]!.updatedAt='2026-09-07T09:59:59Z';expect(parseProjectDirectory(earlier)).toMatchObject({ok:false,reason:'corrupt'})})
 it('does not adopt or remove an orphan workspace',async()=>{const orphan=envelope('orphan'),repository=new MemoryProjectPortfolioPersistence({directory:directory('project-A',['project-A']),projects:[['project-A',envelope('project-A')],['orphan',orphan]]});expect(await repository.loadPortfolio()).toMatchObject({status:'ready',directory:{projects:[{id:'project-A'}]}});expect(repository.projects.get('orphan')).toEqual(orphan)})
})
