import type {SearchRequest} from '../commerce/client/catalog-client'
import type {CatalogProductResult,CatalogSearchResult} from '../commerce/providers/catalog-provider'
import type {ProductCluster,ProviderIdentity,ProviderMessage} from '../commerce/domain/commerce'
import {findByProviderIdentity,providerIdentityKey,sameProviderIdentity} from '../commerce/domain/provider-identity'
import {compareProductEvaluations} from '../comparison/compare-products'
import type {ProductComparison} from '../comparison/domain/product-comparison'
import {evaluateProductAgainstGoal} from '../evaluation/evaluate-product'
import type {ProductEvaluation} from '../evaluation/domain/product-evaluation'
import type {GoalCondition,GoalConditionKind,PurchaseGoal,PurchaseGoalDraft} from '../goals/domain/purchase-goal'
import {createPurchaseGoalDraft,revisePurchaseGoalDraft,validatePurchaseGoal} from '../goals/domain/purchase-goal'
import {createPurchasePlan,type PlanEvaluation,type PurchasePlan} from '../planning/domain/purchase-plan'
import {evaluatePurchasePlan,neutralOffer} from '../planning/evaluate-plan'
import {productEvidenceValues,refreshRetainedProductEvidence,retainProductEvidence,type ProductEvidenceRegistry} from '../planning/product-evidence-registry'
import {addProductToPlan,rebasePlanToGoal,removePlanLine,selectPlanLineOffer,setPlanLineQuantity} from '../planning/mutate-plan'
import type {PlanChangeProposal,ProposalStatus} from '../proposals/domain/plan-change-proposal'
import {applyProposalOperations,approveProposal,createPlanChangeProposal,proposalEffectiveStatus,rejectProposal} from '../proposals/proposal-service'
import {compileDiscoveryStrategy} from '../sourcing/compile-discovery-strategy'
import type {DiscoveryStrategy,EvidenceGap} from '../sourcing/domain/discovery-strategy'

export interface MarketContext{country:string;currency:string;language?:string}
export type DiscoveryMode='exploratory_human'|'active_goal_human'|'agent_sourcing'
export type DiscoveryStatus='idle'|'initial_loading'|'pagination_loading'|'ready'|'empty'|'error'|'stale'
export interface DiscoveryError{code:ApplicationErrorCode;message:string}
export interface DiscoveryWorkspace{
 revision:number;status:DiscoveryStatus;mode:DiscoveryMode;query:string;market:MarketContext;strategy?:DiscoveryStrategy
 goalRevision?:number;criteriaKey?:string;activeRequestId?:string;lastAcceptedRequestId?:string;candidates:ProductCluster[];messages:ProviderMessage[]
 pagination:{cursor?:string;hasMore:boolean;estimatedTotal?:number};error?:DiscoveryError
}
export type ApplicationActivityKind='agent_search'|'agent_proposal_created'|'proposal_rejected'|'proposal_applied'|'proposal_stale'|'read_tool_call'
export interface ApplicationActivity{id:number;timestamp:string;kind:ApplicationActivityKind;toolName:string;outcome:'success'|'failure';summary:string}
export interface CoSourceSessionState{
 id:string;revision:number;market:MarketContext;goalDraft:PurchaseGoalDraft;activeGoal?:PurchaseGoal
 humanDiscovery:DiscoveryWorkspace;agentDiscovery:DiscoveryWorkspace;retainedProducts:ProductCluster[];comparisonIds:ProviderIdentity[]
 plan:PurchasePlan;proposals:PlanChangeProposal[];activities:ApplicationActivity[]
}
export type ApplicationErrorCode='invalid_input'|'invalid_state'|'provider_unavailable'|'provider_throttled'|'evidence_unavailable'|'stale_state'|'invalid_proposal'
export type ApplicationResult<T>={ok:true;value:T}|{ok:false;code:ApplicationErrorCode;message:string}
type ApplicationFailure={ok:false;code:ApplicationErrorCode;message:string}
export interface ExploreCandidatesInput{query:string;cursor?:string;limit?:number}
export interface GoalSourcingInput{cursor?:string;limit?:number}
export interface AgentSourcingInput{query:string;market:MarketContext;cursor?:string;limit?:number;maximumPrice?:SearchRequest['maximumPrice'];condition?:SearchRequest['condition'];attributes?:SearchRequest['attributes']}
export interface SourceCandidatesResult{products:ProductCluster[];messages:ProviderMessage[];pagination:CatalogSearchResult['pagination'];strategy?:DiscoveryStrategy}
export interface CatalogProductInput{identity:ProviderIdentity;market:MarketContext;selectedOptions?:Array<{name:string;value:string}>}
export interface CatalogPort{search(input:SearchRequest):Promise<CatalogSearchResult>;product(input:CatalogProductInput):Promise<CatalogProductResult>}

export interface CoSourceApplication{
 getSnapshot():CoSourceSessionState;subscribe(listener:()=>void):()=>void
 editGoal(changes:Partial<Omit<PurchaseGoalDraft,'state'|'id'|'revision'>>):void
 addGoalCondition(kind:GoalConditionKind):void;editGoalCondition(kind:GoalConditionKind,id:string,changes:Partial<GoalCondition>):void;removeGoalCondition(kind:GoalConditionKind,id:string):void
 compileSourcingPlan():ApplicationResult<DiscoveryStrategy>;searchCandidates(input:ExploreCandidatesInput):Promise<ApplicationResult<SourceCandidatesResult>>;sourceCandidatesForActiveGoal(input?:GoalSourcingInput):Promise<ApplicationResult<SourceCandidatesResult>>;sourceCandidatesForAgent(input:AgentSourcingInput):Promise<ApplicationResult<SourceCandidatesResult>>
 retainCandidate(identity:ProviderIdentity):ApplicationResult<ProductCluster>;inspectCandidate(identity:ProviderIdentity):Promise<ApplicationResult<ProductCluster>>;dismissAgentCandidates():void
 toggleComparison(identity:ProviderIdentity):void;clearComparison():void;evaluateCandidate(identity:ProviderIdentity):ApplicationResult<ProductEvaluation>;compareCandidates(a:ProviderIdentity,b:ProviderIdentity):ApplicationResult<ProductComparison>;getEvidenceGaps(identity?:ProviderIdentity):ApplicationResult<EvidenceGap[]>
 evaluatePurchasePlan():ApplicationResult<PlanEvaluation>;addCandidateToPlan(identity:ProviderIdentity):ApplicationResult<PurchasePlan>;removePlanLine(lineId:string):void;setPlanLineQuantity(lineId:string,quantity:number):void;selectPlanLineOffer(lineId:string,offer?:ProviderIdentity):void;rebasePlan():void
 createPlanProposal(input:unknown):ApplicationResult<PlanChangeProposal>;approvePlanProposal(id:string):ApplicationResult<PurchasePlan|undefined>;rejectPlanProposal(id:string):ApplicationResult<PlanChangeProposal>;reviewPlanProposal(id:string):ApplicationResult<{status:ProposalStatus;before:PlanEvaluation;after?:PlanEvaluation}>
 recordActivity(activity:Omit<ApplicationActivity,'id'|'timestamp'>):void
}

const collectionFor={requirement:'requirements',preference:'preferences',exclusion:'exclusions'} as const
export const MAX_AGENT_CANDIDATES=10
const defaultId=()=>globalThis.crypto?.randomUUID?.()??`cosource-${Date.now()}-${Math.random().toString(36).slice(2)}`
const emptyPagination=()=>({hasMore:false as const})
const workspace=(mode:DiscoveryMode,market:MarketContext):DiscoveryWorkspace=>({revision:0,status:'idle',mode,query:'',market:{...market},candidates:[],messages:[],pagination:emptyPagination()})
const goalMeaning=(goal:PurchaseGoalDraft|PurchaseGoal)=>JSON.stringify({id:goal.id,summary:goal.summary,searchFocus:goal.searchFocus,quantity:goal.quantity,maximumItemPrice:goal.maximumItemPrice,budget:goal.budget,requirements:goal.requirements,preferences:goal.preferences,exclusions:goal.exclusions})
const safeFailure=(error:unknown):ApplicationFailure=>{const item=error as{code?:string;retryAfterSeconds?:number};if(item?.code==='provider_throttled')return{ok:false,code:'provider_throttled',message:`The live catalog is temporarily busy.${item.retryAfterSeconds?` Try again in about ${item.retryAfterSeconds} seconds.`:' Please try again shortly.'}`};return{ok:false,code:'provider_unavailable',message:'Live catalog search is temporarily unavailable. Please try again.'}}

export function createCoSourceApplication(dependencies:{catalog:CatalogPort;market:MarketContext;makeId?:()=>string;now?:()=>string}):CoSourceApplication{
 const makeId=dependencies.makeId??defaultId,now=dependencies.now??(()=>new Date().toISOString()),listeners=new Set<()=>void>()
 const draft=createPurchaseGoalDraft(makeId());let evidence:ProductEvidenceRegistry=new Map(),humanAuthority=0,agentAuthority=0
 let state:CoSourceSessionState={id:makeId(),revision:0,market:{...dependencies.market},goalDraft:draft,humanDiscovery:workspace('exploratory_human',dependencies.market),agentDiscovery:workspace('agent_sourcing',dependencies.market),retainedProducts:[],comparisonIds:[],plan:createPurchasePlan(makeId(),'unvalidated-goal',0),proposals:[],activities:[]}
 const commit=(changes:Partial<Omit<CoSourceSessionState,'revision'>>)=>{const entries=Object.entries(changes) as Array<[keyof CoSourceSessionState,unknown]>;if(entries.every(([key,value])=>Object.is(state[key],value)))return false;state={...state,...changes,revision:state.revision+1};listeners.forEach(listener=>listener());return true}
 const updateWorkspace=(channel:'human'|'agent',changes:Partial<DiscoveryWorkspace>)=>{const key=channel==='human'?'humanDiscovery':'agentDiscovery',current=state[key],next={...current,...changes,revision:current.revision+1};commit({[key]:next});return next}
 const invalidateGoalDiscovery=()=>{const current=state.humanDiscovery;if(current.mode==='active_goal_human'&&(current.status!=='idle'||current.candidates.length>0)){humanAuthority++;updateWorkspace('human',{status:'stale',activeRequestId:undefined,error:{code:'stale_state',message:'The active goal changed; source again against the current goal.'}})}}
 const syncGoal=(nextDraft:PurchaseGoalDraft)=>{if(goalMeaning(nextDraft)===goalMeaning(state.goalDraft))return;const parsed=validatePurchaseGoal(nextDraft),previous=state.activeGoal,meaningChanged=parsed.success&&(!previous||goalMeaning(parsed.data)!==goalMeaning(previous)),nextGoal=meaningChanged?parsed.data:previous;commit({goalDraft:nextDraft,...(nextGoal!==previous?{activeGoal:nextGoal}: {})});if(meaningChanged)invalidateGoalDiscovery()}
 const allProducts=()=>{const map=new Map<string,ProductCluster>();[...state.humanDiscovery.candidates,...state.agentDiscovery.candidates,...state.retainedProducts].forEach(product=>map.set(providerIdentityKey(product.identity),product));return[...map.values()]}
 const locate=(identity:ProviderIdentity)=>findByProviderIdentity(allProducts(),identity)
 const retain=(product:ProductCluster)=>{const next=retainProductEvidence(evidence,product);if(next===evidence)return false;evidence=next;commit({retainedProducts:productEvidenceValues(evidence)});return true}
 const recordActivity:CoSourceApplication['recordActivity']=activity=>commit({activities:[{...activity,id:(state.activities[0]?.id??0)+1,timestamp:now()},...state.activities].slice(0,20)})
 const compileActive=():ApplicationResult<DiscoveryStrategy>=>{if(!state.activeGoal)return{ok:false,code:'invalid_state',message:'A validated purchase goal is required.'};try{return{ok:true,value:compileDiscoveryStrategy(state.activeGoal,state.market)}}catch{return{ok:false,code:'invalid_input',message:'A product being sourced is required.'}}}
 const sameMarket=(market:MarketContext)=>market.country===state.market.country&&market.currency===state.market.currency&&(market.language??state.market.language)===state.market.language
 const stale=(message:string):ApplicationResult<never>=>({ok:false,code:'stale_state',message})
 async function runDiscovery(channel:'human'|'agent',input:{query:string;mode:DiscoveryMode;strategy?:DiscoveryStrategy;goalRevision?:number;cursor?:string;limit?:number;maximumPrice?:SearchRequest['maximumPrice'];condition?:SearchRequest['condition'];attributes?:SearchRequest['attributes']}):Promise<ApplicationResult<SourceCandidatesResult>>{
  const query=input.query.trim(),current=channel==='human'?state.humanDiscovery:state.agentDiscovery,criteriaKey=JSON.stringify({query,mode:input.mode,goalRevision:input.goalRevision,strategy:input.strategy?.constraints,maximumPrice:input.maximumPrice,condition:input.condition,attributes:input.attributes,limit:input.limit??6})
  if(!query)return{ok:false,code:'invalid_input',message:'Enter a product to search for.'}
  const pagination=Boolean(input.cursor)
  if(pagination&&(current.mode!==input.mode||current.query!==query||current.criteriaKey!==criteriaKey||current.pagination.cursor!==input.cursor||!current.pagination.hasMore||current.status!=='ready'))return{ok:false,code:'invalid_input',message:'Pagination does not belong to the current discovery workspace.'}
  const agentRemaining=channel==='agent'?(pagination?MAX_AGENT_CANDIDATES-current.candidates.length:MAX_AGENT_CANDIDATES):Number.POSITIVE_INFINITY
  if(channel==='agent'&&pagination&&agentRemaining<=0)return{ok:false,code:'invalid_input',message:'The agent discovery workspace already contains its maximum candidates.'}
  const authority=channel==='human'?++humanAuthority:++agentAuthority,requestId=makeId(),loading:DiscoveryStatus=pagination?'pagination_loading':'initial_loading'
  updateWorkspace(channel,{status:loading,mode:input.mode,query,market:{...state.market},strategy:input.strategy,goalRevision:input.goalRevision,criteriaKey,activeRequestId:requestId,error:undefined,...(!pagination?{candidates:[],messages:[],pagination:emptyPagination(),lastAcceptedRequestId:undefined}: {})})
  const request:SearchRequest={query,country:state.market.country,currency:state.market.currency,intent:input.strategy?.humanIntent,limit:channel==='agent'?Math.min(input.limit??6,agentRemaining):input.limit??6,cursor:input.cursor,available:input.strategy?.constraints.available??(channel==='agent'?true:undefined),shipsTo:input.strategy?.constraints.shipsToCountry??(channel==='agent'?state.market.country:undefined),maximumPrice:input.strategy?.constraints.maximumPrice??input.maximumPrice,condition:input.strategy?.constraints.condition??input.condition,attributes:input.strategy?.constraints.attributes??input.attributes,view:input.strategy||channel==='agent'?'offer':undefined}
  try{const result=await dependencies.catalog.search(request),stillCurrent=(channel==='human'?humanAuthority:agentAuthority)===authority,live=channel==='human'?state.humanDiscovery:state.agentDiscovery;if(!stillCurrent||live.activeRequestId!==requestId||input.goalRevision!==undefined&&state.activeGoal?.revision!==input.goalRevision)return stale('A newer discovery state superseded this response.');const acceptedLimit=channel==='agent'?(pagination?Math.max(0,MAX_AGENT_CANDIDATES-live.candidates.length):MAX_AGENT_CANDIDATES):result.products.length,products=result.products.slice(0,acceptedLimit),previousEvidence=evidence;evidence=refreshRetainedProductEvidence(evidence,products);const candidates=pagination?[...live.candidates,...products]:products,boundReached=channel==='agent'&&candidates.length>=MAX_AGENT_CANDIDATES,canonicalPagination=boundReached?emptyPagination():result.pagination,status:DiscoveryStatus=candidates.length===0?'empty':'ready';updateWorkspace(channel,{status,candidates,messages:result.messages.slice(0,20),pagination:canonicalPagination,activeRequestId:undefined,lastAcceptedRequestId:requestId,error:undefined});if(evidence!==previousEvidence)commit({retainedProducts:productEvidenceValues(evidence)});return{ok:true,value:{products,messages:result.messages,pagination:canonicalPagination,strategy:input.strategy}}}catch(error){const failure=safeFailure(error),stillCurrent=(channel==='human'?humanAuthority:agentAuthority)===authority,live=channel==='human'?state.humanDiscovery:state.agentDiscovery;if(!stillCurrent||live.activeRequestId!==requestId)return stale('A newer discovery state superseded this failure.');updateWorkspace(channel,{status:'error',activeRequestId:undefined,error:{code:failure.code,message:failure.message}});return failure}
 }
 const mutatePlan=(next:PurchasePlan)=>{if(next!==state.plan)commit({plan:next})}
 const application:CoSourceApplication={
  getSnapshot:()=>state,subscribe:listener=>{listeners.add(listener);return()=>listeners.delete(listener)},
  editGoal:changes=>{const candidate={...state.goalDraft,...changes};if(goalMeaning(candidate)===goalMeaning(state.goalDraft))return;syncGoal(revisePurchaseGoalDraft(state.goalDraft,changes))},
  addGoalCondition:kind=>{const key=collectionFor[kind];syncGoal(revisePurchaseGoalDraft(state.goalDraft,{[key]:[...state.goalDraft[key],{id:makeId(),operator:'free_text',value:''}]}))},
  editGoalCondition:(kind,id,changes)=>{const key=collectionFor[kind],items=state.goalDraft[key],target=items.find(item=>item.id===id);if(!target||Object.entries(changes).every(([key,value])=>Object.is(target[key as keyof GoalCondition],value)))return;syncGoal(revisePurchaseGoalDraft(state.goalDraft,{[key]:items.map(item=>item.id===id?{...item,...changes}:item)}))},
  removeGoalCondition:(kind,id)=>{const key=collectionFor[kind];if(!state.goalDraft[key].some(item=>item.id===id))return;syncGoal(revisePurchaseGoalDraft(state.goalDraft,{[key]:state.goalDraft[key].filter(item=>item.id!==id)}))},
  compileSourcingPlan:()=>compileActive(),
  searchCandidates:input=>runDiscovery('human',{...input,mode:'exploratory_human'}),
  sourceCandidatesForActiveGoal:(input={})=>{const result=compileActive();return result.ok?runDiscovery('human',{query:result.value.query,mode:'active_goal_human',strategy:result.value,goalRevision:result.value.goalRevision,...input}):Promise.resolve(result)},
  sourceCandidatesForAgent:async input=>{if(!sameMarket(input.market)){const failure={ok:false,code:'invalid_input',message:`Agent searches must use the active ${state.market.country} / ${state.market.currency} market.`} as const;recordActivity({kind:'agent_search',toolName:'search_products',outcome:'failure',summary:failure.message});return failure}const result=await runDiscovery('agent',{...input,mode:'agent_sourcing'});recordActivity({kind:'agent_search',toolName:'search_products',outcome:result.ok?'success':'failure',summary:result.ok?`Real commerce search returned ${result.value.products.length} candidate${result.value.products.length===1?'':'s'}.`:result.message});return result},
  retainCandidate:identity=>{const product=locate(identity);if(!product)return{ok:false,code:'evidence_unavailable',message:'Candidate evidence is unavailable.'};retain(product);return{ok:true,value:product}},
  async inspectCandidate(identity){const product=locate(identity);if(!product)return{ok:false,code:'evidence_unavailable',message:'Candidate evidence is unavailable.'};retain(product);try{const result=await dependencies.catalog.product({identity,market:state.market}),detailed=result.product;if(!sameProviderIdentity(identity,detailed.identity))return{ok:false,code:'evidence_unavailable',message:'Provider returned a different product identity.'};evidence=retainProductEvidence(evidence,detailed);const refresh=(current:DiscoveryWorkspace)=>current.candidates.some(item=>sameProviderIdentity(item.identity,identity))?{...current,candidates:current.candidates.map(item=>sameProviderIdentity(item.identity,identity)?detailed:item),revision:current.revision+1}:current;commit({humanDiscovery:refresh(state.humanDiscovery),agentDiscovery:refresh(state.agentDiscovery),retainedProducts:productEvidenceValues(evidence)});return{ok:true,value:detailed}}catch(error){return safeFailure(error)}},
  dismissAgentCandidates:()=>{agentAuthority++;const current=state.agentDiscovery;if(current.status==='idle'&&current.candidates.length===0)return;updateWorkspace('agent',{status:'idle',query:'',criteriaKey:undefined,activeRequestId:undefined,lastAcceptedRequestId:undefined,candidates:[],messages:[],pagination:emptyPagination(),error:undefined,strategy:undefined,goalRevision:undefined})},
  toggleComparison:identity=>{const selected=state.comparisonIds.some(item=>sameProviderIdentity(item,identity));if(!selected){const product=locate(identity);if(product)retain(product)}const next=selected?state.comparisonIds.filter(item=>!sameProviderIdentity(item,identity)):state.comparisonIds.length<2?[...state.comparisonIds,identity]:[state.comparisonIds[1]!,identity];commit({comparisonIds:next})},clearComparison:()=>{if(state.comparisonIds.length)commit({comparisonIds:[]})},
  evaluateCandidate:identity=>{if(!state.activeGoal)return{ok:false,code:'invalid_state',message:'A validated purchase goal is required.'};const product=findByProviderIdentity(state.retainedProducts,identity);return product?{ok:true,value:evaluateProductAgainstGoal(state.activeGoal,product,neutralOffer(product))}:{ok:false,code:'evidence_unavailable',message:'Product must be retained first.'}},
  compareCandidates:(a,b)=>{const first=application.evaluateCandidate(a),second=application.evaluateCandidate(b);if(!first.ok||!second.ok)return{ok:false,code:'evidence_unavailable',message:'Both products must have retained evidence.'};const pa=findByProviderIdentity(state.retainedProducts,a)!,pb=findByProviderIdentity(state.retainedProducts,b)!;return{ok:true,value:compareProductEvaluations({product:a,title:pa.title.value,evaluation:first.value},{product:b,title:pb.title.value,evaluation:second.value})}},
  getEvidenceGaps:identity=>{const strategy=compileActive();if(!strategy.ok)return strategy;const gaps=[...strategy.value.evidenceGaps];if(identity){const evaluation=application.evaluateCandidate(identity);if(!evaluation.ok)return evaluation;for(const item of [...evaluation.value.requirements,...evaluation.value.preferences].filter(item=>item.status==='unknown'))if(!gaps.some(gap=>gap.goalConditionId===item.conditionId))gaps.push({goalConditionId:item.conditionId,description:item.condition.value||item.condition.field||'Condition',reason:item.reason,resolution:'search_for_stronger_evidence',relevance:item.kind==='preference'?'preference':'mandatory'})}return{ok:true,value:gaps}},
  evaluatePurchasePlan:()=>state.activeGoal?{ok:true,value:evaluatePurchasePlan(state.activeGoal,state.plan,state.retainedProducts)}:{ok:false,code:'invalid_state',message:'A validated purchase goal is required.'},
  addCandidateToPlan:identity=>{const product=locate(identity);if(!product)return{ok:false,code:'evidence_unavailable',message:'Candidate evidence is unavailable.'};if(!state.activeGoal)return{ok:false,code:'invalid_state',message:'A validated purchase goal is required.'};retain(product);const base=state.plan.lines.length===0?{...state.plan,goalId:state.activeGoal.id,goalRevision:state.activeGoal.revision}:state.plan,plan=addProductToPlan(base,product,makeId());mutatePlan(plan);return{ok:true,value:plan}},
  removePlanLine:lineId=>mutatePlan(removePlanLine(state.plan,lineId)),setPlanLineQuantity:(lineId,quantity)=>mutatePlan(setPlanLineQuantity(state.plan,lineId,quantity)),selectPlanLineOffer:(lineId,offer)=>mutatePlan(selectPlanLineOffer(state.plan,lineId,offer,state.retainedProducts)),rebasePlan:()=>{if(state.activeGoal)mutatePlan(rebasePlanToGoal(state.plan,state.activeGoal.id,state.activeGoal.revision))},
  createPlanProposal:input=>{const result=createPlanChangeProposal(input,{goal:state.activeGoal,plan:state.plan,retainedProducts:state.retainedProducts},makeId,now);if(!result.ok){recordActivity({kind:result.code==='stale_revision'?'proposal_stale':'agent_proposal_created',toolName:'propose_plan_changes',outcome:'failure',summary:result.message});return{ok:false,code:result.code==='stale_revision'?'stale_state':'invalid_proposal',message:result.message}}commit({proposals:[result.proposal,...state.proposals].slice(0,20)});recordActivity({kind:'agent_proposal_created',toolName:'propose_plan_changes',outcome:'success',summary:`Agent proposal ${result.proposal.id} created for human review.`});return{ok:true,value:result.proposal}},
  approvePlanProposal:id=>{const proposal=state.proposals.find(item=>item.id===id);if(!proposal){const failure={ok:false,code:'invalid_proposal',message:'Proposal was not found.'} as const;recordActivity({kind:'proposal_applied',toolName:'human_approve_and_apply',outcome:'failure',summary:failure.message});return failure}const before=state.plan.revision,result=approveProposal(proposal,{goal:state.activeGoal,plan:state.plan,retainedProducts:state.retainedProducts},now);const plan=result.plan&&result.plan.lines.length>0&&state.plan.lines.length===0&&state.activeGoal?{...result.plan,goalId:state.activeGoal.id,goalRevision:state.activeGoal.revision}:result.plan;commit({proposals:state.proposals.map(item=>item.id===id?result.proposal:item),...(plan?{plan}: {})});const applied=Boolean(plan),staleStatus=result.proposal.status==='stale';recordActivity({kind:staleStatus?'proposal_stale':'proposal_applied',toolName:'human_approve_and_apply',outcome:applied?'success':'failure',summary:applied?`Agent-proposed changes were approved and applied. Revision ${before} → ${plan!.revision}.`:result.proposal.error??'Proposal was not applied.'});return{ok:true,value:plan}},
  rejectPlanProposal:id=>{const proposal=state.proposals.find(item=>item.id===id);if(!proposal){const failure={ok:false,code:'invalid_proposal',message:'Proposal was not found.'} as const;recordActivity({kind:'proposal_rejected',toolName:'human_reject',outcome:'failure',summary:failure.message});return failure}const rejected=rejectProposal(proposal,now),didReject=rejected!==proposal;if(didReject)commit({proposals:state.proposals.map(item=>item.id===id?rejected:item)});recordActivity({kind:'proposal_rejected',toolName:'human_reject',outcome:didReject?'success':'failure',summary:didReject?'Agent proposal rejected by the human; plan unchanged.':'Proposal was not pending and could not be rejected.'});return{ok:true,value:rejected}},
  reviewPlanProposal:id=>{const proposal=state.proposals.find(item=>item.id===id);if(!proposal||!state.activeGoal)return{ok:false,code:'invalid_proposal',message:'Proposal or validated goal is unavailable.'};const proposalState={goal:state.activeGoal,plan:state.plan,retainedProducts:state.retainedProducts},status=proposalEffectiveStatus(proposal,proposalState),before=evaluatePurchasePlan(state.activeGoal,state.plan,state.retainedProducts),preview=status==='pending'?applyProposalOperations(proposal,proposalState):undefined;return{ok:true,value:{status,before,after:preview?.ok?evaluatePurchasePlan(state.activeGoal,preview.plan,state.retainedProducts):undefined}}},recordActivity,
 }
 return application
}

export function proposalStatus(application:CoSourceApplication,proposal:PlanChangeProposal){const state=application.getSnapshot();return proposalEffectiveStatus(proposal,{goal:state.activeGoal,plan:state.plan,retainedProducts:state.retainedProducts})}
