import type {SearchRequest} from '../commerce/client/catalog-client'
import type {CatalogProductResult,CatalogSearchResult} from '../commerce/providers/catalog-provider'
import type {ProductCluster,ProviderIdentity,ProviderMessage} from '../commerce/domain/commerce'
import {findByProviderIdentity,providerIdentityKey,sameProviderIdentity} from '../commerce/domain/provider-identity'
import {compareProductEvaluations} from '../comparison/compare-products'
import type {ProductComparison} from '../comparison/domain/product-comparison'
import {evaluateProductAgainstGoal} from '../evaluation/evaluate-product'
import type {ProductEvaluation} from '../evaluation/domain/product-evaluation'
import type {GoalCondition,GoalConditionKind,PurchaseGoal,PurchaseGoalDraft} from '../goals/domain/purchase-goal'
import {createPurchaseGoalDraft,revisePurchaseGoalDraft,validatePurchaseGoal} from '../goals/domain/purchase-goal'
import type {GoalInterpretationEffectiveStatus,GoalInterpretationProposal} from '../goals/domain/goal-interpretation-proposal'
import {goalInterpretationInputSchema,proposalEffectiveStatus as interpretationEffectiveStatus} from '../goals/domain/goal-interpretation-proposal'
import {createPurchasePlan,type PlanEvaluation,type PurchasePlan} from '../planning/domain/purchase-plan'
import {evaluatePurchasePlan,neutralOffer} from '../planning/evaluate-plan'
import {assessEvidenceFreshness} from '../evidence/domain/evidence'
import {findProductEvidence,observeProductEvidence,productEvidenceEntries,productEvidenceValues,retainProductEvidence,type ProductEvidenceEntry,type ProductEvidenceLedger} from '../evidence/product-evidence-ledger'
import {addProductToPlan,rebasePlanToGoal,removePlanLine,selectPlanLineOffer,setPlanLineQuantity} from '../planning/mutate-plan'
import type {PlanChangeProposal,ProposalStatus} from '../proposals/domain/plan-change-proposal'
import {applyProposalOperations,approveProposal,createPlanChangeProposal,proposalEffectiveStatus,rejectProposal} from '../proposals/proposal-service'
import {compileDiscoveryStrategy} from '../sourcing/compile-discovery-strategy'
import type {DiscoveryStrategy,EvidenceGap} from '../sourcing/domain/discovery-strategy'
import {projectPurchaseGoalToResourceRequirement,type ResourceRequirement} from '../requirements'

export interface MarketContext{country:string;currency:string;language?:string}
export type DiscoveryMode='exploratory_human'|'active_goal_human'|'agent_sourcing'
export type DiscoveryStatus='idle'|'initial_loading'|'pagination_loading'|'ready'|'empty'|'error'|'stale'
export interface DiscoveryError{code:ApplicationErrorCode;message:string}
export interface EvidenceRefreshState{status:'idle'|'loading'|'success'|'error';requestId?:string;error?:DiscoveryError}
export interface DiscoveryWorkspace{
 revision:number;status:DiscoveryStatus;mode:DiscoveryMode;query:string;market:MarketContext;strategy?:DiscoveryStrategy
 goalRevision?:number;criteriaKey?:string;activeRequestId?:string;lastAcceptedRequestId?:string;candidates:ProductCluster[];messages:ProviderMessage[]
 pagination:{cursor?:string;hasMore:boolean;estimatedTotal?:number};error?:DiscoveryError
}
export type ApplicationActivityKind='agent_search'|'agent_proposal_created'|'proposal_rejected'|'proposal_applied'|'proposal_stale'|'interpretation_submitted'|'interpretation_rejected'|'interpretation_adopted'|'goal_committed'|'read_tool_call'
export interface ApplicationActivity{id:number;timestamp:string;kind:ApplicationActivityKind;toolName:string;outcome:'success'|'failure';summary:string}
export interface CoSourceSessionState{
 id:string;revision:number;market:MarketContext;goalDraft:PurchaseGoalDraft;activeGoal?:PurchaseGoal
 humanDiscovery:DiscoveryWorkspace;agentDiscovery:DiscoveryWorkspace;retainedProducts:ProductCluster[];retainedEvidence:ProductEvidenceEntry[];evidenceRefresh:Record<string,EvidenceRefreshState>;comparisonIds:ProviderIdentity[]
 plan:PurchasePlan;proposals:PlanChangeProposal[];goalInterpretationProposals:GoalInterpretationProposal[];activities:ApplicationActivity[]
}
export type ApplicationErrorCode='invalid_input'|'invalid_state'|'provider_unavailable'|'provider_throttled'|'evidence_unavailable'|'stale_state'|'invalid_proposal'
export type ApplicationResult<T>={ok:true;value:T}|{ok:false;code:ApplicationErrorCode;message:string}
export type GoalCommitmentStatus='no_active_goal'|'committed'|'uncommitted_changes'
type ApplicationFailure={ok:false;code:ApplicationErrorCode;message:string}
export interface ExploreCandidatesInput{query:string;cursor?:string;limit?:number}
export interface GoalSourcingInput{cursor?:string;limit?:number}
export interface AgentSourcingInput{query:string;market:MarketContext;cursor?:string;limit?:number;maximumPrice?:SearchRequest['maximumPrice'];condition?:SearchRequest['condition'];attributes?:SearchRequest['attributes']}
export interface SourceCandidatesResult{products:ProductCluster[];messages:ProviderMessage[];pagination:CatalogSearchResult['pagination'];strategy?:DiscoveryStrategy}
export interface CatalogProductInput{identity:ProviderIdentity;market:MarketContext;selectedOptions?:Array<{name:string;value:string}>}
export interface CatalogPort{search(input:SearchRequest):Promise<CatalogSearchResult>;product(input:CatalogProductInput):Promise<CatalogProductResult>}

export interface CoSourceApplication{
 getSnapshot():CoSourceSessionState;subscribe(listener:()=>void):()=>void
 editGoal(changes:Partial<Omit<PurchaseGoalDraft,'state'|'id'|'revision'>>):void
 addGoalCondition(kind:GoalConditionKind):void;editGoalCondition(kind:GoalConditionKind,id:string,changes:Partial<GoalCondition>):void;removeGoalCondition(kind:GoalConditionKind,id:string):void
 commitGoalDraft():ApplicationResult<PurchaseGoal>;getGoalCommitmentStatus():GoalCommitmentStatus;submitGoalInterpretation(input:unknown):ApplicationResult<GoalInterpretationProposal>;rejectGoalInterpretation(id:string):ApplicationResult<GoalInterpretationProposal>;adoptGoalInterpretation(id:string):ApplicationResult<PurchaseGoalDraft>;getGoalInterpretationStatus(id:string):GoalInterpretationEffectiveStatus|undefined
 getActiveResourceRequirement():ApplicationResult<ResourceRequirement>
 compileSourcingPlan():ApplicationResult<DiscoveryStrategy>;searchCandidates(input:ExploreCandidatesInput):Promise<ApplicationResult<SourceCandidatesResult>>;sourceCandidatesForActiveGoal(input?:GoalSourcingInput):Promise<ApplicationResult<SourceCandidatesResult>>;sourceCandidatesForAgent(input:AgentSourcingInput):Promise<ApplicationResult<SourceCandidatesResult>>
 retainCandidate(identity:ProviderIdentity):ApplicationResult<ProductCluster>;inspectCandidate(identity:ProviderIdentity):Promise<ApplicationResult<ProductCluster>>;refreshRetainedEvidence(identity:ProviderIdentity):Promise<ApplicationResult<ProductEvidenceEntry>>;dismissAgentCandidates():void
 toggleComparison(identity:ProviderIdentity):void;clearComparison():void;evaluateCandidate(identity:ProviderIdentity):ApplicationResult<ProductEvaluation>;compareCandidates(a:ProviderIdentity,b:ProviderIdentity):ApplicationResult<ProductComparison>;getEvidenceGaps(identity?:ProviderIdentity):ApplicationResult<EvidenceGap[]>
 evaluatePurchasePlan():ApplicationResult<PlanEvaluation>;addCandidateToPlan(identity:ProviderIdentity):ApplicationResult<PurchasePlan>;removePlanLine(lineId:string):void;setPlanLineQuantity(lineId:string,quantity:number):void;selectPlanLineOffer(lineId:string,offer?:ProviderIdentity):void;rebasePlan():void
 createPlanProposal(input:unknown):ApplicationResult<PlanChangeProposal>;approvePlanProposal(id:string):ApplicationResult<PurchasePlan|undefined>;rejectPlanProposal(id:string):ApplicationResult<PlanChangeProposal>;reviewPlanProposal(id:string):ApplicationResult<{status:ProposalStatus;before:PlanEvaluation;after?:PlanEvaluation}>
 recordActivity(activity:Omit<ApplicationActivity,'id'|'timestamp'>):void
}

const collectionFor={requirement:'requirements',preference:'preferences',exclusion:'exclusions'} as const
export const MAX_AGENT_CANDIDATES=10
const defaultId=()=>globalThis.crypto?.randomUUID?.()??`cosource-${Date.now()}-${Math.random().toString(36).slice(2)}`
const emptyPagination=()=>({hasMore:false as const})
const workspace=(mode:DiscoveryMode,market:MarketContext):DiscoveryWorkspace=>({revision:0,status:'idle',mode,query:'',market:{...market},candidates:[],messages:[],pagination:emptyPagination()})
const goalMeaning=(goal:PurchaseGoalDraft|PurchaseGoal)=>JSON.stringify({id:goal.id,summary:goal.summary,searchFocus:goal.searchFocus,quantity:goal.quantity,maximumItemPrice:goal.maximumItemPrice,budget:goal.budget,requirements:goal.requirements,preferences:goal.preferences,exclusions:goal.exclusions})
const safeFailure=(error:unknown):ApplicationFailure=>{const item=error as{code?:string;retryAfterSeconds?:number};if(item?.code==='provider_throttled')return{ok:false,code:'provider_throttled',message:`The live catalog is temporarily busy.${item.retryAfterSeconds?` Try again in about ${item.retryAfterSeconds} seconds.`:' Please try again shortly.'}`};return{ok:false,code:'provider_unavailable',message:'Live catalog search is temporarily unavailable. Please try again.'}}

export function createCoSourceApplication(dependencies:{catalog:CatalogPort;market:MarketContext;makeId?:()=>string;now?:()=>string}):CoSourceApplication{
 const makeId=dependencies.makeId??defaultId,now=dependencies.now??(()=>new Date().toISOString()),listeners=new Set<()=>void>()
 const draft=createPurchaseGoalDraft(makeId());let evidence:ProductEvidenceLedger=new Map(),humanAuthority=0,agentAuthority=0;const refreshAuthority=new Map<string,number>()
 let state:CoSourceSessionState={id:makeId(),revision:0,market:{...dependencies.market},goalDraft:draft,humanDiscovery:workspace('exploratory_human',dependencies.market),agentDiscovery:workspace('agent_sourcing',dependencies.market),retainedProducts:[],retainedEvidence:[],evidenceRefresh:{},comparisonIds:[],plan:createPurchasePlan(makeId(),'unvalidated-goal',0),proposals:[],goalInterpretationProposals:[],activities:[]}
 const commit=(changes:Partial<Omit<CoSourceSessionState,'revision'>>)=>{const entries=Object.entries(changes) as Array<[keyof CoSourceSessionState,unknown]>;if(entries.every(([key,value])=>Object.is(state[key],value)))return false;state={...state,...changes,revision:state.revision+1};listeners.forEach(listener=>listener());return true}
 const updateWorkspace=(channel:'human'|'agent',changes:Partial<DiscoveryWorkspace>)=>{const key=channel==='human'?'humanDiscovery':'agentDiscovery',current=state[key],next={...current,...changes,revision:current.revision+1};commit({[key]:next});return next}
 const invalidateGoalDiscovery=()=>{const current=state.humanDiscovery;if(current.mode==='active_goal_human'&&(current.status!=='idle'||current.candidates.length>0)){humanAuthority++;updateWorkspace('human',{status:'stale',activeRequestId:undefined,error:{code:'stale_state',message:'The active goal changed; source again against the current goal.'}})}}
 const syncDraft=(nextDraft:PurchaseGoalDraft)=>{if(goalMeaning(nextDraft)===goalMeaning(state.goalDraft))return;commit({goalDraft:nextDraft})}
 const allProducts=()=>{const map=new Map<string,ProductCluster>();[...state.humanDiscovery.candidates,...state.agentDiscovery.candidates,...state.retainedProducts].forEach(product=>map.set(providerIdentityKey(product.identity),product));return[...map.values()]}
 const locate=(identity:ProviderIdentity)=>findByProviderIdentity(allProducts(),identity)
 const publishEvidence=()=>commit({retainedProducts:productEvidenceValues(evidence),retainedEvidence:productEvidenceEntries(evidence)})
 const retain=(product:ProductCluster)=>{const result=retainProductEvidence(evidence,product,now(),makeId());if(result.ok&&result.ledger!==evidence){evidence=result.ledger;publishEvidence()}return result}
 const setRefresh=(identity:ProviderIdentity,value:EvidenceRefreshState)=>commit({evidenceRefresh:{...state.evidenceRefresh,[providerIdentityKey(identity)]:value}})
 const beginRefresh=(identity:ProviderIdentity)=>{const key=providerIdentityKey(identity),authority=(refreshAuthority.get(key)??0)+1,requestId=makeId();refreshAuthority.set(key,authority);setRefresh(identity,{status:'loading',requestId});return{key,authority,requestId}}
 const recordActivity:CoSourceApplication['recordActivity']=activity=>commit({activities:[{...activity,id:(state.activities[0]?.id??0)+1,timestamp:now()},...state.activities].slice(0,20)})
 const compileActive=():ApplicationResult<DiscoveryStrategy>=>{if(!state.activeGoal)return{ok:false,code:'invalid_state',message:'A validated purchase goal is required.'};try{return{ok:true,value:compileDiscoveryStrategy(state.activeGoal,state.market)}}catch{return{ok:false,code:'invalid_input',message:'A product being sourced is required.'}}}
 const evaluatePlan=(plan=state.plan)=>{const goal=state.activeGoal!;const requirement=projectPurchaseGoalToResourceRequirement(goal,{market:state.market,workspaceId:state.id});return evaluatePurchasePlan(goal,plan,state.retainedProducts,state.retainedEvidence,now(),requirement.evidenceFreshness)}
 const sameMarket=(market:MarketContext)=>market.country===state.market.country&&market.currency===state.market.currency&&(market.language??state.market.language)===state.market.language
 const stale=(message:string):ApplicationResult<never>=>({ok:false,code:'stale_state',message})
 async function runDiscovery(channel:'human'|'agent',input:{query:string;mode:DiscoveryMode;strategy?:DiscoveryStrategy;goalRevision?:number;cursor?:string;limit?:number;maximumPrice?:SearchRequest['maximumPrice'];condition?:SearchRequest['condition'];attributes?:SearchRequest['attributes']}):Promise<ApplicationResult<SourceCandidatesResult>>{
  const query=input.query.trim(),current=channel==='human'?state.humanDiscovery:state.agentDiscovery,criteriaKey=JSON.stringify({query,mode:input.mode,goalRevision:input.goalRevision,strategy:input.strategy?.constraints,maximumPrice:input.maximumPrice,condition:input.condition,attributes:input.attributes,limit:input.limit??6})
  if(!query)return{ok:false,code:'invalid_input',message:'Enter a product to search for.'}
  const pagination=Boolean(input.cursor)
  if(pagination&&(current.mode!==input.mode||current.query!==query||current.criteriaKey!==criteriaKey||current.pagination.cursor!==input.cursor||!current.pagination.hasMore||current.status!=='ready'))return{ok:false,code:'invalid_input',message:'Pagination does not belong to the current discovery workspace.'}
  const agentRemaining=channel==='agent'?(pagination?MAX_AGENT_CANDIDATES-current.candidates.length:MAX_AGENT_CANDIDATES):Number.POSITIVE_INFINITY
  if(channel==='agent'&&pagination&&agentRemaining<=0)return{ok:false,code:'invalid_input',message:'The agent discovery workspace already contains its maximum candidates.'}
  const authority=channel==='human'?++humanAuthority:++agentAuthority,requestId=makeId(),loading:DiscoveryStatus=pagination?'pagination_loading':'initial_loading'
  updateWorkspace(channel,{status:loading,mode:input.mode,query,market:{...state.market},strategy:input.strategy,goalRevision:input.goalRevision,criteriaKey,activeRequestId:requestId,error:undefined,...(!pagination?{candidates:[],messages:[],pagination:emptyPagination(),lastAcceptedRequestId:undefined}: {})})
  const request:SearchRequest={query,country:state.market.country,currency:state.market.currency,intent:input.strategy?.humanIntent,limit:channel==='agent'?Math.min(input.limit??6,agentRemaining):input.limit??6,cursor:input.cursor,available:input.strategy?.constraints.available??(channel==='agent'?true:undefined),shipsTo:input.strategy?.constraints.shipsToCountry??(channel==='agent'?state.market.country:undefined),maximumPrice:input.strategy?.constraints.maximumPrice??input.maximumPrice,condition:input.strategy?.constraints.condition??input.condition,attributes:input.strategy?.constraints.attributes??input.attributes,view:input.strategy||channel==='agent'?'offer':undefined}
  try{const result=await dependencies.catalog.search(request),stillCurrent=(channel==='human'?humanAuthority:agentAuthority)===authority,live=channel==='human'?state.humanDiscovery:state.agentDiscovery;if(!stillCurrent||live.activeRequestId!==requestId||input.goalRevision!==undefined&&state.activeGoal?.revision!==input.goalRevision)return stale('A newer discovery state superseded this response.');const acceptedLimit=channel==='agent'?(pagination?Math.max(0,MAX_AGENT_CANDIDATES-live.candidates.length):MAX_AGENT_CANDIDATES):result.products.length,products=result.products.slice(0,acceptedLimit),candidates=pagination?[...live.candidates,...products]:products,boundReached=channel==='agent'&&candidates.length>=MAX_AGENT_CANDIDATES,canonicalPagination=boundReached?emptyPagination():result.pagination,status:DiscoveryStatus=candidates.length===0?'empty':'ready';updateWorkspace(channel,{status,candidates,messages:result.messages.slice(0,20),pagination:canonicalPagination,activeRequestId:undefined,lastAcceptedRequestId:requestId,error:undefined});return{ok:true,value:{products,messages:result.messages,pagination:canonicalPagination,strategy:input.strategy}}}catch(error){const failure=safeFailure(error),stillCurrent=(channel==='human'?humanAuthority:agentAuthority)===authority,live=channel==='human'?state.humanDiscovery:state.agentDiscovery;if(!stillCurrent||live.activeRequestId!==requestId)return stale('A newer discovery state superseded this failure.');updateWorkspace(channel,{status:'error',activeRequestId:undefined,error:{code:failure.code,message:failure.message}});return failure}
 }
 const mutatePlan=(next:PurchasePlan)=>{if(next!==state.plan)commit({plan:next})}
 const application:CoSourceApplication={
  getSnapshot:()=>state,subscribe:listener=>{listeners.add(listener);return()=>listeners.delete(listener)},
  editGoal:changes=>{const candidate={...state.goalDraft,...changes};if(goalMeaning(candidate)===goalMeaning(state.goalDraft))return;syncDraft(revisePurchaseGoalDraft(state.goalDraft,changes))},
  addGoalCondition:kind=>{const key=collectionFor[kind];syncDraft(revisePurchaseGoalDraft(state.goalDraft,{[key]:[...state.goalDraft[key],{id:makeId(),operator:'free_text',value:''}]}))},
  editGoalCondition:(kind,id,changes)=>{const key=collectionFor[kind],items=state.goalDraft[key],target=items.find(item=>item.id===id);if(!target||Object.entries(changes).every(([key,value])=>Object.is(target[key as keyof GoalCondition],value)))return;syncDraft(revisePurchaseGoalDraft(state.goalDraft,{[key]:items.map(item=>item.id===id?{...item,...changes}:item)}))},
  removeGoalCondition:(kind,id)=>{const key=collectionFor[kind];if(!state.goalDraft[key].some(item=>item.id===id))return;syncDraft(revisePurchaseGoalDraft(state.goalDraft,{[key]:state.goalDraft[key].filter(item=>item.id!==id)}))},
  commitGoalDraft:()=>{const parsed=validatePurchaseGoal(state.goalDraft);if(!parsed.success){const failure={ok:false,code:'invalid_input',message:'Complete a valid goal before committing it.'} as const;recordActivity({kind:'goal_committed',toolName:'human_commit_goal',outcome:'failure',summary:failure.message});return failure}const previous=state.activeGoal;if(previous&&goalMeaning(previous)===goalMeaning(parsed.data)){recordActivity({kind:'goal_committed',toolName:'human_commit_goal',outcome:'success',summary:'The committed goal already matches the active goal.'});return{ok:true,value:previous}}const active={...parsed.data,revision:previous?previous.revision+1:parsed.data.revision};commit({activeGoal:active});invalidateGoalDiscovery();recordActivity({kind:'goal_committed',toolName:'human_commit_goal',outcome:'success',summary:`Draft revision ${state.goalDraft.revision} committed as active goal revision ${active.revision}.`});return{ok:true,value:active}},
  getGoalCommitmentStatus:()=>!state.activeGoal?'no_active_goal':goalMeaning(state.goalDraft)===goalMeaning(state.activeGoal)?'committed':'uncommitted_changes',
  getActiveResourceRequirement:()=>state.activeGoal?{ok:true,value:projectPurchaseGoalToResourceRequirement(state.activeGoal,{market:state.market,workspaceId:state.id})}:{ok:false,code:'invalid_state',message:'A validated resource requirement is not available.'},
  submitGoalInterpretation:input=>{const parsed=goalInterpretationInputSchema.safeParse(input);if(!parsed.success)return{ok:false,code:'invalid_input',message:'Interpretation proposal input is invalid or exceeds its bounds.'};const item=parsed.data;if(item.sessionId!==state.id||item.draftId!==state.goalDraft.id||item.draftRevision!==state.goalDraft.revision)return{ok:false,code:'stale_state',message:'Interpretation must target the current session and exact draft revision.'};const candidate:PurchaseGoalDraft={state:'draft',id:item.draftId,revision:item.draftRevision,...item.proposed};if(!validatePurchaseGoal(candidate).success)return{ok:false,code:'invalid_input',message:'The proposed goal values are invalid.'};const proposal:GoalInterpretationProposal={...item,id:makeId(),createdAt:now(),status:'pending'},superseded=state.goalInterpretationProposals.map(existing=>existing.status==='pending'?{...existing,status:'superseded' as const}:existing);commit({goalInterpretationProposals:[proposal,...superseded].slice(0,20)});recordActivity({kind:'interpretation_submitted',toolName:'propose_goal_interpretation',outcome:'success',summary:`Interpretation proposal ${proposal.id} submitted for human review.`});return{ok:true,value:proposal}},
  rejectGoalInterpretation:id=>{const proposal=state.goalInterpretationProposals.find(item=>item.id===id),status=proposal&&interpretationEffectiveStatus(proposal,state.id,state.goalDraft);if(!proposal||status!=='pending'){const failure={ok:false,code:'invalid_proposal',message:'Only the current pending interpretation can be rejected.'} as const;recordActivity({kind:'interpretation_rejected',toolName:'human_reject_interpretation',outcome:'failure',summary:failure.message});return failure}const rejected={...proposal,status:'rejected' as const};commit({goalInterpretationProposals:state.goalInterpretationProposals.map(item=>item.id===id?rejected:item)});recordActivity({kind:'interpretation_rejected',toolName:'human_reject_interpretation',outcome:'success',summary:'Interpretation proposal rejected; draft and active goal unchanged.'});return{ok:true,value:rejected}},
  adoptGoalInterpretation:id=>{const proposal=state.goalInterpretationProposals.find(item=>item.id===id),status=proposal&&interpretationEffectiveStatus(proposal,state.id,state.goalDraft);if(!proposal||status!=='pending'){const failure={ok:false,code:'invalid_proposal',message:'Only the current applicable interpretation can be adopted.'} as const;recordActivity({kind:'interpretation_adopted',toolName:'human_adopt_interpretation',outcome:'failure',summary:failure.message});return failure}const values={summary:proposal.proposed.summary,searchFocus:proposal.proposed.searchFocus,quantity:proposal.proposed.quantity,maximumItemPrice:proposal.proposed.maximumItemPrice,budget:proposal.proposed.budget,requirements:proposal.proposed.requirements,preferences:proposal.proposed.preferences,exclusions:proposal.proposed.exclusions},candidate={...state.goalDraft,...values},nextDraft=goalMeaning(candidate)===goalMeaning(state.goalDraft)?state.goalDraft:revisePurchaseGoalDraft(state.goalDraft,values),adopted={...proposal,status:'adopted' as const};commit({goalDraft:nextDraft,goalInterpretationProposals:state.goalInterpretationProposals.map(item=>item.id===id?adopted:item)});recordActivity({kind:'interpretation_adopted',toolName:'human_adopt_interpretation',outcome:'success',summary:'Interpretation adopted into the editable draft; active goal unchanged.'});return{ok:true,value:nextDraft}},
  getGoalInterpretationStatus:id=>{const proposal=state.goalInterpretationProposals.find(item=>item.id===id);return proposal&&interpretationEffectiveStatus(proposal,state.id,state.goalDraft)},
  compileSourcingPlan:()=>compileActive(),
  searchCandidates:input=>runDiscovery('human',{...input,mode:'exploratory_human'}),
  sourceCandidatesForActiveGoal:(input={})=>{const result=compileActive();return result.ok?runDiscovery('human',{query:result.value.query,mode:'active_goal_human',strategy:result.value,goalRevision:result.value.goalRevision,...input}):Promise.resolve(result)},
  sourceCandidatesForAgent:async input=>{if(!sameMarket(input.market)){const failure={ok:false,code:'invalid_input',message:`Agent searches must use the active ${state.market.country} / ${state.market.currency} market.`} as const;recordActivity({kind:'agent_search',toolName:'search_products',outcome:'failure',summary:failure.message});return failure}const result=await runDiscovery('agent',{...input,mode:'agent_sourcing'});recordActivity({kind:'agent_search',toolName:'search_products',outcome:result.ok?'success':'failure',summary:result.ok?`Real commerce search returned ${result.value.products.length} candidate${result.value.products.length===1?'':'s'}.`:result.message});return result},
  retainCandidate:identity=>{const product=locate(identity);if(!product)return{ok:false,code:'evidence_unavailable',message:'Candidate evidence is unavailable.'};return retain(product).ok?{ok:true,value:product}:{ok:false,code:'evidence_unavailable',message:'The retained evidence ledger has reached its bounded capacity.'}},
  async inspectCandidate(identity){const product=locate(identity);if(!product)return{ok:false,code:'evidence_unavailable',message:'Candidate evidence is unavailable.'};if(!retain(product).ok)return{ok:false,code:'evidence_unavailable',message:'The retained evidence ledger has reached its bounded capacity.'};const request=beginRefresh(identity);try{const result=await dependencies.catalog.product({identity,market:state.market}),detailed=result.product;if(refreshAuthority.get(request.key)!==request.authority)return stale('A newer evidence refresh superseded this response.');if(!sameProviderIdentity(identity,detailed.identity)){const failure={ok:false,code:'evidence_unavailable',message:'Provider returned a different product identity.'} as const;setRefresh(identity,{status:'error',requestId:request.requestId,error:{code:failure.code,message:failure.message}});return failure}evidence=observeProductEvidence(evidence,detailed,now(),makeId());publishEvidence();setRefresh(identity,{status:'success',requestId:request.requestId});const refresh=(current:DiscoveryWorkspace)=>current.candidates.some(item=>sameProviderIdentity(item.identity,identity))?{...current,candidates:current.candidates.map(item=>sameProviderIdentity(item.identity,identity)?detailed:item),revision:current.revision+1}:current;commit({humanDiscovery:refresh(state.humanDiscovery),agentDiscovery:refresh(state.agentDiscovery)});return{ok:true,value:detailed}}catch(error){if(refreshAuthority.get(request.key)!==request.authority)return stale('A newer evidence refresh superseded this failure.');const failure=safeFailure(error);setRefresh(identity,{status:'error',requestId:request.requestId,error:{code:failure.code,message:failure.message}});return failure}},
  async refreshRetainedEvidence(identity){const entry=findProductEvidence(evidence,identity);if(!entry)return{ok:false,code:'evidence_unavailable',message:'Product must be retained before its evidence can be refreshed.'};const request=beginRefresh(identity);try{const result=await dependencies.catalog.product({identity,market:state.market});if(refreshAuthority.get(request.key)!==request.authority)return stale('A newer evidence refresh superseded this response.');if(!sameProviderIdentity(identity,result.product.identity)){const failure={ok:false,code:'evidence_unavailable',message:'Provider returned a different product identity.'} as const;setRefresh(identity,{status:'error',requestId:request.requestId,error:{code:failure.code,message:failure.message}});return failure}evidence=observeProductEvidence(evidence,result.product,now(),makeId());publishEvidence();setRefresh(identity,{status:'success',requestId:request.requestId});return{ok:true,value:findProductEvidence(evidence,identity)!}}catch(error){if(refreshAuthority.get(request.key)!==request.authority)return stale('A newer evidence refresh superseded this failure.');const failure=safeFailure(error);setRefresh(identity,{status:'error',requestId:request.requestId,error:{code:failure.code,message:failure.message}});return failure}},
  dismissAgentCandidates:()=>{agentAuthority++;const current=state.agentDiscovery;if(current.status==='idle'&&current.candidates.length===0)return;updateWorkspace('agent',{status:'idle',query:'',criteriaKey:undefined,activeRequestId:undefined,lastAcceptedRequestId:undefined,candidates:[],messages:[],pagination:emptyPagination(),error:undefined,strategy:undefined,goalRevision:undefined})},
  toggleComparison:identity=>{const selected=state.comparisonIds.some(item=>sameProviderIdentity(item,identity));if(!selected){const product=locate(identity);if(!product||!retain(product).ok)return}const next=selected?state.comparisonIds.filter(item=>!sameProviderIdentity(item,identity)):state.comparisonIds.length<2?[...state.comparisonIds,identity]:[state.comparisonIds[1]!,identity];commit({comparisonIds:next})},clearComparison:()=>{if(state.comparisonIds.length)commit({comparisonIds:[]})},
  evaluateCandidate:identity=>{if(!state.activeGoal)return{ok:false,code:'invalid_state',message:'A validated purchase goal is required.'};const entry=findProductEvidence(evidence,identity),product=entry?.current.product,requirement=projectPurchaseGoalToResourceRequirement(state.activeGoal,{market:state.market,workspaceId:state.id});return product?{ok:true,value:evaluateProductAgainstGoal(state.activeGoal,product,neutralOffer(product),{observedAt:entry.current.observedAt,freshness:assessEvidenceFreshness(entry.current.observedAt,requirement.evidenceFreshness,now())})}:{ok:false,code:'evidence_unavailable',message:'Product must be retained first.'}},
  compareCandidates:(a,b)=>{const first=application.evaluateCandidate(a),second=application.evaluateCandidate(b);if(!first.ok||!second.ok)return{ok:false,code:'evidence_unavailable',message:'Both products must have retained evidence.'};const pa=findByProviderIdentity(state.retainedProducts,a)!,pb=findByProviderIdentity(state.retainedProducts,b)!;return{ok:true,value:compareProductEvaluations({product:a,title:pa.title.value,evaluation:first.value},{product:b,title:pb.title.value,evaluation:second.value})}},
  getEvidenceGaps:identity=>{const strategy=compileActive();if(!strategy.ok)return strategy;const gaps=[...strategy.value.evidenceGaps];if(identity){const evaluation=application.evaluateCandidate(identity);if(!evaluation.ok)return evaluation;for(const item of [...evaluation.value.requirements,...evaluation.value.preferences].filter(item=>item.status==='unknown'))if(!gaps.some(gap=>gap.goalConditionId===item.conditionId))gaps.push({subject:identity,goalConditionId:item.conditionId,description:item.condition.value||item.condition.field||'Condition',reason:item.reason,gapType:item.issue??'missing',resolution:item.issue==='inferred'||item.issue==='conflict'?'requires_merchant_verification':'search_for_stronger_evidence',relevance:item.kind==='preference'?'preference':'mandatory'});if(evaluation.value.evidence?.freshness==='stale')gaps.push({subject:identity,description:'Evidence freshness',reason:'The last accepted observation is older than the active requirement permits.',gapType:'stale',resolution:'refresh_retained_evidence',relevance:'mandatory'})}return{ok:true,value:gaps.slice(0,50)}},
  evaluatePurchasePlan:()=>state.activeGoal?{ok:true,value:evaluatePlan()}:{ok:false,code:'invalid_state',message:'A validated purchase goal is required.'},
  addCandidateToPlan:identity=>{const product=locate(identity);if(!product)return{ok:false,code:'evidence_unavailable',message:'Candidate evidence is unavailable.'};if(!state.activeGoal)return{ok:false,code:'invalid_state',message:'A validated purchase goal is required.'};if(!retain(product).ok)return{ok:false,code:'evidence_unavailable',message:'The retained evidence ledger has reached its bounded capacity.'};const base=state.plan.lines.length===0?{...state.plan,goalId:state.activeGoal.id,goalRevision:state.activeGoal.revision}:state.plan,plan=addProductToPlan(base,product,makeId());mutatePlan(plan);return{ok:true,value:plan}},
  removePlanLine:lineId=>mutatePlan(removePlanLine(state.plan,lineId)),setPlanLineQuantity:(lineId,quantity)=>mutatePlan(setPlanLineQuantity(state.plan,lineId,quantity)),selectPlanLineOffer:(lineId,offer)=>mutatePlan(selectPlanLineOffer(state.plan,lineId,offer,state.retainedProducts)),rebasePlan:()=>{if(state.activeGoal)mutatePlan(rebasePlanToGoal(state.plan,state.activeGoal.id,state.activeGoal.revision))},
  createPlanProposal:input=>{const result=createPlanChangeProposal(input,{goal:state.activeGoal,plan:state.plan,retainedProducts:state.retainedProducts},makeId,now);if(!result.ok){recordActivity({kind:result.code==='stale_revision'?'proposal_stale':'agent_proposal_created',toolName:'propose_plan_changes',outcome:'failure',summary:result.message});return{ok:false,code:result.code==='stale_revision'?'stale_state':'invalid_proposal',message:result.message}}commit({proposals:[result.proposal,...state.proposals].slice(0,20)});recordActivity({kind:'agent_proposal_created',toolName:'propose_plan_changes',outcome:'success',summary:`Agent proposal ${result.proposal.id} created for human review.`});return{ok:true,value:result.proposal}},
  approvePlanProposal:id=>{const proposal=state.proposals.find(item=>item.id===id);if(!proposal){const failure={ok:false,code:'invalid_proposal',message:'Proposal was not found.'} as const;recordActivity({kind:'proposal_applied',toolName:'human_approve_and_apply',outcome:'failure',summary:failure.message});return failure}const before=state.plan.revision,result=approveProposal(proposal,{goal:state.activeGoal,plan:state.plan,retainedProducts:state.retainedProducts},now);const plan=result.plan&&result.plan.lines.length>0&&state.plan.lines.length===0&&state.activeGoal?{...result.plan,goalId:state.activeGoal.id,goalRevision:state.activeGoal.revision}:result.plan;commit({proposals:state.proposals.map(item=>item.id===id?result.proposal:item),...(plan?{plan}: {})});const applied=Boolean(plan),staleStatus=result.proposal.status==='stale';recordActivity({kind:staleStatus?'proposal_stale':'proposal_applied',toolName:'human_approve_and_apply',outcome:applied?'success':'failure',summary:applied?`Agent-proposed changes were approved and applied. Revision ${before} → ${plan!.revision}.`:result.proposal.error??'Proposal was not applied.'});return{ok:true,value:plan}},
  rejectPlanProposal:id=>{const proposal=state.proposals.find(item=>item.id===id);if(!proposal){const failure={ok:false,code:'invalid_proposal',message:'Proposal was not found.'} as const;recordActivity({kind:'proposal_rejected',toolName:'human_reject',outcome:'failure',summary:failure.message});return failure}const rejected=rejectProposal(proposal,now),didReject=rejected!==proposal;if(didReject)commit({proposals:state.proposals.map(item=>item.id===id?rejected:item)});recordActivity({kind:'proposal_rejected',toolName:'human_reject',outcome:didReject?'success':'failure',summary:didReject?'Agent proposal rejected by the human; plan unchanged.':'Proposal was not pending and could not be rejected.'});return{ok:true,value:rejected}},
  reviewPlanProposal:id=>{const proposal=state.proposals.find(item=>item.id===id);if(!proposal||!state.activeGoal)return{ok:false,code:'invalid_proposal',message:'Proposal or validated goal is unavailable.'};const proposalState={goal:state.activeGoal,plan:state.plan,retainedProducts:state.retainedProducts},status=proposalEffectiveStatus(proposal,proposalState),before=evaluatePlan(),preview=status==='pending'?applyProposalOperations(proposal,proposalState):undefined;return{ok:true,value:{status,before,after:preview?.ok?evaluatePlan(preview.plan):undefined}}},recordActivity,
 }
 return application
}

export function proposalStatus(application:CoSourceApplication,proposal:PlanChangeProposal){const state=application.getSnapshot();return proposalEffectiveStatus(proposal,{goal:state.activeGoal,plan:state.plan,retainedProducts:state.retainedProducts})}
