import { describe, expect, it, vi } from 'vitest'
import type { ProductCluster } from '../commerce/domain/commerce'
import { createCoSourceApplication } from './cosource-application'
import {providerIdentityKey} from '../commerce/domain/provider-identity'

const provenance={kind:'provider_explicit' as const,provider:'shopify_global_catalog' as const}
const product=(title:string):ProductCluster=>({identity:{provider:'shopify_global_catalog',id:'p1'},title:{value:title,provenance},media:[],offers:[],offerCompleteness:'provider_returned_unknown',provenance})
function fixture(details:Array<ProductCluster|Error>){let id=0,index=0;const now=vi.fn().mockReturnValueOnce('2026-01-01T00:00:00Z').mockReturnValueOnce('2026-01-02T00:00:00Z').mockReturnValue('2026-01-03T00:00:00Z');const application=createCoSourceApplication({market:{country:'GB',currency:'GBP'},makeId:()=>`id-${++id}`,now,catalog:{search:async()=>({products:[product('Search')],messages:[],pagination:{hasMore:false}}),product:async()=>{const value=details[index++];if(value instanceof Error)throw value;return{product:value!,selectedOptions:[],messages:[]}}}});return application}

describe('application evidence ledger',()=>{
 it('does not let accepted discovery overwrite retained evidence',async()=>{const application=fixture([product('Detail')]);await application.searchCandidates({query:'item'});application.retainCandidate(product('Search').identity);await application.searchCandidates({query:'item again'});expect(application.getSnapshot().retainedProducts[0]?.title.value).toBe('Search');expect(application.getSnapshot().retainedEvidence[0]?.current.sequence).toBe(1)})
 it('refreshes the same identity, preserves history, and does not revise the plan',async()=>{const application=fixture([product('Refreshed')]);await application.searchCandidates({query:'item'});application.retainCandidate(product('Search').identity);application.editGoal({summary:'Buy item'});application.commitGoalDraft();application.addCandidateToPlan(product('Search').identity);const revision=application.getSnapshot().plan.revision;const result=await application.refreshRetainedEvidence(product('Search').identity);expect(result).toMatchObject({ok:true,value:{current:{sequence:2,product:{title:{value:'Refreshed'}}},history:[{sequence:1}]}});expect(application.getSnapshot().plan.revision).toBe(revision)})
 it('preserves the last accepted observation on refresh failure and rejects wrong identity',async()=>{const application=fixture([new Error('offline'),{...product('Wrong'),identity:{provider:'shopify_global_catalog',id:'other'}}]);await application.searchCandidates({query:'item'});application.retainCandidate(product('Search').identity);const before=application.getSnapshot().retainedEvidence[0];expect(await application.refreshRetainedEvidence(product('Search').identity)).toMatchObject({ok:false,code:'provider_unavailable'});expect(application.getSnapshot().retainedEvidence[0]).toEqual(before);expect(await application.refreshRetainedEvidence(product('Search').identity)).toMatchObject({ok:false,code:'evidence_unavailable'});expect(application.getSnapshot().retainedEvidence[0]).toEqual(before)})
 it('accepts only the latest concurrent refresh and stores lifecycle in the kernel',async()=>{let resolveFirst!:(value:{product:ProductCluster;selectedOptions:never[];messages:never[]})=>void,resolveSecond!:(value:{product:ProductCluster;selectedOptions:never[];messages:never[]})=>void;const catalogProduct=vi.fn().mockImplementationOnce(()=>new Promise(resolve=>{resolveFirst=resolve})).mockImplementationOnce(()=>new Promise(resolve=>{resolveSecond=resolve}));let id=0;const application=createCoSourceApplication({market:{country:'GB',currency:'GBP'},makeId:()=>`id-${++id}`,now:()=>`2026-01-0${Math.min(id,9)}T00:00:00Z`,catalog:{search:async()=>({products:[product('Initial')],messages:[],pagination:{hasMore:false}}),product:catalogProduct}});await application.searchCandidates({query:'item'});const identity=product('Initial').identity,key=providerIdentityKey(identity);application.retainCandidate(identity);const first=application.refreshRetainedEvidence(identity),second=application.refreshRetainedEvidence(identity);expect(application.getSnapshot().evidenceRefresh[key]).toMatchObject({status:'loading'});resolveSecond({product:product('Newest request'),selectedOptions:[],messages:[]});expect(await second).toMatchObject({ok:true});resolveFirst({product:product('Late stale response'),selectedOptions:[],messages:[]});expect(await first).toMatchObject({ok:false,code:'stale_state'});expect(application.getSnapshot().retainedEvidence[0]?.current.product.title.value).toBe('Newest request');expect(application.getSnapshot().evidenceRefresh[key]).toMatchObject({status:'success'})})
})
