import {describe,expect,it,vi} from 'vitest'
import {COMMERCE_PROVIDERS,type ProductCluster} from '../commerce/domain/commerce'
import {createCoSourceApplication,type CatalogPort} from './cosource-application'

const provider=COMMERCE_PROVIDERS.shopifyGlobalCatalog,provenance={kind:'provider_explicit' as const,provider},market={country:'GB',currency:'GBP'},product:ProductCluster={identity:{provider,id:'p'},title:{value:'Product',provenance},media:[],offers:[],offerCompleteness:'featured_only',provenance}
function fixture(){let n=0;const search=vi.fn(async()=>({products:[product],messages:[],pagination:{hasMore:false}})),catalog:CatalogPort={search,product:async()=>({product,selectedOptions:[],messages:[]})},app=createCoSourceApplication({catalog,market,makeId:()=>`id-${++n}`,now:()=>`2026-09-02T00:00:${n.toString().padStart(2,'0')}Z`});return{app,search}}
const input=(app:ReturnType<typeof fixture>['app'],changes:Record<string,unknown>={})=>{const state=app.getSnapshot();return{sessionId:state.id,draftId:state.goalDraft.id,draftRevision:state.goalDraft.revision,proposed:{summary:'Equip a team',searchFocus:'office chairs',quantity:6,maximumItemPrice:{minorAmount:12000,currency:'GBP'},budget:{minorAmount:60000,currency:'GBP'},requirements:[{id:'r1',operator:'free_text',value:'adjustable'}],preferences:[{id:'p1',operator:'free_text',value:'black'}],exclusions:[]},interpretationNotes:'Structured the requested outcome without asserting product facts.',assumptions:['Quantity means individual chairs.'],unresolvedQuestions:['Should delivery be required?'],...changes}}

describe('B3 goal interpretation and commitment',()=>{
 it('derives every commitment status from canonical goal meaning without mutating revisions',()=>{const{app}=fixture();expect(app.getGoalCommitmentStatus()).toBe('no_active_goal');app.editGoal({summary:'Canonical A',searchFocus:'chairs'});app.commitGoalDraft();expect(app.getGoalCommitmentStatus()).toBe('committed');const committed=app.getSnapshot();app.editGoal({summary:'Canonical A'});expect(app.getSnapshot()).toBe(committed);expect(app.getGoalCommitmentStatus()).toBe('committed');app.editGoal({summary:'Canonical B'});expect(app.getGoalCommitmentStatus()).toBe('uncommitted_changes');app.editGoal({summary:'Canonical A'});const restored=app.getSnapshot();expect(app.getGoalCommitmentStatus()).toBe('committed');expect(app.getSnapshot().goalDraft.revision).toBe(restored.goalDraft.revision);expect(app.getSnapshot().activeGoal?.revision).toBe(restored.activeGoal?.revision);app.editGoal({summary:''});expect(app.getGoalCommitmentStatus()).toBe('uncommitted_changes')})
 it('keeps draft proposal and active goal distinct without provider access',()=>{const{app,search}=fixture(),draft=app.getSnapshot().goalDraft;const submitted=app.submitGoalInterpretation(input(app));expect(submitted.ok).toBe(true);const state=app.getSnapshot();expect(state.goalDraft).toBe(draft);expect(state.activeGoal).toBeUndefined();expect(state.goalInterpretationProposals).toHaveLength(1);expect(search).not.toHaveBeenCalled();expect(state.activities.filter(item=>item.kind==='interpretation_submitted')).toHaveLength(1)})
 it('rejects malformed, excessive, and inexact money input without mutation',()=>{const{app}=fixture(),before=app.getSnapshot();expect(app.submitGoalInterpretation(input(app,{extra:true}))).toMatchObject({ok:false,code:'invalid_input'});expect(app.getSnapshot()).toBe(before);expect(app.submitGoalInterpretation(input(app,{assumptions:Array(21).fill('bounded')}))).toMatchObject({ok:false,code:'invalid_input'});expect(app.getSnapshot()).toBe(before);expect(app.submitGoalInterpretation(input(app,{interpretationNotes:'x'.repeat(2001)}))).toMatchObject({ok:false,code:'invalid_input'});expect(app.getSnapshot()).toBe(before);expect(app.submitGoalInterpretation(input(app,{proposed:{...input(app).proposed,maximumItemPrice:{minorAmount:1.5,currency:'GBP'}}}))).toMatchObject({ok:false,code:'invalid_input'});expect(app.submitGoalInterpretation(input(app,{proposed:{...input(app).proposed,budget:{minorAmount:100,currency:'ZZZ'}}}))).toMatchObject({ok:false,code:'invalid_input'});expect(app.getSnapshot()).toBe(before)})
 it('binds exact session and draft revision',()=>{const{app}=fixture(),before=app.getSnapshot();expect(app.submitGoalInterpretation(input(app,{sessionId:'other'}))).toMatchObject({ok:false,code:'stale_state'});expect(app.submitGoalInterpretation(input(app,{draftRevision:99}))).toMatchObject({ok:false,code:'stale_state'});expect(app.getSnapshot()).toBe(before)})
 it('stales on meaningful draft revision but not a semantic no-op and never revives after restoration',()=>{const{app}=fixture();const submitted=app.submitGoalInterpretation(input(app));if(!submitted.ok)return;const before=app.getSnapshot();app.editGoal({summary:before.goalDraft.summary});expect(app.getSnapshot()).toBe(before);expect(app.getGoalInterpretationStatus(submitted.value.id)).toBe('pending');app.editGoal({summary:'temporary'});expect(app.getGoalInterpretationStatus(submitted.value.id)).toBe('stale');app.editGoal({summary:''});expect(app.getGoalInterpretationStatus(submitted.value.id)).toBe('stale')})
 it('explicitly supersedes an older pending proposal',()=>{const{app}=fixture(),first=app.submitGoalInterpretation(input(app)),second=app.submitGoalInterpretation(input(app,{interpretationNotes:'A newer interpretation.'}));expect(first.ok&&second.ok).toBe(true);if(!first.ok||!second.ok)return;expect(app.getGoalInterpretationStatus(first.value.id)).toBe('superseded');expect(app.getGoalInterpretationStatus(second.value.id)).toBe('pending')})
 it('prevents rejected and stale adoption',()=>{const{app}=fixture(),first=app.submitGoalInterpretation(input(app));if(!first.ok)return;app.rejectGoalInterpretation(first.value.id);expect(app.adoptGoalInterpretation(first.value.id)).toMatchObject({ok:false,code:'invalid_proposal'});const second=app.submitGoalInterpretation(input(app));if(!second.ok)return;app.editGoal({summary:'changed'});expect(app.adoptGoalInterpretation(second.value.id)).toMatchObject({ok:false,code:'invalid_proposal'})})
 it('adopts into editable draft only and permits later human editing',()=>{const{app}=fixture();app.editGoal({summary:'Human draft'});app.commitGoalDraft();const active=app.getSnapshot().activeGoal!,submitted=app.submitGoalInterpretation(input(app));if(!submitted.ok)return;expect(app.adoptGoalInterpretation(submitted.value.id).ok).toBe(true);expect(app.getSnapshot().goalDraft).toMatchObject({summary:'Equip a team',searchFocus:'office chairs',quantity:6});expect(app.getSnapshot().activeGoal).toBe(active);expect(app.getSnapshot().activities.filter(item=>item.kind==='interpretation_adopted')).toHaveLength(1);app.editGoal({quantity:7});expect(app.getSnapshot().goalDraft.quantity).toBe(7);expect(app.getSnapshot().activeGoal).toBe(active)})
 it('changes active authority only on explicit meaningful commit and preserves no-op identity',()=>{const{app}=fixture();app.editGoal({summary:'Human intent',searchFocus:'chairs'});expect(app.getSnapshot().activeGoal).toBeUndefined();const first=app.commitGoalDraft();expect(first.ok).toBe(true);const active=app.getSnapshot().activeGoal!;app.editGoal({summary:''});expect(app.commitGoalDraft()).toMatchObject({ok:false,code:'invalid_input'});expect(app.getSnapshot().activeGoal).toBe(active);app.editGoal({summary:'Human intent'});const recommit=app.commitGoalDraft();expect(recommit.ok&&recommit.value).toBe(active);expect(app.getSnapshot().activeGoal!.revision).toBe(active.revision)})
 it('meaningful commitment retains discovery and populated-plan staleness rules',async()=>{const{app}=fixture();app.editGoal({summary:'First',searchFocus:'products'});app.commitGoalDraft();await app.sourceCandidatesForActiveGoal();app.addCandidateToPlan(product.identity);const active=app.getSnapshot().activeGoal!;app.editGoal({summary:'Second'});expect(app.getSnapshot().humanDiscovery.status).toBe('ready');expect(app.getSnapshot().activeGoal).toBe(active);app.commitGoalDraft();expect(app.getSnapshot().humanDiscovery.status).toBe('stale');expect(app.evaluatePurchasePlan()).toMatchObject({ok:true,value:{stale:true}})})
})
