import {describe,expect,it,vi} from 'vitest'
import {COMMERCE_PROVIDERS,type ProductCluster} from '../commerce/domain/commerce'
import type {CatalogSearchResult} from '../commerce/providers/catalog-provider'
import {createCoSourceApplication,MAX_AGENT_CANDIDATES,type CatalogPort} from './cosource-application'

const provider=COMMERCE_PROVIDERS.shopifyGlobalCatalog,provenance={kind:'provider_explicit' as const,provider},market={country:'GB',currency:'GBP'}
const product=(id:string,title=id):ProductCluster=>({identity:{provider,id},title:{value:title,provenance},media:[],offers:[{identity:{provider,id:`${id}-offer`},title:{value:title,provenance},price:{minorAmount:1000,currency:'GBP'},availability:{state:'available',basis:'catalog_signal',provenance},selectedOptions:[],media:[],correlations:[],provenance}],offerCompleteness:'featured_only',featuredOfferId:`${id}-offer`,provenance})
const result=(products:ProductCluster[],cursor?:string):CatalogSearchResult=>({products,messages:[],pagination:{hasMore:Boolean(cursor),cursor}})
function deferred<T>(){let resolve!:(value:T)=>void,reject!:(reason?:unknown)=>void;const promise=new Promise<T>((yes,no)=>{resolve=yes;reject=no});return{promise,resolve,reject}}
function fixture(search:CatalogPort['search']=async()=>result([])){let n=0;const catalog:CatalogPort={search,product:async input=>({product:product(input.identity.id,'Detailed'),selectedOptions:[],messages:[]})},application=createCoSourceApplication({catalog,market,makeId:()=>`id-${++n}`,now:()=>`2026-09-02T00:00:${n.toString().padStart(2,'0')}Z`});application.editGoal({summary:'Initial goal',searchFocus:'products'});return application}

describe('B2 canonical session and discovery lifecycle',()=>{
 it('accepts only the latest response in one channel',async()=>{const first=deferred<CatalogSearchResult>(),second=deferred<CatalogSearchResult>(),search=vi.fn().mockReturnValueOnce(first.promise).mockReturnValueOnce(second.promise),app=fixture(search);const old=app.searchCandidates({query:'old'}),latest=app.searchCandidates({query:'latest'});second.resolve(result([product('latest')]));expect((await latest).ok).toBe(true);first.resolve(result([product('old')]));expect(await old).toMatchObject({ok:false,code:'stale_state'});expect(app.getSnapshot().humanDiscovery.candidates[0]?.identity.id).toBe('latest')})
 it('keeps human and agent request authority independent',async()=>{const human=deferred<CatalogSearchResult>(),agent=deferred<CatalogSearchResult>(),search=vi.fn().mockReturnValueOnce(human.promise).mockReturnValueOnce(agent.promise),app=fixture(search);const humanCall=app.searchCandidates({query:'human'}),agentCall=app.sourceCandidatesForAgent({query:'agent',market});agent.resolve(result([product('agent')]));human.resolve(result([product('human')]));expect((await humanCall).ok&&(await agentCall).ok).toBe(true);expect(app.getSnapshot().humanDiscovery.candidates[0]?.identity.id).toBe('human');expect(app.getSnapshot().agentDiscovery.candidates[0]?.identity.id).toBe('agent')})
 it('rejects an agent completion after dismissal',async()=>{const pending=deferred<CatalogSearchResult>(),app=fixture(()=>pending.promise),call=app.sourceCandidatesForAgent({query:'agent',market});app.dismissAgentCandidates();pending.resolve(result([product('late')]));expect(await call).toMatchObject({ok:false,code:'stale_state'});expect(app.getSnapshot().agentDiscovery).toMatchObject({status:'idle',candidates:[]})})
 it('rejects an old goal-derived completion after active-goal change',async()=>{const pending=deferred<CatalogSearchResult>(),app=fixture(()=>pending.promise),call=app.sourceCandidatesForActiveGoal();app.editGoal({summary:'Meaningfully changed goal'});pending.resolve(result([product('late')]));expect(await call).toMatchObject({ok:false,code:'stale_state'});expect(app.getSnapshot().humanDiscovery.status).toBe('stale')})
 it('clears old candidates when a new initial request begins',async()=>{const second=deferred<CatalogSearchResult>(),search=vi.fn().mockResolvedValueOnce(result([product('old')])).mockReturnValueOnce(second.promise),app=fixture(search);await app.searchCandidates({query:'old'});const pending=app.searchCandidates({query:'new'});expect(app.getSnapshot().humanDiscovery).toMatchObject({query:'new',status:'initial_loading',candidates:[]});second.resolve(result([product('new')]));await pending})
 it('rejects mismatched pagination before provider access',async()=>{const search=vi.fn().mockResolvedValue(result([product('a')],'cursor-1')),app=fixture(search);await app.searchCandidates({query:'products'});expect(await app.searchCandidates({query:'other',cursor:'cursor-1'})).toMatchObject({ok:false,code:'invalid_input'});expect(await app.searchCandidates({query:'products',cursor:'wrong'})).toMatchObject({ok:false,code:'invalid_input'});expect(search).toHaveBeenCalledTimes(1)})
 it('bounds the complete agent workspace across pagination and ignores discarded evidence',async()=>{const first=Array.from({length:6},(_,index)=>product(`a${index+1}`)),second=[product('a7'),product('a8'),product('a9'),product('a10'),product('retained','Discarded fresh'),product('a12')],search=vi.fn().mockResolvedValueOnce(result([product('retained','Retained old')])).mockResolvedValueOnce(result(first,'agent-next')).mockResolvedValueOnce(result(second,'agent-third')),app=fixture(search);await app.searchCandidates({query:'retain'});app.retainCandidate(product('retained').identity);await app.sourceCandidatesForAgent({query:'agent',market,limit:6});const continued=await app.sourceCandidatesForAgent({query:'agent',market,limit:6,cursor:'agent-next'});expect(continued).toMatchObject({ok:true,value:{products:[{identity:{id:'a7'}},{identity:{id:'a8'}},{identity:{id:'a9'}},{identity:{id:'a10'}}],pagination:{hasMore:false}}});expect(app.getSnapshot().agentDiscovery.candidates).toHaveLength(MAX_AGENT_CANDIDATES);expect(app.getSnapshot().agentDiscovery.pagination).toEqual({hasMore:false});expect(app.getSnapshot().retainedProducts[0]?.title.value).toBe('Retained old');expect(await app.sourceCandidatesForAgent({query:'agent',market,limit:6,cursor:'agent-third'})).toMatchObject({ok:false,code:'invalid_input'});expect(search).toHaveBeenCalledTimes(3)})
 it('does not apply the agent workspace bound to human pagination',async()=>{const first=Array.from({length:6},(_,index)=>product(`h${index+1}`)),second=Array.from({length:6},(_,index)=>product(`h${index+7}`)),search=vi.fn().mockResolvedValueOnce(result(first,'human-next')).mockResolvedValueOnce(result(second,'human-third')),app=fixture(search);await app.searchCandidates({query:'human',limit:6});const continued=await app.searchCandidates({query:'human',limit:6,cursor:'human-next'});expect(continued).toMatchObject({ok:true,value:{products:second,pagination:{hasMore:true,cursor:'human-third'}}});expect(app.getSnapshot().humanDiscovery.candidates).toHaveLength(12)})
 it('preserves the last valid active goal during invalid editing',()=>{const app=fixture(),active=app.getSnapshot().activeGoal;app.editGoal({summary:''});expect(app.getSnapshot().goalDraft.summary).toBe('');expect(app.getSnapshot().activeGoal).toBe(active)})
 it('preserves active authority when an invalid draft is restored exactly',async()=>{const app=fixture(async()=>result([product('a'),product('b')],'next'));await app.sourceCandidatesForActiveGoal();app.retainCandidate(product('a').identity);app.retainCandidate(product('b').identity);app.addCandidateToPlan(product('a').identity);const before=app.getSnapshot(),created=app.createPlanProposal({planId:before.plan.id,planRevision:before.plan.revision,goalId:before.activeGoal!.id,goalRevision:before.activeGoal!.revision,operations:[{type:'add_retained_product',product:product('b').identity}]});expect(created.ok).toBe(true);const active=app.getSnapshot().activeGoal!,draftRevision=app.getSnapshot().goalDraft.revision;app.editGoal({summary:''});app.editGoal({summary:'Initial goal'});const restored=app.getSnapshot();expect(restored.goalDraft.revision).toBe(draftRevision+2);expect(restored.activeGoal).toBe(active);expect(restored.activeGoal!.revision).toBe(active.revision);expect(restored.humanDiscovery.status).toBe('ready');expect(app.evaluatePurchasePlan()).toMatchObject({ok:true,value:{stale:false}});if(created.ok)expect(app.reviewPlanProposal(created.value.id)).toMatchObject({ok:true,value:{status:'pending'}})})
 it('still replaces active authority for a meaningful valid change',async()=>{const app=fixture(async()=>result([product('a')],'next'));await app.sourceCandidatesForActiveGoal();app.retainCandidate(product('a').identity);app.addCandidateToPlan(product('a').identity);const active=app.getSnapshot().activeGoal!;app.editGoal({summary:'Meaningfully different'});expect(app.getSnapshot().activeGoal).not.toBe(active);expect(app.getSnapshot().activeGoal!.revision).toBeGreaterThan(active.revision);expect(app.getSnapshot().humanDiscovery.status).toBe('stale');expect(app.evaluatePurchasePlan()).toMatchObject({ok:true,value:{stale:true}})})
 it('preserves goal and root revisions for semantic no-ops',()=>{const app=fixture(),before=app.getSnapshot();app.editGoal({summary:before.goalDraft.summary});app.clearComparison();app.removePlanLine('missing');expect(app.getSnapshot()).toBe(before);expect(app.getSnapshot().revision).toBe(before.revision);expect(app.getSnapshot().activeGoal?.revision).toBe(before.activeGoal?.revision)})
 it('refreshes retained matching identity without retaining unrelated results or revising the plan',async()=>{const search=vi.fn().mockResolvedValueOnce(result([product('a','Old')])).mockResolvedValueOnce(result([product('a','Fresh'),product('b','Unrelated')])),app=fixture(search);await app.searchCandidates({query:'first'});app.retainCandidate(product('a').identity);const plan=app.getSnapshot().plan;await app.searchCandidates({query:'second'});expect(app.getSnapshot().retainedProducts.map(item=>[item.identity.id,item.title.value])).toEqual([['a','Fresh']]);expect(app.getSnapshot().plan).toBe(plan)})
})

describe('B2 plan lifecycle',()=>{
 it('keeps an empty plan neutral and not stale',()=>{const app=fixture();app.editGoal({budget:{minorAmount:5000,currency:'GBP'}});const evaluation=app.evaluatePurchasePlan();expect(evaluation).toMatchObject({ok:true,value:{status:'draft',stale:false}});if(evaluation.ok)expect(evaluation.value).not.toHaveProperty('budget')})
 it('binds the first human line and later becomes stale after goal revision',async()=>{const app=fixture(async()=>result([product('a')]));await app.searchCandidates({query:'a'});const goal=app.getSnapshot().activeGoal!;app.addCandidateToPlan(product('a').identity);expect(app.getSnapshot().plan).toMatchObject({goalId:goal.id,goalRevision:goal.revision,lines:[{}]});app.editGoal({summary:'Changed after planning'});expect(app.evaluatePurchasePlan()).toMatchObject({ok:true,value:{stale:true}})})
 it('binds the first approved agent-proposed line to the current goal',async()=>{const app=fixture(async()=>result([product('a')]));await app.sourceCandidatesForAgent({query:'a',market});app.retainCandidate(product('a').identity);const state=app.getSnapshot(),created=app.createPlanProposal({planId:state.plan.id,planRevision:state.plan.revision,goalId:state.activeGoal!.id,goalRevision:state.activeGoal!.revision,operations:[{type:'add_retained_product',product:product('a').identity}]});expect(created.ok).toBe(true);if(!created.ok)return;app.approvePlanProposal(created.value.id);expect(app.getSnapshot().plan).toMatchObject({goalId:state.activeGoal!.id,goalRevision:state.activeGoal!.revision,lines:[{}]})})
})
