import {useMemo,useState} from 'react'
import './App.css'
import type {MerchantOffer,ProductCluster,ProvenanceKind,ProviderIdentity} from './commerce/domain/commerce'
import {providerIdentityKey,sameProviderIdentity} from './commerce/domain/provider-identity'
import type {CatalogProductResult} from './commerce/providers/catalog-provider'
import {formatMoney,MoneyDisplayError} from './commerce/domain/money-display'
import {PurchaseGoalPanel} from './goals/PurchaseGoalPanel'
import {GoalInterpretationPanel} from './goals/GoalInterpretationPanel'
import type {ProductEvaluation} from './evaluation/domain/product-evaluation'
import {ProductEvaluationPanel} from './evaluation/ProductEvaluationPanel'
import {DecisionWorkspace} from './planning/DecisionWorkspace'
import {useWebMCP} from './webmcp/use-webmcp'
import {WebMCPStatusPanel} from './webmcp/WebMCPStatusPanel'
import {ProposalReviewPanel} from './proposals/ProposalReviewPanel'
import {createBrowserApplication} from './application/browser-application'
import {useCoSourceApplication} from './application/use-cosource-application'
import type {ApplicationResult} from './application/cosource-application'

const availabilityText={available:'Listed as available',unavailable:'Unavailable',unknown:'Availability not confirmed'}
const provenanceText:Record<ProvenanceKind,string>={provider_explicit:'Provided',provider_inferred:'Inferred',cosource_derived:'Derived',unknown:'Unknown'}
function money(offer:MerchantOffer){try{return formatMoney(offer.price)}catch(error){return error instanceof MoneyDisplayError?'Price unavailable — unsupported currency':'Price unavailable'}}
const safeExternal=(url?:string)=>url?.startsWith('https://')?url:undefined
function ProductImage({product}:{product:ProductCluster}){const[broken,setBroken]=useState(false),image=product.media[0];return image&&!broken?<img src={image.url} alt={image.altText||product.title.value} loading="lazy" onError={()=>setBroken(true)}/>:<div className="image-fallback">No image</div>}
function ResultCard({product,onOpen,comparisonSelected,onToggleComparison,maximumItemPrice}:{product:ProductCluster;onOpen:()=>void;comparisonSelected:boolean;onToggleComparison:()=>void;maximumItemPrice?:{minorAmount:number;currency:string}}){const featured=product.featuredOfferId?product.offers.find(offer=>offer.identity.provider===product.identity.provider&&offer.identity.id===product.featuredOfferId):undefined,displayedOffer=featured??product.offers[0],priceConflict=Boolean(displayedOffer&&maximumItemPrice&&displayedOffer.price.currency===maximumItemPrice.currency&&displayedOffer.price.minorAmount>maximumItemPrice.minorAmount);return <article className="result-card"><ProductImage product={product}/><div className="card-copy"><div className="card-labels"><span>Product cluster</span>{product.description?.provenance.kind==='provider_inferred'&&<span className="evidence">Inferred details</span>}</div><h3>{product.title.value}</h3>{product.description&&<p className="description">{product.description.value}</p>}{displayedOffer?<div className="featured"><span>{featured?'Featured offer':'Returned offer'}</span><strong>{money(displayedOffer)}</strong><span>{displayedOffer.merchant?.name||displayedOffer.merchant?.domain||'Merchant not named'}</span><span>{availabilityText[displayedOffer.availability.state]}</span></div>:<p>No offer was returned for this cluster.</p>}{priceConflict&&<p className="notice error">Known conflict — exceeds maximum item price</p>}<p className="completeness">More offers may be available. Open the product to check.</p><div className="offer-links"><button type="button" className="secondary" onClick={onOpen}>View product and offers</button><button type="button" className="secondary" aria-pressed={comparisonSelected} onClick={onToggleComparison}>{comparisonSelected?'Remove from comparison':'Select for comparison'}</button></div></div></article>}
function Detail({result,loading,error,onClose,evaluation}:{result?:CatalogProductResult;loading:boolean;error?:string;onClose:()=>void;evaluation?:ProductEvaluation}){return <aside className="detail" aria-labelledby="detail-title" aria-live="polite"><div className="detail-head"><p className="eyebrow">Product detail</p><button type="button" className="quiet" onClick={onClose}>Close</button></div>{loading&&<p role="status">Loading product and merchant offers…</p>}{error&&<div className="notice error" role="alert">{error}</div>}{result&&<><h2 id="detail-title">{result.product.title.value}</h2><p className="trust-note">Product information: {provenanceText[result.product.title.provenance.kind]}. Some descriptions and attributes may require verification.</p>{evaluation?<ProductEvaluationPanel evaluation={evaluation}/>:<p className="notice">Complete a valid purchase goal to evaluate this product.</p>}<h3>{result.product.offers.length} merchant {result.product.offers.length===1?'offer':'offers'}</h3><div className="offers">{result.product.offers.map(offer=><article className="offer" key={providerIdentityKey(offer.identity)}><h4>{offer.merchant?.name||offer.merchant?.domain||'Merchant not named'}</h4><strong className="offer-price">{money(offer)}</strong><span>{availabilityText[offer.availability.state]}</span><div className="offer-links">{safeExternal(offer.productUrl)&&<a href={offer.productUrl} target="_blank" rel="noopener noreferrer">View on merchant site</a>}{safeExternal(offer.handoffUrl)&&<a href={offer.handoffUrl} target="_blank" rel="noopener noreferrer">Continue with merchant</a>}</div></article>)}</div></>}</aside>}

function App(){
 const [application]=useState(createBrowserApplication),state=useCoSourceApplication(application),goal=state.activeGoal,human=state.humanDiscovery,products=human.candidates,agentCandidates=state.agentDiscovery.candidates,comparisonIds=state.comparisonIds
 const [query,setQuery]=useState(''),[validation,setValidation]=useState(''),[detail,setDetail]=useState<CatalogProductResult>(),[detailState,setDetailState]=useState<'closed'|'loading'|'success'|'error'>('closed'),[detailError,setDetailError]=useState('')
 const submitted=human.query,cursor=human.pagination.cursor,hasMore=human.pagination.hasMore,status=human.status==='initial_loading'?'loading':human.status==='pagination_loading'?'loadingMore':human.status,error=human.error?.message??'',searchMode=human.mode==='active_goal_human'?'goal':'exploratory'
 const webmcp=useWebMCP(application)
 const decisionProducts=useMemo(()=>{const map=new Map<string,ProductCluster>();[...products,...agentCandidates].forEach(product=>map.set(providerIdentityKey(product.identity),product));return[...map.values()]},[products,agentCandidates])
 const comparison=comparisonIds.length===2?application.compareCandidates(comparisonIds[0]!,comparisonIds[1]!):undefined,planEvaluation=goal?application.evaluatePurchasePlan():undefined,detailEvaluation=detail?application.evaluateCandidate(detail.product.identity):undefined
 const goalController={goal:state.goalDraft,activeGoal:state.activeGoal,commitmentStatus:application.getGoalCommitmentStatus(),edit:application.editGoal,addCondition:application.addGoalCondition,editCondition:application.editGoalCondition,removeCondition:application.removeGoalCondition,commitGoal:application.commitGoalDraft}
 function presentDiscoveryFailure(result:ApplicationResult<unknown>){if(result.ok||result.code==='stale_state')return;const canonical=application.getSnapshot().humanDiscovery.error;if(canonical?.code!==result.code||canonical.message!==result.message)setValidation(result.message)}
 async function search(nextQuery:string,nextCursor?:string){setValidation('');if(!nextCursor){setDetail(undefined);setDetailState('closed')}const result=await application.searchCandidates({query:nextQuery,cursor:nextCursor,limit:6});presentDiscoveryFailure(result)}
 function submit(event:React.FormEvent){event.preventDefault();const trimmed=query.trim();if(!trimmed){setValidation('Enter a product to search for.');return}setValidation('');void search(trimmed)}
 async function sourceGoal(nextCursor?:string){setValidation('');if(!nextCursor){setDetail(undefined);setDetailState('closed')}const result=await application.sourceCandidatesForActiveGoal({cursor:nextCursor,limit:6});if(result.ok&&result.value.strategy)setQuery(result.value.strategy.query);else presentDiscoveryFailure(result)}
 async function openProduct(product:ProductCluster){setDetail(undefined);setDetailError('');setDetailState('loading');const result=await application.inspectCandidate(product.identity);if(result.ok){setDetail({product:result.value,selectedOptions:[],messages:[]});setDetailState('success')}else{setDetailError(result.message);setDetailState('error')}}
 const selected=(identity:ProviderIdentity)=>comparisonIds.some(item=>sameProviderIdentity(item,identity))
 function approve(id:string){application.approvePlanProposal(id)}
 function reject(id:string){application.rejectPlanProposal(id)}
 return <div className="app-shell"><header className="site-header"><div><a className="brand" href="/">CoSource</a><span>Agent-native commerce intelligence</span></div><p>Human-authored intent · Live discovery</p></header><main>
  <PurchaseGoalPanel {...goalController} sourceGoal={()=>{void sourceGoal()}}/>
  <GoalInterpretationPanel proposals={state.goalInterpretationProposals} statusFor={application.getGoalInterpretationStatus} onAdopt={id=>{application.adoptGoalInterpretation(id)}} onReject={id=>{application.rejectGoalInterpretation(id)}}/>
  <section className="hero" aria-labelledby="page-title"><p className="eyebrow">2 · Search real products</p><h1 id="page-title">Search real products across merchants.</h1><p>Explore product clusters and inspect returned offers without rankings or unsupported suitability claims.</p><form className="search-form" onSubmit={submit}><label htmlFor="product-search">What are you looking for?</label><div className="search-row"><input id="product-search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Try notebook, backpack, or desk lamp" maxLength={500}/><button disabled={status==='loading'}>{status==='loading'?'Searching…':'Search products'}</button></div><p>Searching with {state.market.country} / {state.market.currency} context. Every price keeps its returned currency.</p>{validation&&<p className="validation" role="alert">{validation}</p>}</form></section>
 <section className="discovery" aria-labelledby="results-title"><div className="results-head"><div><p className="eyebrow">Discovery results</p><h2 id="results-title">{submitted?`${status==='stale'?'Stale results':'Results'} for “${submitted}”`:'Ready when you are'}</h2></div>{products.length>0&&<span>{products.length} product {products.length===1?'cluster':'clusters'} shown</span>}</div><div aria-live="polite">{status==='idle'&&<div className="empty-state"><h3>Start with an ordinary product search</h3><p>Results come live through CoSource’s secure commerce gateway.</p></div>}{status==='loading'&&<div className="loading-grid" role="status"><span>Searching the live catalog…</span><i/><i/><i/></div>}{status==='empty'&&<div className="empty-state"><h3>No matching products returned</h3><p>Try a broader product name or check the spelling.</p></div>}{status==='error'&&<div className="notice error" role="alert"><p>{error}</p><button className="secondary" onClick={()=>void(searchMode==='goal'?sourceGoal():search(submitted))}>Try again</button></div>}{status==='stale'&&<div className="notice" role="alert"><p>These visible results were sourced against an earlier goal revision and are stale, not current recommendations. Source again against the current goal to refresh them.</p><button className="secondary" onClick={()=>void sourceGoal()}>Source again against current goal</button></div>}</div>{products.length>0&&<div className="workspace"><div className="results-list">{products.map(product=><ResultCard key={providerIdentityKey(product.identity)} product={product} maximumItemPrice={goal?.maximumItemPrice} comparisonSelected={selected(product.identity)} onToggleComparison={()=>application.toggleComparison(product.identity)} onOpen={()=>void openProduct(product)}/>)}{hasMore&&status!=='stale'&&<button className="load-more" disabled={status==='loadingMore'} onClick={()=>void(searchMode==='goal'?sourceGoal(cursor):search(submitted,cursor))}>{status==='loadingMore'?'Loading more…':'Load more products'}</button>}</div>{detailState!=='closed'&&<Detail result={detail} loading={detailState==='loading'} error={detailError} evaluation={detailEvaluation?.ok?detailEvaluation.value:undefined} onClose={()=>setDetailState('closed')}/>}</div>}</section>
 {human.strategy&&<section className="strategy-summary"><p className="eyebrow">{status==='stale'?'Stale sourcing strategy':'Sourcing strategy'}</p><h2>{status==='stale'?'Previously searched for':'Searching for'} {human.strategy.query}</h2><h3>Applying</h3><ul><li>Available products</li><li>Ships to {human.strategy.market.country}</li>{human.strategy.constraints.maximumPrice&&<li>Maximum item price: {formatMoney(human.strategy.constraints.maximumPrice)}</li>}</ul><h3>Still needs verification</h3>{human.strategy.evidenceGaps.length?<ul>{human.strategy.evidenceGaps.map((gap,index)=><li key={`${gap.goalConditionId??'gap'}-${index}`}>{gap.description}</li>)}</ul>:<p>No discovery-level gaps identified.</p>}</section>}
  {agentCandidates.length>0&&<section className="discovery agent-candidates"><p className="eyebrow">Agent search</p><h2>Real market candidates for human review</h2><p>These candidates are not retained decision evidence until you inspect or compare them.</p><div className="results-list">{agentCandidates.map(product=><ResultCard key={providerIdentityKey(product.identity)} product={product} maximumItemPrice={goal?.maximumItemPrice} comparisonSelected={selected(product.identity)} onToggleComparison={()=>application.toggleComparison(product.identity)} onOpen={()=>void openProduct(product)}/>)}</div><button className="secondary" onClick={application.dismissAgentCandidates}>Dismiss candidates</button></section>}
  {goal&&planEvaluation?.ok&&<><DecisionWorkspace goal={goal} products={decisionProducts} evidenceProducts={state.retainedProducts} plan={state.plan} planEvaluation={planEvaluation.value} comparison={comparison?.ok?comparison.value:undefined} comparisonIds={comparisonIds} onClearComparison={application.clearComparison} onAddProduct={identity=>{application.addCandidateToPlan(identity)}} onRemoveLine={application.removePlanLine} onSetQuantity={application.setPlanLineQuantity} onSelectOffer={application.selectPlanLineOffer} onRebase={application.rebasePlan}/><ProposalReviewPanel proposals={state.proposals} plan={state.plan} products={state.retainedProducts} onApprove={approve} onReject={reject} getReview={application.reviewPlanProposal}/></>}
 </main><WebMCPStatusPanel {...webmcp} activities={state.activities}/><footer><p>Catalog facts may be incomplete or provider-inferred. Verify details with the merchant before purchase.</p></footer></div>
}
export default App
