// @vitest-environment jsdom
import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, describe, expect, it, vi } from 'vitest'
import '@testing-library/jest-dom/vitest'
import App from './App'

const provenance = { kind: 'provider_explicit', provider: 'shopify_global_catalog' }
function product(id: string, title: string, currency = 'GBP', merchant = 'Merchant One') {
  return { identity: { provider: 'shopify_global_catalog', id }, title: { value: title, provenance }, description: { value: 'Provider-created description', provenance: { ...provenance, kind: 'provider_inferred' } }, media: [], featuredOfferId: `${id}-offer`, offerCompleteness: 'featured_only', provenance,
    offers: [{ identity: { provider: 'shopify_global_catalog', id: `${id}-offer` }, title: { value: title, provenance }, merchant: { name: merchant, provenance }, productUrl: 'https://merchant.test/product', handoffUrl: 'https://merchant.test/cart', price: { minorAmount: 2499, currency }, availability: { state: 'available', basis: 'catalog_signal', provenance }, selectedOptions: [], media: [], correlations: [], provenance }] }
}
const ok = (data: unknown) => Promise.resolve(new Response(JSON.stringify({ ok: true, data }), { status: 200, headers: { 'Content-Type': 'application/json' } }))
const commitGoal=()=>userEvent.click(screen.getByRole('button',{name:'Commit draft as active goal'}))
const openExploratory=async()=>{await userEvent.click(screen.getByRole('link',{name:'Discover'}));await userEvent.click(screen.getByText('Exploratory catalog search'))}
afterEach(() => { cleanup();window.history.replaceState(null,'','/'); vi.unstubAllGlobals() })

// Full rendered user-interaction tests need a bounded allowance under aggregate worker contention.
describe('product discovery UI', { timeout: 10_000 }, () => {
  it('keeps the human UI available when WebMCP is unsupported',()=>{render(<App/>);expect(screen.getByText('WebMCP unavailable in this browser')).toBeInTheDocument();expect(screen.getByText('Editable goal draft')).toBeInTheDocument()})
  it('shows real registration and invocation activity with a model context',async()=>{const registered:Array<{tool:WebMCPToolDefinition;signal?:AbortSignal}>=[];const modelContext=Object.assign(new EventTarget(),{async registerTool(tool:WebMCPToolDefinition,options?:{signal?:AbortSignal}){registered.push({tool,signal:options?.signal})}});Object.defineProperty(document,'modelContext',{configurable:true,value:modelContext});try{render(<App/>);expect(await screen.findByText('WebMCP ready')).toBeInTheDocument();expect(screen.getByText('13 registered WebMCP tools')).toBeInTheDocument();const tool=registered.find(item=>item.tool.name==='get_purchase_plan')!.tool;await tool.execute({});await userEvent.click(screen.getByRole('link',{name:'Review'}));await userEvent.click(screen.getByRole('button',{name:'Agent activity'}));expect(await screen.findByText('get_purchase_plan')).toBeInTheDocument();expect(screen.getAllByText(/Read completed/).length).toBeGreaterThan(0);cleanup();expect(registered.every(item=>item.signal?.aborted)).toBe(true)}finally{delete (document as Document&{modelContext?:WebMCPModelContext}).modelContext}})
  it('visibly separates agent interpretation, editable draft, and human-committed active goal',async()=>{const registered:WebMCPToolDefinition[]=[];const modelContext=Object.assign(new EventTarget(),{async registerTool(tool:WebMCPToolDefinition){registered.push(tool)}});Object.defineProperty(document,'modelContext',{configurable:true,value:modelContext});try{render(<App/>);await screen.findByText('WebMCP ready');await userEvent.type(screen.getByLabelText('What are you trying to buy or achieve?'),'Need seating for a small team');const tool=(name:string)=>registered.find(item=>item.name===name)!;let context!:Record<string,unknown>;await act(async()=>{context=await tool('get_goal_context').execute({}) as Record<string,unknown>});const data=context.data as {sessionId:string;draft:{id:string;revision:number}};await act(async()=>{await tool('propose_goal_interpretation').execute({sessionId:data.sessionId,draftId:data.draft.id,draftRevision:data.draft.revision,proposed:{summary:'Seat a small team',searchFocus:'office chairs',quantity:4,requirements:[{id:'adjustable',operator:'free_text',value:'adjustable height'}],preferences:[],exclusions:[]},interpretationNotes:'Structured the human request for review.',assumptions:['One chair per team member.'],unresolvedQuestions:['What material is preferred?']})});expect(await screen.findByRole('heading',{name:'Proposed structured goal'})).toBeInTheDocument();expect(screen.getByText('One chair per team member.')).toBeInTheDocument();expect(screen.getByText('What material is preferred?')).toBeInTheDocument();expect(screen.getByText(/No active goal/)).toBeInTheDocument();expect(screen.getByRole('button',{name:'Adopt into editable draft'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Reject interpretation'})).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Adopt into editable draft'}));expect(screen.getByLabelText('Product being sourced')).toHaveValue('office chairs');expect(screen.getByText(/No active goal/)).toBeInTheDocument();await userEvent.clear(screen.getByLabelText('Quantity optional'));await userEvent.type(screen.getByLabelText('Quantity optional'),'5');expect(screen.getByLabelText('Quantity optional')).toHaveValue(5);await commitGoal();expect(screen.getByRole('heading',{name:'Active purchase goal'})).toBeInTheDocument();expect(screen.getByText(/Committed revision \d+/)).toBeInTheDocument()}finally{delete (document as Document&{modelContext?:WebMCPModelContext}).modelContext}})
  it('builds and edits one transparent structured purchase goal', async () => {
    render(<App />)
    const summary = screen.getByLabelText('What are you trying to buy or achieve?')
    await userEvent.type(summary, 'Six office chairs')
    await userEvent.type(screen.getByLabelText('Quantity optional'), '6')
    await userEvent.type(screen.getByLabelText('Budget amount'), '800')
    await userEvent.click(screen.getByRole('button', { name: 'Add hard requirement' }))
    await userEvent.type(screen.getByLabelText('Must have 1 value'), 'adjustable arms')
    await userEvent.click(screen.getByRole('button', { name: 'Add preference' }))
    await userEvent.type(screen.getByLabelText('Prefer 1 value'), 'black')
    await userEvent.click(screen.getByRole('button', { name: 'Add exclusion' }))
    await userEvent.type(screen.getByLabelText('Exclude 1 value'), 'leather')
    expect(screen.getByText('6 × Six office chairs')).toBeInTheDocument()
    expect(screen.getByText('GBP 800.00')).toBeInTheDocument()
    expect(screen.getByText('adjustable arms')).toBeInTheDocument(); expect(screen.getByText('black')).toBeInTheDocument(); expect(screen.getByText('leather')).toBeInTheDocument()
    await userEvent.click(screen.getByRole('button', { name: 'Remove preference 1' }))
    expect(screen.queryByText('black')).not.toBeInTheDocument()
    expect(screen.queryByText(/product matches|fit score|recommended product/i)).not.toBeInTheDocument()
  })
  it('uses explicit product focus for goal sourcing without interpreting the summary', async () => {
    vi.stubGlobal('fetch',vi.fn().mockResolvedValue(await ok({products:[],messages:[],pagination:{hasMore:false}})));render(<App />);await userEvent.type(screen.getByLabelText('What are you trying to buy or achieve?'),'keep students dry');await userEvent.type(screen.getByLabelText('Product being sourced'),'student raincoats');await commitGoal();await userEvent.click(screen.getByRole('button',{name:/Source active goal/}));expect(screen.getByLabelText('What are you looking for?')).toHaveValue('student raincoats');expect(await screen.findByText('Searching for student raincoats')).toBeInTheDocument()
  })
  it('defaults budget currency to GBP and accepts a real supported currency outside the former shortlist', async () => {
    render(<App />); expect(screen.getByLabelText('Budget currency')).toHaveValue('GBP'); await userEvent.type(screen.getByLabelText('What are you trying to buy or achieve?'), 'Office supplies')
    await userEvent.type(screen.getByLabelText('Budget amount'), '25')
    await userEvent.clear(screen.getByLabelText('Budget currency')); await userEvent.type(screen.getByLabelText('Budget currency'), 'AUD')
    expect(screen.getByText('AUD 25.00')).toBeInTheDocument()
  })
  it('validates empty queries locally', async () => {
    render(<App />);await openExploratory(); await userEvent.click(screen.getByRole('button', { name: 'Search products' }))
    expect(screen.getByRole('alert')).toHaveTextContent('Enter a product')
  })
  it('submits, shows loading, and renders real-shape facts honestly', async () => {
    let resolve!: (value: Response) => void; vi.stubGlobal('fetch', vi.fn(() => new Promise<Response>((done) => { resolve = done })))
    render(<App />);await openExploratory(); await userEvent.type(screen.getByLabelText('What are you looking for?'), '  backpack  '); await userEvent.click(screen.getByRole('button', { name: 'Search products' }))
    expect(screen.getByText('Searching the live catalog…')).toBeInTheDocument()
    resolve(await ok({ products: [product('p1', 'Canvas Backpack')], messages: [], pagination: { hasMore: false } }))
    expect(await screen.findByText('Canvas Backpack')).toBeInTheDocument(); expect(screen.getByText('GBP 24.99')).toBeInTheDocument(); expect(screen.getByText('Inferred details')).toBeInTheDocument(); expect(screen.getByText('Listed as available')).toBeInTheDocument(); expect(screen.getByText(/More offers may be available/)).toBeInTheDocument()
  })
  it('calls an offer featured only when canonical evidence identifies it', async () => {
    const withoutEvidence = product('p1', 'Unranked Bag')
    delete (withoutEvidence as { featuredOfferId?: string }).featuredOfferId
    vi.stubGlobal('fetch', vi.fn().mockResolvedValue(await ok({ products: [withoutEvidence], messages: [], pagination: { hasMore: false } })))
    render(<App />);await openExploratory(); const input = screen.getByLabelText('What are you looking for?'); await userEvent.type(input, 'bag'); fireEvent.submit(input.closest('form')!)
    expect(await screen.findByText('Returned offer')).toBeInTheDocument()
    expect(screen.queryByText('Featured offer')).not.toBeInTheDocument()
  })
  it('renders empty and safe error states', async () => {
    const fetch = vi.fn().mockResolvedValueOnce(await ok({ products: [], messages: [], pagination: { hasMore: false } })).mockResolvedValueOnce(new Response(JSON.stringify({ ok: false, error: { code: 'provider_throttled', message: 'raw', retryAfterSeconds: 5 } }), { status: 429 }))
    vi.stubGlobal('fetch', fetch); render(<App />);await openExploratory(); const input = screen.getByLabelText('What are you looking for?'); await userEvent.type(input, 'nothing'); fireEvent.submit(input.closest('form')!); expect(await screen.findByText('No matching products returned')).toBeInTheDocument(); await userEvent.clear(input); await userEvent.type(input, 'again'); fireEvent.submit(input.closest('form')!); expect(await screen.findByText(/Try again in about 5 seconds/)).toBeInTheDocument()
  })
  it('renders one application-owned provider error and keeps canonical retry',async()=>{const fetch=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({ok:false,error:{code:'provider_throttled',message:'raw',retryAfterSeconds:5}}),{status:429})).mockResolvedValueOnce(await ok({products:[],messages:[],pagination:{hasMore:false}}));vi.stubGlobal('fetch',fetch);render(<App/>);await openExploratory();const input=screen.getByLabelText('What are you looking for?');await userEvent.type(input,'lamp');fireEvent.submit(input.closest('form')!);const message=await screen.findByText(/Try again in about 5 seconds/);expect(message).toBeInTheDocument();expect(screen.getAllByText(/Try again in about 5 seconds/)).toHaveLength(1);expect(screen.getAllByRole('alert')).toHaveLength(1);await userEvent.click(screen.getByRole('button',{name:'Try again'}));expect(await screen.findByText('No matching products returned')).toBeInTheDocument();expect(fetch).toHaveBeenCalledTimes(2)})
  it('appends cursor pagination and resets it for a new search', async () => {
    const fetch = vi.fn().mockResolvedValueOnce(await ok({ products: [product('p1','First')], messages: [], pagination: { hasMore: true, cursor: 'next-1' } })).mockResolvedValueOnce(await ok({ products: [product('p2','Second')], messages: [], pagination: { hasMore: false } })).mockResolvedValueOnce(await ok({ products: [product('p3','Fresh')], messages: [], pagination: { hasMore: false } })); vi.stubGlobal('fetch', fetch)
    render(<App />);await openExploratory(); const input = screen.getByLabelText('What are you looking for?'); await userEvent.type(input,'lamp'); fireEvent.submit(input.closest('form')!); await screen.findByText('First'); await userEvent.click(screen.getByRole('button',{name:'Load more products'})); expect(await screen.findByText('Second')).toBeInTheDocument(); expect(screen.getByText('First')).toBeInTheDocument(); expect(JSON.parse(fetch.mock.calls[1]![1].body)).toMatchObject({ cursor:'next-1' }); await userEvent.clear(input); await userEvent.type(input,'notebook'); fireEvent.submit(input.closest('form')!); await screen.findByText('Fresh'); expect(screen.queryByText('First')).not.toBeInTheDocument()
  })
  it('presents goal-derived results as stale and refreshes without the old cursor',async()=>{let resolveRefresh!:(value:Response)=>void;const fetch=vi.fn().mockResolvedValueOnce(await ok({products:[product('old','Earlier goal result')],messages:[],pagination:{hasMore:true,cursor:'old-cursor'}})).mockImplementationOnce(()=>new Promise<Response>(resolve=>{resolveRefresh=resolve}));vi.stubGlobal('fetch',fetch);render(<App/>);await userEvent.type(screen.getByLabelText('What are you trying to buy or achieve?'),'Furnish an office');let focus=screen.getByLabelText('Product being sourced');await userEvent.type(focus,'chairs');await commitGoal();await userEvent.click(screen.getByRole('button',{name:/Source active goal/}));expect(await screen.findByText('Earlier goal result')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Load more products'})).toBeInTheDocument();await userEvent.click(screen.getByRole('link',{name:'Define'}));focus=screen.getByLabelText('Product being sourced');await userEvent.clear(focus);await userEvent.type(focus,'desks');await commitGoal();await userEvent.click(screen.getByRole('link',{name:'Discover'}));expect(screen.getByText(/earlier goal revision and are stale/i)).toBeInTheDocument();expect(screen.getByText(/Stale results for/)).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Load more products'})).not.toBeInTheDocument();const refresh=screen.getByRole('button',{name:'Source again against current goal'});await userEvent.click(refresh);expect(screen.getByText('Searching the live catalog…')).toBeInTheDocument();expect(screen.queryByText('Earlier goal result')).not.toBeInTheDocument();const body=JSON.parse((fetch.mock.calls[1]![1] as RequestInit).body as string);expect(body).toMatchObject({query:'desks'});expect(body).not.toHaveProperty('cursor');resolveRefresh(await ok({products:[product('fresh','Current goal result')],messages:[],pagination:{hasMore:false}}));expect(await screen.findByText('Current goal result')).toBeInTheDocument()})
  it('shows a pre-lifecycle sourcing failure over an older stale workspace error',async()=>{const fetch=vi.fn().mockResolvedValue(await ok({products:[product('old','Still stale result')],messages:[],pagination:{hasMore:true,cursor:'stale-cursor'}}));vi.stubGlobal('fetch',fetch);render(<App/>);await userEvent.type(screen.getByLabelText('What are you trying to buy or achieve?'),'Furnish an office');let focus=screen.getByLabelText('Product being sourced');await userEvent.type(focus,'chairs');await commitGoal();await userEvent.click(screen.getByRole('button',{name:/Source active goal/}));expect(await screen.findByText('Still stale result')).toBeInTheDocument();await userEvent.click(screen.getByRole('link',{name:'Define'}));focus=screen.getByLabelText('Product being sourced');await userEvent.clear(focus);await commitGoal();await userEvent.click(screen.getByRole('link',{name:'Discover'}));expect(screen.getByText(/earlier goal revision and are stale/i)).toBeInTheDocument();expect(screen.getByRole('button',{name:'Source again against current goal'})).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Load more products'})).not.toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Source again against current goal'}));expect(screen.getByText('A product being sourced is required.')).toHaveClass('validation');expect(fetch).toHaveBeenCalledTimes(1);expect(screen.getByText(/Stale results for/)).toBeInTheDocument();expect(screen.getByText('Still stale result')).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Load more products'})).not.toBeInTheDocument()})
  it('opens richer detail with unranked mixed-currency offers and safe links', async () => {
    const searchProduct = product('p1','Travel Bag'); const detailProduct = { ...searchProduct, offers: [searchProduct.offers[0], product('p2','Travel Bag','USD','Merchant Two').offers[0]] }
    vi.stubGlobal('fetch', vi.fn().mockResolvedValueOnce(await ok({ products:[searchProduct],messages:[],pagination:{hasMore:false} })).mockResolvedValueOnce(await ok({ product:detailProduct,selectedOptions:[],messages:[] })))
    render(<App />);await openExploratory(); const input=screen.getByLabelText('What are you looking for?'); await userEvent.type(input,'bag'); fireEvent.submit(input.closest('form')!); await userEvent.click(await screen.findByRole('button',{name:'View product and offers'})); expect(await screen.findByText('2 merchant offers')).toBeInTheDocument(); expect(screen.getAllByText('GBP 24.99').length).toBeGreaterThan(0); expect(screen.getByText('USD 24.99')).toBeInTheDocument(); expect(screen.queryByText(/recommended merchant|best deal/i)).not.toBeInTheDocument(); await waitFor(() => expect(screen.getAllByRole('link',{name:'View on merchant site'})[0]).toHaveAttribute('rel','noopener noreferrer'))
    expect(screen.getByText('Complete a valid purchase goal to evaluate this product.')).toBeInTheDocument()
  })
  it('renders deterministic evidence evaluation only for a valid goal', async () => {
    const searchProduct = product('p1','Black Bag'); const detailProduct = { ...searchProduct, attributes: { value:[{name:'Colour',value:'Black'}], provenance } }
    vi.stubGlobal('fetch', vi.fn().mockResolvedValueOnce(await ok({products:[searchProduct],messages:[],pagination:{hasMore:false}})).mockResolvedValueOnce(await ok({product:detailProduct,selectedOptions:[],messages:[]})))
    render(<App />); await userEvent.type(screen.getByLabelText('What are you trying to buy or achieve?'),'A black bag'); await userEvent.click(screen.getByRole('button',{name:'Add hard requirement'})); await userEvent.selectOptions(screen.getByLabelText('Must have 1 operator'),'equals'); await userEvent.type(screen.getByLabelText('Must have 1 field'),'colour'); await userEvent.type(screen.getByLabelText('Must have 1 value'),'black')
    await commitGoal();await openExploratory();const input=screen.getByLabelText('What are you looking for?'); await userEvent.type(input,'bag'); fireEvent.submit(input.closest('form')!); await userEvent.click(await screen.findByRole('button',{name:'View product and offers'})); expect(await screen.findByText('Eligible')).toBeInTheDocument(); expect(screen.getByText('Provided field "Colour" is "Black".')).toBeInTheDocument(); expect(screen.queryByText(/match score|best match|top pick/i)).not.toBeInTheDocument()
  })
  it('compares two products and keeps a revisioned human-owned plan', async () => {
    const first=product('p1','First Bag'),second=product('p2','Second Bag')
    vi.stubGlobal('fetch',vi.fn().mockResolvedValue(await ok({products:[first,second],messages:[],pagination:{hasMore:false}})))
    render(<App/>);await userEvent.type(screen.getByLabelText('What are you trying to buy or achieve?'),'A bag');await userEvent.type(screen.getByLabelText('Budget amount'),'30.00');await commitGoal();await openExploratory();const input=screen.getByLabelText('What are you looking for?');await userEvent.type(input,'bag');fireEvent.submit(input.closest('form')!);const compareButtons=await screen.findAllByRole('button',{name:'Select for comparison'});await userEvent.click(compareButtons[0]!);await userEvent.click(compareButtons[1]!);expect(screen.getByText('No clear winner — insufficient evidence')).toBeInTheDocument();const addButtons=screen.getAllByRole('button',{name:'Add to purchase plan'});await userEvent.click(addButtons[0]!);expect(screen.getByText(/Plan revision 1/)).toBeInTheDocument();expect(screen.getByText('Plan budget: unknown')).toBeInTheDocument();expect(screen.getByText((_,element)=>element?.tagName==='STRONG'&&element.textContent?.includes('Conservative landed-cost lower bound:')===true)).toBeInTheDocument();expect(screen.getByText('Exact landed total is not proven.')).toBeInTheDocument();await userEvent.click(screen.getByRole('link',{name:'Define'}));await userEvent.type(screen.getByLabelText('What are you trying to buy or achieve?'),' updated');await commitGoal();await userEvent.click(screen.getByRole('link',{name:'Plan'}));expect(screen.getByRole('alert')).toHaveTextContent('goal changed');await userEvent.click(screen.getByRole('button',{name:'Remove'}));expect(screen.getByText(/A product enters the plan only when you choose/)).toBeInTheDocument();expect(screen.queryByText(/\d+%|recommended|top pick/i)).not.toBeInTheDocument()
  })
  it('retains canonical plan evidence across multiple unrelated searches', async () => {
    const a=product('a','Retained A'),aPeer=product('a-peer','A Peer'),b=product('b','Retained B'),bPeer=product('b-peer','B Peer'),third=product('third','Third Result')
    vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(await ok({products:[a,aPeer],messages:[],pagination:{hasMore:false}})).mockResolvedValueOnce(await ok({products:[b,bPeer],messages:[],pagination:{hasMore:false}})).mockResolvedValueOnce(await ok({products:[third],messages:[],pagination:{hasMore:false}})))
    render(<App/>);await userEvent.type(screen.getByLabelText('What are you trying to buy or achieve?'),'A multi-search plan');await commitGoal();await openExploratory();let input=screen.getByLabelText('What are you looking for?')
    await userEvent.type(input,'category a');fireEvent.submit(input.closest('form')!);let compare=await screen.findAllByRole('button',{name:'Select for comparison'});await userEvent.click(compare[0]!);await userEvent.click(compare[1]!);await userEvent.click(screen.getAllByRole('button',{name:'Add to purchase plan'})[0]!);expect(screen.getAllByText('Retained A').length).toBeGreaterThan(0);await userEvent.click(screen.getByRole('link',{name:'Compare'}));await userEvent.click(screen.getByRole('button',{name:'Clear comparison'}))
    await openExploratory();input=screen.getByLabelText('What are you looking for?');await userEvent.clear(input);await userEvent.type(input,'category b');fireEvent.submit(input.closest('form')!);await screen.findByText('Retained B');compare=await screen.findAllByRole('button',{name:'Select for comparison'});await userEvent.click(compare[0]!);await userEvent.click(compare[1]!);await userEvent.click(screen.getAllByRole('button',{name:'Add to purchase plan'})[0]!);expect(screen.getByText(/Plan revision 2/)).toBeInTheDocument();expect(screen.getByText('Retained A')).toBeInTheDocument();expect(screen.getAllByText('Retained B').length).toBeGreaterThan(0)
    await openExploratory();input=screen.getByLabelText('What are you looking for?');await userEvent.clear(input);await userEvent.type(input,'category c');fireEvent.submit(input.closest('form')!);await screen.findByText('Third Result');await userEvent.click(screen.getByRole('link',{name:'Plan'}));expect(screen.getAllByText('Retained A').length).toBeGreaterThan(0);expect(screen.getAllByText('Retained B').length).toBeGreaterThan(0);expect(screen.getByText((_,element)=>element?.tagName==='STRONG'&&element.textContent?.includes('Listing/base-price subtotal:')===true)).toBeInTheDocument()
  })
  it('promotes a comparison-selected candidate into WebMCP proposal co-activity without pre-adding it',async()=>{
    const candidate=product('candidate','Human-selected candidate'),registered:WebMCPToolDefinition[]=[];const modelContext=Object.assign(new EventTarget(),{async registerTool(tool:WebMCPToolDefinition){registered.push(tool)}});Object.defineProperty(document,'modelContext',{configurable:true,value:modelContext});vi.stubGlobal('fetch',vi.fn().mockResolvedValue(await ok({products:[candidate],messages:[],pagination:{hasMore:false}})))
    try{render(<App/>);await screen.findByText('WebMCP ready');await userEvent.type(screen.getByLabelText('What are you trying to buy or achieve?'),'A candidate product');await commitGoal();await openExploratory();const input=screen.getByLabelText('What are you looking for?');await userEvent.type(input,'candidate');fireEvent.submit(input.closest('form')!);await screen.findByText('Human-selected candidate')
      const tool=(name:string)=>registered.find(item=>item.name===name)!;let retained!:Record<string,unknown>;await act(async()=>{retained=await tool('list_retained_products').execute({}) as Record<string,unknown>});expect((retained.data as {products:unknown[]}).products).toHaveLength(0)
      await userEvent.click(screen.getByRole('button',{name:'Select for comparison'}));await act(async()=>{retained=await tool('list_retained_products').execute({}) as Record<string,unknown>});expect((retained.data as {products:Array<{identity:{id:string};inPlan:boolean}>}).products).toEqual([expect.objectContaining({identity:expect.objectContaining({id:'candidate'}),inPlan:false})])
      await userEvent.click(screen.getByRole('button',{name:'Remove from comparison'}));await act(async()=>{retained=await tool('list_retained_products').execute({}) as Record<string,unknown>});expect((retained.data as {products:unknown[]}).products).toHaveLength(1)
      let requirement!:Record<string,unknown>,plan!:Record<string,unknown>;await act(async()=>{requirement=await tool('get_resource_requirement').execute({}) as Record<string,unknown>;plan=await tool('get_purchase_plan').execute({}) as Record<string,unknown>});const goalData=requirement.data as {id:string;revision:number},planData=plan.data as {id:string;revision:number;lines:unknown[]};expect(planData.lines).toHaveLength(0)
      await act(async()=>{await tool('propose_plan_changes').execute({planId:planData.id,planRevision:planData.revision,goalId:goalData.id,goalRevision:goalData.revision,operations:[{type:'add_retained_product',product:candidate.identity}],reason:'Add the human-selected candidate'})});await userEvent.click(screen.getByRole('link',{name:'Review'}));expect(await screen.findByText('Add the human-selected candidate')).toBeInTheDocument();await act(async()=>{plan=await tool('get_purchase_plan').execute({}) as Record<string,unknown>});expect((plan.data as {revision:number;lines:unknown[]}).lines).toHaveLength(0)
      await userEvent.click(screen.getByRole('button',{name:'Approve and apply'}));await act(async()=>{plan=await tool('get_purchase_plan').execute({}) as Record<string,unknown>});expect(plan.data).toMatchObject({revision:1,lines:[{product:candidate.identity}]})
    }finally{delete (document as Document&{modelContext?:WebMCPModelContext}).modelContext}
  })
  it('retains and refreshes richer opened detail without revising the plan',async()=>{const searchProduct=product('detail','Search evidence'),detailProduct={...searchProduct,title:{value:'Richer canonical detail',provenance},attributes:{value:[{name:'Material',value:'Canvas'}],provenance}},registered:WebMCPToolDefinition[]=[];const modelContext=Object.assign(new EventTarget(),{async registerTool(tool:WebMCPToolDefinition){registered.push(tool)}});Object.defineProperty(document,'modelContext',{configurable:true,value:modelContext});vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(await ok({products:[searchProduct],messages:[],pagination:{hasMore:false}})).mockResolvedValueOnce(await ok({product:detailProduct,selectedOptions:[],messages:[]})))
    try{render(<App/>);await screen.findByText('WebMCP ready');await openExploratory();const input=screen.getByLabelText('What are you looking for?');await userEvent.type(input,'detail');fireEvent.submit(input.closest('form')!);await userEvent.click(await screen.findByRole('button',{name:'View product and offers'}));await screen.findByRole('heading',{name:'Richer canonical detail',level:2});const tool=(name:string)=>registered.find(item=>item.name===name)!;let inspected!:Record<string,unknown>,plan!:Record<string,unknown>;await act(async()=>{inspected=await tool('inspect_product').execute({product:searchProduct.identity}) as Record<string,unknown>;plan=await tool('get_purchase_plan').execute({}) as Record<string,unknown>});expect((inspected.data as {title:{value:string}}).title.value).toBe('Richer canonical detail');expect((plan.data as {revision:number}).revision).toBe(0)}finally{delete (document as Document&{modelContext?:WebMCPModelContext}).modelContext}
  })
  it('keeps WebMCP search candidates separate until human comparison engagement',async()=>{const candidate=product('agent-real','Agent real candidate'),registered:WebMCPToolDefinition[]=[];const modelContext=Object.assign(new EventTarget(),{async registerTool(tool:WebMCPToolDefinition){registered.push(tool)}});Object.defineProperty(document,'modelContext',{configurable:true,value:modelContext});vi.stubGlobal('fetch',vi.fn().mockResolvedValue(await ok({products:[candidate],messages:[],pagination:{hasMore:false}})));try{render(<App/>);await screen.findByText('WebMCP ready');const searchTool=registered.find(tool=>tool.name==='search_products')!,listTool=registered.find(tool=>tool.name==='list_retained_products')!;await act(async()=>{await searchTool.execute({query:'candidate',country:'GB',currency:'GBP',limit:5})});await userEvent.click(screen.getByRole('link',{name:'Discover'}));expect(await screen.findByText('Real market candidates for human review')).toBeInTheDocument();let listed!:Record<string,unknown>;await act(async()=>{listed=await listTool.execute({}) as Record<string,unknown>});expect((listed.data as {products:unknown[]}).products).toHaveLength(0);await userEvent.click(screen.getByRole('button',{name:'Select for comparison'}));await act(async()=>{listed=await listTool.execute({}) as Record<string,unknown>});expect((listed.data as {products:{identity:{id:string}}[]}).products[0]?.identity.id).toBe('agent-real')}finally{delete (document as Document&{modelContext?:WebMCPModelContext}).modelContext}})
  it('shows strategy gaps and flags a returned same-currency item-price conflict',async()=>{const expensive=product('expensive','Expensive raincoat');vi.stubGlobal('fetch',vi.fn().mockResolvedValue(await ok({products:[expensive],messages:[],pagination:{hasMore:false}})));render(<App/>);await userEvent.type(screen.getByLabelText('What are you trying to buy or achieve?'),'Keep students dry');await userEvent.type(screen.getByLabelText('Product being sourced'),'student raincoats');await userEvent.type(screen.getByLabelText('Quantity optional'),'150');await userEvent.type(screen.getByLabelText('Maximum item price amount'),'20.00');await userEvent.click(screen.getByRole('button',{name:'Add hard requirement'}));await userEvent.type(screen.getByLabelText('Must have 1 value'),'waterproof');await commitGoal();await userEvent.click(screen.getByRole('button',{name:/Source active goal/}));expect(await screen.findByText('Known conflict — exceeds maximum item price')).toBeInTheDocument();expect(screen.getByText('Quantity 150')).toBeInTheDocument();expect(screen.getAllByText('waterproof')).toHaveLength(1);const fetchMock=vi.mocked(fetch),body=JSON.parse((fetchMock.mock.calls[0]![1] as RequestInit).body as string);expect(body).toMatchObject({query:'student raincoats',maximumPrice:{minorAmount:2000,currency:'GBP'},available:true,shipsTo:'GB'});expect(body).not.toHaveProperty('budget')})
})
