import {useCallback,useEffect,useMemo,useState} from 'react'
import './App.css'
import {SupplierIntelligencePanel} from './suppliers/SupplierIntelligencePanel'
import {EvidenceResolutionPanel} from './evidence/EvidenceResolutionPanel'
import type {MerchantOffer,ProductCluster,ProvenanceKind,ProviderIdentity} from './commerce/domain/commerce'
import {providerIdentityKey,sameProviderIdentity} from './commerce/domain/provider-identity'
import type {CatalogProductResult} from './commerce/providers/catalog-provider'
import {formatMoney,MoneyDisplayError} from './commerce/domain/money-display'
import {PurchaseGoalPanel} from './goals/PurchaseGoalPanel'
import {GoalInterpretationPanel} from './goals/GoalInterpretationPanel'
import type {ProductEvaluation} from './evaluation/domain/product-evaluation'
import {ProductEvaluationPanel} from './evaluation/ProductEvaluationPanel'
import {DecisionWorkspace,ScenarioPlanningPanel} from './planning/DecisionWorkspace'
import {useWebMCP} from './webmcp/use-webmcp'
import {createBrowserApplication} from './application/browser-application'
import {useCoSourceApplication} from './application/use-cosource-application'
import {usePersistence} from './application/persistence/use-persistent-application'
import {useProjectPortfolio} from './application/portfolio/use-project-portfolio'
import type {ProjectPortfolio,PortfolioSnapshot} from './application/portfolio/project-portfolio-controller'
import {ProjectControls} from './application/portfolio/ProjectControls'
import type {PersistentApplication} from './application/persistence/persistent-application'
import type {ApplicationResult} from './application/cosource-application'
import {OperationsPanel} from './operations/OperationsPanel'
import {WorkspaceHealthPanel} from './monitoring/WorkspaceHealthPanel'
import {composeWorkspaceHealth} from './monitoring/domain/workspace-health'
import {formatGoalCondition} from './goals/domain/condition-presentation'
import {WorkspaceHeader,WorkspaceNavigation,type WorkspaceView} from './workspace/WorkspaceHeader'
import {journeyAction} from './workspace/journey'
import {CollaborationWorkspace} from './workspace/CollaborationWorkspace'
import './workspace/C2.css'
import './workspace/Responsive.css'
import './workspace/CUX2.css'

const availabilityText={available:'Listed as available',unavailable:'Unavailable',unknown:'Availability not confirmed'}
const provenanceText:Record<ProvenanceKind,string>={provider_explicit:'Provided',provider_inferred:'Inferred',cosource_derived:'Derived',unknown:'Unknown'}
function money(offer:MerchantOffer){try{return formatMoney(offer.price)}catch(error){return error instanceof MoneyDisplayError?'Price unavailable — unsupported currency':'Price unavailable'}}
const safeExternal=(url?:string)=>url?.startsWith('https://')?url:undefined
function ProductImage({product}:{product:ProductCluster}){const[broken,setBroken]=useState(false),image=product.media[0];return image&&!broken?<img src={image.url} alt={image.altText||product.title.value} loading="lazy" onError={()=>setBroken(true)}/>:<div className="image-fallback">No image</div>}
function ResultCard({product,onOpen,comparisonSelected,onToggleComparison,maximumItemPrice}:{product:ProductCluster;onOpen:()=>void;comparisonSelected:boolean;onToggleComparison:()=>void;maximumItemPrice?:{minorAmount:number;currency:string}}){const featured=product.featuredOfferId?product.offers.find(offer=>offer.identity.provider===product.identity.provider&&offer.identity.id===product.featuredOfferId):undefined,displayedOffer=featured??product.offers[0],priceConflict=Boolean(displayedOffer&&maximumItemPrice&&displayedOffer.price.currency===maximumItemPrice.currency&&displayedOffer.price.minorAmount>maximumItemPrice.minorAmount);return <article className="result-card"><ProductImage product={product}/><div className="card-copy"><div className="card-labels"><span>Product cluster</span>{product.description?.provenance.kind==='provider_inferred'&&<span className="evidence">Inferred details</span>}</div><h3>{product.title.value}</h3>{product.description&&<p className="description">{product.description.value}</p>}{displayedOffer?<div className="featured"><span>{featured?'Featured offer':'Returned offer'}</span><strong>{money(displayedOffer)}</strong><span>{displayedOffer.merchant?.name||displayedOffer.merchant?.domain||'Merchant not named'}</span><span>{availabilityText[displayedOffer.availability.state]}</span></div>:<p>No offer was returned for this cluster.</p>}{priceConflict&&<p className="notice error">Known conflict — exceeds maximum item price</p>}<p className="completeness">More offers may be available. Open the product to check.</p><div className="offer-links"><button type="button" className="secondary" onClick={onOpen}>View product and offers</button><button type="button" className="secondary" aria-pressed={comparisonSelected} onClick={onToggleComparison}>{comparisonSelected?'Remove from comparison':'Select for comparison'}</button></div></div></article>}
function Detail({result,loading,error,onClose,evaluation}:{result?:CatalogProductResult;loading:boolean;error?:string;onClose:()=>void;evaluation?:ProductEvaluation}){return <aside className="detail" aria-labelledby="detail-title" aria-live="polite"><div className="detail-head"><p className="eyebrow">Product detail</p><button type="button" className="quiet" onClick={onClose}>Close</button></div>{loading&&<p role="status">Loading product and merchant offers…</p>}{error&&<div className="notice error" role="alert">{error}</div>}{result&&<><h2 id="detail-title">{result.product.title.value}</h2><p className="trust-note">Product information: {provenanceText[result.product.title.provenance.kind]}. Some descriptions and attributes may require verification.</p>{evaluation?<ProductEvaluationPanel evaluation={evaluation}/>:<p className="notice">Complete a valid purchase goal to evaluate this product.</p>}<h3>{result.product.offers.length} merchant {result.product.offers.length===1?'offer':'offers'}</h3><div className="offers">{result.product.offers.map(offer=><article className="offer" key={providerIdentityKey(offer.identity)}><h4>{offer.merchant?.name||offer.merchant?.domain||'Merchant not named'}</h4><strong className="offer-price">{money(offer)}</strong><span>{availabilityText[offer.availability.state]}</span><div className="offer-links">{safeExternal(offer.productUrl)&&<a href={offer.productUrl} target="_blank" rel="noopener noreferrer">View on merchant site</a>}{safeExternal(offer.handoffUrl)&&<a href={offer.handoffUrl} target="_blank" rel="noopener noreferrer">Continue with merchant</a>}</div></article>)}</div></>}</aside>}

function StageHeader({title,purpose,status,back,next,nextEnabled=true,onNavigate}:{title:string;purpose:string;status:string;back?:{view:WorkspaceView;href:string;label:string};next?:{view:WorkspaceView;href:string;label:string};nextEnabled?:boolean;onNavigate:(view:WorkspaceView,href:string)=>void}){
 return <header className="stage-header"><div><p className="eyebrow">Active workflow stage</p><h1>{title}</h1><p>{purpose}</p><span className="stage-state">{status}</span></div><nav aria-label={`${title} stage controls`}>{back&&<a className="secondary button-link" href={back.href} onClick={()=>onNavigate(back.view,back.href)}>Back · {back.label}</a>}{next&&(nextEnabled?<a className="button-link" href={next.href} onClick={()=>onNavigate(next.view,next.href)}>Continue · {next.label}</a>:<span className="button-link disabled" aria-disabled="true">Continue · {next.label}</span>)}</nav></header>
}

function ProjectApp({persistent,portfolio,portfolioSnapshot}:{persistent:PersistentApplication;portfolio:ProjectPortfolio;portfolioSnapshot:PortfolioSnapshot}){
 const application=persistent.application,persistence=usePersistence(persistent),state=useCoSourceApplication(application),goal=state.activeGoal,human=state.humanDiscovery,products=human.candidates,agentCandidates=state.agentDiscovery.candidates,comparisonIds=state.comparisonIds
 const initialAdvancedTarget=['#evidence-resolution','#supplier-intelligence','#scenario-planning','#supervised-operations'].includes(window.location.hash)
 const initialView=(()=>{const hash=window.location.hash;if(hash==='#workspace-overview')return'overview';if(hash==='#stage-define')return'define';if(hash==='#stage-discover')return'discover';if(hash==='#stage-compare')return'compare';if(hash==='#stage-plan')return'plan';if(hash==='#stage-review')return'review';if(initialAdvancedTarget||hash==='#decision-intelligence')return'intelligence';return journeyAction(state).href.slice(7) as WorkspaceView})()
 type IntelligenceView='evidence'|'suppliers'|'scenarios'|'operations'
 const initialIntelligence: IntelligenceView=window.location.hash==='#supplier-intelligence'?'suppliers':window.location.hash==='#scenario-planning'?'scenarios':window.location.hash==='#supervised-operations'?'operations':'evidence'
 const [query,setQuery]=useState(''),[validation,setValidation]=useState(''),[detail,setDetail]=useState<CatalogProductResult>(),[detailState,setDetailState]=useState<'closed'|'loading'|'success'|'error'>('closed'),[detailError,setDetailError]=useState(''),[activeView,setActiveView]=useState<WorkspaceView>(initialView),[intelligenceView,setIntelligenceView]=useState<IntelligenceView>(initialIntelligence),[mountedIntelligence,setMountedIntelligence]=useState<IntelligenceView[]>(initialAdvancedTarget?[initialIntelligence]:[]),[contextOpen,setContextOpen]=useState(()=>window.innerWidth>=1100)
 const submitted=human.query,cursor=human.pagination.cursor,hasMore=human.pagination.hasMore,status=human.status==='initial_loading'?'loading':human.status==='pagination_loading'?'loadingMore':human.status,error=human.error?.message??'',searchMode=human.mode==='active_goal_human'?'goal':'exploratory'
 const gatedRecovery=persistence.status==='recovery_required'&&persistence.access==='gated',webmcp=useWebMCP(application,persistence.status!=='restoring'&&persistence.status!=='recovery_required')
 const decisionProducts=useMemo(()=>{const map=new Map<string,ProductCluster>();[...products,...agentCandidates].forEach(product=>map.set(providerIdentityKey(product.identity),product));return[...map.values()]},[products,agentCandidates])
 const comparison=comparisonIds.length===2?application.compareCandidates(comparisonIds[0]!,comparisonIds[1]!):undefined,planEvaluation=goal?application.evaluatePurchasePlan():undefined,scenarios=goal?application.getScenarios():undefined,detailEvaluation=detail?application.evaluateCandidate(detail.product.identity):undefined,projectHealth=application.getWorkspaceHealth()
 const goalController={goal:state.goalDraft,activeGoal:state.activeGoal,commitmentStatus:application.getGoalCommitmentStatus(),edit:application.editGoal,addCondition:application.addGoalCondition,editCondition:application.editGoalCondition,removeCondition:application.removeGoalCondition,commitGoal:application.commitGoalDraft}
 const revealTarget=useCallback((target:string)=>{const area:IntelligenceView=target==='#supplier-intelligence'?'suppliers':target==='#scenario-planning'?'scenarios':target==='#supervised-operations'?'operations':'evidence';if(!['#evidence-resolution','#supplier-intelligence','#scenario-planning','#supervised-operations','#decision-intelligence'].includes(target))return;setActiveView('intelligence');setIntelligenceView(area);setMountedIntelligence(current=>current.includes(area)?current:[...current,area]);window.requestAnimationFrame(()=>document.querySelector<HTMLElement>('#decision-intelligence')?.scrollIntoView?.({block:'start'}))},[])
 const navigateView=useCallback((view:WorkspaceView,target:string)=>{setActiveView(view);if(view==='intelligence')revealTarget(target);else window.requestAnimationFrame(()=>document.querySelector<HTMLElement>(target)?.scrollIntoView?.({block:'start'}))},[revealTarget])
 useEffect(()=>{const reveal=()=>{const hash=window.location.hash;const stage=hash.match(/^#stage-(define|discover|compare|plan|review)$/)?.[1] as WorkspaceView|undefined;if(stage)setActiveView(stage);else if(hash==='#workspace-overview')setActiveView('overview');else revealTarget(hash)};reveal();window.addEventListener('hashchange',reveal);return()=>window.removeEventListener('hashchange',reveal)},[revealTarget])
 useEffect(()=>{const sync=()=>setContextOpen(window.innerWidth>=1100);window.addEventListener('resize',sync);return()=>window.removeEventListener('resize',sync)},[])
 function presentDiscoveryFailure(result:ApplicationResult<unknown>){if(result.ok||result.code==='stale_state')return;const canonical=application.getSnapshot().humanDiscovery.error;if(canonical?.code!==result.code||canonical.message!==result.message)setValidation(result.message)}
 async function search(nextQuery:string,nextCursor?:string){setValidation('');if(!nextCursor){setDetail(undefined);setDetailState('closed')}const result=await application.searchCandidates({query:nextQuery,cursor:nextCursor,limit:6});presentDiscoveryFailure(result)}
 function submit(event:React.FormEvent){event.preventDefault();const trimmed=query.trim();if(!trimmed){setValidation('Enter a product to search for.');return}setValidation('');void search(trimmed)}
 async function sourceGoal(nextCursor?:string){setValidation('');if(!nextCursor){setDetail(undefined);setDetailState('closed')}const result=await application.sourceCandidatesForActiveGoal({cursor:nextCursor,limit:6});if(result.ok&&result.value.strategy)setQuery(result.value.strategy.query);else presentDiscoveryFailure(result)}
 async function openProduct(product:ProductCluster){setDetail(undefined);setDetailError('');setDetailState('loading');const result=await application.inspectCandidate(product.identity);if(result.ok){setDetail({product:result.value,selectedOptions:[],messages:[]});setDetailState('success')}else{setDetailError(result.message);setDetailState('error')}}
 const selected=(identity:ProviderIdentity)=>comparisonIds.some(item=>sameProviderIdentity(item,identity))
 function toggleComparison(identity:ProviderIdentity){const wasSelected=selected(identity);application.toggleComparison(identity);if(!wasSelected&&comparisonIds.length===1)navigateView('compare','#stage-compare')}
 function approve(id:string){application.approvePlanProposal(id)}
 function reject(id:string){application.rejectPlanProposal(id)}
 function loadExample(){
  const draft=application.getSnapshot().goalDraft
  ;(['requirement','preference','exclusion'] as const).forEach(kind=>{const key=kind==='requirement'?'requirements':kind==='preference'?'preferences':'exclusions';draft[key].forEach(item=>application.removeGoalCondition(kind,item.id))})
  application.editGoal({summary:'Equip a 12-person mobile design team with reliable business laptops',searchFocus:'business laptop',quantity:12,maximumItemPrice:{minorAmount:150000,currency:'GBP'},budget:{minorAmount:1800000,currency:'GBP'}})
  const add=(kind:'requirement'|'preference'|'exclusion',value:string)=>{application.addGoalCondition(kind);const key=kind==='requirement'?'requirements':kind==='preference'?'preferences':'exclusions',item=application.getSnapshot().goalDraft[key].at(-1);if(item)application.editGoalCondition(kind,item.id,{operator:'free_text',value})}
  add('requirement','32 GB RAM');add('requirement','1 TB SSD');add('requirement','Three-year warranty');add('preference','Repairable design');add('preference','Replaceable storage');add('exclusion','Refurbished devices')
 }
 if(persistence.status==='restoring')return <main className="persistence-gate" aria-busy="true"><h1>Restoring your CoSource workspace…</h1><p role="status" aria-live="polite">Checking this device for saved decision work.</p></main>
 if(gatedRecovery)return <main className="persistence-gate"><h1>Saved workspace needs recovery</h1><p role="alert">{persistence.message} It has not been changed or deleted.</p><button onClick={()=>void persistent.retry()}>Try restoration again</button></main>
 const persistenceText=persistence.status==='saving'?'Saving changes locally…':persistence.status==='save_error'?'Changes are not safely stored.':persistence.status==='unavailable'?persistence.message:persistence.status==='recovery_required'?'Workspace preserved in memory — saved data needs recovery. Local saving and agent tools are disabled.':persistence.status==='conflict'?'Save conflict — another tab stored a newer workspace.':persistence.lastSavedAt?`Saved locally ${new Date(persistence.lastSavedAt).toLocaleString()}`:'Local workspace ready',persistenceFacts=persistence.status==='ready'||persistence.status==='saving'?{status:persistence.status,retrySupported:false}:{status:persistence.status,retrySupported:persistence.status==='save_error'||persistence.status==='recovery_required'||persistence.status==='unavailable'&&persistence.retryCapability==='supported',...('message'in persistence?{message:persistence.message}:{}),...('access'in persistence?{access:persistence.access}:{})},health=composeWorkspaceHealth(projectHealth,{persistence:persistenceFacts,webmcp:{status:webmcp.status,toolCount:webmcp.toolCount,requiredToolCount:13}})
 const persistenceNode=<span id="persistence-status" className={`header-save-state persistence-${persistence.status}`} role={persistence.status==='save_error'||persistence.status==='recovery_required'||persistence.status==='conflict'?'alert':'status'} aria-live="polite">{persistenceText}</span>
 return <div className="app-shell"><div id="webmcp-status"><WorkspaceHeader state={state} commitment={application.getGoalCommitmentStatus()} webmcp={webmcp.status} toolCount={webmcp.toolCount} projectControls={<ProjectControls portfolio={portfolio} snapshot={portfolioSnapshot}/>} persistenceStatus={persistenceNode}/></div><div className="workspace-shell"><WorkspaceNavigation state={state} activeView={activeView} onNavigate={navigateView}/><main className="active-workspace" data-active-view={activeView}>
  {activeView==='overview'&&<section className="overview-workspace" id="workspace-overview"><p className="eyebrow">Operational overview</p><h1>CoSource turns a resource requirement into an evidence-backed, human-approved plan.</h1><div className="overview-summary"><div><h2>Current project</h2><p>{goal?.summary??'No requirement committed yet.'}</p><p><strong>Status:</strong> {health.status.replaceAll('_',' ')} · {health.counts.blocking} blocking · {health.counts.attention} attention</p></div><div><h2>Live source</h2><p>Shopify Global Catalog supplies current product and offer evidence. The provider-neutral engine can support other truthful resource sources when connected.</p></div><div><h2>Human and agent roles</h2><p>Agents research, evaluate and propose. You commit requirements, select candidates, change the plan and approve consequential decisions.</p></div></div><ol className="process-line" aria-label="CoSource process"><li>Define</li><li>Source</li><li>Compare</li><li>Resolve</li><li>Plan</li><li>Approve</li></ol><aside className="overview-next"><strong>Safest next action</strong><a className="button-link" href={journeyAction(state).href} onClick={()=>navigateView(journeyAction(state).href.slice(7) as WorkspaceView,journeyAction(state).href)}>{journeyAction(state).label}</a></aside></section>}
  {activeView==='define'&&<><StageHeader title="Define" purpose="Build and explicitly commit the requirement that controls sourcing." status={application.getGoalCommitmentStatus().replaceAll('_',' ')} back={{view:'overview',href:'#workspace-overview',label:'Overview'}} next={{view:'discover',href:'#stage-discover',label:'Discover'}} nextEnabled={Boolean(goal)} onNavigate={navigateView}/><PurchaseGoalPanel {...goalController} loadExample={loadExample} sourceGoal={()=>{navigateView('discover','#stage-discover');void sourceGoal()}}/>{state.goalInterpretationProposals.length>0?<GoalInterpretationPanel proposals={state.goalInterpretationProposals} statusFor={application.getGoalInterpretationStatus} onAdopt={id=>{application.adoptGoalInterpretation(id)}} onReject={id=>{application.rejectGoalInterpretation(id)}}/>:<aside className="interpretation-guidance"><strong>Agent goal interpretations are optional.</strong><span>Any proposal appears here for human review and changes only the editable draft when adopted.</span></aside>}</>}
  {activeView==='discover'&&<><StageHeader title="Discover" purpose="Source live catalog evidence against the committed requirement." status={status.replaceAll('_',' ')} back={{view:'define',href:'#stage-define',label:'Define'}} next={{view:'compare',href:'#stage-compare',label:'Compare'}} nextEnabled={comparisonIds.length===2} onNavigate={navigateView}/><section className="hero" id="stage-discover" aria-labelledby="page-title"><p className="eyebrow">Shopify Global Catalog</p><h2 id="page-title">Source against the active requirement.</h2>{goal?<div className="goal-source-action"><div><strong>{goal.searchFocus??goal.summary}</strong><span>Applies the committed requirement, market and supported constraints.</span></div><button type="button" aria-label="Source requirement with active constraints" disabled={status==='loading'} onClick={()=>void sourceGoal()}>{status==='loading'?'Sourcing…':'Source active requirement'}</button></div>:<p>Commit a valid requirement to make evidence-led sourcing the primary action.</p>}<details className="exploratory-search"><summary>Exploratory catalog search</summary><form className="search-form" onSubmit={submit}><label htmlFor="product-search">Exploratory search</label><div className="search-row"><input id="product-search" aria-label="What are you looking for?" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Try business laptop or mobile workstation" maxLength={500}/><button className="secondary" aria-label="Search products" disabled={status==='loading'}>{status==='loading'?'Searching…':'Explore catalog'}</button></div><p>Separate from active sourcing · {state.market.country} / {state.market.currency}.</p>{validation&&<p className="validation" role="alert">{validation}</p>}</form></details></section>
 {(status!=='idle'||products.length>0)&&<section className="discovery" aria-labelledby="results-title"><div className="results-head"><div><p className="eyebrow">Discovery results</p><h2 id="results-title">{submitted?`${status==='stale'?'Stale results':'Results'} for “${submitted}”`:'Evidence-led sourcing'}</h2></div>{products.length>0&&<span>{products.length} product {products.length===1?'cluster':'clusters'} shown</span>}</div><div aria-live="polite">{status==='loading'&&<div className="loading-grid" role="status"><span>Searching the live catalog…</span><i/><i/><i/></div>}{status==='empty'&&<div className="empty-state"><h3>No matching products returned</h3><p>Try a broader product name or check the spelling.</p></div>}{status==='error'&&<div className="notice error" role="alert"><p>{error}</p><button className="secondary" onClick={()=>void(searchMode==='goal'?sourceGoal():search(submitted))}>Try again</button></div>}{status==='stale'&&<div className="notice" role="alert"><p>These visible results were sourced against an earlier goal revision and are stale, not current recommendations. Source again against the current goal to refresh them.</p><button className="secondary" onClick={()=>void sourceGoal()}>Source again against current goal</button></div>}</div>{products.length>0&&<div className="workspace"><div className="results-list">{products.map(product=><ResultCard key={providerIdentityKey(product.identity)} product={product} maximumItemPrice={goal?.maximumItemPrice} comparisonSelected={selected(product.identity)} onToggleComparison={()=>toggleComparison(product.identity)} onOpen={()=>void openProduct(product)}/>)}{hasMore&&status!=='stale'&&<button className="load-more" disabled={status==='loadingMore'} onClick={()=>void(searchMode==='goal'?sourceGoal(cursor):search(submitted,cursor))}>{status==='loadingMore'?'Loading more…':'Load more products'}</button>}</div>{detailState!=='closed'&&<Detail result={detail} loading={detailState==='loading'} error={detailError} evaluation={detailEvaluation?.ok?detailEvaluation.value:undefined} onClose={()=>setDetailState('closed')}/>}</div>}</section>}
 {human.strategy&&<details className="strategy-summary"><summary>Sourcing method and gaps</summary><p className="eyebrow">{status==='stale'?'Stale sourcing strategy':'Sourcing strategy'}</p><h2>{status==='stale'?'Previously searched for':'Searching for'} {human.strategy.query}</h2>{human.sourcingPlan&&<><p>Requirement revision {human.sourcingPlan.requirementRevision}. Source searched: {human.sourcingPlan.legs.map(leg=>leg.source.name).join(', ')||'No capable source'}.</p><h3>What CoSource asked the source to enforce</h3><ul>{human.sourcingPlan.legs.flatMap(leg=>leg.projectedInput.appliedConstraints.map(condition=><li key={`${leg.source.id}-applied-${condition.id}`}>Applied: {formatGoalCondition(condition)}</li>))}{human.sourcingPlan.legs.flatMap(leg=>leg.limitations.map((gap,index)=><li key={`${leg.source.id}-limitation-${gap.constraintId??index}`}>{leg.source.name} could not apply: {gap.description}</li>))}{human.sourcingPlan.mandatoryGaps.map((gap,index)=><li key={`mandatory-${gap.constraintId??index}`}>Still required across all sources: {gap.description}</li>)}{human.sourcingPlan.preferenceGaps.map((gap,index)=><li key={`preference-${gap.constraintId??index}`}>Preference still unresolved: {gap.description}</li>)}{human.sourcingPlan.capabilityWarnings.map((warning,index)=><li key={`warning-${index}`}>{warning}</li>)}</ul></>}<h3>Applying</h3><ul><li>Available products</li><li>Ships to {human.strategy.market.country}</li>{human.strategy.constraints.maximumPrice&&<li>Maximum item price: {formatMoney(human.strategy.constraints.maximumPrice)}</li>}</ul><h3>Still needs verification</h3>{human.strategy.evidenceGaps.length?<ul>{human.strategy.evidenceGaps.map((gap,index)=><li key={`${gap.goalConditionId??'gap'}-${index}`}>{gap.description}</li>)}</ul>:<p>No discovery-level gaps identified.</p>}</details>}
  {agentCandidates.length>0&&<section className="discovery agent-candidates"><p className="eyebrow">Agent search</p><h2>Real market candidates for human review</h2><p>These candidates are not retained decision evidence until you inspect or compare them.</p><div className="results-list">{agentCandidates.map(product=><ResultCard key={providerIdentityKey(product.identity)} product={product} maximumItemPrice={goal?.maximumItemPrice} comparisonSelected={selected(product.identity)} onToggleComparison={()=>application.toggleComparison(product.identity)} onOpen={()=>void openProduct(product)}/>)}</div><button className="secondary" onClick={application.dismissAgentCandidates}>Dismiss candidates</button></section>}</>}
  {!goal&&activeView==='compare'&&<><StageHeader title="Compare" purpose="Compare two human-selected candidates without scoring or automatic recommendation." status="Unavailable until a requirement is committed" back={{view:'discover',href:'#stage-discover',label:'Discover'}} next={{view:'plan',href:'#stage-plan',label:'Plan'}} nextEnabled={false} onNavigate={navigateView}/><section className="locked-stage" id="stage-compare" aria-labelledby="locked-compare-title"><h2 id="locked-compare-title">Commit a goal before comparing candidates.</h2><p>Then source real products, inspect their evidence, and select two candidates.</p><a className="button-link" href="#stage-define" onClick={()=>navigateView('define','#stage-define')}>Define and commit a goal</a></section></>}
  {!goal&&activeView==='plan'&&<><StageHeader title="Plan" purpose="Assemble human-selected lines, offers, quantities and known costs." status="Unavailable until comparison" back={{view:'compare',href:'#stage-compare',label:'Compare'}} next={{view:'review',href:'#stage-review',label:'Review'}} nextEnabled={false} onNavigate={navigateView}/><section className="locked-stage locked-plan" id="stage-plan" aria-labelledby="locked-plan-title"><h2 id="locked-plan-title">The purchase plan follows a human comparison decision.</h2><p>Nothing is added automatically.</p></section></>}
  {goal&&planEvaluation?.ok&&(activeView==='compare'||activeView==='plan')&&<><StageHeader title={activeView==='compare'?'Compare':'Plan'} purpose={activeView==='compare'?'Compare known, conflicting and missing evidence side by side.':'Assemble selected lines, offers, quantities and known cost coverage.'} status={activeView==='compare'?`${comparisonIds.length} of 2 candidates selected`:planEvaluation.value.status.replaceAll('_',' ')} back={activeView==='compare'?{view:'discover',href:'#stage-discover',label:'Discover'}:{view:'compare',href:'#stage-compare',label:'Compare'}} next={activeView==='compare'?{view:'plan',href:'#stage-plan',label:'Plan'}:{view:'review',href:'#stage-review',label:'Review'}} nextEnabled={activeView==='compare'?comparisonIds.length===2:state.plan.lines.length>0} onNavigate={navigateView}/><DecisionWorkspace
    goal={goal} products={decisionProducts} evidenceProducts={state.retainedProducts} evidenceEntries={state.retainedEvidence} evidenceRefresh={state.evidenceRefresh} plan={state.plan} planEvaluation={planEvaluation.value}
    comparison={comparison?.ok?comparison.value:undefined} comparisonIds={comparisonIds} pendingProposal={state.proposals.some(proposal=>proposal.status==='pending')}
    onClearComparison={application.clearComparison} onAddProduct={identity=>{application.addCandidateToPlan(identity);navigateView('plan','#stage-plan')}} onRemoveLine={application.removePlanLine}
    activeView={activeView==='plan'?'plan':'compare'} onSetQuantity={application.setPlanLineQuantity} onSelectOffer={application.selectPlanLineOffer} onRebase={application.rebasePlan} onRefreshEvidence={application.refreshRetainedEvidence}/></>}
  {activeView==='review'&&<><StageHeader title="Review" purpose="Inspect agent proposals and the human decision trail before any consequential change." status={`${state.proposals.filter(proposal=>proposal.status==='pending').length} pending proposals`} back={{view:'plan',href:'#stage-plan',label:'Plan'}} next={{view:'intelligence',href:'#decision-intelligence',label:'Decision intelligence'}} onNavigate={navigateView}/><CollaborationWorkspace proposals={state.proposals} plan={state.plan} products={state.retainedProducts} onApprove={approve} onReject={reject} getReview={application.reviewPlanProposal} {...webmcp} activities={state.activities}/></>}
  {activeView==='intelligence'&&<><StageHeader title="Decision intelligence" purpose="Resolve evidence, assess suppliers, test scenarios and supervise operations one area at a time." status={intelligenceView} back={{view:'review',href:'#stage-review',label:'Review'}} onNavigate={navigateView}/><section className="advanced-workspace" id="decision-intelligence" aria-labelledby="advanced-workspace-title"><h2 id="advanced-workspace-title" className="sr-only">Decision intelligence workspace</h2><nav className="intelligence-nav" aria-label="Decision intelligence areas"><a href="#evidence-resolution" aria-current={intelligenceView==='evidence'?'page':undefined} onClick={()=>revealTarget('#evidence-resolution')}>Evidence</a><a href="#supplier-intelligence" aria-current={intelligenceView==='suppliers'?'page':undefined} onClick={()=>revealTarget('#supplier-intelligence')}>Suppliers</a><a href="#scenario-planning" aria-current={intelligenceView==='scenarios'?'page':undefined} onClick={()=>revealTarget('#scenario-planning')}>Scenarios</a>{goal&&<a href="#supervised-operations" aria-current={intelligenceView==='operations'?'page':undefined} onClick={()=>revealTarget('#supervised-operations')}>Operations</a>}</nav><div className="advanced-workspace-body">{mountedIntelligence.includes('evidence')&&<div hidden={intelligenceView!=='evidence'}><EvidenceResolutionPanel application={application} state={state}/></div>}{mountedIntelligence.includes('suppliers')&&<div id="supplier-intelligence" hidden={intelligenceView!=='suppliers'}><SupplierIntelligencePanel application={application} state={state}/></div>}{mountedIntelligence.includes('scenarios')&&<div hidden={intelligenceView!=='scenarios'}><ScenarioPlanningPanel scenarios={scenarios?.ok?scenarios.value:undefined} onApplyScenario={application.applyScenario}/></div>}{goal&&mountedIntelligence.includes('operations')&&<div id="supervised-operations" hidden={intelligenceView!=='operations'}><OperationsPanel application={application} state={state}/></div>}</div></section></>}
 </main><aside aria-label="Workspace context"><details className="context-rail" open={contextOpen} onToggle={event=>setContextOpen(event.currentTarget.open)}><summary>Requirement context</summary><div className="context-content"><section><p className="eyebrow">Active requirement</p>{goal?<><h2>{goal.summary}</h2><p>{goal.quantity??'Quantity not set'} · {goal.budget?formatMoney(goal.budget):'Budget not set'}</p></>:<><h2>No committed requirement</h2><p>The editable draft remains separate.</p></>}</section><section><p className="eyebrow">Decision posture</p><strong>{health.status.replaceAll('_',' ')}</strong><p>{health.counts.blocking} blocking · {health.counts.attention} attention</p><details className="health-actions"><summary>Inspect health actions</summary><WorkspaceHealthPanel application={application} persistent={persistent} health={health} onNavigate={revealTarget}/></details></section><section className="context-activity" aria-labelledby="context-activity-title"><p className="eyebrow">Recent activity</p><h2 id="context-activity-title">Human and agent trail</h2>{state.activities.length?<ol>{state.activities.slice(0,2).map(activity=>{const human=activity.toolName.startsWith('human_')||['goal_committed','proposal_rejected','proposal_applied','interpretation_rejected','interpretation_adopted','scenario_applied','operational_case_opened','operational_case_updated'].includes(activity.kind);return <li key={activity.id} data-actor={human?'human':'agent'}><span>{human?'Human':'Agent / tool'}</span><p>{activity.summary}</p></li>})}</ol>:<p>No human or agent activity yet.</p>}<a href="#stage-review" onClick={()=>navigateView('review','#stage-review')}>Open full review trail</a></section><section className="approval-boundary"><strong>Human approval boundary</strong><p>Agents research and propose. They cannot purchase, pay, accept terms or contact suppliers.</p></section></div></details></aside></div><footer><p>Catalog facts may be incomplete or provider-inferred. Verify details and final terms with the merchant before purchase. CoSource does not perform checkout or payment.</p></footer></div>
}
function App(){const[portfolio]=useState(createBrowserApplication),snapshot=useProjectPortfolio(portfolio);if(snapshot.status==='restoring')return <main className="persistence-gate" aria-busy="true"><h1>Restoring your CoSource workspace…</h1><p role="status">Checking this device for saved decision work.</p></main>;if(!snapshot.active)return <main className="persistence-gate"><h1>Saved projects need recovery</h1><p role="alert">{snapshot.message} Stored data has not been changed or deleted.</p>{snapshot.status!=='conflict'&&<button onClick={()=>void portfolio.retry()}>Try restoration again</button>}</main>;return <ProjectApp key={snapshot.active.application.getSnapshot().id} persistent={snapshot.active} portfolio={portfolio} portfolioSnapshot={snapshot}/>}
export default App
