import {useMemo,useState} from 'react'
import './App.css'
import {SupplierIntelligencePanel} from './suppliers/SupplierIntelligencePanel'
import type {MerchantOffer,ProductCluster,ProvenanceKind,ProviderIdentity} from './commerce/domain/commerce'
import {providerIdentityKey,sameProviderIdentity} from './commerce/domain/provider-identity'
import type {CatalogProductResult} from './commerce/providers/catalog-provider'
import {formatMoney,MoneyDisplayError} from './commerce/domain/money-display'
import {PurchaseGoalPanel} from './goals/PurchaseGoalPanel'
import {GoalInterpretationPanel} from './goals/GoalInterpretationPanel'
import type {ProductEvaluation} from './evaluation/domain/product-evaluation'
import {ProductEvaluationPanel} from './evaluation/ProductEvaluationPanel'
import {DecisionWorkspace} from './planning/DecisionWorkspace'
import {useWebMCP} from './webmcp/use-webmcp'
import {createBrowserApplication} from './application/browser-application'
import {useCoSourceApplication} from './application/use-cosource-application'
import {usePersistence} from './application/persistence/use-persistent-application'
import {useProjectPortfolio} from './application/portfolio/use-project-portfolio'
import type {ProjectPortfolio,PortfolioSnapshot} from './application/portfolio/project-portfolio-controller'
import {ProjectControls} from './application/portfolio/ProjectControls'
import type {PersistentApplication} from './application/persistence/persistent-application'
import type {ApplicationResult} from './application/cosource-application'
import {formatGoalCondition} from './goals/domain/condition-presentation'
import {WorkspaceHeader} from './workspace/WorkspaceHeader'
import {CollaborationWorkspace} from './workspace/CollaborationWorkspace'
import './workspace/C2.css'
import './workspace/Responsive.css'

const availabilityText={available:'Listed as available',unavailable:'Unavailable',unknown:'Availability not confirmed'}
const provenanceText:Record<ProvenanceKind,string>={provider_explicit:'Provided',provider_inferred:'Inferred',cosource_derived:'Derived',unknown:'Unknown'}
function money(offer:MerchantOffer){try{return formatMoney(offer.price)}catch(error){return error instanceof MoneyDisplayError?'Price unavailable — unsupported currency':'Price unavailable'}}
const safeExternal=(url?:string)=>url?.startsWith('https://')?url:undefined
function ProductImage({product}:{product:ProductCluster}){const[broken,setBroken]=useState(false),image=product.media[0];return image&&!broken?<img src={image.url} alt={image.altText||product.title.value} loading="lazy" onError={()=>setBroken(true)}/>:<div className="image-fallback">No image</div>}
function ResultCard({product,onOpen,comparisonSelected,onToggleComparison,maximumItemPrice}:{product:ProductCluster;onOpen:()=>void;comparisonSelected:boolean;onToggleComparison:()=>void;maximumItemPrice?:{minorAmount:number;currency:string}}){const featured=product.featuredOfferId?product.offers.find(offer=>offer.identity.provider===product.identity.provider&&offer.identity.id===product.featuredOfferId):undefined,displayedOffer=featured??product.offers[0],priceConflict=Boolean(displayedOffer&&maximumItemPrice&&displayedOffer.price.currency===maximumItemPrice.currency&&displayedOffer.price.minorAmount>maximumItemPrice.minorAmount);return <article className="result-card"><ProductImage product={product}/><div className="card-copy"><div className="card-labels"><span>Product cluster</span>{product.description?.provenance.kind==='provider_inferred'&&<span className="evidence">Inferred details</span>}</div><h3>{product.title.value}</h3>{product.description&&<p className="description">{product.description.value}</p>}{displayedOffer?<div className="featured"><span>{featured?'Featured offer':'Returned offer'}</span><strong>{money(displayedOffer)}</strong><span>{displayedOffer.merchant?.name||displayedOffer.merchant?.domain||'Merchant not named'}</span><span>{availabilityText[displayedOffer.availability.state]}</span></div>:<p>No offer was returned for this cluster.</p>}{priceConflict&&<p className="notice error">Known conflict — exceeds maximum item price</p>}<p className="completeness">More offers may be available. Open the product to check.</p><div className="offer-links"><button type="button" className="secondary" onClick={onOpen}>View product and offers</button><button type="button" className="secondary" aria-pressed={comparisonSelected} onClick={onToggleComparison}>{comparisonSelected?'Remove from comparison':'Select for comparison'}</button></div></div></article>}
function Detail({result,loading,error,onClose,evaluation}:{result?:CatalogProductResult;loading:boolean;error?:string;onClose:()=>void;evaluation?:ProductEvaluation}){return <aside className="detail" aria-labelledby="detail-title" aria-live="polite"><div className="detail-head"><p className="eyebrow">Product detail</p><button type="button" className="quiet" onClick={onClose}>Close</button></div>{loading&&<p role="status">Loading product and merchant offers…</p>}{error&&<div className="notice error" role="alert">{error}</div>}{result&&<><h2 id="detail-title">{result.product.title.value}</h2><p className="trust-note">Product information: {provenanceText[result.product.title.provenance.kind]}. Some descriptions and attributes may require verification.</p>{evaluation?<ProductEvaluationPanel evaluation={evaluation}/>:<p className="notice">Complete a valid purchase goal to evaluate this product.</p>}<h3>{result.product.offers.length} merchant {result.product.offers.length===1?'offer':'offers'}</h3><div className="offers">{result.product.offers.map(offer=><article className="offer" key={providerIdentityKey(offer.identity)}><h4>{offer.merchant?.name||offer.merchant?.domain||'Merchant not named'}</h4><strong className="offer-price">{money(offer)}</strong><span>{availabilityText[offer.availability.state]}</span><div className="offer-links">{safeExternal(offer.productUrl)&&<a href={offer.productUrl} target="_blank" rel="noopener noreferrer">View on merchant site</a>}{safeExternal(offer.handoffUrl)&&<a href={offer.handoffUrl} target="_blank" rel="noopener noreferrer">Continue with merchant</a>}</div></article>)}</div></>}</aside>}

function ProjectApp({persistent,portfolio,portfolioSnapshot}:{persistent:PersistentApplication;portfolio:ProjectPortfolio;portfolioSnapshot:PortfolioSnapshot}){
 const application=persistent.application,persistence=usePersistence(persistent),state=useCoSourceApplication(application),goal=state.activeGoal,human=state.humanDiscovery,products=human.candidates,agentCandidates=state.agentDiscovery.candidates,comparisonIds=state.comparisonIds
 const [query,setQuery]=useState(''),[validation,setValidation]=useState(''),[detail,setDetail]=useState<CatalogProductResult>(),[detailState,setDetailState]=useState<'closed'|'loading'|'success'|'error'>('closed'),[detailError,setDetailError]=useState('')
 const submitted=human.query,cursor=human.pagination.cursor,hasMore=human.pagination.hasMore,status=human.status==='initial_loading'?'loading':human.status==='pagination_loading'?'loadingMore':human.status,error=human.error?.message??'',searchMode=human.mode==='active_goal_human'?'goal':'exploratory'
 const gatedRecovery=persistence.status==='recovery_required'&&persistence.access==='gated',webmcp=useWebMCP(application,persistence.status!=='restoring'&&persistence.status!=='recovery_required')
 const decisionProducts=useMemo(()=>{const map=new Map<string,ProductCluster>();[...products,...agentCandidates].forEach(product=>map.set(providerIdentityKey(product.identity),product));return[...map.values()]},[products,agentCandidates])
 const comparison=comparisonIds.length===2?application.compareCandidates(comparisonIds[0]!,comparisonIds[1]!):undefined,planEvaluation=goal?application.evaluatePurchasePlan():undefined,detailEvaluation=detail?application.evaluateCandidate(detail.product.identity):undefined
 const goalController={goal:state.goalDraft,activeGoal:state.activeGoal,commitmentStatus:application.getGoalCommitmentStatus(),edit:application.editGoal,addCondition:application.addGoalCondition,editCondition:application.editGoalCondition,removeCondition:application.removeGoalCondition,commitGoal:application.commitGoalDraft}
 function presentDiscoveryFailure(result:ApplicationResult<unknown>){if(result.ok||result.code==='stale_state')return;const canonical=application.getSnapshot().humanDiscovery.error;if(canonical?.code!==result.code||canonical.message!==result.message)setValidation(result.message)}
 async function search(nextQuery:string,nextCursor?:string){setValidation('');if(!nextCursor){setDetail(undefined);setDetailState('closed')}const result=await application.searchCandidates({query:nextQuery,cursor:nextCursor,limit:6});presentDiscoveryFailure(result)}
 function submit(event:React.FormEvent){event.preventDefault();const trimmed=query.trim();if(!trimmed){setValidation('Enter a product to search for.');return}setValidation('');void search(trimmed)}
 async function sourceGoal(nextCursor?:string){setValidation('');if(!nextCursor){setDetail(undefined);setDetailState('closed')}const result=await application.sourceCandidatesForActiveGoal({cursor:nextCursor,limit:6});if(result.ok&&result.value.strategy)setQuery(result.value.strategy.query);else presentDiscoveryFailure(result)}
 async function openProduct(product:ProductCluster){setDetail(undefined);setDetailError('');setDetailState('loading');const result=await application.inspectCandidate(product.identity);if(result.ok){setDetail({product:result.value,selectedOptions:[],messages:[]});setDetailState('success')}else{setDetailError(result.message);setDetailState('error')}}
 const selected=(identity:ProviderIdentity)=>comparisonIds.some(item=>sameProviderIdentity(item,identity))
 function approve(id:string){application.approvePlanProposal(id)}
 function reject(id:string){application.rejectPlanProposal(id)}
 function loadExample(){
  const draft=application.getSnapshot().goalDraft
  ;(['requirement','preference','exclusion'] as const).forEach(kind=>{const key=kind==='requirement'?'requirements':kind==='preference'?'preferences':'exclusions';draft[key].forEach(item=>application.removeGoalCondition(kind,item.id))})
  application.editGoal({summary:'Equip 30 pupils with waterproof backpacks for a school trip',searchFocus:'waterproof school backpack',quantity:30,maximumItemPrice:{minorAmount:3500,currency:'GBP'},budget:{minorAmount:105000,currency:'GBP'}})
  const add=(kind:'requirement'|'preference'|'exclusion',value:string)=>{application.addGoalCondition(kind);const key=kind==='requirement'?'requirements':kind==='preference'?'preferences':'exclusions',item=application.getSnapshot().goalDraft[key].at(-1);if(item)application.editGoalCondition(kind,item.id,{operator:'free_text',value})}
  add('requirement','Waterproof');add('preference','Reflective details');add('exclusion','Leather')
 }
 if(persistence.status==='restoring')return <main className="persistence-gate" aria-busy="true"><h1>Restoring your CoSource workspace…</h1><p role="status" aria-live="polite">Checking this device for saved decision work.</p></main>
 if(gatedRecovery)return <main className="persistence-gate"><h1>Saved workspace needs recovery</h1><p role="alert">{persistence.message} It has not been changed or deleted.</p><button onClick={()=>void persistent.retry()}>Try restoration again</button></main>
 const persistenceText=persistence.status==='saving'?'Saving changes locally…':persistence.status==='save_error'?'Changes are not safely stored.':persistence.status==='unavailable'?persistence.message:persistence.status==='recovery_required'?'Workspace preserved in memory — saved data needs recovery. Local saving and agent tools are disabled.':persistence.status==='conflict'?'Save conflict — another tab stored a newer workspace.':persistence.lastSavedAt?`Saved locally ${new Date(persistence.lastSavedAt).toLocaleString()}`:'Local workspace ready',retryLabel=persistence.status==='save_error'?'Retry save':(persistence.status==='unavailable'&&persistence.retryCapability==='supported')||persistence.status==='recovery_required'?'Retry local storage':undefined
 return <div className="app-shell"><ProjectControls portfolio={portfolio} snapshot={portfolioSnapshot}/><div className={`persistence-status persistence-${persistence.status}`} role={persistence.status==='save_error'||persistence.status==='recovery_required'||persistence.status==='conflict'?'alert':'status'} aria-live="polite"><span>{persistenceText}</span>{retryLabel&&<button className="quiet" onClick={()=>void persistent.retry()}>{retryLabel}</button>}</div><WorkspaceHeader state={state} commitment={application.getGoalCommitmentStatus()} webmcp={webmcp.status} toolCount={webmcp.toolCount}/><main>
  <PurchaseGoalPanel {...goalController} loadExample={loadExample} sourceGoal={()=>{void sourceGoal()}}/>
  {state.goalInterpretationProposals.length>0?<GoalInterpretationPanel proposals={state.goalInterpretationProposals} statusFor={application.getGoalInterpretationStatus} onAdopt={id=>{application.adoptGoalInterpretation(id)}} onReject={id=>{application.rejectGoalInterpretation(id)}}/>:<aside className="interpretation-guidance"><strong>Agent goal interpretations are optional.</strong><span>Any proposal appears here for human review and changes only the editable draft when adopted.</span></aside>}
  <section className="hero" id="stage-discover" aria-labelledby="page-title"><p className="eyebrow">Discover · Live commerce data</p><h2 id="page-title">Source for your goal—or explore freely.</h2><p><strong>Active-goal sourcing</strong> applies the committed goal and market constraints. <strong>Exploratory search</strong> remains a separate way to inspect the live catalog.</p><form className="search-form" onSubmit={submit}><label htmlFor="product-search">What are you looking for? <span className="mode-label" aria-hidden="true">Exploratory search</span></label><div className="search-row"><input id="product-search" aria-label="What are you looking for?" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Try notebook, backpack, or desk lamp" maxLength={500}/><button disabled={status==='loading'}>{status==='loading'?'Searching…':'Search products'}</button></div><p>Live search uses {state.market.country} / {state.market.currency} context. Every price keeps its returned currency.</p>{validation&&<p className="validation" role="alert">{validation}</p>}</form></section>
 <section className="discovery" aria-labelledby="results-title"><div className="results-head"><div><p className="eyebrow">Discovery results</p><h2 id="results-title">{submitted?`${status==='stale'?'Stale results':'Results'} for “${submitted}”`:'Ready when you are'}</h2></div>{products.length>0&&<span>{products.length} product {products.length===1?'cluster':'clusters'} shown</span>}</div><div aria-live="polite">{status==='idle'&&<div className="empty-state"><h3>Start with an ordinary product search</h3><p>Results come live through CoSource’s secure commerce gateway.</p></div>}{status==='loading'&&<div className="loading-grid" role="status"><span>Searching the live catalog…</span><i/><i/><i/></div>}{status==='empty'&&<div className="empty-state"><h3>No matching products returned</h3><p>Try a broader product name or check the spelling.</p></div>}{status==='error'&&<div className="notice error" role="alert"><p>{error}</p><button className="secondary" onClick={()=>void(searchMode==='goal'?sourceGoal():search(submitted))}>Try again</button></div>}{status==='stale'&&<div className="notice" role="alert"><p>These visible results were sourced against an earlier goal revision and are stale, not current recommendations. Source again against the current goal to refresh them.</p><button className="secondary" onClick={()=>void sourceGoal()}>Source again against current goal</button></div>}</div>{products.length>0&&<div className="workspace"><div className="results-list">{products.map(product=><ResultCard key={providerIdentityKey(product.identity)} product={product} maximumItemPrice={goal?.maximumItemPrice} comparisonSelected={selected(product.identity)} onToggleComparison={()=>application.toggleComparison(product.identity)} onOpen={()=>void openProduct(product)}/>)}{hasMore&&status!=='stale'&&<button className="load-more" disabled={status==='loadingMore'} onClick={()=>void(searchMode==='goal'?sourceGoal(cursor):search(submitted,cursor))}>{status==='loadingMore'?'Loading more…':'Load more products'}</button>}</div>{detailState!=='closed'&&<Detail result={detail} loading={detailState==='loading'} error={detailError} evaluation={detailEvaluation?.ok?detailEvaluation.value:undefined} onClose={()=>setDetailState('closed')}/>}</div>}</section>
 {human.strategy&&<section className="strategy-summary"><p className="eyebrow">{status==='stale'?'Stale sourcing strategy':'Sourcing strategy'}</p><h2>{status==='stale'?'Previously searched for':'Searching for'} {human.strategy.query}</h2>{human.sourcingPlan&&<><p>Requirement revision {human.sourcingPlan.requirementRevision}. Source searched: {human.sourcingPlan.legs.map(leg=>leg.source.name).join(', ')||'No capable source'}.</p><h3>What CoSource asked the source to enforce</h3><ul>{human.sourcingPlan.legs.flatMap(leg=>leg.projectedInput.appliedConstraints.map(condition=><li key={`${leg.source.id}-applied-${condition.id}`}>Applied: {formatGoalCondition(condition)}</li>))}{human.sourcingPlan.legs.flatMap(leg=>leg.limitations.map((gap,index)=><li key={`${leg.source.id}-limitation-${gap.constraintId??index}`}>{leg.source.name} could not apply: {gap.description}</li>))}{human.sourcingPlan.mandatoryGaps.map((gap,index)=><li key={`mandatory-${gap.constraintId??index}`}>Still required across all sources: {gap.description}</li>)}{human.sourcingPlan.preferenceGaps.map((gap,index)=><li key={`preference-${gap.constraintId??index}`}>Preference still unresolved: {gap.description}</li>)}{human.sourcingPlan.capabilityWarnings.map((warning,index)=><li key={`warning-${index}`}>{warning}</li>)}</ul></>}<h3>Applying</h3><ul><li>Available products</li><li>Ships to {human.strategy.market.country}</li>{human.strategy.constraints.maximumPrice&&<li>Maximum item price: {formatMoney(human.strategy.constraints.maximumPrice)}</li>}</ul><h3>Still needs verification</h3>{human.strategy.evidenceGaps.length?<ul>{human.strategy.evidenceGaps.map((gap,index)=><li key={`${gap.goalConditionId??'gap'}-${index}`}>{gap.description}</li>)}</ul>:<p>No discovery-level gaps identified.</p>}</section>}
  {agentCandidates.length>0&&<section className="discovery agent-candidates"><p className="eyebrow">Agent search</p><h2>Real market candidates for human review</h2><p>These candidates are not retained decision evidence until you inspect or compare them.</p><div className="results-list">{agentCandidates.map(product=><ResultCard key={providerIdentityKey(product.identity)} product={product} maximumItemPrice={goal?.maximumItemPrice} comparisonSelected={selected(product.identity)} onToggleComparison={()=>application.toggleComparison(product.identity)} onOpen={()=>void openProduct(product)}/>)}</div><button className="secondary" onClick={application.dismissAgentCandidates}>Dismiss candidates</button></section>}
  {!goal&&<><section className="locked-stage" id="stage-compare" aria-labelledby="locked-compare-title"><p className="eyebrow">Compare · Locked stage</p><h2 id="locked-compare-title">Commit a goal before comparing candidates.</h2><p>Then source real products, inspect their evidence, and select two candidates. Comparison never ranks or selects for you.</p><a className="button-link" href="#stage-define">Define and commit a goal</a></section><section className="locked-stage locked-plan" id="stage-plan" aria-labelledby="locked-plan-title"><p className="eyebrow">Plan · Locked stage</p><h2 id="locked-plan-title">The purchase plan follows a human comparison decision.</h2><p>Nothing is added automatically. Choose a product from the evidence comparison when this stage unlocks.</p><a className="button-link" href="#stage-compare">See comparison requirements</a></section></>}
  <SupplierIntelligencePanel application={application} state={state}/>
  {goal&&planEvaluation?.ok&&<DecisionWorkspace
    goal={goal} products={decisionProducts} evidenceProducts={state.retainedProducts} evidenceEntries={state.retainedEvidence} evidenceRefresh={state.evidenceRefresh} plan={state.plan} planEvaluation={planEvaluation.value}
    comparison={comparison?.ok?comparison.value:undefined} comparisonIds={comparisonIds} pendingProposal={state.proposals.some(proposal=>proposal.status==='pending')}
    onClearComparison={application.clearComparison} onAddProduct={identity=>{application.addCandidateToPlan(identity)}} onRemoveLine={application.removePlanLine}
    onSetQuantity={application.setPlanLineQuantity} onSelectOffer={application.selectPlanLineOffer} onRebase={application.rebasePlan} onRefreshEvidence={application.refreshRetainedEvidence}/>}
 </main><CollaborationWorkspace proposals={state.proposals} plan={state.plan} products={state.retainedProducts} onApprove={approve} onReject={reject} getReview={application.reviewPlanProposal} {...webmcp} activities={state.activities}/><footer><p>Catalog facts may be incomplete or provider-inferred. Verify details and final terms with the merchant before purchase. CoSource does not perform checkout or payment.</p></footer></div>
}
function App(){const[portfolio]=useState(createBrowserApplication),snapshot=useProjectPortfolio(portfolio);if(snapshot.status==='restoring')return <main className="persistence-gate" aria-busy="true"><h1>Restoring your CoSource workspace…</h1><p role="status">Checking this device for saved decision work.</p></main>;if(!snapshot.active)return <main className="persistence-gate"><h1>Saved projects need recovery</h1><p role="alert">{snapshot.message} Stored data has not been changed or deleted.</p>{snapshot.status!=='conflict'&&<button onClick={()=>void portfolio.retry()}>Try restoration again</button>}</main>;return <ProjectApp key={snapshot.active.application.getSnapshot().id} persistent={snapshot.active} portfolio={portfolio} portfolioSnapshot={snapshot}/>}
export default App
