import {describe,expect,it,vi} from 'vitest'
import type {ProductCluster} from '../../commerce/domain/commerce'
import {providerIdentityKey} from '../../commerce/domain/provider-identity'
import {createCoSourceApplication,type CatalogPort} from '../cosource-application'
import {createPersistentApplication} from './persistent-application'
import {parsePersistedWorkspace} from './persisted-workspace-schema'
import {durableProjection,PERSISTED_WORKSPACE_FORMAT_VERSION,type PersistedWorkspaceEnvelope,type WorkspacePersistencePort} from './workspace-persistence'
import {MemoryWorkspacePersistence} from './memory-workspace-persistence'

const provenance={kind:'provider_explicit' as const,provider:'shopify_global_catalog' as const}
const product:ProductCluster={identity:{provider:'shopify_global_catalog',id:'p1'},title:{value:'Pack',provenance},media:[],offers:[],offerCompleteness:'provider_returned_unknown',provenance}
const market={country:'GB',currency:'GBP',language:'en'}
const tick=()=>new Promise(resolve=>setTimeout(resolve,0))
function core(catalog?:Partial<CatalogPort>){let id=0;return createCoSourceApplication({market,makeId:()=>`id-${++id}`,now:()=>`2026-09-06T12:00:00.000Z`,catalog:{search:catalog?.search??(async()=>({products:[product],messages:[],pagination:{hasMore:false}})),product:catalog?.product??(async()=>({product,selectedOptions:[],messages:[]}))}})}
function record(application=core(),durableRevision=0):PersistedWorkspaceEnvelope{const payload=durableProjection(application.getSnapshot());return{formatVersion:PERSISTED_WORKSPACE_FORMAT_VERSION,workspaceId:payload.id,durableRevision,savedAt:'2026-09-06T12:00:00.000Z',market,payload}}

describe('durable workspace persistence',()=>{
 it('makes missing-record compare-and-save semantics deterministic in memory',async()=>{const repository=new MemoryWorkspacePersistence();expect(await repository.compareAndSave(record(core(),2),1)).toEqual({ok:false,reason:'conflict',currentRevision:0});expect(repository.record).toBeUndefined();expect(repository.writes).toHaveLength(0)})
 it('matches production stale and malformed-record conflict safety in memory',async()=>{const original=record(core(),0),repository=new MemoryWorkspacePersistence(original);expect(await repository.compareAndSave(record(core(),1),undefined)).toEqual({ok:false,reason:'conflict',currentRevision:0});expect(repository.record).toEqual(original);repository.record={durableRevision:0,bad:true};await expect(repository.compareAndSave(record(core(),1),0)).rejects.toThrow('stored workspace record is invalid');expect(repository.record).toEqual({durableRevision:0,bad:true});expect(repository.writes).toHaveLength(0)})
 it('clones successful memory writes and results independently',async()=>{const input=record(core(),0),repository=new MemoryWorkspacePersistence(),result=await repository.compareAndSave(input,undefined);input.payload.goalDraft.summary='mutated input';if(result.ok)result.record.payload.goalDraft.summary='mutated result';expect((repository.record as PersistedWorkspaceEnvelope).payload.goalDraft.summary).toBe('');expect(repository.writes[0]?.payload.goalDraft.summary).toBe('')})
 it('clones constructor seeds and load results independently',async()=>{const seed=record(core(),0),repository=new MemoryWorkspacePersistence(seed);seed.payload.goalDraft.summary='mutated seed';const loaded=await repository.load() as PersistedWorkspaceEnvelope;loaded.payload.goalDraft.summary='mutated load';expect((repository.record as PersistedWorkspaceEnvelope).payload.goalDraft.summary).toBe('')})
 it('initializes and saves exactly one fresh canonical workspace when no record exists',async()=>{const repository=new MemoryWorkspacePersistence(),application=core(),controller=createPersistentApplication(application,repository,()=> '2026-09-06T12:00:00.000Z');await Promise.all([controller.initialize(),controller.initialize()]);expect(repository.writes).toHaveLength(1);expect(controller.getPersistenceSnapshot()).toMatchObject({status:'ready',lastSavedRevision:0});expect(repository.writes[0]?.workspaceId).toBe(application.getSnapshot().id)})
 it('restores durable owners atomically while execution state starts idle and providers remain untouched',async()=>{const first=core();first.editGoal({summary:'Durable goal',searchFocus:'packs'});first.commitGoalDraft();await first.searchCandidates({query:'packs'});first.retainCandidate(product.identity);first.toggleComparison(product.identity);first.addCandidateToPlan(product.identity);first.recordActivity({kind:'read_tool_call',toolName:'test',outcome:'success',summary:'durable'});const saved=record(first,7),repository=new MemoryWorkspacePersistence(saved),search=vi.fn(),lookup=vi.fn(),second=core({search,product:lookup}),notifications=vi.fn();second.subscribe(notifications);const controller=createPersistentApplication(second,repository);await controller.initialize();const restored=second.getSnapshot();expect(notifications).toHaveBeenCalledOnce();expect(restored.id).toBe(first.getSnapshot().id);expect(restored.goalDraft).toEqual(first.getSnapshot().goalDraft);expect(restored.activeGoal).toEqual(first.getSnapshot().activeGoal);expect(restored.retainedEvidence).toEqual(first.getSnapshot().retainedEvidence);expect(restored.comparisonIds).toEqual([product.identity]);expect(restored.plan).toEqual(first.getSnapshot().plan);expect(restored.activities[0]?.summary).toBe('durable');expect(restored.humanDiscovery).toMatchObject({status:'idle',candidates:[],pagination:{hasMore:false}});expect(restored.agentDiscovery).toMatchObject({status:'idle',candidates:[]});expect(restored.evidenceRefresh).toEqual({});expect(search).not.toHaveBeenCalled();expect(lookup).not.toHaveBeenCalled()})
 it('round-trips evidence current/history and preserves provider-scoped identity',async()=>{const first=core();await first.searchCandidates({query:'pack'});first.retainCandidate(product.identity);await first.refreshRetainedEvidence(product.identity);const saved=record(first,2);expect(parsePersistedWorkspace(saved)).toMatchObject({ok:true});const second=core(),controller=createPersistentApplication(second,new MemoryWorkspacePersistence(saved));await controller.initialize();const entry=second.getSnapshot().retainedEvidence[0]!;expect(providerIdentityKey(entry.subject)).toBe(providerIdentityKey(product.identity));expect(entry.current.sequence).toBe(2);expect(entry.history).toHaveLength(1)})
 it('does not write for semantic no-ops or transient discovery lifecycle, but writes durable changes',async()=>{let release!:(value:{products:ProductCluster[];messages:never[];pagination:{hasMore:false}})=>void;const pending=new Promise<{products:ProductCluster[];messages:never[];pagination:{hasMore:false}}>(resolve=>{release=resolve}),application=core({search:()=>pending}),repository=new MemoryWorkspacePersistence(),controller=createPersistentApplication(application,repository);await controller.initialize();const baseline=repository.writes.length;application.editGoal({summary:''});expect(repository.writes).toHaveLength(baseline);const search=application.searchCandidates({query:'pack'});await tick();expect(repository.writes).toHaveLength(baseline);release({products:[],messages:[],pagination:{hasMore:false}});await search;await tick();expect(repository.writes).toHaveLength(baseline);application.editGoal({summary:'A durable change'});await tick();expect(repository.writes.length).toBe(baseline+1)})
 it('serializes rapid durable writes so the newest projection wins',async()=>{const base=new MemoryWorkspacePersistence(),calls:Array<()=>void>=[];const repository:WorkspacePersistencePort={load:()=>base.load(),compareAndSave:async(item,expected)=>{await new Promise<void>(resolve=>calls.push(resolve));return base.compareAndSave(item,expected)}};const application=core(),controller=createPersistentApplication(application,repository);const initialization=controller.initialize();await tick();calls.shift()?.();await initialization;application.editGoal({summary:'one'});application.editGoal({summary:'two'});await tick();calls.shift()?.();await tick();calls.shift()?.();await tick();expect((base.record as PersistedWorkspaceEnvelope).payload.goalDraft.summary).toBe('two');expect(base.writes.map(item=>item.durableRevision)).toEqual([0,1,2])})
 it('preserves in-memory work on save failure and retries the newest state',async()=>{let fail=true;const memory=new MemoryWorkspacePersistence(),repository:WorkspacePersistencePort={load:()=>memory.load(),compareAndSave:async(item,expected)=>{if(fail)throw new Error('quota');return memory.compareAndSave(item,expected)}};const application=core(),controller=createPersistentApplication(application,repository);await controller.initialize();expect(controller.getPersistenceSnapshot().status).toBe('save_error');application.editGoal({summary:'newest'});fail=false;await controller.retry();expect(controller.getPersistenceSnapshot().status).toBe('ready');expect((memory.record as PersistedWorkspaceEnvelope).payload.goalDraft.summary).toBe('newest')})
 it('rejects stale concurrent writers without overwriting either workspace',async()=>{const seed=record(core(),0),repository=new MemoryWorkspacePersistence(seed),a=core(),b=core(),first=createPersistentApplication(a,repository),second=createPersistentApplication(b,repository);await Promise.all([first.initialize(),second.initialize()]);a.editGoal({summary:'first tab'});await tick();b.editGoal({summary:'second tab'});await tick();expect(second.getPersistenceSnapshot()).toMatchObject({status:'conflict',storedRevision:1});expect(b.getSnapshot().goalDraft.summary).toBe('second tab');expect((repository.record as PersistedWorkspaceEnvelope).payload.goalDraft.summary).toBe('first tab')})
 it.each([['malformed',{bad:true},'corrupt'],['future version',{...record(),formatVersion:2},'incompatible']] as const)('keeps %s stored data untouched and disables automatic saving',async(_label,stored,reason)=>{const repository=new MemoryWorkspacePersistence(stored),application=core(),controller=createPersistentApplication(application,repository);await controller.initialize();expect(controller.getPersistenceSnapshot()).toMatchObject({status:'recovery_required',reason,access:'gated'});application.editGoal({summary:'must not overwrite'});await tick();expect(repository.record).toEqual(stored);expect(repository.writes).toHaveLength(0)})
 it('rejects invalid identities, unsafe money, revisions, ledger overflow, history overflow, and unknown nested fields',()=>{const cases:unknown[]=[];const identity=record();identity.payload.comparisonIds=[{provider:'shopify_global_catalog',id:'missing'}];cases.push(identity);const unsafe=record();unsafe.payload.goalDraft.maximumItemPrice={currency:'GBP',minorAmount:Number.MAX_SAFE_INTEGER+1};cases.push(unsafe);const revision=record();revision.payload.plan.revision=-1;cases.push(revision);const overflow=record();overflow.payload.retainedEvidence=Array.from({length:51},()=>({})) as unknown as typeof overflow.payload.retainedEvidence;cases.push(overflow);const history=record();history.payload.retainedEvidence=[{subject:product.identity,current:{id:'o7',sequence:7,observedAt:'2026-09-06T12:00:00.000Z',origin:{kind:'commerce_provider',provider:'shopify_global_catalog'},provenanceStrength:'provider_explicit',product},history:Array.from({length:6},(_,index)=>({id:`o${index}`,sequence:6-index,observedAt:'2026-09-06T12:00:00.000Z',origin:{kind:'commerce_provider',provider:'shopify_global_catalog'},provenanceStrength:'provider_explicit',product}))}];cases.push(history);const unknown=record() as PersistedWorkspaceEnvelope&{extra?:boolean};unknown.extra=true;cases.push(unknown);for(const item of cases)expect(parsePersistedWorkspace(item)).toMatchObject({ok:false})})
 it('reports retryable bounded memory-only mode without mutating the workspace',async()=>{const application=core(),before=application.getSnapshot(),controller=createPersistentApplication(application,{load:async()=>{throw new Error('blocked')},compareAndSave:async()=>{throw new Error('blocked')}});await controller.initialize();expect(controller.getPersistenceSnapshot()).toMatchObject({status:'unavailable',retryCapability:'supported'});expect(application.getSnapshot()).toBe(before)})
 it('restores a valid record after unavailable storage recovers when memory is unchanged',async()=>{const storedApplication=core();storedApplication.editGoal({summary:'stored goal'});const stored=record(storedApplication,0),repository=new MemoryWorkspacePersistence(stored);repository.unavailable=true;const application=core(),controller=createPersistentApplication(application,repository);await controller.initialize();repository.unavailable=false;await controller.retry();expect(application.getSnapshot().goalDraft.summary).toBe('stored goal');expect(controller.getPersistenceSnapshot()).toMatchObject({status:'ready',lastSavedRevision:0});expect(repository.writes).toHaveLength(0)})
 it('initializes empty recovered storage exactly once when memory is unchanged',async()=>{const repository=new MemoryWorkspacePersistence();repository.unavailable=true;const application=core(),subscribe=vi.spyOn(application,'subscribe'),controller=createPersistentApplication(application,repository);await controller.initialize();repository.unavailable=false;await Promise.all([controller.retry(),controller.retry()]);expect(repository.writes).toHaveLength(1);expect(subscribe).toHaveBeenCalledOnce();expect(repository.record).toMatchObject({payload:{id:application.getSnapshot().id}})})
 it('atomically saves the newest memory workspace when recovered storage is empty',async()=>{const repository=new MemoryWorkspacePersistence();repository.unavailable=true;const application=core(),controller=createPersistentApplication(application,repository);await controller.initialize();application.editGoal({summary:'new in-memory goal'});repository.unavailable=false;await controller.retry();expect(controller.getPersistenceSnapshot().status).toBe('ready');expect(repository.writes).toHaveLength(1);expect((repository.record as PersistedWorkspaceEnvelope).payload.goalDraft.summary).toBe('new in-memory goal')})
 it('preserves memory edits when unavailable storage later exposes an older workspace',async()=>{const storedApplication=core();storedApplication.editGoal({summary:'stored goal'});const stored=record(storedApplication,0);let available=false;const repository:WorkspacePersistencePort={load:async()=>{if(!available)throw new Error('blocked');return structuredClone(stored)},compareAndSave:async()=>{throw new Error('must not write')}};const application=core(),controller=createPersistentApplication(application,repository);await controller.initialize();application.editGoal({summary:'new in-memory goal'});available=true;await controller.retry();expect(application.getSnapshot().goalDraft.summary).toBe('new in-memory goal');expect(await repository.load()).toEqual(stored);expect(controller.getPersistenceSnapshot()).toMatchObject({status:'conflict'})})
 it.each([['corrupt',{bad:true}],['incompatible',{...record(),formatVersion:2}]])('keeps changed memory and %s recovered storage untouched',async(_label,stored)=>{let available=false;const writes=vi.fn(),load=vi.fn(async()=>{if(!available)throw new Error('blocked');return structuredClone(stored)}),repository:WorkspacePersistencePort={load,compareAndSave:writes};const application=core(),controller=createPersistentApplication(application,repository);await controller.initialize();application.editGoal({summary:'new in-memory goal'});const preserved=structuredClone(application.getSnapshot());available=true;await Promise.all([controller.retry(),controller.retry()]);expect(application.getSnapshot()).toEqual(preserved);expect(controller.getPersistenceSnapshot()).toMatchObject({status:'recovery_required',access:'memory_preserved'});expect(load).toHaveBeenCalledTimes(2);expect(writes).not.toHaveBeenCalled();expect(await repository.load()).toEqual(stored)})
})
