// @vitest-environment jsdom
import {cleanup,renderHook,waitFor} from '@testing-library/react'
import {StrictMode,type ReactNode} from 'react'
import {afterEach,describe,expect,it,vi} from 'vitest'
import {createCoSourceApplication,type CatalogPort} from '../cosource-application'
import {useWebMCP} from '../../webmcp/use-webmcp'
import {WEBMCP_TOOL_NAMES} from '../../webmcp/application-tools'
import {createPersistentApplication} from './persistent-application'
import {usePersistence} from './use-persistent-application'
import {durableProjection,PERSISTED_WORKSPACE_FORMAT_VERSION,type PersistedWorkspaceEnvelope,type WorkspacePersistencePort} from './workspace-persistence'

const market={country:'GB',currency:'GBP',language:'en'}
const wrapper=({children}:{children:ReactNode})=><StrictMode>{children}</StrictMode>
const deferred=<T,>()=>{let resolve!:(value:T)=>void;const promise=new Promise<T>(done=>{resolve=done});return{promise,resolve}}
function core(catalog?:Partial<CatalogPort>){return createCoSourceApplication({market,makeId:()=> 'workspace',now:()=> '2026-09-07T00:00:00.000Z',catalog:{search:catalog?.search??(async()=>({products:[],messages:[],pagination:{hasMore:false}})),product:catalog?.product??(async()=>{throw new Error('unused')})}})}
function savedWorkspace(){const application=core();application.editGoal({summary:'Restored goal',searchFocus:'restored'});const payload=durableProjection(application.getSnapshot());return{formatVersion:PERSISTED_WORKSPACE_FORMAT_VERSION,workspaceId:payload.id,durableRevision:0,savedAt:'2026-09-07T00:00:00.000Z',market,payload} satisfies PersistedWorkspaceEnvelope}

afterEach(()=>{cleanup();Reflect.deleteProperty(document,'modelContext')})

describe('persistence and WebMCP lifecycle',()=>{
 it('restores atomically before registering exactly thirteen tools under StrictMode',async()=>{const load=deferred<unknown>(),loadRecord=vi.fn(()=>load.promise),search=vi.fn(),product=vi.fn(),writes=vi.fn(async(record:PersistedWorkspaceEnvelope)=>({ok:true as const,record})),repository:WorkspacePersistencePort={load:loadRecord,compareAndSave:writes},application=core({search,product}),subscribe=vi.spyOn(application,'subscribe'),controller=createPersistentApplication(application,repository),tools=new Map<string,WebMCPToolDefinition>(),registrations:string[]=[];Object.defineProperty(document,'modelContext',{configurable:true,value:Object.assign(new EventTarget(),{async registerTool(tool:WebMCPToolDefinition,options?:{signal?:AbortSignal}){registrations.push(tool.name);tools.set(tool.name,tool);options?.signal?.addEventListener('abort',()=>tools.delete(tool.name),{once:true})}})});const view=renderHook(()=>{const persistence=usePersistence(controller),webmcp=useWebMCP(application,persistence.status!=='restoring'&&persistence.status!=='recovery_required');return{persistence,webmcp}},{wrapper});expect(tools.size).toBe(0);expect(registrations).toHaveLength(0);load.resolve(savedWorkspace());await waitFor(()=>expect(view.result.current.persistence.status).toBe('ready'));await waitFor(()=>expect(view.result.current.webmcp).toMatchObject({status:'ready',toolCount:13}));expect([...tools.keys()].sort()).toEqual([...WEBMCP_TOOL_NAMES].sort());expect([...tools.keys()]).not.toEqual(expect.arrayContaining(['persist_workspace','recover_workspace','clear_storage','checkout','make_payment','purchase']));expect(registrations).toHaveLength(13);expect(loadRecord).toHaveBeenCalledOnce();expect(subscribe).toHaveBeenCalledOnce();expect(writes).not.toHaveBeenCalled();const response=await tools.get('get_goal_context')!.execute({}) as {ok:boolean;data:{sessionId:string;draft:{summary:string}}};expect(response).toMatchObject({ok:true,data:{sessionId:'workspace',draft:{summary:'Restored goal'}}});expect(search).not.toHaveBeenCalled();expect(product).not.toHaveBeenCalled()})
 it('keeps all tools unavailable when deferred restoration requires recovery',async()=>{const load=deferred<unknown>(),search=vi.fn(),product=vi.fn(),writes=vi.fn(),repository:WorkspacePersistencePort={load:()=>load.promise,compareAndSave:writes},application=core({search,product}),controller=createPersistentApplication(application,repository),registrations=vi.fn();Object.defineProperty(document,'modelContext',{configurable:true,value:Object.assign(new EventTarget(),{registerTool:registrations})});const view=renderHook(()=>{const persistence=usePersistence(controller),webmcp=useWebMCP(application,persistence.status!=='restoring'&&persistence.status!=='recovery_required');return{persistence,webmcp}},{wrapper});load.resolve({bad:true});await waitFor(()=>expect(view.result.current.persistence.status).toBe('recovery_required'));expect(view.result.current.webmcp).toMatchObject({status:'unavailable',toolCount:0});expect(registrations).not.toHaveBeenCalled();expect(writes).not.toHaveBeenCalled();expect(search).not.toHaveBeenCalled();expect(product).not.toHaveBeenCalled()})
 it('keeps preserved human memory accessible but withdraws every tool when recovered storage is corrupt',async()=>{let available=false;const load=vi.fn(async()=>{if(!available)throw new Error('blocked');return{bad:true}}),writes=vi.fn(),application=core(),controller=createPersistentApplication(application,{load,compareAndSave:writes}),tools=new Map<string,WebMCPToolDefinition>();Object.defineProperty(document,'modelContext',{configurable:true,value:Object.assign(new EventTarget(),{async registerTool(tool:WebMCPToolDefinition,options?:{signal?:AbortSignal}){tools.set(tool.name,tool);options?.signal?.addEventListener('abort',()=>tools.delete(tool.name),{once:true})}})});const view=renderHook(()=>{const persistence=usePersistence(controller),webmcp=useWebMCP(application,persistence.status!=='restoring'&&persistence.status!=='recovery_required');return{persistence,webmcp}},{wrapper});await waitFor(()=>expect(view.result.current.persistence.status).toBe('unavailable'));application.editGoal({summary:'preserved human goal'});const preserved=structuredClone(application.getSnapshot());available=true;await Promise.all([controller.retry(),controller.retry()]);await waitFor(()=>expect(view.result.current.persistence).toMatchObject({status:'recovery_required',access:'memory_preserved'}));await waitFor(()=>expect(tools.size).toBe(0));expect(view.result.current.webmcp).toMatchObject({status:'unavailable',toolCount:0});expect(application.getSnapshot()).toEqual(preserved);expect(load).toHaveBeenCalledTimes(2);expect(writes).not.toHaveBeenCalled()})
})
