// @vitest-environment jsdom
import {act,cleanup,render,screen} from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import {afterEach,describe,expect,it,vi} from 'vitest'
import '@testing-library/jest-dom/vitest'
import App from '../App'

type Tool={name:string;execute:(input:unknown)=>Promise<unknown>|unknown}
async function setup(){const tools:Tool[]=[];const modelContext=Object.assign(new EventTarget(),{async registerTool(tool:Tool){tools.push(tool)}});Object.defineProperty(document,'modelContext',{configurable:true,value:modelContext});render(<App/>);await screen.findByText('WebMCP ready');return{name:(value:string)=>tools.find(tool=>tool.name===value)!}}
async function propose(tool:(value:string)=>Tool,proposed:Record<string,unknown>){let context!:Record<string,unknown>;await act(async()=>{context=await tool('get_goal_context').execute({}) as Record<string,unknown>});const data=context.data as {sessionId:string;draft:{id:string;revision:number}};await act(async()=>{await tool('propose_goal_interpretation').execute({sessionId:data.sessionId,draftId:data.draft.id,draftRevision:data.draft.revision,proposed:{summary:'Reviewed goal',requirements:[],preferences:[],exclusions:[],...proposed},interpretationNotes:'Structured for human review.',assumptions:[],unresolvedQuestions:[]})})}
afterEach(()=>{cleanup();delete (document as Document&{modelContext?:unknown}).modelContext;vi.unstubAllGlobals()})

describe('B3R goal interpretation review fidelity',()=>{
 it('renders the kernel commitment status through meaningful edit and exact restoration',async()=>{await setup();const summary=screen.getByLabelText('What are you trying to buy or achieve?');await userEvent.type(summary,'Canonical A');await userEvent.click(screen.getByRole('button',{name:'Commit draft as active goal'}));expect(screen.queryByText(/draft has uncommitted changes/i)).not.toBeInTheDocument();await userEvent.clear(summary);await userEvent.type(summary,'Canonical B');expect(screen.getByText(/draft has uncommitted changes/i)).toBeInTheDocument();await userEvent.clear(summary);await userEvent.type(summary,'Canonical A');expect(screen.queryByText(/draft has uncommitted changes/i)).not.toBeInTheDocument()},10_000)
 it('blocks invalid visible decimals, preserves the active goal, and commits the corrected value',async()=>{const{name}=await setup(),summary=screen.getByLabelText('What are you trying to buy or achieve?'),amount=screen.getByLabelText('Budget amount');await userEvent.type(summary,'Money safety');const commit=screen.getByRole('button',{name:'Commit draft as active goal'});await userEvent.type(amount,'10.00');await userEvent.click(commit);await userEvent.clear(amount);await userEvent.type(amount,'10.999');expect(screen.getByRole('alert')).toHaveTextContent(/valid overall budget/i);expect(commit).toBeDisabled();let result!:Record<string,unknown>;await act(async()=>{result=await name('get_resource_requirement').execute({}) as Record<string,unknown>});expect(result.data).toMatchObject({cost:{totalBudget:{minorAmount:1000,currency:'GBP'}}});await userEvent.clear(amount);await userEvent.type(amount,'12.34');expect(screen.queryByRole('alert')).not.toBeInTheDocument();expect(commit).toBeEnabled();await userEvent.click(commit);await act(async()=>{result=await name('get_resource_requirement').execute({}) as Record<string,unknown>});expect(result.data).toMatchObject({cost:{totalBudget:{minorAmount:1234,currency:'GBP'}}})})
 it('blocks unsupported visible currency until corrected and commits matching canonical money',async()=>{const{name}=await setup(),summary=screen.getByLabelText('What are you trying to buy or achieve?'),amount=screen.getByLabelText('Maximum item price amount'),currency=screen.getByLabelText('Maximum item price currency');await userEvent.type(summary,'Currency safety');const commit=screen.getByRole('button',{name:'Commit draft as active goal'});await userEvent.type(amount,'15.25');await userEvent.click(commit);await userEvent.clear(currency);await userEvent.type(currency,'ZZZ');expect(screen.getByRole('alert')).toHaveTextContent(/supported currency/i);expect(commit).toBeDisabled();let result!:Record<string,unknown>;await act(async()=>{result=await name('get_resource_requirement').execute({}) as Record<string,unknown>});expect(result.data).toMatchObject({cost:{unitCeiling:{minorAmount:1525,currency:'GBP'}}});await userEvent.clear(currency);await userEvent.type(currency,'USD');expect(screen.queryByRole('alert')).not.toBeInTheDocument();expect(commit).toBeEnabled();await userEvent.click(commit);await act(async()=>{result=await name('get_resource_requirement').execute({}) as Record<string,unknown>});expect(result.data).toMatchObject({cost:{unitCeiling:{minorAmount:1525,currency:'USD'}}})})
 it('populates adopted exact money, including a zero-fraction currency',async()=>{const{ name }=await setup();await propose(name,{maximumItemPrice:{minorAmount:1234,currency:'GBP'},budget:{minorAmount:500,currency:'JPY'}});await userEvent.click(screen.getByRole('button',{name:'Adopt into editable draft'}));expect(screen.getByLabelText('Maximum item price amount')).toHaveValue('12.34');expect(screen.getByLabelText('Maximum item price currency')).toHaveValue('GBP');expect(screen.getByLabelText('Budget amount')).toHaveValue('500');expect(screen.getByLabelText('Budget currency')).toHaveValue('JPY')})
 it('replaces visible money on adoption and clears canonical money omitted by a later proposal',async()=>{const{ name }=await setup();await userEvent.type(screen.getByLabelText('Maximum item price amount'),'9.99');await userEvent.type(screen.getByLabelText('Budget amount'),'20.00');await propose(name,{maximumItemPrice:{minorAmount:1500,currency:'USD'},budget:{minorAmount:3000,currency:'EUR'}});await userEvent.click(screen.getByRole('button',{name:'Adopt into editable draft'}));expect(screen.getByLabelText('Maximum item price amount')).toHaveValue('15.00');expect(screen.getByLabelText('Maximum item price currency')).toHaveValue('USD');expect(screen.getByLabelText('Budget amount')).toHaveValue('30.00');expect(screen.getByLabelText('Budget currency')).toHaveValue('EUR');await propose(name,{});await userEvent.click(screen.getAllByRole('button',{name:'Adopt into editable draft'}).at(-1)!);expect(screen.getByLabelText('Maximum item price amount')).toHaveValue('');expect(screen.getByLabelText('Maximum item price currency')).toHaveValue('GBP');expect(screen.getByLabelText('Budget amount')).toHaveValue('');expect(screen.getByLabelText('Budget currency')).toHaveValue('GBP')})
 it('commits exactly the adopted money after ordinary human decimal editing',async()=>{const{ name }=await setup();await propose(name,{maximumItemPrice:{minorAmount:1234,currency:'GBP'},budget:{minorAmount:5000,currency:'GBP'}});await userEvent.click(screen.getByRole('button',{name:'Adopt into editable draft'}));const amount=screen.getByLabelText('Maximum item price amount');await userEvent.clear(amount);await userEvent.type(amount,'18.75');expect(amount).toHaveValue('18.75');await userEvent.click(screen.getByRole('button',{name:'Commit draft as active goal'}));let result!:Record<string,unknown>;await act(async()=>{result=await name('get_resource_requirement').execute({}) as Record<string,unknown>});expect(result.data).toMatchObject({cost:{unitCeiling:{minorAmount:1875,currency:'GBP'},totalBudget:{minorAmount:5000,currency:'GBP'}}})})
 it('renders every proposed condition with complete shared semantics',async()=>{const{ name }=await setup();await propose(name,{requirements:[{id:'eq',operator:'equals',field:'colour',value:'black'},{id:'true',operator:'is_true',field:'waterproof'},{id:'false',operator:'is_false',field:'contains latex'}],preferences:[{id:'min',operator:'at_least',field:'warranty years',value:'2'},{id:'max',operator:'at_most',field:'weight kg',value:'1.5'}],exclusions:[{id:'text',operator:'free_text',value:'No refurbished products'}]});expect(await screen.findByText(/colour equals black/)).toBeInTheDocument();expect(screen.getByText(/waterproof is required \(true\)/)).toBeInTheDocument();expect(screen.getByText(/contains latex must be false \(excluded\)/)).toBeInTheDocument();expect(screen.getByText(/warranty years at least 2/)).toBeInTheDocument();expect(screen.getByText(/weight kg at most 1.5/)).toBeInTheDocument();expect(screen.getByText('No refurbished products')).toBeInTheDocument()})
 it('makes active-goal sourcing authority explicit across uncommitted and committed edits',async()=>{const candidate={identity:{provider:'shopify_global_catalog',id:'chair'},title:{value:'Chair result',provenance:{kind:'provider_explicit',provider:'shopify_global_catalog'}},media:[],offers:[],offerCompleteness:'featured_only',provenance:{kind:'provider_explicit',provider:'shopify_global_catalog'}},fetch=vi.fn().mockImplementation(()=>new Response(JSON.stringify({ok:true,data:{products:[candidate],messages:[],pagination:{hasMore:false}}}),{status:200,headers:{'Content-Type':'application/json'}}));vi.stubGlobal('fetch',fetch);await setup();const summary=screen.getByLabelText('What are you trying to buy or achieve?'),focus=screen.getByLabelText('Product being sourced');await userEvent.type(summary,'Goal A');await userEvent.type(focus,'chairs');await userEvent.click(screen.getByRole('button',{name:'Commit draft as active goal'}));await userEvent.clear(summary);await userEvent.type(summary,'Goal B');await userEvent.clear(focus);await userEvent.type(focus,'desks');expect(screen.getByText(/draft has uncommitted changes/i)).toBeInTheDocument();expect(screen.getByRole('button',{name:'Source active goal: chairs'})).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Source active goal: chairs'}));expect(await screen.findByText('Chair result')).toBeInTheDocument();expect(JSON.parse(fetch.mock.calls[0]![1].body)).toMatchObject({query:'chairs'});await userEvent.click(screen.getByRole('button',{name:'Commit draft as active goal'}));expect(screen.getByText(/Stale results for/)).toBeInTheDocument();expect(screen.getByRole('button',{name:'Source active goal: desks'})).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Source active goal: desks'}));expect(JSON.parse(fetch.mock.calls[1]![1].body)).toMatchObject({query:'desks'})})
})
