import {formatMoney} from '../commerce/domain/money-display'
import {formatGoalCondition} from './domain/condition-presentation'
import type {GoalInterpretationEffectiveStatus,GoalInterpretationProposal} from './domain/goal-interpretation-proposal'
import './GoalInterpretationPanel.css'

function ConditionList({items}:{items:GoalInterpretationProposal['proposed']['requirements']}){
 return <>{items.map(formatGoalCondition).join(', ')||'None'}</>
}

export function GoalInterpretationPanel({proposals,statusFor,onAdopt,onReject}:{proposals:GoalInterpretationProposal[];statusFor:(id:string)=>GoalInterpretationEffectiveStatus|undefined;onAdopt:(id:string)=>void;onReject:(id:string)=>void}){
 return <section className="interpretation-review" aria-labelledby="interpretation-title"><p className="eyebrow">Agent interpretation</p><h2 id="interpretation-title">Goal interpretation proposals</h2><p>Agent interpretations are validated input, not commerce evidence. Only you can adopt one into the editable draft, and adoption does not activate it.</p>{proposals.length===0?<p className="muted">No interpretation proposal this session.</p>:proposals.map(proposal=>{const status=statusFor(proposal.id)??proposal.status,values=proposal.proposed;return <article className="interpretation" key={proposal.id}><header><h3>Proposed structured goal</h3><strong>{status}</strong></header><p>{proposal.interpretationNotes}</p><dl><div><dt>Outcome</dt><dd>{values.summary}</dd></div>{values.searchFocus&&<div><dt>Product focus</dt><dd>{values.searchFocus}</dd></div>}{values.quantity&&<div><dt>Quantity</dt><dd>{values.quantity}</dd></div>}{values.maximumItemPrice&&<div><dt>Maximum item price</dt><dd>{formatMoney(values.maximumItemPrice)}</dd></div>}{values.budget&&<div><dt>Overall budget</dt><dd>{formatMoney(values.budget)}</dd></div>}<div><dt>Hard requirements</dt><dd><ConditionList items={values.requirements}/></dd></div><div><dt>Preferences</dt><dd><ConditionList items={values.preferences}/></dd></div><div><dt>Exclusions</dt><dd><ConditionList items={values.exclusions}/></dd></div></dl><h4>Stated assumptions</h4>{proposal.assumptions.length?<ul>{proposal.assumptions.map((item,index)=><li key={index}>{item}</li>)}</ul>:<p>None stated.</p>}<h4>Unresolved questions</h4>{proposal.unresolvedQuestions.length?<ul>{proposal.unresolvedQuestions.map((item,index)=><li key={index}>{item}</li>)}</ul>:<p>None stated.</p>}{status==='stale'&&<p role="alert">This interpretation is stale because the editable draft changed.</p>}{status==='pending'&&<div className="interpretation-actions"><button type="button" onClick={()=>onAdopt(proposal.id)}>Adopt into editable draft</button><button type="button" className="secondary" onClick={()=>onReject(proposal.id)}>Reject interpretation</button></div>}</article>})}</section>
}
