import {useEffect,useRef,useState} from 'react'
import './PurchaseGoalPanel.css'
import {formatMoneyInput,parseMoneyInput} from '../commerce/domain/money-input'
import {formatMoney} from '../commerce/domain/money-display'
import {formatGoalCondition} from './domain/condition-presentation'
import type {GoalCondition,GoalConditionKind,PurchaseGoal,PurchaseGoalDraft} from './domain/purchase-goal'
import {validatePurchaseGoal} from './domain/purchase-goal'
import type {GoalCommitmentStatus} from '../application/cosource-application'

interface Props{goal:PurchaseGoalDraft;activeGoal?:PurchaseGoal;commitmentStatus:GoalCommitmentStatus;edit:(changes:Partial<Omit<PurchaseGoalDraft,'state'|'id'|'revision'>>)=>void;addCondition:(kind:GoalConditionKind)=>void;editCondition:(kind:GoalConditionKind,id:string,changes:Partial<GoalCondition>)=>void;removeCondition:(kind:GoalConditionKind,id:string)=>void;commitGoal:()=>void;sourceGoal:()=>void;loadExample:()=>void}
const groups:Array<{kind:GoalConditionKind;key:'requirements'|'preferences'|'exclusions';title:string;add:string}>=[{kind:'requirement',key:'requirements',title:'Must have',add:'Add hard requirement'},{kind:'preference',key:'preferences',title:'Prefer',add:'Add preference'},{kind:'exclusion',key:'exclusions',title:'Exclude',add:'Add exclusion'}]
const operatorLabels={free_text:'Free text',equals:'Equals',is_true:'Is true',is_false:'Is false',at_most:'At most',at_least:'At least'},supportedCurrencies=Intl.supportedValuesOf('currency')
const moneyKey=(money:PurchaseGoalDraft['budget'])=>money?`${money.currency}:${money.minorAmount}`:''
const initialMoney=(money:PurchaseGoalDraft['budget'])=>money?formatMoneyInput(money.minorAmount,money.currency):''
export function PurchaseGoalPanel(props:Props){
 const [budgetAmount,setBudgetAmount]=useState(()=>initialMoney(props.goal.budget)),[budgetCurrency,setBudgetCurrency]=useState(props.goal.budget?.currency??'GBP'),[budgetError,setBudgetError]=useState(''),[maximumAmount,setMaximumAmount]=useState(()=>initialMoney(props.goal.maximumItemPrice)),[maximumCurrency,setMaximumCurrency]=useState(props.goal.maximumItemPrice?.currency??'GBP'),[maximumError,setMaximumError]=useState('')
 const expectedBudget=useRef<string|undefined>(undefined),expectedMaximum=useRef<string|undefined>(undefined);const validation=validatePurchaseGoal(props.goal),hasMoneyError=Boolean(budgetError||maximumError)
 useEffect(()=>{const key=moneyKey(props.goal.budget);if(expectedBudget.current!==undefined&&expectedBudget.current===key){expectedBudget.current=undefined;return}setBudgetAmount(initialMoney(props.goal.budget));setBudgetCurrency(props.goal.budget?.currency??'GBP');setBudgetError('')},[props.goal.budget])
 useEffect(()=>{const key=moneyKey(props.goal.maximumItemPrice);if(expectedMaximum.current!==undefined&&expectedMaximum.current===key){expectedMaximum.current=undefined;return}setMaximumAmount(initialMoney(props.goal.maximumItemPrice));setMaximumCurrency(props.goal.maximumItemPrice?.currency??'GBP');setMaximumError('')},[props.goal.maximumItemPrice])
 function updateMoney(field:'budget'|'maximumItemPrice',amount:string,currency:string){if(field==='budget'){setBudgetAmount(amount);setBudgetCurrency(currency)}else{setMaximumAmount(amount);setMaximumCurrency(currency)}if(!amount){if(field==='budget'){setBudgetError('');expectedBudget.current=''}else{setMaximumError('');expectedMaximum.current=''}props.edit({[field]:undefined});return}try{const value=parseMoneyInput(amount,currency);if(field==='budget'){setBudgetError('');expectedBudget.current=moneyKey(value)}else{setMaximumError('');expectedMaximum.current=moneyKey(value)}props.edit({[field]:value})}catch{const message=field==='budget'?'Enter a valid overall budget and supported currency.':'Enter a valid maximum item price and supported currency.';if(field==='budget')setBudgetError(message);else setMaximumError(message)}}
 return <section className="goal-section" id="stage-define" aria-labelledby="goal-title"><div className="goal-intro"><div><p className="eyebrow">Define · Human-owned intent</p><h2 id="goal-title">Editable goal draft</h2><p>Draft edits do not change the active purchase goal until you commit them.</p></div><div className="example-starter"><strong>Need a quick tour?</strong><span>Load a school-trip example into the draft only.</span><button type="button" className="secondary" onClick={props.loadExample}>Use example buying need</button></div></div><div className="goal-layout"><div className="goal-editor">
  <label htmlFor="goal-summary">What are you trying to buy or achieve?</label><textarea id="goal-summary" value={props.goal.summary} maxLength={1000} onChange={event=>props.edit({summary:event.target.value})} placeholder="For example: equip students for wet weather"/><p className="field-help">Required, up to 1,000 characters.</p>
  <label htmlFor="goal-search-focus">Product being sourced</label><input id="goal-search-focus" value={props.goal.searchFocus??''} maxLength={500} onChange={event=>props.edit({searchFocus:event.target.value||undefined})} placeholder="For example: student raincoats"/><p className="field-help">Enter this directly; it is not inferred from the summary.</p>
  <div className="goal-basics"><div><label htmlFor="goal-quantity">Quantity <span>optional</span></label><input id="goal-quantity" type="number" min="1" max="100000" value={props.goal.quantity??''} onChange={event=>props.edit({quantity:event.target.value?Number(event.target.value):undefined})}/></div>
   <fieldset><legend>Maximum item price <span>optional</span></legend><div className="budget-row"><label><span>Amount</span><input aria-label="Maximum item price amount" inputMode="decimal" value={maximumAmount} onChange={event=>updateMoney('maximumItemPrice',event.target.value,maximumCurrency)} placeholder="30.00"/></label><label><span>Currency</span><input aria-label="Maximum item price currency" list="supported-currencies" maxLength={3} value={maximumCurrency} onChange={event=>updateMoney('maximumItemPrice',maximumAmount,event.target.value.toUpperCase())}/></label></div>{maximumError&&<p className="validation" role="alert">{maximumError}</p>}</fieldset>
   <fieldset><legend>Overall plan budget <span>optional</span></legend><div className="budget-row"><label><span>Amount</span><input aria-label="Budget amount" inputMode="decimal" value={budgetAmount} onChange={event=>updateMoney('budget',event.target.value,budgetCurrency)} placeholder="4500.00"/></label><label><span>Currency</span><input aria-label="Budget currency" list="supported-currencies" maxLength={3} value={budgetCurrency} onChange={event=>updateMoney('budget',budgetAmount,event.target.value.toUpperCase())}/><datalist id="supported-currencies">{supportedCurrencies.map(currency=><option key={currency} value={currency}/>)}</datalist></label></div>{budgetError&&<p className="validation" role="alert">{budgetError}</p>}</fieldset></div>
  <details className="refinements" open={props.goal.requirements.length+props.goal.preferences.length+props.goal.exclusions.length>0}><summary>Requirements, preferences and exclusions <span>{props.goal.requirements.length+props.goal.preferences.length+props.goal.exclusions.length} added</span></summary><p>Refine the goal with evidence-aware constraints. Unknown evidence remains visible later.</p>{groups.map(group=><fieldset className="condition-group" key={group.kind}><legend>{group.title}</legend>{props.goal[group.key].map((condition,index)=><div className="condition-row" key={condition.id}><label><span>Operator</span><select aria-label={`${group.title} ${index+1} operator`} value={condition.operator} onChange={event=>props.editCondition(group.kind,condition.id,{operator:event.target.value as GoalCondition['operator'],field:undefined,value:''})}>{Object.entries(operatorLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{condition.operator!=='free_text'&&<label><span>Field</span><input aria-label={`${group.title} ${index+1} field`} value={condition.field??''} maxLength={100} onChange={event=>props.editCondition(group.kind,condition.id,{field:event.target.value})}/></label>}{!['is_true','is_false'].includes(condition.operator)&&<label className="condition-value"><span>{condition.operator==='free_text'?'Condition':'Value'}</span><input aria-label={`${group.title} ${index+1} value`} value={condition.value??''} maxLength={500} onChange={event=>props.editCondition(group.kind,condition.id,{value:event.target.value})}/></label>}<button type="button" className="remove" aria-label={`Remove ${group.kind} ${index+1}`} onClick={()=>props.removeCondition(group.kind,condition.id)}>Remove</button></div>)}<button type="button" className="secondary add-condition" onClick={()=>props.addCondition(group.kind)}>{group.add}</button></fieldset>)}</details>
 </div><aside className="goal-preview" aria-labelledby="preview-title" aria-live="polite"><div className="preview-head"><h3 id="preview-title">Structured draft</h3><span>Revision {props.goal.revision}</span></div>{props.goal.summary?<><strong className="goal-summary">{props.goal.quantity?`${props.goal.quantity} × `:''}{props.goal.summary}</strong>{props.goal.searchFocus&&<p><span>Product</span><strong>{props.goal.searchFocus}</strong></p>}{props.goal.quantity&&<p><span>Quantity</span><strong>{props.goal.quantity}</strong></p>}{props.goal.maximumItemPrice&&<p><span>Maximum item price</span><strong>{formatMoney(props.goal.maximumItemPrice)}</strong></p>}{props.goal.budget&&<p><span>Overall budget</span><strong>{formatMoney(props.goal.budget)}</strong></p>}{groups.map(group=><div key={group.kind}><h4>{group.title}</h4>{props.goal[group.key].length?<ul>{props.goal[group.key].map(condition=><li key={condition.id}>{formatGoalCondition(condition)}</li>)}</ul>:<p className="muted">None entered</p>}</div>)}<button type="button" disabled={!validation.success||hasMoneyError} onClick={props.commitGoal}>Commit draft as active goal</button></>:<p className="muted">Enter a summary to create a valid structured draft.</p>}{!validation.success&&props.goal.summary&&<p className="validation" role="alert">Some goal fields are incomplete or invalid.</p>}{props.commitmentStatus==='uncommitted_changes'&&<p className="notice">This draft has uncommitted changes. Sourcing continues to use the active purchase goal until you commit.</p>}<div className="active-goal"><h3>Active purchase goal</h3>{props.activeGoal?<><p><strong>{props.activeGoal.summary}</strong></p><p>Committed revision {props.activeGoal.revision}</p>{props.activeGoal.searchFocus&&<p>Product: {props.activeGoal.searchFocus}</p>}<p>Uncommitted draft edits are excluded from sourcing.</p><button type="button" className="secondary" disabled={!props.activeGoal.searchFocus?.trim()} onClick={props.sourceGoal}>Source active goal{props.activeGoal.searchFocus?`: ${props.activeGoal.searchFocus}`:''}</button></>:<p className="muted">No active goal. Commit a valid draft explicitly.</p>}</div></aside></div></section>
}
