import {useState} from 'react'
import type {CoSourceApplication,CoSourceSessionState} from '../application/cosource-application'
import type {EvidenceIssue} from './domain/evidence-resolution'

const labels={missing:'Missing evidence',stale:'Stale evidence',conflicting:'Conflicting claims',verification_required:'Verification required',unresolved_cost:'Unresolved cost',unavailable:'Evidence unavailable'}
export function EvidenceResolutionPanel({application,state}:{application:CoSourceApplication;state:CoSourceSessionState}){
 const[result,setResult]=useState(''),[notes,setNotes]=useState<Record<string,string>>({}),[values,setValues]=useState<Record<string,string>>({}),issues=application.getEvidenceIssues(),items=issues.ok?issues.value:[],blocking=items.filter(item=>item.blocksReadiness&&!item.resolved),other=items.filter(item=>!item.blocksReadiness&&!item.resolved)
 const verify=(issueId:string,outcome:'confirmed'|'rejected'|'recorded',claimReference?:string)=>{const response=application.recordHumanVerification({issueId,outcome,claimReference,value:values[issueId],note:notes[issueId]});setResult(response.ok?'Human verification recorded. Canonical issues were recomputed.':response.message);if(response.ok){setNotes({...notes,[issueId]:''});setValues({...values,[issueId]:''})}}
 const refresh=async(issue:EvidenceIssue)=>{if(issue.subject.kind!=='candidate')return;const response=await application.refreshRetainedEvidence({provider:issue.subject.source as never,id:issue.subject.id});setResult(response.ok?'Evidence refreshed; canonical issues were recomputed.':response.message)}
 return <section className="evidence-resolution" id="evidence-resolution" aria-labelledby="evidence-resolution-title">
  <p className="eyebrow">Review · Human controlled</p><h2 id="evidence-resolution-title">Evidence resolution</h2>
  <p>{blocking.length} blocking issues · {other.length} non-blocking issues. Original source observations remain retained.</p>{result&&<p role="status">{result}</p>}
  {!state.activeGoal?<p>Commit a goal to review requirement-bound evidence.</p>:!items.length?<p>No unresolved evidence issue is currently projected.</p>:<div className="evidence-groups">{[...blocking,...other,...items.filter(item=>item.resolved)].map(issue=>{const verification=state.humanVerifications.find(item=>item.issueId===issue.id),evaluation=issue.subject.kind==='candidate'?application.evaluateCandidate({provider:issue.subject.source as never,id:issue.subject.id}):undefined,condition=evaluation?.ok?[...evaluation.value.requirements,...evaluation.value.preferences,...evaluation.value.exclusions].find(item=>`condition:${item.conditionId}`===issue.field):undefined,refreshState=issue.subject.kind==='candidate'?state.evidenceRefresh[JSON.stringify([issue.subject.source,issue.subject.id])]:undefined;return <article key={issue.id} className="evidence-issue"><h3>{labels[issue.kind]}</h3><p><strong>{issue.importance}</strong> · {issue.field}{issue.resolved?' · resolved':''}</p><p>{issue.reason}</p>{verification&&<p><strong>Human verified:</strong> {verification.value??verification.claimReference} · {condition?.status??'verification retained'} · attributed to human verification.</p>}{issue.evidence.observedAt&&<p>Accepted observation: <time dateTime={issue.evidence.observedAt}>{issue.evidence.observedAt}</time></p>}{refreshState&&refreshState.status!=='idle'&&<p>Refresh: {refreshState.status}{refreshState.error?` · ${refreshState.error.message}`:''}</p>}<p>Routes: {issue.routes.join(', ').replaceAll('_',' ')}</p>{!issue.resolved&&issue.subject.kind==='candidate'&&issue.routes.includes('refresh_evidence')&&<button type="button" className="secondary" disabled={refreshState?.status==='loading'} onClick={()=>void refresh(issue)}>{refreshState?.status==='loading'?'Refreshing evidence…':'Refresh evidence'}</button>}{!issue.resolved&&issue.routes.includes('record_missing_fact')&&<fieldset><legend>Record a verified missing fact</legend><label>Verified value<input value={values[issue.id]??''} onChange={event=>setValues({...values,[issue.id]:event.target.value})}/></label><label>Verification note<textarea value={notes[issue.id]??''} onChange={event=>setNotes({...notes,[issue.id]:event.target.value})}/></label><button type="button" className="secondary" onClick={()=>verify(issue.id,'recorded')}>Record human verification</button></fieldset>}{!issue.resolved&&issue.claimReferences.length>0&&<fieldset><legend>Verify one exact current claim</legend><label>Verification note<textarea value={notes[issue.id]??''} onChange={event=>setNotes({...notes,[issue.id]:event.target.value})}/></label>{issue.claimReferences.map(claim=><div key={claim}><code>{claim}</code><button type="button" className="secondary" onClick={()=>verify(issue.id,'confirmed',claim)}>Confirm this claim</button><button type="button" className="quiet" onClick={()=>verify(issue.id,'rejected',claim)}>Reject this claim</button></div>)}</fieldset>}</article>})}</div>}
  <p>Merchant checkout remains the final payable-cost verification. CoSource cannot order or pay.</p>
 </section>
}
