// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest'
import {cleanup,render,screen} from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import {afterEach,describe,expect,it,vi} from 'vitest'
import {createCoSourceApplication} from '../application/cosource-application'
import type {ProductCluster} from '../commerce/domain/commerce'
import {durableProjection,PERSISTED_WORKSPACE_FORMAT_VERSION} from '../application/persistence/workspace-persistence'
import {parsePersistedWorkspace} from '../application/persistence/persisted-workspace-schema'
import {EvidenceResolutionPanel} from './EvidenceResolutionPanel'

const provider='shopify_global_catalog' as const,provenance={kind:'provider_explicit' as const,provider}
const product:ProductCluster={identity:{provider,id:'product'},title:{value:'Chair',provenance},attributes:{value:[],provenance},media:[],offers:[{identity:{provider,id:'offer'},title:{value:'Chair',provenance},price:{minorAmount:1000,currency:'GBP'},availability:{state:'available',basis:'catalog_signal',provenance},selectedOptions:[],media:[],correlations:[],provenance}],featuredOfferId:'offer',offerCompleteness:'featured_only',provenance}
function app(candidate=product){let id=0;return createCoSourceApplication({market:{country:'GB',currency:'GBP'},makeId:()=>`id-${++id}`,now:()=> '2026-09-11T12:00:00.000Z',catalog:{search:async()=>({products:[candidate],messages:[],pagination:{hasMore:false}}),product:async()=>({product:candidate,selectedOptions:[],messages:[]})}})}
async function setup(candidate=product){const application=app(candidate);application.editGoal({summary:'Chair',searchFocus:'chair'});application.addGoalCondition('requirement');const condition=application.getSnapshot().goalDraft.requirements[0]!;application.editGoalCondition('requirement',condition.id,{operator:'equals',field:'Size',value:'large'});application.addGoalCondition('preference');const preference=application.getSnapshot().goalDraft.preferences[0]!;application.editGoalCondition('preference',preference.id,{operator:'equals',field:'Color',value:'blue'});application.commitGoalDraft();await application.searchCandidates({query:'chair'});application.retainCandidate(candidate.identity);return application}
afterEach(cleanup)
describe('application evidence resolution',()=>{
 it('derives deterministic blocking and preference issues and records bounded human evidence without rewriting observations or plans',async()=>{const application=await setup(),before=application.getSnapshot(),first=application.getEvidenceIssues(product.identity),second=application.getEvidenceIssues(product.identity);expect(first).toEqual(second);expect(first.ok).toBe(true);if(!first.ok)return;const missing=first.value.find(item=>item.field.includes(before.activeGoal!.requirements[0]!.id))!;const preference=first.value.find(item=>item.importance==='preference')!;expect(missing.blocksReadiness).toBe(true);expect(preference.blocksReadiness).toBe(false);const listener=vi.fn(),unsubscribe=application.subscribe(listener),failedBefore=application.getSnapshot();expect(application.recordHumanVerification({issueId:'wrong',outcome:'recorded',value:'large',note:'Checked'})).toMatchObject({ok:false,code:'stale_state'});expect(application.getSnapshot()).toBe(failedBefore);expect(listener).not.toHaveBeenCalled();const observation=before.retainedEvidence[0]!,plan=before.plan,result=application.recordHumanVerification({issueId:missing.id,outcome:'recorded',value:'large',note:'Checked the labelled specification.'});expect(result).toMatchObject({ok:true,value:{workspaceId:before.id,requirementRevision:before.activeGoal!.revision}});expect(application.getSnapshot().retainedEvidence[0]).toBe(observation);expect(application.getSnapshot().plan).toBe(plan);expect(application.getEvidenceIssues(product.identity)).toMatchObject({ok:true,value:expect.arrayContaining([expect.objectContaining({id:missing.id,resolved:true,blocksReadiness:false})])});const revision=application.getSnapshot().revision,activities=application.getSnapshot().activities;expect(application.recordHumanVerification({issueId:missing.id,outcome:'recorded',value:'large',note:'Checked the labelled specification.'})).toMatchObject({ok:true,value:{id:result.ok?result.value.id:undefined}});expect(application.getSnapshot().revision).toBe(revision);expect(application.getSnapshot().activities).toBe(activities);unsubscribe()})
 it('persists verification separately and makes old requirement revisions inapplicable without deleting history',async()=>{const application=await setup(),issues=application.getEvidenceIssues(product.identity);if(!issues.ok)return;const target=issues.value.find(item=>item.kind==='missing'&&item.importance==='mandatory')!;expect(application.recordHumanVerification({issueId:target.id,outcome:'recorded',value:'large',note:'Human checked'}).ok).toBe(true);const saved=durableProjection(application.getSnapshot());expect(saved.humanVerifications).toHaveLength(1);const restored=app();restored.restoreWorkspace(saved);expect(restored.getSnapshot().humanVerifications).toEqual(saved.humanVerifications);restored.editGoal({summary:'Revised chair'});restored.commitGoalDraft();expect(restored.getSnapshot().humanVerifications).toHaveLength(1);const current=restored.getEvidenceIssues(product.identity);expect(current.ok&&current.value.every(item=>item.id!==target.id)).toBe(true)})
 it('renders blockers before preferences and preserves human input after rejection',async()=>{const application=await setup(),view=render(<EvidenceResolutionPanel application={application} state={application.getSnapshot()}/>);expect(screen.getByText(/1 blocking issues · 1 non-blocking issues/)).toBeInTheDocument();const values=screen.getAllByLabelText('Verified value'),notes=screen.getAllByLabelText('Verification note');await userEvent.type(values[0]!,'large');await userEvent.click(screen.getAllByRole('button',{name:'Record human verification'})[0]!);expect(screen.getByRole('status')).toHaveTextContent(/invalid/i);expect(values[0]).toHaveValue('large');await userEvent.type(notes[0]!,'Checked the labelled specification');await userEvent.click(screen.getAllByRole('button',{name:'Record human verification'})[0]!);expect(screen.getByRole('status')).toHaveTextContent(/recorded/i);view.rerender(<EvidenceResolutionPanel application={application} state={application.getSnapshot()}/>);expect(screen.getByText(/condition:.*resolved/)).toBeInTheDocument();expect(screen.getByText(/checkout remains the final payable-cost verification/i)).toBeInTheDocument()})
 it('rejects reserved command fields and corrupt persisted verification cross-bindings',async()=>{const application=await setup(),issueResult=application.getEvidenceIssues(product.identity);if(!issueResult.ok)return;const issue=issueResult.value.find(item=>item.kind==='missing'&&item.importance==='mandatory')!,before=application.getSnapshot(),listener=vi.fn(),unsubscribe=application.subscribe(listener);for(const extra of [{id:'caller'},{workspaceId:'other'},{requirementId:'other'},{requirementRevision:99},{verifiedAt:'2020-01-01T00:00:00.000Z'},{revision:3},{unknown:true}])expect(application.recordHumanVerification({issueId:issue.id,outcome:'recorded',value:'large',note:'Checked',...extra})).toMatchObject({ok:false,code:'invalid_input'});expect(application.getSnapshot()).toBe(before);expect(listener).not.toHaveBeenCalled();unsubscribe();expect(application.recordHumanVerification({issueId:issue.id,outcome:'recorded',value:'large',note:'Checked'}).ok).toBe(true);const payload=durableProjection(application.getSnapshot()),base={formatVersion:PERSISTED_WORKSPACE_FORMAT_VERSION,workspaceId:payload.id,durableRevision:0,savedAt:'2026-09-11T12:00:00.000Z',market:payload.market,payload},verification=payload.humanVerifications![0]!;expect(parsePersistedWorkspace(base).ok).toBe(true);const corrupt=(changes:Record<string,unknown>,additional?:unknown)=>structuredClone({...base,payload:{...base.payload,humanVerifications:[{...verification,...changes},...(additional?[additional]:[])]}});for(const record of [corrupt({workspaceId:'other'}),corrupt({},verification),corrupt({requirementId:'other'}),corrupt({requirementRevision:99}),corrupt({subject:{kind:'candidate',source:provider,id:'missing'}}),corrupt({field:'condition:missing'}),corrupt({claimReference:'claim:bad:source:value'})])expect(parsePersistedWorkspace(record)).toEqual({ok:false,reason:'corrupt'})})
 it('removes conflict actions after one exact claim is reconciled',async()=>{const conflict={...product,attributes:{value:[{name:'Size',value:'large'},{name:'Size',value:'small'}],provenance}},application=await setup(conflict),issues=application.getEvidenceIssues(conflict.identity);if(!issues.ok)return;const issue=issues.value.find(item=>item.kind==='conflicting')!,small=issue.claimReferences.find(reference=>decodeURIComponent(reference).endsWith(':small'))!;const view=render(<EvidenceResolutionPanel application={application} state={application.getSnapshot()}/>);expect(screen.getAllByRole('button',{name:'Confirm this claim'})).toHaveLength(2);expect(screen.getAllByRole('button',{name:'Reject this claim'})).toHaveLength(2);expect(application.recordHumanVerification({issueId:issue.id,outcome:'rejected',claimReference:small,note:'Rejected exact claim'}).ok).toBe(true);view.rerender(<EvidenceResolutionPanel application={application} state={application.getSnapshot()}/>);expect(screen.queryByRole('button',{name:'Confirm this claim'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Reject this claim'})).not.toBeInTheDocument();expect(screen.getByText(/resolved/)).toBeInTheDocument()})
})
