import type {ProductCluster,ProvenanceKind,ProviderIdentity} from '../commerce/domain/commerce'
import {providerIdentityKey} from '../commerce/domain/provider-identity'

export const PRODUCT_EVIDENCE_HISTORY_LIMIT=5
export const PRODUCT_EVIDENCE_ENTRY_LIMIT=50
export interface ProductEvidenceObservation{id:string;sequence:number;observedAt:string;origin:{kind:'commerce_provider';provider:string};provenanceStrength:ProvenanceKind;product:ProductCluster;supersededBy?:string}
export interface ProductEvidenceEntry{subject:ProviderIdentity;current:ProductEvidenceObservation;history:ProductEvidenceObservation[]}
export type ProductEvidenceLedger=ReadonlyMap<string,ProductEvidenceEntry>
export type RetainProductEvidenceResult={ok:true;ledger:ProductEvidenceLedger;entry:ProductEvidenceEntry;created:boolean}|{ok:false;ledger:ProductEvidenceLedger;reason:'capacity_reached'}
function strength(product:ProductCluster):ProvenanceKind{const kinds=[product.title.provenance.kind,product.description?.provenance.kind,product.attributes?.provenance.kind,product.options?.provenance.kind].filter(Boolean) as ProvenanceKind[];return kinds.includes('provider_explicit')?'provider_explicit':kinds.includes('cosource_derived')?'cosource_derived':kinds.includes('provider_inferred')?'provider_inferred':'unknown'}
export function observeProductEvidence(ledger:ProductEvidenceLedger,product:ProductCluster,observedAt:string,observationId:string):ProductEvidenceLedger{const parsed=Date.parse(observedAt);if(!Number.isFinite(parsed))throw new TypeError('Observation time must be a valid instant');const key=providerIdentityKey(product.identity),previous=ledger.get(key);if(!previous&&ledger.size>=PRODUCT_EVIDENCE_ENTRY_LIMIT)return ledger;const sequence=(previous?.current.sequence??0)+1,time=new Date(parsed).toISOString(),current:ProductEvidenceObservation={id:observationId,sequence,observedAt:time,origin:{kind:'commerce_provider',provider:product.identity.provider},provenanceStrength:strength(product),product},history=previous?[{...previous.current,supersededBy:observationId},...previous.history].slice(0,PRODUCT_EVIDENCE_HISTORY_LIMIT):[],next=new Map(ledger);next.set(key,{subject:{...product.identity},current,history});return next}
export function retainProductEvidence(ledger:ProductEvidenceLedger,product:ProductCluster,observedAt:string,observationId:string):RetainProductEvidenceResult{const existing=findProductEvidence(ledger,product.identity);if(existing)return{ok:true,ledger,entry:existing,created:false};if(ledger.size>=PRODUCT_EVIDENCE_ENTRY_LIMIT)return{ok:false,ledger,reason:'capacity_reached'};const next=observeProductEvidence(ledger,product,observedAt,observationId);return{ok:true,ledger:next,entry:findProductEvidence(next,product.identity)!,created:true}}
export function productEvidenceEntries(ledger:ProductEvidenceLedger):ProductEvidenceEntry[]{return[...ledger.values()]}
export function productEvidenceValues(ledger:ProductEvidenceLedger):ProductCluster[]{return productEvidenceEntries(ledger).map(entry=>entry.current.product)}
export function findProductEvidence(ledger:ProductEvidenceLedger,identity:ProviderIdentity){return ledger.get(providerIdentityKey(identity))}
