import {describe,expect,it} from 'vitest'
import {createCoSourceApplication} from '../application/cosource-application'
import type {ProductCluster,ProvenanceKind} from '../commerce/domain/commerce'

const provider='shopify_global_catalog' as const
const product=(id:string,values:string[]=[],kind:ProvenanceKind='provider_explicit'):ProductCluster=>({identity:{provider,id},title:{value:id,provenance:{kind:'provider_explicit',provider}},attributes:{value:values.map(value=>({name:'Size',value})),provenance:{kind,provider}},media:[],offers:[{identity:{provider,id:`${id}-offer`},title:{value:id,provenance:{kind:'provider_explicit',provider}},price:{minorAmount:1000,currency:'GBP'},oneTimeCostCoverage:{status:'complete',evidence:{strength:'source_explicit',source:'fixture'}},availability:{state:'available',basis:'catalog_signal',provenance:{kind:'provider_explicit',provider}},selectedOptions:[],media:[],correlations:[],provenance:{kind:'provider_explicit',provider}}],featuredOfferId:`${id}-offer`,offerCompleteness:'featured_only',provenance:{kind:'provider_explicit',provider}})
async function setup(item:ProductCluster,conditionInput:{operator:'equals'|'is_true'|'is_false'|'at_most'|'at_least';field:string;value?:string}={operator:'equals',field:'Size',value:'large'}){let id=0;const application=createCoSourceApplication({market:{country:'GB',currency:'GBP'},makeId:()=>`id-${++id}`,now:()=> '2026-09-11T12:00:00.000Z',catalog:{search:async()=>({products:[item],messages:[],pagination:{hasMore:false}}),product:async()=>({product:item,selectedOptions:[],messages:[]})}});application.editGoal({summary:'Large item',searchFocus:'item'});application.addGoalCondition('requirement');const condition=application.getSnapshot().goalDraft.requirements[0]!;application.editGoalCondition('requirement',condition.id,conditionInput);application.commitGoalDraft();await application.searchCandidates({query:'item'});application.retainCandidate(item.identity);return application}
describe('R8R verification-aware evaluation regressions',()=>{
 it.each([['small','failed','blocked_by_known_failure'],['large','satisfied','ready_on_current_evidence']] as const)('evaluates recorded %s using canonical condition semantics',(async(value,status,readiness)=>{const item=product(value),application=await setup(item),original=application.getSnapshot().retainedEvidence[0]!,issues=application.getEvidenceIssues(item.identity);if(!issues.ok)return;const missing=issues.value.find(issue=>issue.field.startsWith('condition:'))!;const planBefore=application.getSnapshot().plan;application.addCandidateToPlan(item.identity);const planRevision=application.getSnapshot().plan.revision;expect(application.recordHumanVerification({issueId:missing.id,outcome:'recorded',value,note:'Checked exact size label'}).ok).toBe(true);const evaluation=application.evaluateCandidate(item.identity);expect(evaluation).toMatchObject({ok:true,value:{requirements:[{status,evidence:{kind:'human_verified',value}}],readiness}});expect(application.getSnapshot().retainedEvidence[0]).toBe(original);expect(application.getSnapshot().plan.revision).toBe(planRevision);expect(application.evaluatePurchasePlan()).toMatchObject({ok:true,value:{readiness:readiness==='blocked_by_known_failure'?'blocked_by_known_failure':expect.any(String)}});expect(planBefore.lines).toHaveLength(0)}))
 it('confirms one exact inferred claim and propagates through candidate evaluation',async()=>{const item=product('inferred',['large'],'provider_inferred'),application=await setup(item),issues=application.getEvidenceIssues(item.identity);if(!issues.ok)return;const issue=issues.value.find(entry=>entry.kind==='verification_required')!;expect(issue.claimReferences).toHaveLength(1);expect(application.recordHumanVerification({issueId:issue.id,outcome:'confirmed',claimReference:issue.claimReferences[0],note:'Checked manufacturer label'}).ok).toBe(true);expect(application.evaluateCandidate(item.identity)).toMatchObject({ok:true,value:{requirements:[{status:'satisfied',evidence:{kind:'human_verified'}}],readiness:'ready_on_current_evidence'}});expect(application.getEvidenceIssues(item.identity)).toMatchObject({ok:true,value:expect.arrayContaining([expect.objectContaining({id:issue.id,resolved:true})])})})
 it('identifies conflicting claims independently and rejects only one without rewriting source data',async()=>{const item=product('conflict',['large','small']),application=await setup(item),original=structuredClone(item.attributes),issues=application.getEvidenceIssues(item.identity);if(!issues.ok)return;const conflict=issues.value.find(entry=>entry.kind==='conflicting')!;expect(conflict.claimReferences).toHaveLength(2);expect(new Set(conflict.claimReferences).size).toBe(2);expect(application.recordHumanVerification({issueId:conflict.id,outcome:'confirmed',claimReference:conflict.claimReferences.join(' / '),note:'Unsafe aggregate'})).toMatchObject({ok:false,code:'invalid_input'});const small=conflict.claimReferences.find(reference=>decodeURIComponent(reference).endsWith(':small'))!;expect(application.recordHumanVerification({issueId:conflict.id,outcome:'rejected',claimReference:small,note:'Rejected exact contradictory claim'}).ok).toBe(true);expect(application.evaluateCandidate(item.identity)).toMatchObject({ok:true,value:{requirements:[{status:'satisfied'}]}});expect(application.getSnapshot().retainedProducts[0]!.attributes).toEqual(original)})
 it.each([
  [{operator:'is_true',field:'Certified'},'true','satisfied'],
  [{operator:'is_false',field:'Restricted'},'false','satisfied'],
  [{operator:'at_least',field:'Capacity',value:'10 kg'},'12 kg','satisfied'],
  [{operator:'at_least',field:'Capacity',value:'10 kg'},'12 lb','unknown'],
 ] as const)('uses canonical boolean and numeric/unit semantics for recorded facts',async(condition,value,status)=>{const item=product(`semantic-${value}`),application=await setup(item,condition),issues=application.getEvidenceIssues(item.identity);if(!issues.ok)return;const issue=issues.value.find(entry=>entry.field.startsWith('condition:'))!;expect(application.recordHumanVerification({issueId:issue.id,outcome:'recorded',value,note:'Human checked fact'}).ok).toBe(true);expect(application.evaluateCandidate(item.identity)).toMatchObject({ok:true,value:{requirements:[{status}]}})})
 it('does not treat arbitrary human text as satisfying a free-text condition',async()=>{const item=product('free-text'),application=await setup(item,{operator:'equals',field:'Notes',value:undefined}),issues=application.getEvidenceIssues(item.identity);if(!issues.ok)return;const issue=issues.value.find(entry=>entry.field.startsWith('condition:'))!;expect(application.recordHumanVerification({issueId:issue.id,outcome:'recorded',value:'looks suitable',note:'Unstructured observation'}).ok).toBe(true);expect(application.evaluateCandidate(item.identity)).toMatchObject({ok:true,value:{requirements:[{status:'unknown'}],readiness:'insufficient_evidence'}})})
})
