import {describe,expect,it} from 'vitest'
import {createCoSourceApplication} from '../application/cosource-application'
import {durableProjection,PERSISTED_WORKSPACE_FORMAT_VERSION} from '../application/persistence/workspace-persistence'
import {parsePersistedWorkspace} from '../application/persistence/persisted-workspace-schema'
import type {ProductCluster} from '../commerce/domain/commerce'
import {createApplicationTools} from '../webmcp/application-tools'

const provider='shopify_global_catalog' as const
const inferred={kind:'provider_inferred' as const,provider},explicit={kind:'provider_explicit' as const,provider}
const product:ProductCluster={identity:{provider,id:'candidate'},title:{value:'Candidate',provenance:explicit},attributes:{value:[{name:'Size',value:'large'}],provenance:inferred},media:[],offers:[{identity:{provider,id:'offer'},title:{value:'Offer',provenance:explicit},price:{minorAmount:1000,currency:'GBP'},availability:{state:'available',basis:'catalog_signal',provenance:explicit},selectedOptions:[],media:[],correlations:[],provenance:explicit}],featuredOfferId:'offer',offerCompleteness:'featured_only',provenance:explicit}
async function setup(){let id=0,tick=0;const application=createCoSourceApplication({market:{country:'GB',currency:'GBP'},makeId:()=>`id-${++id}`,now:()=>new Date(Date.parse('2026-09-11T00:00:00.000Z')+tick++*60000).toISOString(),catalog:{search:async()=>({products:[product],messages:[],pagination:{hasMore:false}}),product:async()=>({product,selectedOptions:[],messages:[]})}});application.editGoal({summary:'Large product',searchFocus:'product'});application.addGoalCondition('requirement');const condition=application.getSnapshot().goalDraft.requirements[0]!;application.editGoalCondition('requirement',condition.id,{operator:'equals',field:'Size',value:'large'});application.commitGoalDraft();await application.searchCandidates({query:'product'});application.retainCandidate(product.identity);return application}
const envelope=(application:Awaited<ReturnType<typeof setup>>)=>{const payload=durableProjection(application.getSnapshot());return{formatVersion:PERSISTED_WORKSPACE_FORMAT_VERSION,workspaceId:payload.id,durableRevision:0,savedAt:'2026-09-12T00:00:00.000Z',market:payload.market,payload}}

describe('R8R3 observation-aware verification lifecycle',()=>{
 it('keeps an old confirmation historical and makes the same claim in a new observation actionable',async()=>{const application=await setup(),first=application.getEvidenceIssues(product.identity);if(!first.ok)return;const issue=first.value.find(item=>item.kind==='verification_required')!,claim=issue.claimReferences[0]!;expect(application.recordHumanVerification({issueId:issue.id,outcome:'confirmed',claimReference:claim,note:'Confirmed observation one'}).ok).toBe(true);expect(application.evaluateCandidate(product.identity)).toMatchObject({ok:true,value:{readiness:'ready_on_current_evidence'}});const retainedBefore=structuredClone(application.getSnapshot().retainedEvidence[0]);await application.refreshRetainedEvidence(product.identity);expect(application.evaluateCandidate(product.identity)).toMatchObject({ok:true,value:{readiness:'verification_required'}});const current=application.getEvidenceIssues(product.identity);expect(current.ok).toBe(true);if(!current.ok)return;const active=current.value.find(item=>item.kind==='verification_required'&&!item.resolved)!;expect(active).toMatchObject({blocksReadiness:true,routes:expect.arrayContaining(['confirm_claim','reject_claim'])});expect(active.id).not.toBe(issue.id);expect(current.value.filter(item=>!item.resolved&&item.field===issue.field)).toHaveLength(1);expect(application.getSnapshot().humanVerifications).toHaveLength(1);expect(application.getSnapshot().retainedEvidence[0]!.history[0]).toEqual({...retainedBefore!.current,supersededBy:application.getSnapshot().retainedEvidence[0]!.current.id});const web=await createApplicationTools(application).find(item=>item.name==='get_evidence_gaps')!.execute({product:product.identity}) as {data:{readiness:string;issues:Array<{id:string;resolved:boolean}>}};expect(web.data).toMatchObject({readiness:'verification_required',issues:expect.arrayContaining([expect.objectContaining({id:active.id,resolved:false})])})})
 it('keeps an evicted claim decision persistable but inapplicable',async()=>{const application=await setup(),issues=application.getEvidenceIssues(product.identity);if(!issues.ok)return;const issue=issues.value.find(item=>item.kind==='verification_required')!;expect(application.recordHumanVerification({issueId:issue.id,outcome:'confirmed',claimReference:issue.claimReferences[0],note:'Historical decision'}).ok).toBe(true);for(let index=0;index<6;index++)expect((await application.refreshRetainedEvidence(product.identity)).ok).toBe(true);const state=application.getSnapshot(),verification=state.humanVerifications[0]!;expect(state.retainedEvidence[0]!.history.some(item=>item.id===verification.claimBinding?.observationId)).toBe(false);expect(state.humanVerifications).toContainEqual(verification);expect(application.evaluateCandidate(product.identity)).toMatchObject({ok:true,value:{readiness:'verification_required'}});expect(parsePersistedWorkspace(envelope(application))).toMatchObject({ok:true})})
 it('rejects forged issue/field bindings and missing observations inside the retained window',async()=>{const application=await setup(),issues=application.getEvidenceIssues(product.identity);if(!issues.ok)return;const issue=issues.value.find(item=>item.kind==='verification_required')!,result=application.recordHumanVerification({issueId:issue.id,outcome:'confirmed',claimReference:issue.claimReferences[0],note:'Exact decision'});if(!result.ok)return;const valid=envelope(application),record=result.value,corrupt=(changes:Record<string,unknown>)=>structuredClone({...valid,payload:{...valid.payload,humanVerifications:[{...record,...changes}]}});expect(parsePersistedWorkspace(corrupt({issueId:'issue-forged'}))).toEqual({ok:false,reason:'corrupt'});expect(parsePersistedWorkspace(corrupt({field:'condition:other'}))).toEqual({ok:false,reason:'corrupt'});expect(parsePersistedWorkspace(corrupt({issueId:'issue-forged',field:'condition:other'}))).toEqual({ok:false,reason:'corrupt'});expect(parsePersistedWorkspace(corrupt({claimBinding:{...record.claimBinding,observationId:'missing'},issueBinding:{...record.issueBinding,observation:{...record.issueBinding.observation,id:'missing'}}}))).toEqual({ok:false,reason:'corrupt'})})
})
