import {describe,expect,it} from 'vitest'
import {createCoSourceApplication} from '../application/cosource-application'
import {durableProjection,PERSISTED_WORKSPACE_FORMAT_VERSION} from '../application/persistence/workspace-persistence'
import {parsePersistedWorkspace} from '../application/persistence/persisted-workspace-schema'
import {evidenceIssueId} from './domain/evidence-resolution'
import type {ProductCluster} from '../commerce/domain/commerce'

const provider='shopify_global_catalog' as const,at='2026-09-11T12:00:00.000Z',explicit={kind:'provider_explicit' as const,provider},inferred={kind:'provider_inferred' as const,provider}
const product:ProductCluster={identity:{provider,id:'candidate'},title:{value:'Candidate',provenance:explicit},attributes:{value:[{name:'Size',value:'large'}],provenance:inferred},media:[],offers:[{identity:{provider,id:'offer'},title:{value:'Applicable',provenance:explicit},price:{minorAmount:1000,currency:'GBP'},availability:{state:'available',basis:'catalog_signal',provenance:explicit},selectedOptions:[],media:[],correlations:[],provenance:explicit},{identity:{provider,id:'other-offer'},title:{value:'Other',provenance:explicit},price:{minorAmount:1200,currency:'GBP'},availability:{state:'available',basis:'catalog_signal',provenance:explicit},selectedOptions:[{name:'Size',value:'small'}],media:[],correlations:[],provenance:explicit}],featuredOfferId:'offer',offerCompleteness:'featured_only',provenance:explicit}
async function setup(){let id=0;const application=createCoSourceApplication({market:{country:'GB',currency:'GBP'},makeId:()=>`id-${++id}`,now:()=>at,catalog:{search:async()=>({products:[product],messages:[],pagination:{hasMore:false}}),product:async()=>({product,selectedOptions:[],messages:[]})}});application.editGoal({summary:'Sized product',searchFocus:'product'});application.addGoalCondition('requirement');application.addGoalCondition('requirement');const [conditionA,conditionB]=application.getSnapshot().goalDraft.requirements;application.editGoalCondition('requirement',conditionA!.id,{operator:'equals',field:'Size',value:'large'});application.editGoalCondition('requirement',conditionB!.id,{operator:'equals',field:'Size',value:'small'});application.commitGoalDraft();await application.searchCandidates({query:'product'});application.retainCandidate(product.identity);const issues=application.getEvidenceIssues(product.identity);if(!issues.ok)throw new Error(issues.message);const issue=issues.value.find(item=>item.field===`condition:${conditionA!.id}`)!;const result=application.recordHumanVerification({issueId:issue.id,outcome:'confirmed',claimReference:issue.claimReferences[0],note:'Confirmed condition A'});if(!result.ok)throw new Error(result.message);const payload=durableProjection(application.getSnapshot()),envelope={formatVersion:PERSISTED_WORKSPACE_FORMAT_VERSION,workspaceId:payload.id,durableRevision:0,savedAt:at,market:payload.market,payload};return{application,envelope,record:result.value,conditionA:conditionA!,conditionB:conditionB!}}

describe('R8R4 canonical persisted issue semantics',()=>{
 it('accepts the exact current canonical condition and issue snapshot',async()=>{const{envelope,record}=await setup(),condition=envelope.payload.activeGoal!.requirements.find(item=>item.id===record.claimBinding?.conditionId)!;expect(record.issueBinding).toMatchObject({kind:'verification_required',conditionKind:'requirement',condition,offer:product.offers[0]!.identity,claims:[{id:record.claimReference}]});expect(parsePersistedWorkspace(envelope)).toMatchObject({ok:true})})
 it('rejects a forged issue kind even when its deterministic ID is recalculated',async()=>{const{envelope,record}=await setup(),issueBinding={...record.issueBinding,kind:'conflicting' as const},issueId=evidenceIssueId({workspaceId:record.workspaceId,requirement:{id:record.requirementId,revision:record.requirementRevision},subject:record.subject,field:record.field,kind:issueBinding.kind,observation:issueBinding.observation}),forged=structuredClone({...envelope,payload:{...envelope.payload,humanVerifications:[{...record,issueId,issueBinding}]}});expect(parsePersistedWorkspace(forged)).toEqual({ok:false,reason:'corrupt'})})
 it('rejects rebinding to another same-field condition, collection, semantics, offer, or claim set',async()=>{const{envelope,record,conditionB:initialB}=await setup(),conditionB=envelope.payload.activeGoal!.requirements.find(item=>item.id===initialB.id)!,corrupt=(changes:Record<string,unknown>)=>structuredClone({...envelope,payload:{...envelope.payload,humanVerifications:[{...record,...changes}]}}),reboundBinding={...record.issueBinding,condition:conditionB},reboundField=`condition:${conditionB.id}`,reboundId=evidenceIssueId({workspaceId:record.workspaceId,requirement:{id:record.requirementId,revision:record.requirementRevision},subject:record.subject,field:reboundField,kind:record.issueBinding.kind,observation:record.issueBinding.observation});expect(parsePersistedWorkspace(corrupt({field:reboundField,issueId:reboundId,issueBinding:reboundBinding}))).toEqual({ok:false,reason:'corrupt'});expect(parsePersistedWorkspace(corrupt({issueBinding:{...record.issueBinding,conditionKind:'preference'}}))).toEqual({ok:false,reason:'corrupt'});expect(parsePersistedWorkspace(corrupt({issueBinding:{...record.issueBinding,condition:{...record.issueBinding.condition,operator:'is_true',value:undefined}}}))).toEqual({ok:false,reason:'corrupt'});expect(parsePersistedWorkspace(corrupt({issueBinding:{...record.issueBinding,offer:product.offers[1]!.identity}}))).toEqual({ok:false,reason:'corrupt'});expect(parsePersistedWorkspace(corrupt({issueBinding:{...record.issueBinding,claims:[]}}))).toEqual({ok:false,reason:'corrupt'})})
})
