import {describe,expect,it} from 'vitest'
import {createCoSourceApplication} from '../application/cosource-application'
import {durableProjection,PERSISTED_WORKSPACE_FORMAT_VERSION} from '../application/persistence/workspace-persistence'
import {parsePersistedWorkspace} from '../application/persistence/persisted-workspace-schema'
import {evidenceIssueId} from './domain/evidence-resolution'
import type {ProductCluster} from '../commerce/domain/commerce'

const provider='shopify_global_catalog' as const,now='2026-09-11T12:00:00.000Z',provenance={kind:'provider_explicit' as const,provider}
const product:ProductCluster={identity:{provider,id:'candidate'},title:{value:'Candidate',provenance},attributes:{value:[],provenance},media:[],offers:[{identity:{provider,id:'offer'},title:{value:'Offer',provenance},price:{minorAmount:1000,currency:'GBP'},availability:{state:'available',basis:'catalog_signal',provenance},selectedOptions:[],media:[],correlations:[],provenance}],featuredOfferId:'offer',offerCompleteness:'featured_only',provenance}
function create(){let id=0;return createCoSourceApplication({market:{country:'GB',currency:'GBP'},makeId:()=>`id-${++id}`,now:()=>now,catalog:{search:async()=>({products:[product],messages:[],pagination:{hasMore:false}}),product:async()=>({product,selectedOptions:[],messages:[]})}})}
async function setup(outcome:'recorded'|'requires_verification'){const application=create();application.editGoal({summary:'Large product',searchFocus:'product'});application.addGoalCondition('requirement');const condition=application.getSnapshot().goalDraft.requirements[0]!;application.editGoalCondition('requirement',condition.id,{operator:'equals',field:'Size',value:'large'});application.commitGoalDraft();await application.searchCandidates({query:'product'});application.retainCandidate(product.identity);const issues=application.getEvidenceIssues(product.identity);if(!issues.ok)throw new Error(issues.message);const issue=issues.value.find(item=>item.kind==='missing')!,result=application.recordHumanVerification({issueId:issue.id,outcome,value:outcome==='recorded'?'small':undefined,note:'Human evidence marker'});if(!result.ok)throw new Error(result.message);return{application,verification:result.value}}
const envelope=(application:ReturnType<typeof create>)=>{const payload=durableProjection(application.getSnapshot());return{formatVersion:PERSISTED_WORKSPACE_FORMAT_VERSION,workspaceId:payload.id,durableRevision:0,savedAt:now,market:payload.market,payload}}

describe('R8R5 outcome-aware evicted verification',()=>{
 it('restores a legitimate evicted recorded fact and preserves its known failure',async()=>{const{application,verification}=await setup('recorded');expect(verification).toMatchObject({outcome:'recorded',value:'small',claimReference:undefined,claimBinding:undefined});expect(parsePersistedWorkspace(envelope(application))).toMatchObject({ok:true});for(let index=0;index<6;index++)expect((await application.refreshRetainedEvidence(product.identity)).ok).toBe(true);const before=application.getSnapshot(),saved=envelope(application),window=[before.retainedEvidence[0]!.current,...before.retainedEvidence[0]!.history];expect(verification.issueBinding.observation!.sequence).toBeLessThan(Math.min(...window.map(item=>item.sequence)));expect(before.humanVerifications).toContainEqual(verification);expect(application.evaluateCandidate(product.identity)).toMatchObject({ok:true,value:{requirements:[{status:'failed'}],readiness:'blocked_by_known_failure'}});expect(parsePersistedWorkspace(saved)).toMatchObject({ok:true});const restored=create();restored.restoreWorkspace(saved.payload);expect(restored.getSnapshot().humanVerifications).toContainEqual(verification);expect(restored.getSnapshot().retainedEvidence).toEqual(before.retainedEvidence);expect(restored.evaluateCandidate(product.identity)).toMatchObject({ok:true,value:{requirements:[{status:'failed'}],readiness:'blocked_by_known_failure'}})})
 it('keeps a claimless requires-verification marker valid after legitimate eviction without improving readiness',async()=>{const{application,verification}=await setup('requires_verification');expect(verification).toMatchObject({outcome:'requires_verification',claimReference:undefined,claimBinding:undefined});for(let index=0;index<6;index++)await application.refreshRetainedEvidence(product.identity);expect(parsePersistedWorkspace(envelope(application))).toMatchObject({ok:true});expect(application.evaluateCandidate(product.identity)).toMatchObject({ok:true,value:{readiness:'insufficient_evidence'}})})
 it('still rejects forged recorded semantics and missing observations inside the retained window',async()=>{const{application,verification}=await setup('recorded'),valid=envelope(application),corrupt=(changes:Record<string,unknown>)=>structuredClone({...valid,payload:{...valid.payload,humanVerifications:[{...verification,...changes}]}}),kind='conflicting' as const,issueId=evidenceIssueId({workspaceId:verification.workspaceId,requirement:{id:verification.requirementId,revision:verification.requirementRevision},subject:verification.subject,field:verification.field,kind,observation:verification.issueBinding.observation});expect(parsePersistedWorkspace(corrupt({issueId,issueBinding:{...verification.issueBinding,kind}}))).toEqual({ok:false,reason:'corrupt'});expect(parsePersistedWorkspace(corrupt({issueBinding:{...verification.issueBinding,condition:{...verification.issueBinding.condition,value:'small'}}}))).toEqual({ok:false,reason:'corrupt'});expect(parsePersistedWorkspace(corrupt({issueId:evidenceIssueId({workspaceId:verification.workspaceId,requirement:{id:verification.requirementId,revision:verification.requirementRevision},subject:verification.subject,field:verification.field,kind:verification.issueBinding.kind,observation:{...verification.issueBinding.observation!,id:'missing'}}),issueBinding:{...verification.issueBinding,observation:{...verification.issueBinding.observation!,id:'missing'}}}))).toEqual({ok:false,reason:'corrupt'})})
})
